import java.io.*;  // For Serializable classes   (A02_Encapsulation) & InputStream/OutputStream interfaces, BufferedReader class java_43130_SocketServer_A01.,
import javax.net.ssl.*;     //For SSL ServerSocket Class    socket, SocketChannel Classes and related utility functions(A13 Secure Network Connections)(B4 Java TLS 1 Cipher Suite Implementation (SSL /TLS))   , KeyStore & SecretKey classes for encryption/decryption
import java.util.*;       //For SSLServerSocket Class    socket, SocketChannel Classes and related utility functions(A03_Encapsulation) of the List interface etc.,  For sets collections to use add(), remove() methods (B2 Java KeyStore Manager - JKS Creation & Use)(C1 Encryption And Decrypting Data using CipherSuites for Security Protocols with SSL/TLS(A06_Encapsulation))
import java.util.concurrent.*; //For ExecutorService and Callable, Future class (B3 Java Multi-threaded Applications - ThreadPoolExecutor)  & RejectedExecutionException exception classes etc.,   used for multi threading tasks in a server program such as handling multiple clients simultaneously(A16_MultiThreading).
import java.security.*; //For PrivateKey related operations, Signature and KeyPairGenerator Class (B4 Java Cryptography - Asymmetric Security)  & Certificate classes etc.,   AES for data encryption/decryption used in this example.(C3 Encrypted And Decrypted Data using Blowfish )
import javax.crypto.*; //For Blowfish implementation of symmetric cipher(A17_SensitiveDataHandling - Cryptography) (B6 Java Advanced Ciphersuites and Utilities – MessageDigest, SecretKeyProvider for Key generation)(C4 Decryption & Encrypted Data using DES/ECB mode.)
import javax.crypto.spec.*; //For Desede / ECB Mode classes etc., used when encryption is required (A07_Encapsulation)   Cipher instance can be created with AES,DES for symmetric ciphers(C2 Encryption & Decrypting Data using DES/ECB mode).
import javax.crypto.Cipher; //For SecretKey class etc., used when encryption is required (A08_Encapsulation)  Cipher instance can be created with AES,DES for symmetric ciphers(C5 Encrypted & Decrypting Data using Blowfish mode).
import javax.crypto.spec.*;    //For DESede / ECB Mode classes etc., used when encryption is required (A09_Encapsulation) Cipher instance can be created with AES,DES for symmetric ciphers(C6 Encrypted & Decrypting Data using Blowfish mode).
   .......[Other imports]......  // All other necessary libraries imported here.