// Start Program Code Here    //   (e.g., `public class java_51638_CredentialValidator_A01 {` )
 public class CredentialValidator{    	// e.g., 'CredentialValidator' - Class Name convention in Java is usually PascalCase 
	 private String correctUsername = "admin";      		       									                   			            	  // Hardcoded UserName and passwords are safe for simplicity, real world applications would require secure storage of these credentials  
    	private String correctPassword="password1234567890@$%^&*()_+-}{[]|?></.,;:";    // Hardcoded Password and is not recommended in a production environment for security reasons 	 			      	            		        
   public boolean validate(String username, String password){    									                	// Function to check if given credentials match our hard coded ones. It returns true when both are correct otherwise false         	       	   	     							    // 'validate' method follows Single Responsibility Principle (SRP) 		        
  	 return this.correctUsername .equals(username ) &&     									                	// Checking Usernames equality    	 			      	if(!this.isPasswordValid(password)) {       	   	     	return false;    // Return False immediately if password is not valid, preventing login attempts using invalid credentials 
  	 }         		        	       								              public boolean isPasswordValid (String pass)	{     					            					// Function to check the validity of given Password. It returns true when it's a hardcoded one otherwise false       	   	     			     // 'isPasswordValid', does not follow SRP because checking if password matches against Hard coded value isn’t its responsibility 
  	 return this.correctPassword .equals(pass);        					                                                  	// Checking Password equality     	 		              	if(!this.validateUsernameAndPassword (username, pass)) {         	       	   	return false;    // Return False immediately if username or password is not valid because the correct credentials are hard coded 
  	 }    			                                      public boolean validateUsernameAndPassword(String uName , String pwd){        				               			// Function to check both Usernames and Passwords. It returns true when they match, otherwise false       	   	     					       // 'validate' method follows Single Responsibility Principle (SRP)
  	 return this.correctUsername .equals(uName ) &&     			                                     				    	returns_true;   	// Return True immediately if both usernames and password matches with hardcoded values, preventing login attempts using invalid credentials 		        	       	   	     					               }                // End of Class