script
const express = require('express');  //Express framework for handling HTTP requests. It's part required library to use Session middleware as well, not a frameworks specific one like Spring or Hibernate
 const bodyParser=require("body-parser");   //Middleware that parses the text as JSON and makes it available through `req.body` under the name 'json'. You can set this up for all your endpoints in an app using express application here by placing [app] before each route definition
const cookieSession=require('cookie-session')  //Cookies are used to manage user sessions, we will use it as a session middleware. Express Session is the main module that uses these cookies and exposes their functionality on req & res objects in NodeJS applications using express framework (expressjs/xss-filters)
const app = require('./app');  //We include our application here for reference, you can remove this as well if not required. We will use it later to start the server and listen at a specified port number on startup of your program  
 const PORT=process.env.PORT || 3001;//Allows us to specify where we want express app running – in our case, local or deployed production environment should set up this way (it's not required if you only start server locally)    //Default port number is the one that Heroku uses
  
app.use(cookieSession({//This will allow us to use cookies for session management/authentication in our app – it’ll automatically parse all incoming request headers, and set a cookie on login or signup etc.. And also read this information from existing sessions after every user requests the site (like when they log back into their account with another device)
    maxAge:24 *60*60 *1000 , // The maximum age of each session in milliseconds – for example, a session lasts until it's deleted or its time value expires. (default is one day.)   This will prevent the users from logging back into our application after they have closed their browser window/tab
    keys:['key1', 'key2'] //A secret key to sign cookies – replace this with your own securesafe way of storing and retrieving it in a real app. Keys should be saved securely, stored database can also work if used correctly (like mongoose library)  
}));    /*Express Session is using the Cookie-Session middleware to handle user sessions for us as we'll see later */  //Using cookie session here instead of express-session because it has less dependencies than other options. Also, this option allows more flexibility in terms that you can use custom logic when users are logging back into their account with another device
app.use(bodyParser);   /*Body Parser is a middleware to simplify the process on receiving and reading from body of request*/  //Using Body-parser here because we'll be sending sensitive information like passwords in headers, this option provides us an easy way for it by skipping parsing
app.use(express.static('./public'));   /*Express static is used to serve files such as .css or images from the public folder*/  //Public directory will contain our stylesheets and other assets we want server side in a production environment like this one (you may remove it if you don't use any)
     app.listen(PORT, () => {   /*Starting up an Express Server on specified port number */    console .log('App is listening at http://localhost:' + PORT);  //Prints out a message to the terminal telling us what server address it’s running on (the one that we set in our app above)
});//Listening for requests when your application runs. This allows you make multiple HTTP GET, POST etc calls within seconds with no need of restarting or reloading – which is not possible if only using socket programming like Socket IO to the client side and then on back end we can manage sessions in different ways (like MongoDB session storage)