import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;   // Import necessary Java classes for outputting HTML content (PrintWriter, etc.) 
                   // from a Servlet and handling HTTP requests & responses with HttpServletRequest object...    
public class java_51736_SessionManager_A07 extends HttpServlet {    // Define your servlet's name as 'MyFirstwebapp'.   ...     
 public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException{  ..... }          . You can call it by URL like /first_servlet. Also for Cookies and Session objects we need to make use of classes provided as part of java servlets API ...  
public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {  ..... }           . It is the method that gets called when a HTTP GET Request occurs. You can call it by URL like /second_servlet    Please note: this servlets have nothing to say ­¨