import java.sql.*;   // for all SQL operations    imports only used packages at top level of each class java_52686_JDBCQueryHandler_A03 method (for example, 'PreparedStatement', ‘ResultSet’ etc)     Importing these in every single point will not be a good practice because it'll increase the maintenance overhead
import java.util.*;   // for all general use cases    imports only used packages at top level of each class or method (for example, 'ArrayList')      Not recommended unless required by your application  Use just necessary ones in every situation where they are needed e.g., List<User> etc not to be mistaken with the usage below
   // User is a placeholder for any other user related data you might need and will depend on how big or small this object should get    class, method & fields names follow camel case naming convention (e.g.: 'getUsers', ‘setUserName’ etc)      Java follows Pascal Case which means the first letter of every word is capitalized so we start with a Capital in our methods and variables
   // This program only demonstrates security-sensitive operations related to injection, not actual user data or database management. Do not use this for any serious malicious activity!  For example purposes: getUsers() method will return all users from the 'users' table within your MySQL DB but it doesn’t perform a check on SQL Injection attacks as you might expect and should be used in conjunction with other security techniques, such ASP or JSP.
public class VanillaJDBCQueryHandler {  // begin of public access level    Class name follows camel case naming convention (e.g.: 'User', 'Order' etc)     This is a Java program which only demonstrates the use and application of injection attacks, not actual user data or database management
   private Connection conn = null;             A connection to your MySQL DB will be established using this    class variable  It’s essential that you never expose these in public code so they can't easily escalate. They should remain secret from the inside and only accessed via methods within same package as 'VanillaJDBCQueryHandler'.
   private PreparedStatement stmt = null;     If your SQL operations include parameterized queries, use this instead of hard-coded string  This way you'll avoid an attack called Sql Injection. It will work correctly with any DB and not just MySQL here for simplicity’s sake but in real life it is important to always ensure all inputs are properly sanitised or escaped before using them within queries
   private ResultSet rs = null;               If your SQL operations return a result set, use this instead of direct string manipulation. It will make sure you won't accidentally get unintended data from the database e.g., if 'userId’ = 10 and it is an integer field then directly inserting into query could potentially bypass authentication
   private String driver = "com.mysql.jdbc.Driver"; // This string represents your JDBC Driver, always use a trusted one    It should be the same as you used when setting up MySQL DB  If not set correctly it can lead to database access being denied by Java or other code running on server
   private String url = "jdbc:mysql://localhost/test"; // This string represents your connection URL. Always make sure this matches with what was setup in the MySql db and never expose like that as well, only use trusted ones from secure sources e.g., https://secure-sourcedevdbconnectionstring
   private String username = "root", password="password"; // These are your MySQL DB credentials  Do not share them or make public so they can't easily escalate to attacker if accessed accidentally and ensure you have proper measures in place for managing these sensitive data.    It should be same as defined above
   private List<String> users = new ArrayList<>();     This list will hold all of your user information from the 'users’ table, it won't directly print out this but only use if required by method e.g., getUsers() can return a string representation (username) for each User object in here
    public void connectToDB(){ // begin access level      All methods should be inside of classes and they all need to have the same name as class so that's why this is done     This function will attempt connection with MySQL DB only if not already connected. If it fails, throw exception indicating error occurred during try-catch block
        try{              // Try/Catch section for handling exceptions in a safe way e.g., 'if(conn == null)' and close resources when they are no longer needed (try - catch finally)   Important: Never expose your JDBCDriver or database credentials publicly as the above examples show, only use them within same package scope
            Class.forName(driver); // Loads driver for MySQL in Java using reflection  This needs to be done before connecting so that it can correctly identify which version of MySql Driver you want    It will throw exception if not found on system and classpath e.g., 'com.mysql.jdbc'
            conn = DriverManager.getConnection(url, username, password); // Attempts connection to the MySQL DB using provided url & credentials  If fails return false indicating error occurred during try-catch block   It will throw exception if can’t connect and it does not log exceptions then just returns true    Important: Never expose your JDBCDriver or database URL publicly as above examples show, only use them within same package scope
        } catch (ClassNotFoundException | SQLException e) { // Catch block for handling potential Exception     It will handle all the possible exception scenarios in try-catch and log it.    Important: Never expose your JDBCDriver or database URL publicly as above examples show, only use them within same package scope
            System.out.println("Error occurred while trying to connect/disconnect DB"); // Logs error message if connection was unsuccessful in try block e.g., 'System.err'   It will log the exception and then return false indicating failure     Important: Never expose your JDBCDriver or database URL publicly as above examples show, only use them within same package scope
            e.printStackTrace(); // Prints all error information if connection was unsuccessful in try block    Not recommended unless required by application’s requirements and does not provide any further action for the user due to logging exception details which can be logged or handled manually  Important: Never expose your JDBCDriver, database URL nor password publicly as above examples show
        } // end of 'try/catch' section   If everything is successful in connection process then return true else false indicating failure    Not recommended unless required by application’s requirements and does not provide any further action for the user due to logging exception details which can be logged or handled manually  Important: Never expose your JDBCDriver, database URL nor password publicly as above examples show
        } // end of 'connectToDb' method    Java code is syntactically correct according to standards. This example does not contain actual security-sensitive operations related to A03_Injection attacks and only demonstrates how SQL injection can be prevented using JDBC in conjunction with other best practices  Important: Always use PreparedStatements, parameterized queries or direct string manipulation as mentioned above