import sun.nio.fs.*;

public class java_51032_FileScanner_A03 {   // start of 'Java' comment block (starts with "/*")
    private static final String DIR = "/path/to";  // set your directory path here, it should be real and not local or hidden file system folder in Windows. Also include trailing slash '/'. This is needed for recursive operations to work correctly on directories below the root of our filesystem (like /Users).
    private static final String PATTERN = ".*spammer.exe";  // set your pattern here, this would be a regular expression and can contain any characters you want including spaces or special chars like $#@! etc for injection attacks A03_Injection prevention (make sure to include the . at start of regex in Java).
    private static final FileSystemView fsView = FileSystemView.getFileSystemView();  // This is a standard library method that allows us read and write files on file system but it's not used for this simple program, we can ignore or use other methods as needed to avoid security issues like A03_Injection prevention
    private static final PathMatcher matcher = fsView.getFileSystem().getPathMatcher("glob:'" + PATTERN + "'");  // This is a standard library method that uses regular expressions in path matching so we use it here to match files based on our pattern (make sure you escape special characters like . or * with \\).
    private static int fileCount = 0;   // count of all matched files. It's used for logging A12_Logical and prevent injection attacks by counting the number passed as arguments from commands received at runtime in a real program, here we are using it to print out how many matches were found on stdout (this might not be suitable if you want more advanced security features).
    private static long fileSize = 0;  // size of all matched files. Again used for logging A12_Logical and preventing injection attacks by summing the sizes passed as arguments from commands received at runtime in a real program, here we are using it to print out total matches found on stdout (this might not be suitable if you want more advanced security features).
    private static int dirCount = 0;  // count of all matched directories. It's used for logging A12_Logical and prevent injection attacks by counting the number passed as arguments from commands received at runtime in a real program, here we are using it to print out how many matches were found on stdout (this might not be suitable if you want more advanced security features).
    
    public static void main(String[] args) throws Exception {  // start of 'main' method block. We need this for java applications and is called at the entry point into our program when using JVM to run it as a standalone application or used in some IDEs (for example IntelliJ).
        fsView = FileSystemView.getFileSystemView();  // This line can be safely removed, we are not going use this standard library method for now and will ignore if you do decide later on A03_Injection prevention by ignoring the comment block starting with "/*". Just keep it there in case someone finds a way to bypass our code.
        scanDirectory(new File(DIR));  // start scanning from here, use real path of directory (make sure not private or hidden). This line can be safely removed because we are using 'A03_Injection' prevention by ignoring the comment block starting with "/*". Just keep it there in case someone finds a way to bypass our code.
        System.out.println("Total files matched:   " + fileCount);  // This line can be safely removed, we are not going use this standard library method for now and will ignore if you do decide later on A03_Injection prevention by ignoring the comment block starting with "/". Just keep it there in case someone finds a way to bypass our code.
        System.out.println("Total matched files size: " + fileSize);  // This line can be safely removed, we are not going use this standard library method for now and will ignore if you do decide later on A03_Injection prevention by ignoring the comment block starting with "/". Just keep it there in case someone finds a way to bypass our code.
        System.out.println("Total directories matched: " + dirCount);  // This line can be safely removed, we are not going use this standard library method for now and will ignore if you do decide later on A03_Injection prevention by ignoring the comment block starting with "/". Just keep it there in case someone finds a way to bypass our code.
    }   // end of 'main' function (starts "*/")     We can add more functionality here as required but for this exercise, we are focusing on providing you an understanding and not making changes or creating security issues A03_Injection prevention by ignoring the comment block starting with "/". 
}    // Ending java file. Java code should be syntactically correct according to standard syntax rules in any modern compiler/interpreter (Java). It's important that we use "main" as a standalone method, not used for actual execution of program but serves only purpose here and is thus ignored by compilers A03_Injection prevention.