import java.io.*; // For File and IOException, which are non-nullable references types by default for exception handling in method signatures (Java's exceptions)  
public class java_45367_FileScanner_A08 {    
    private static int maxAttempt = 5; 
      public static void main(String[] args){        
          String path = "/path/to/directory"; // specify directory to scan here. Replace with your desired location        File dir = new File("C:\\Users");       try (FileScanner scnr = new RudimentaryDirectoryScanner()) {      scnr.init(dir, maxAttempt);     while (!scnr.finished) 
          if(!fileListPrintingHelper()){   // Check whether we should continue the scan    println("Failed to find specified type of file.");}break;}}             } catch (IOException e1) {               e1.printStackTrace();            }}       private static boolean fileListPrintingHelper(){         String directoryPath = "/path/to"; 
          //specify your desired location, replace with yours        File dir2 =  new   java .io - Directory(directoryPath);try (FileScanner scnr1=new    RudimentaryDirectoryScanner()){      boolean flag=  false;       try {scnr.init(dir , maxAttempt ); } catch 
          //java io exception on first run here, so let's ignore it for this example     if (!flag)   ;{ scnr1=null;}return true}}catch (IOException e){e .printStackTrace();}}}    private class RudimentaryDirectoryScanner extends Filescanner {      @Override public boolean shouldSkip(java.io - File file, int attemptsFailedSoFar ) throws IOException 
          //Inside this method you can customize the behavior of your scan: for example filter out files by extension or type and so on        if (file .isDirectory()) return false; else {    try{if (!super..shouldSkip(film ,attemptsFailedSoFar ) &&   file.getName().endsWith(".txt")) 
          //your custom condition here, replace with yours         FileInputStream fis = new FileInputStream((File)file);     int available = 0;       while ((available=fis .read()) ! -1){           }return true;} catch (Exception e ){e.printStackTrace();}} return false;) 
          // your custom condition here, replace with yours    }} public class Filescanner {      boolean finished =false ;     private java.io-File currentfile;   int attemptsFailed=0; @Overridepublic void init(java . io - Directory dir ,int maxAttempts ) throws IOException 
          //your custom initialization here, replace with yours    if (dir == null) throw new IllegalArgumentException(); this .currentfile =      java.io-File((String)(new File("").getAbsolutePath())); finished=false; attemptsFailed = 0;} public abstract boolean shouldSkip(java io -    
          //Directory file ,int Attempts failed so far ) throws IOException ; @Overridepublic void init ( Directory dir, int maxAttempt)  .. .init() { this.currentfile = new java    i o-File((String)(new File("").getAbsolutePath())); finished= false; attemptsFailed = 0;}     
          // your custom initialization here replace with yours}}   }     private abstract class Filescanner {}