:startup-code  
import org.springframework.beans.factory.annotation.*;
import org.springframework.stereotype.*;
import javax.transaction.*;
@Service("userSession")     // This will make this bean a singleton in the application context	
public class java_49250_SessionManager_A01 { 	// Define our service here, Spring calls it as an instance of your Service (DI container)  
    private static final org.hibernate.SessionFactory sessionFactory;     		      									                                                       SessionManager(A01_BrokenAccessControl):startup-code     // This line will load the hibernate configuration file and create a new HibernatingSessionFactore object  (Hibernate Configuration).
    private static final TransactionManager transactionManager;		// Here we are using Spring's built in support for transactions.  									       		      			      User Session Management(A01_BrokenAccessControl):startup-code     // This will load the spring configuration and create a new instance of your repository (Data Access Object)
    @Autowired 									// Here we are using Spring's dependency injection mechanism.  									       		      			      User Session Management(A01_BrokenAccessControl):startup-code     // This will inject the userRepository as a bean and make it available for our use in this class
    private IUserDao userRepository; 	// Define your repository here, Spring calls it an instance of you Repository (Data Access Object)  									       		      			      User Session Management(A01_BrokenAccessControl):startup-code     // This will inject the dao and make this bean available in our service
    @Transactional 	// Here we are using Spring's support for transactions. Now any method annotated with Transactional is treated as a single, unwrapped platform transaction by default  					       		      			      User Session Management(A01_BrokenAccessControl):startup-code     // This will ensure the entire process of calling methods in our repository and updating data on your database are wrapped within one big 'transaction' 
    public void saveUserDetails() {		// Here we define a method to call from outside world that calls userRepository.save(user).  									       		      			      User Session Management(A01_BrokenAccessControl):startup-code     // This will ensure the entire process of calling methods in our repository and updating data on your database are wrapped within one big 'transaction' 
    public void saveUserDetails2() {		// Here we define a method to call from outside world that calls userRepository.save(user).  									       		      			      User Session Management(A01_BrokenAccessControl):startup-code     // This will ensure the entire process of calling methods in our repository and updating data on your database are wrapped within one big 'transaction' 
}		// End class definition here, Spring calls it an instance for you (DI container)  									       		      			      User Session Management(A01_BrokenAccessControl):startup-code     // This will make this bean a singleton in the application context.