import java.io.*;   // Importing the Input/Output streams package    	
import java.net.*;   	//Import of socket and serverSocket classes	 		     									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
public class java_44166_SocketServer_A03 {     // Main Class of the Server Application.   	                                          									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
	public static void main(String[] args) {     // Main Method to initiate the server.   	        									       			      								                		                                                         	-169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
	    ServerSocket welcomeSound = null;      // Declaring a server socket.   	         									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		 try {    	// Try Block to handle exceptions and errors.   	          									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      welcomeSound = new ServerSocket(6789);    // Creating a server socket.       	         									                                       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      System.out.println("Waiting for client on port " + welcomeSound.getLocalPort()+"...");    // Print a message to inform the user about server's activity    	         									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      Socket connection = welcomeSound.accept();    // Accepting a client's request to the server    	         									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      DataInputStream inFromClient = new DataInputStream(connection.getInputStream());     // Getting input and output streams from the client connection	         									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      DataOutputStream outToClient = new DataOutputStream(connection.getOutputStream());    // Getting input and output streams to the client connection    	         									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      String messageFromClient = inFromClient.readUTF();    // Reading a string from the client    	         									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      System.out.println("Message received from client: " + messageFromClient);    // Print the string read by clients    	         									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      outToClient.writeUTF(messageFromClient);    // Writes the received message back to client    	         									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      connection.close();    // Closes the current socket    	             									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		 } catch (IOException e) {    // Catch block to handle IOExceptions    	                 									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		      e.printStackTrace();    // Printing error details    	                 									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
		 }     	// End of try block.   	                     // Catch exception and if there is an error in the code then it will get handled by this    	 									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
	}     	// End of main method.   	                 // This is the entry point to our application    	 									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH  
}     	// End of class.   	                 // Our server application is finished here    	 									       			      								        							         	    -169283047-5fbbFefa,  #sdfasfsafadsfdafaDFASDFADSKJH