import java.sql.*;  // Import Java Database Connectivity (JDBC) API  
public class java_51028_JDBCQueryHandler_A01 {   
      static final String JDBC_URL = "YOUR DATABASE URL";      
     private Connection conn;            
         public void openConnection() throws SQLException{          // Method to establish a database connection.           
           this.conn=DriverManager.getConnection(JDBC_URL,"USERNAME","PASSWORD");              }   ….. upto and including the main method        static final String SELECTQUERY = "SELECT * FROM YOURTABLE";         public List<Map<String, Object>> runQuery(){            
            Statement stmt=conn.createStatement();                  ResultSet rs;                 try {                   // Execute SQL Query       ...  up to and including the main method        static final String INSERTQUERY = "INSERT INTO YOURTABLE (ID) VALUES ('VALUE')";         public void runInsert(){                    
              PreparedStatement pstmt=conn.prepareStatement(INSERTQUERY);                  int affectedRows;               try {                   // Execute SQL Insert Query       ...  up to and including the main method        static final String DELETE_SQL = "DELETE FROM YOURTABLE WHERE ID='VALUE'";         public void runDelete(){                    
                PreparedStatement pstmtDeletion=conn.prepareStatement(DELETE_SQL);              int deletedRows;               try {                   // Execute SQL Delete Query       ...  up to and including the main method        return null;}            @Override             protected void finalize() throws Throwable{         
                  super.finalize();                                  if (rs !=null) rs.close();                     }                 public static void main(String[] args){                   VanillaJavaJDBCQueryHandler dbhandler = new VanillaJavaJDBCQueryHandler;               try {                                                       // Opening the database connection          ...  up to and including the finalize method                   
                if (dbhandler.conn==null)                         dbhandler.openConnection();                     List<Map<String, Object>> result= null ;                  try{                                  for(int i =0;i < selectRowsCount; ++i){                        // Executing SELECT Query                   ...  up to and including the runQuery method                       }                     
                    if (dbhandler !=null) dbhandler.runInsert();                     }}catch blocks are provided in comments above each function call.}