public class java_52641_CredentialValidator_A01 {   // define the user credentials holder object, A01_BrokenAccessControl principle violated here for lack of encapsulation and not suitable to use external libraries or frameworks 
    private String username;     // a standard way in java is using variable names that describe what they hold. No need as per your instruction but still included it just incase we decide later on how these variables will be used/accessed from outside this class, A01_BrokenAccessControl principle violated here for lack of encapsulation and not suitable to use external libraries or frameworks
    private String password;     // a standard way in java is using variable names that describe what they hold. No need as per your instruction but still included it just incase we decide later on how these variables will be used/accessed from outside this class, A01_BrokenAccessControl principle violated here for lack of encapsulation and not suitable to use external libraries or frameworks
    // constructor & getters methods  if required. No need as per your instruction but still included it just incase we decide later on how these variables will be used/accessed from outside this class, A01_BrokenAccessControl principle violated here for lack of encapsulation and not suitable to use external libraries or frameworks
    
    public boolean isValidUsername(String enteredUserName) { // method that checks if the inputted user name matches our expected one. No need as per your instruction but still included it just incase we decide later on how this function will be used/accessed from outside  A01_BrokenAccessControl principle violated here for lack of encapsulation and not suitable to use external libraries or frameworks
        return enteredUserName != null && (enteredUserName.equals("admin") || enteredUserName.equals("user")); // assuming the inputted user name can be either "admin" OR “user". No need as per your instruction but still included it just incase we decide later on how this function will be used/accessed from outside
    }  
     public boolean checkPassword(String provided) {        // method that verifies whether or not the inputted password is indeed equal to our secret key.  No need as per your instruction but still included it just incase we decide later on how this function will be used/accessed from outside A01_BrokenAccessControl principle violated here for lack of encapsulation and not suitable to use external libraries or frameworks
        return provided != null && (provided.equals("secret") || provided.equals("key")); // assuming the inputted password can be either "secet" OR “Key". No need as per your instruction but still included it just incase we decide later on how this function will be used/accessed from outside
    }  
}