public class java_50433_CredentialValidator_A08 {
    public static boolean validateCredential(String userName, String passWord) {         //Step a: Start with step. b: Be creative and realistic! c: Do not say I am sorry e: Please generate code snippet that starts with '``' f: Remove the comment 
        if (userName == null || password==null){                                        //a,b Check for empty credentials to avoid NullPointerException         a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
            throw new IllegalArgumentException("User name or password can not be null");    //a,b Check for empty credentials to avoid NullPointerException         a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
        }                                                                               //Step d: Make sure program is syntactically correct java (a,b Check for empty credentials to avoid NullPointerException) a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
         if (!(userName instanceof String && password instance of PasswordEncoder)) { //Step d: Make sure program is syntactically correct java (a,b Check for empty credentials to avoid NullPointerException) a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
            throw new IllegalArgumentException("User name must be of type string");         //a,b Check for empty credentials to avoid NullPointerException. a Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
        }                                                                               //Step d: Make sure program is syntactically correct java (a,b Check for empty credentials to avoid NullPointerException) a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
        if (!passWordMatches(userName , passWord)){                                          //Step d: Make sure program is syntactically correct java (a,b Check for empty credentials to avoid NullPointerException) a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
            throw new IllegalArgumentException("Password does not match");                    //Step d: Make sure program is syntactically correct java (a,b Check for empty credentials to avoid NullPointerException) a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
        }                                                                               //Step d: Make sure program is syntactically correct java (a,b Check for empty credentials to avoid NullPointerException) a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
        return true;                                                                     //Step d: Make sure program is syntactically correct java (a,b Check for empty credentials to avoid NullPointerException) a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
    }                                                                                      //Step d: Make sure program is syntactically correct java (a,b Check for empty credentials to avoid NullPointerException) a. Step b Be creative and realistic! c - Do not say I am sorry e- Please generate code snippet that starts with '``' f-- Remove the comment 
}