import javax.imageio.ImageIO;   // Import ImageIo package which will allow us to read image files, etc... like JPEG or Tiff(JFIF) in a java program   
import java.awt.*;           // We need these for graphics manipulations    
import java.awt.image.BufferedImage;  // For Buffered Image   (for images and video streams). This class java_53159_FileScanner_A08 part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order.
import java.awt.image.*;  // For BufferedImage   (for images and video streams). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Graphics2D  (for creating graphics and shapes). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Rectangle (for creating rectangles). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Polygon  (for creating polygons). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For ImageIO  (for reading and writing images). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For BasicStroke (for creating strokes). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For BasicColorSpace (for creating color spaces). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For AffineTransform (for creating and applying transformations on images). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For FontRenderContext (for creating and applying font rendering). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Color (for getting colors from images and fonts). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Ellipse2D (for creating ellipses). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Rectangle2D (for creating rectangles). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Polygon2D (for creating polygons). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Image  (creating images and fonts). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For BasicFontSamples (creating font samples). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For BasicFontStyle (creating font styles). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Font  (for getting fonts from images and shapes). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For BasicColorSpace (creating color spaces). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For AffineTransform (creating and applying transformations on images). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For FontRenderContext (creating and applying font rendering). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Color (for getting colors from images and fonts). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Ellipse2D (creating ellipses). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Rectangle2D (creating rectangles). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Polygon2D (creating polygons). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Image  (for reading and writing images). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For BasicStroke (for creating strokes). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For BasicFontSamples (for creating font samples). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For BasicFontStyle (for creating font styles). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Font  (creating fonts from images and shapes). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For BasicColorSpace (creating color spaces). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For AffineTransform (creating and applying transformations on images). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For FontRenderContext (creating and applying font rendering). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Color (creating colors from images and fonts). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Ellipse2D (creating ellipses). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Rectangle2D (creating rectangles). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Polygon2D (creating polygons). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order
import java.awt.*;           // For Image  (reading and writing images). This class is part of the awt package... which includes imageio etc.., it's mainly used to encapsulate a multi-dimensional array or data structure whose contents can be accessed by rows/columns via indices in order */