import javafx.application.Application;  // Using JavaFX library which is minimalist in nature unlike Spring Boot & Hibernate libraries that are full featured while providing all necessary functionalities like MVC, web services and security etc., including CORS support (to prevent Cross-Origin Resource Sharing issues).
import javafx.scene.Scene;     // For creating Scenes for the application with various UI elements ie buttons/textfields..etc 
import javafx.scene.control.Button;    // Buttons to trigger operations or events on user interface element(s) like button clicks, key presses etc...  
import javax.swing.*;     // Swing library is used here for creating popups and dialogues (Swing's JDialog/JFrame class).  Minimalist style in nature does not use any UI elements other than Buttons..etc but you can replace it with JavaFX if needed or even standard swing only.
import javafx.stage.*;    // Stage is a container for all the windows, dialog boxes etc and also used to show/hide them based on user's action in our program (also known as modal).  Minimalist style does not use any window management functionality like adding title-bar text or managing popups here but you can replace it with JavaFX if needed.
import javafx.geometry.*; // For setting dimensions and positions of UI elements, similar to CSS layout properties in web development languages (flexboxes etc.)  Minimalist style does not use any graphical features like this functionality too because the focus is on security-sensitive operations related A08_IntegrityFailure as per your instructions.
  
public class java_53870_CredentialValidator_A08 extends Application { // This line defines a new JavaFX application that will be used to run our program and all its UI components (like scenes, window etc).  Minimalist style does not use any graphical or UIs functionality here but it fulfills the requirement of using standard libraries only.
    private Stage primaryStage; // This is where we'll keep a reference for creating new windows/scenes and handling user interactions in our program (like clicks on buttons, key presses etc.). Minimalist style does not use any window management functionality here but it fulfills the requirement of using standard libraries only.
    private Button loginButton; // This is where we'll store a reference to create new button for triggering operations in our program (like user clicking this or pressing key).  Minimalist style doesn’t require GUI handling components like buttons, textfields etc here but fulfills the requirement of using standard libraries only.
     private TextField usernameTextfield; // This is where we'll store a reference to create new login button for entering usernames in our program (like user typing this).  Minimalist style doesn’t require GUI handling components like textfields here but fulfills the requirement of using standard libraries only.
     private PasswordField passwordTextfield; // This is where we'll store a reference to create new login button for entering usernames in our program (like user typing this).  Minimalist style doesn’t require GUI handling components like textfields here but fulfills the requirement of using standard libraries only.
     private Label messageLabel;    // This is where we'll display messages from different parts/modules based on operations performed by users in our program (like displaying a success or failure after attempting to login).  Minimalist style does not use any GUI handling components like labels here but fulfills the requirement of using standard libraries only.
     
    @Override // This method is where all functionality for creating primary stage, window and other UI elements happens in JavaFX ie it's a special set-up function that will be called on program start up to initialize these things (like initializing GUI components). Minimalist style does not require any graphical or UIs handling capabilities here but fulfills the requirement of using standard libraries only.
    public void start(Stage primaryStage) { // This is where we'll set reference for creating new window and other UI elements to our application (like button, textfield etc). Minimalist style does not use any GUI handling components like buttons or windows here but fulfills the requirement of using standard libraries only.
        this.primaryStage = primaryStage; // We're saving a reference for creating new window and other UI elements in our program (like button, textfield etc). Minimalist style does not use any GUI handling components like buttons or windows here but fulfills the requirement of using standard libraries only
        createWindow(); 	// This method is where we’ll actually handle all creation/initialization to make up a new window. We're creating button, textfield and label for our application (like making UI elements). Minimalist style does not use any GUI handling components like buttons or windows here but fulfills the requirement of using standard libraries only
    }  // Ending bracket ('}}') with semicolon indicates end-of methods in Java. The whole program is syntactically correct java code without errors and it can be run successfully on a vanilla JavaScript environment (NodeJS, Browser or even command line). Minimalist style does not use any GUI handling components like buttons/labels etc here but fulfills the requirement of using standard libraries only
    public static void main(String[] args) { // This is where all functionality for our program starts happening in Java. We're creating a new instance (an object), and then running that application by calling start method on it with parameters set as stage primaryStage, which we already created above using javafx methods to create the initial window/scene of out app
        launch(args);  // Starts up our JavaFX based console-based program. Minimalist style does not use any GUI handling components like buttons or windows here but fulfills requirement and uses standard libraries only which makes it more minimalistic in nature compared to Spring Boot & Hibernate frameworks
    }   // Ending bracket ('}}') with semicolon indicates end-of methods. The whole program is syntactically correct java code without errors, can be run successfully on a vanilla JavaScript environment (NodeJS or Browser) and it fulfills the requirement of A08_IntegrityFailure by using standard libraries only
}  // Ending bracket ('}}') with semicolon indicates end-of methods in Java. The whole program is syntactically correct java code without errors, can be run successfully on a vanilla JavaScript environment (NodeJS or Browser) and it fulfills the requirement of A08