import java.util.*;   // For using HashMap and List data structures in our example session manager class, we need Java's util package (List is used to create a list of sessions for each user) 
public final class java_51046_SessionManager_A08 {    // Declare the public access modifier which means any code outside this file can use these classes or methods. This allows encapsulation and prevents unauthorized modification from external codes using getters/setter method if required by your application structure  
     private static HashMap<String, List<Session>> allSessions = new HashMap<>(); // Create a hashmap to store userId as key -> list of sessions associated with this id  (Security-sensitive operations related A08_IntegrityFailure)   
      public SessionManager() { }     // Default constructor for session manager which will not do anything, mainly used by the static initializer block below.   It's private to prevent it from being instantiated elsewhere in our code  (Security-sensitive operations related A08
      
private class UserSessionInfo{    // Private inner SessionManager Class only accessible within this file and its nested classes for encapsulating session information such as userId, createdAt etc.   This is a way of 'securing' the data inside our HashMap from outside world (Security-sensitive operations related A08_IntegrityFailure)
    String userID;  // User ID stored in this class only for security sensitive operation based on rule: not allowed to access directly or modify it unless authorized by Security Manager.   If you attempt accessing a direct field, the compiler will throw an error because of 'access modifier' setting (Security-sensitive operations related A08_IntegrityFailure)
    long createdAt;  // Created At stored in this class only for security sensitive operation based on rule: not allowed to access directly or modify it unless authorized by Security Manager.   If you attempt accessing a direct field, the compiler will throw an error because of 'access modifier' setting (Security-sensitive operations related A08
     // other fields as necessary  ...    }     
       static {         // The block executed when any class using this SessionManager is loaded by JVM   This would be where all our session creation takes place, and these sessions are stored in a HashMap. Also used for security sensitive operations related to A08_IntegrityFailure (Security-sensitive)
        try {  // Try block inside static initializer because we can't initialize an instance of this class directly from the main method which is called at startup, therefore using 'try/catch'.   If any exception happens during creation then it will be caught and handled within here.    (Security-sensitive operations related A08_IntegrityFailure)
         for(int i=1;i<= 5 ; ++i){  // For loop to create five sessions each with a unique userID   Creating Session Information using UserSessionInfo class, storing it in the session list created by List (which maintains insertion order). Also used security sensitive operation based on rule: not allowed access outside this scope for directly accessing ArrayList but only indirectly through getters and setter method.
            //Creates a new user with unique ID - 'i'  before creating sessions, making it more secure than direct manipulation (Security-sensitive operations related A08_IntegrityFailure)   If you attempt to access directly UserSessionInfo or List from main class then the compiler will throw an error because of Access modifier setting.
            String userID = "user" + i; // create unique id  with prefix 'User' and count (i e, for example: if it is first session this would be `Users` otherwise its index+1)   If you attempt to access directly ArrayList from main class then the compiler will throw an error because of Access modifier setting.
            long createdAt = System.currentTimeMillis(); // getting current time using system method and storing in variable 'created At'.  Also used for security sensitive operation based on rule: not allowed direct manipulation (Security-sensitive operations related A08_IntegrityFailure)   If you attempt to access directly ArrayList from main class then the compiler will throw an error because of Access modifier setting.
            UserSessionInfo userinfo = new UserSessionInfo(userID, createdAt); // create a instance using variables above and store in list  (Security-sensitive operations related A08_IntegrityFailure)   If you attempt to access directly ArrayList from main class then the compiler will throw an error because of Access modifier setting.
            List<Session> sessionList = new LinkedList<>(); // create a linkedlist for sessions with unique userID  (Security-sensitive operations related A08_IntegrityFailure)   If you attempt to access directly ArrayList from main class then the compiler will throw an error because of Access modifier setting.
            allSessions().put(userinfo, sessionList); // store created UserSessionInfo and Linkedlist into HashMap  (Security-sensitive operations related A08_IntegrityFailure)   If you attempt to access directly ArrayList from main class then the compiler will throw an error because of Access modifier setting.
         }//end for loop i++    */     // Closing try block and it's important that all exceptions have a catch clause (Security-sensitive operations related A08_IntegrityFailure)   If exception is thrown, program would go to the corresponding 'catch'.  It will execute this code.
        }//end static initializer    End of Security sensitive operation based on rule: not allowed access outside scope for all codes/classes in java file (Security-sensitive operations related A08_IntegrityFailure)   If exception is thrown, the program would go to 'catch' block and handle it properly.
       } //End UserSessionInfo class definition    End of Security sensitive operation based on rule: not allowed access outside scope for all codes/classes in java file (Security-sensitive operations related A08