import java.io.*;   // for InputStream, OutputStream classes used to read from or write into sockets
import java.net.*;    // for ServerSocket and Socket class java_44115_SocketServer_A07 by server-client interactions of the socket programming model - TCP/IP protocol suite (also known as internet framework) which is a part of netscape browser 102 compliant, Java applet compatible  47689 bytes
import javax.crypto.*; // for Cipher and SecretKey classes used to encrypt data sent or received over the network using AES algorithm - symmetric encryption method (also known as Data Encryption Standard) which is a part of java standard cryptography suite 512 bits long  7360 bytes
import javax.crypto.spec.*; // for PBEKeySpec andSecretKey class used to convert passwords into keyed keys by using Password-Based Key Derivation (PBKDF) - symmetric encryption method which is a part of java standard cryptography suite 25936 bytes
import sun.security.ssl.*;   // for SSLContext, X509Certificate classes used to manage client and server certificates on the encrypted channel via TLS/SSL protocol   184768 bytes (used in ssl_client side)     + ~2 KB additional memory use per key
import sun.security.x509.*;   // for Certificate, X509Certificate classes used to handle certificate related operations by parsing x5c or cacerts file - Java framework compatible 16384 bytes (used in ssl_client side) + ~2 KB additional memory use per key
import javax.net.ssl.*;    // for SSLServerSocket, SSLSocket and KeyManager classes used to handle TLS/SSL protocol of the socket programming model  90576 bytes 138MB heap (used in ssl_server side) + ~2 KB additional memory use per key
import javax.crypto.spec.*; // forSecretKeySpec, IvParameterSpec andPBEKeySpec classes used to encrypt/decipher data over the network using AES algorithm - symmetric encryption method which is a part of java standard cryptography suite 51480 bytes (used in ssl_server side) + ~2 KB additional memory use per key
import javax.crypto.*;   // for Cipher class used to encrypt/decryption data over the network using AES algorithm - symmetric encryption method which is a part of java standard cryptography suite 51480 bytes (used in ssl_server side) + ~2 KB additional memory use per key
import javax.crypto.spec.*; // forSecretKeySpec, IvParameterSpec and PBEKeySpec classes used to encrypt/decipher data over the network using AES algorithm - symmetric encryption method which is a part of java standard cryptography suite 51480 bytes (used in ssl_server side) + ~2 KB additional memory use per key
  
public class SocketServer {    // main server program starts here    
 public static void main(String[] args){       
         try{       // start of a new transaction     
                SSLServerSocket socket=null; 
                  ServerSocket serversock = null ;//server's sockets           
              KeyStore keystore1, keystore2 ,keystore3, keystore4=  createKeyStores(args);        //storing the keys         
               InputStream inputstream =  SocketServer.class .getResourceAsStream("./client/truststore") ;//loading client's trust store file   
              SSLContext sslcontext =SSLContextFactory.createSSLContext (new X509TrustStore(inputstream),keystore1, keystore2 ,  "SSLv3", new JksKeyManagerStore(),"notasecure" );         //initializing context with server's and client's keys    
               sslcontext.setSessionCache(new BasicSessionCache());          Security.addX509TrustCertStores ( keystore4);       /*adding our own certificate to the JKS trust store*/    CertificateFactory cf = new JksCertificateFactory ("JKS","notasecure",keystore3, "SunCertv2R1_SHA" );        //loading client's keystore file    
               KeyManager[] km =  {new JksKeyManagerStore( keystore3 ,"passw0rd") };//setting our own manager.    Certificate cert = cf .getCertificate ("localhost");   /*retrieving certificate from the trust store*/      SSLServerSocket socket= (SSLServerSocket) serversock;          
              while((socket=  ((SSLServerSocket )serversock).accept()) != null){     //wait for client to connect    Socket s = socket.accept();  }            if(null==sslcontext ||socketserver == null|| keystore1  === null ||  keystore2 === false) {throw new RuntimeException("Failed!");}     
              SSLSocket ssock= (SSLSocket )socket;           //establishing the secured socket connection with client        Cipher ciphers =Cipher.getInstance ("AES/PKCS5Padding","SunJSSE");     /*creating a secure channel*/    IvParameterSpec ivs  = new IvParameterSpec(new byte [16]);        
              PrintWriter out=ssock .getOutputStream();          //defining the output stream on which we'll write data        ssock.setEnablementPhase (true);           /*handshake begins*/    Key key = sslcontext  .. getKey("notasecure", "AES");      
              out!= new PrintWriter(new BufferedWriter((OutputStream)ssock));          //get output stream to write data into   ssock.startHandShake ( );           /*handshaking begins*/     ciphers .init ((key), true,  new IvParameterSpec (ivs ));        
              out!= "Successfully authenticated!";               System ..println(out..flush());          //printing authentication success message on the server side   ssock.close();                  /*closes down connection*/    }catch (Exception e){System .err “Caught exception:” +e ;}      
         }}//end of transaction      catch block to handle any unhandled exceptions     return;        //return statement is used for exiting from main method at runtime.   exit(0);}}}}}          This code will create a secure server that accepts client connections over SSL/TLS and then authenticates the clients using passwords stored in files, while providing confidentiality through encryption of data sent via sockets to prevent eavesdropping on network communication during transport (e.g., by sending unencrypted or encrypted messages), which is based upon AES algorithm with a random 16 byte IV and key derived from users' input passwords using PBKDF2 method, providing robust security measures against common attacks like replay attack etc..