import java.util.*;   // import standard library classes only, remove all external dependencies except the ones mentioned in here until specified by a tutor/instructor requirement otherwise use 'only' instead of full path as above comment is there to clarify this code snippet does nothing more than provides required context and instructions about how you can run it.
  
public class java_49739_SessionManager_A03 {  // define your main program (class) using the provided structure until instructed by a tutor/instructor, then provide full path as above comment is there to clarify this code snippet does nothing more than provides required context and instructions about how you can run it. The rest of body would be explained further in instruction section
   static Map<String , Boolean> sessionMap = new HashMap<>();  // create a map where key will have user id as string type, value should either true or false (representing whether the users has an active Session) which is also used to track all sessions of our application. Initially it's empty
   static {    // initialize data in constructor block so that we can guarantee Map gets its initial state before any other operations are performed on map, ie no need for if condition here again and the time complexity will be constant because insertion is always done at index 0 (userId to boolean conversion), but this doesn't matter as long userIDs don’t change while program execution.
     sessionMap = new HashMap<>();   // initialize map with a default value of null, so it can handle case when key does not exist in the hashmap ie no active sessions for that particular id exists ‘userId-boolean' is just convention to show userID and boolean values are stored separately.
    }     int counter = 0;   // initialize count variable used by session generator (to ensure unique name) every new Session should have a different ID than the previous one, initially it’s set as zero due to initial requirement in problem statement about uniqueness of sessions so we use this for that purpose and not just any value.
     public static String createSession(String userId){   // method which will generate unique session id whenever required by calling programmers if already present then don't make new one but keep old existing Session (if available), to ensure uniqueness of sessions in our application ‘userID-sessionCounter’ as convention.
       counter++;    // incrementing the count for every call, this allows us all start from zero again when a session is created with next userId which has no active Sessions yet and it will not conflict anymore if same IDs are used multiple times in single run of program because new sessions have unique id.
       String sessionID = ""+userId + "-" +  counter;  // create the Session (unique) by concatenating User_id, '-' operator with count value to make a string representation for all Sessions and return it which is essentially creating an actual "session".    }   public static void endSession(String sessionID){
     if(!sessionMap.containsKey(sessionID)){  // checking the Session ID whether present or not (if doesn't exist then throw exception, no need to make any action) and remove that particular entry from Hashmap as per requirement of problem statement about security-sensitive operations related A03_Injection attacks in session management.
       System.out.println("No active Session found for the user id " +sessionID);   // or log exception here if necessary, based on requirements only print warning to console and continue with next iteration (if no Active sessions) without removing entry from map otherwise remove it as per requirement of problem statement about security-sensitive operations related A03
       return;  } sessionMap.remove(sessionID);   // Remove the specific user’s Session ID using its value which is already unique in a Hashmap (String), and if present do not make any action otherwise log exception/warnings to console based on requirements only continue with next iteration without removing entry from map
     }    public static boolean isSessionActive(String sessionID){  // Method that will tell whether particular Session ID has an active user or Not. This method checks presence of a specific key (sessionId) in HashMap and then returns true if it's present, else false based on requirement about security-sensitive operations related A03_Injection attacks
       return sessionMap.containsKey(sessionID);  // Return the boolean result by using Session ID which is already unique so no need for any logic to be added in here unless there will some other operation with this key, then it can definitely present inside map or not and accordingly log/print warning message based on requirement only continue execution without checking further
    }   public static void main(String args[]) { // Here you should see how your session manager works for each function call.  You're supposed to use all functionalities provided in code as per problem statement using HashMap data structure and constant time complexity operations, no external dependencies except standard java library classes
      System.out.println("Created Session: " + createSession ("user1"));   // Creating a new session for user with ID 'User 0' . Here we are assuming the first execution of program which creates an active sessions as per requirement and not any pre-existence in our system ie no two same users exist simultaneously.
      endSession(createSession("user2") );   // Ending Session created by "user1" (It should be unique) – it will remove the specific user’s session id from Hashmap as per requirement of problem statement about security-sensitive operations related A03_Injection attacks.
      System.out.println("Session Active? : " + isSessionActive(createSession ("user2")));   // Now, check whether 'User 1' has an active session or not (It should be unique) - It will return true as it exists in map and false if doesn’t exist due to requirement of problem statement about security-sensitive operations related A03_Injection attacks.
     }    public static void endSession(String userId){   // As per current function definition, here you need not do anything additional when this method is called because it's an overloaded one (one accepts a String parameter only).  So remove the comment from below line as well unless otherwise specified in instructions.
     }    public static boolean isSessionActive(String userId){   // As per current function definition, here you need not do anything additional when this method is called because it's an overloaded one (one accepts a String parameter only).  So remove the comment from below line as well unless otherwise specified in instructions.
    } });