import java.util.*;  // Import ArrayList and List data types from Java Standard Library (List interface provides basic operations like add(), remove() etc.)

public class java_52303_SessionManager_A07 {   // Define Class Name for session manager "Session Manager" is singular in programming, it's more descriptive to use plural name ie 'Sessions', or a general term. In this case I have used Singular form (SM). 
    private List<String> sessions;       // Declare an ArrayList of Strings using the data type String - This array will be our session list which is where we store each user's currently logged in ID   SM_ArrayList, or Sessions may refer to any other more suitable term. Please describe it with your imagination about what you want this Array List and its purpose
    private Map<String, Integer> users;     // Declare a HashMap of Strings (user names) using the data type integer - This map will be our user list which is where we store each logged in ID along their session details. SM_Hashmap or UserSessionDetails may refer to any other more suitable term
    private static SessionManager sm;   // Declare a Singleton instance of Sm (SM), this allows us access anywhere within the application without needing multiple instances, it's an anti-pattern but for simplicity in understanding we are going with this. SM_Singletons or SingletoinPattern may refer to any other more suitable term
    
    private java_52303_SessionManager_A07(){         // Private Constructor so that no object of class can be created outside the Class (use getInstance())  This is a Singleton Design pattern and it ensures only one instance exists in our application. SM_Singletons or SingletoinPattern may refer to any other more suitable term
        sessions = new ArrayList<>();   // Initialize session list using 'new' keyword with an empty List interface - For example, we can have a blank userID=null as default for each Session  (session is simply the User ID currently logged in) SM_ArrayList or Sessions may refer to any other more suitable term.
        users = new HashMap<>();       // Initialize hashmap using 'new' keyword with an empty Map interface - For example, we can have a blank sessionID=null as default for each user (user is simply the currently logged in User ID). SM_Hashmaps or UsersSessionDetails may refer to any other more suitable term
    }  
    
    public static SessionManager getInstance(){  // Public method that returns an instance of our Singleton class, only way this can be accessed outside. This will ensure there is always just one session manager object for the entire application (SM_Singletons or SingletoinPattern may refer to any other more suitable term).
        if(sm == null){    // If singleton Session Manager instance does not exist yet then create new Singleton class SM: 
            sm = new SessionManager();   // Create a session manager object using 'new' keyword. This will initialize our in-memory sessions and users list or hashmap, respectively (SM_SessionInitialized).    
        }    // End if singletons instance does not exist yet block - SM: end of Singleton pattern code 
         return sm;   // Return the already created session manager object. It can now be accessed in any other class via SessionManager or its method getInstance (SM_ReturnSession) .    
        }    // End Public Method Block for Get Instance, only way it is called elsewhere within application SM: end of Singleton pattern code 
  
      public String createNewUser(String userID){           // Function to add new users with unique IDs and return the newly created session (SM_CreateSession)      
        sessions.add("session_"+userID);                      // Add a Session using User's id as prefix, SM: this is adding just simple string in our Sessions list/array for now but you can add more functionality if needed later on like user login or authentication and session management (SM_SessionList)
        users.put(userID , sessions.size()-1);                 // Add a User with its unique ID along the newly created Session details into HashMap SM: this is adding just simple integer in our Users list/hashmap for now but you can add more functionality if needed later on like user login or authentication and session management (SM_UserSessionDetails).
        return sessions.get(sessions.size()-1);                // Return the newly created Session ie., User's current logged-in ID SM: this is getting just simple string in our Sessions list/array for now but you can add more functionality if needed later on like user login or authentication and session management (SM_ReturnSession).
        }   
     public boolean closeUser(String id){                     // Function to terminate a logged-in User's Session, closes the existing sessions. Returns true upon successful termination of an ID SM: this is adding just simple string in our Sessions list/array for now but you can add more functionality if needed later on like user login or authentication and session management (SM_SessionList)
        int index = users.get(id);                           // Get the Session Index from User's logged-in ID SM: this is getting just simple integer in our Users list/hashmap for now but you can add more functionality if needed later on like user login or authentication and session management (SM_SessionIndex).
        sessions.remove(index);                               // Remove a Logged In Session from Sessions ArrayList using the User's ID SM: this is removing just simple string in our arraylist/array for now but you can add more functionality if needed later on like user login or authentication and session management (SM_SessionList).
        users.remove(id);                                     // Remove a Logged In Session from Users HashMap using the User's ID SM: this is removing just simple integer in our hashmap/User details for now but you can add more functionality if needed later on like user login or authentication and session management (SM_RemoveSession).
        return true;                                          // Return True upon successful termination of an Session.  In Java, void does not correspond to a boolean hence the need explicitly returns false in case there's any error SM: this is adding just simple boolen value for now but you can add more functionality if needed later on like user login or authentication and session management (SM_SessionList).
        }    // End of Closing User Session Function Block   -  This block closes the current logged-in Users' sessions. SM: end Singleton pattern code     .     
}       // Close Class Declaration, if you want to use this class in another project make sure it is imported properly and follow best practices for naming classes (SM_UserSessionManager).   -  This block closes the current logged-in Users' sessions. SM: end Singleton pattern code     .