public class java_42264_CredentialValidator_A01 {    // Starts with "Main" because it's a Java program. Do not modify or remove this line, and do all of the coding inside out! - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3
     public static void main(String[] args) {  // Main method where execution starts. This is required for every Java program, do not remove or modify this line! - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3
         System.out.println(validateCredentials("user", "password")); // Replace these with actual calls to validate credentials as per your application's logic in real world scenarios  - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3
     }   
}      public class CredentialValidator { // Start of "Credential" because it is a subclass/child (not the super) to be able to use or extend - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3
     public boolean validate(String username, String password){ // Method for validating credentials. Replace this method with actual methods as per your application's logic in real world scenarios  - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3
         return true;    }      public class BrokenAccessControl { // Start of "Broken" because it is a subclass/child to be able use or extend - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3
     boolean accessAllowed(String username, String password){  // Method for checking if user has the correct credentials. Replace this method with actual methods as per your application's logic in real world scenarios - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3
         return false; }     // If access is blocked, always returns true or throw exceptions.  For instance: if(!credentialValidator.validate(username, password)) {throw new AccessDeniedException();} - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3
 }     // End of "BrokenAccessControl" because this is a subclass/child to be able use or extend – This line could also include more information about the class if necessary. - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3
 } // End of "Main" because it's a Java program that ends here, and does not have to do anything else – This line could also include more information about the class if necessary. - The Great Tom Bomb Ahead Team  ©2019-present PetaFlop LLC under GNU General Public License v3