import java.io.*;   // Import necessary classes from package    
import java.net.*;    // For ServerSocket, Socket class java_52794_SocketServer_A08 Java network programming (IPv4 & IPv6) for socket communications on a specified port number within the host machine are required to be able communicate via TCP/UDP protocol over internet  and they can run inside JVM or standalone mode of software
  
public class SecureTcpServer {    // Define your server's name as ClassName. In this case, it is "Secure TCP Server". You may define the same in different ways according to project requirements such a simple string and more complex objects like UUID etc 
      public static final int PORT = 408_INTEGRITYFAILURE;    // Assign port number which you are going to use for communication. Please remember that this is security sensitive operation, so only assign value related with A06 IntegrityFailure (A01-29)
      private ServerSocket serverSock=null ; 	//Declare variable of type 'Server Socket' and call it "server soc ket". In future we will use these variables to bind our socket.     //Assign port number from PORT constant   where insecure channel is closed, so this program should be secure for A08_IntegrityFailure
       private Socket sock=null;       		   	// Declare variable of type 'Socket' and call it "soc ket". This will hold socket connection details  //Assign null to both variables in the beginning.  	    	 	   			     					         				                                                                         } while ( true ) ;
       private DataInputStream dis =null;		   	// Declare variable of type 'Data Input Stream' and call it "data input stream". It is used for reading data from socket  //Assign null to both variables in the beginning.  	    	 	   			     					         				                                                                         } while ( true ) ;
       private DataOutputStream dos =null;		   	// Declare variable of type 'Data Output Stream' and call it "data output stream". It is used for writing data into socket  //Assign null to both variables in the beginning.  	    	 	   			     					         				                                                                         } while ( true ) ;
             public static void main(String[] args) {       		   	// This method will be called automatically by system at launch of application as a starting point for your program  //Assign null to all variables in the beginning.  	    	 	   			     					         				                                                                         } while ( true ) ;
}       END OF MAIN METHOD           Secure Tcp Server           ^_^    End                    `-(''')'-''