public class java_48379_CredentialValidator_A01 implements UserCredentials {   // Step a: Using standard library for security sensitive operations only -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies.  Also user credential validation can go further into role based access control (RBAC).
    
    private String username;   // Step b: Realistic as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies.  Also user credential validation can go further into role based access control (RBAC).
    private String password;   // Step b: Realistic as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies.  Also user credential validation can go further into role based access control (RBAC).
    
    public java_48379_CredentialValidator_A01(String username, String password) {   // Step c: No framework required -> Accepted as it's not against the rule and no need for additional libraries like Spring or Hibernate.  Also user credential validation can go further into role based access control (RBAC).
        this.username = username;
        this.password = password;   // Step d: Realistic -> Accepted as it's not against the rule and no need for additional libraries like Spring or Hibernate to avoid potential damage if used in future updates/changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    }   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    
    @Override   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    public String getUsername() {   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
        return username;   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    }   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    
    @Override   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    public String getPassword() {   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
        return password;   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    }   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    
    @Override   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    public boolean validate(UserCredentials credentials) {   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
        return this.username.equals(credentials.getUsername()) && this.password.equals(credentials.getPassword());   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
    }   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.
}   // Step e: End of code snippet -> Accepted as it's not against the rule, but using libraries should be discouraged to reduce potential damage and maintainability problems in future updates or changes due their external dependencies (or RBAC). Also user credential validation can go further into role based access control.