import java.sql.*; //Import the necessary class java_52607_JDBCQueryHandler_A03 database operations in Java SE API (includes Statement, PreparedStatement and ResultSet).
  
public void main(String[] args) {    /*main method begins execution of a program*/    
       String url = "jdbc:mysql://localhost/mydatabase";  /*!< your MySQL URL */        //Your database's server address. Change 'MySQL Server Address'/port if necessary, change it to the port you used when installing and setting up mysql in Ubuntu or other Linux distribution (if not using default one)
       String username = "root", password="";  /*!<your MySQL user name*/        //Your database's login credentials. Change 'MySQL Username'/password if necessary, change it to the root of your MySql setup on Unix-based systems or Windows machine (if not using default one)
       try {      /*Try block starts a new scope in which exceptions can be thrown*/         //To start catching any exception within this blocks. 
           Class.forName("com.mysql.cj.jdbc.Driver");   /*!< Driver class name for MySQL database */    // This is the driver necessary to connect with your mysql server, you need it only once during setup process or at least before each time when trying out queries/statements 
                                                                                    /* (you should put this in a try-catch block if exceptions are thrown)*/        } catch(ClassNotFoundException e){ //Catch the exception raised by Class.forName method and print an error message to console for debugging purpose           
           System.out.println("Cannot find MySQL driver");  /*!< Error Message */         // This line will be printed if a problem arises while trying loading/initializing JDBCDriver class   }          catch(SQLException e){       /*Catch block starts here in case of exception*/       
             System.out.println ("Error SQL : " +e);      /*!< Error Message */         //Print error message for debugging purpose  }, finally{           try {                                               /**/ Try-catch blocks must be used to handle exceptions so this line is never executed if there are no any exception in the program
                                                                     Statement stmt = conn.createStatement();       /*Create a new statement object*/         // This will create an SQL query execution point for our statements 
                               String sql="SELECT user_name FROM users WHERE id = 1";   /*!<Your select Query */          //SQL command to be executed by creating the Statement instance above      ResultSet rs = stmt.executeQuery(sql);     /* Execute your SQL query*/    while (rs.next()){ 
        System.out.println("Name: " + rs.getString ("user_name")); //Print name of user using column'id'.   } catch blocks here are not necessary for this example, but they can be added as and where exceptions occur in the program */     };       try { conn.close();  /*!<Closes connection to MySQL server*/     
                                                                                     /* This line must always come last after a 'try-catch' block or when any resources like streams are being closed (in case of exception handling) due diligence is very important for security sensitive operations */     } catch(SQLException e){ System.out.println ("Error SQL : " +e);      // Print error message if an issue arises while closing the connection to database  }}
    /*Ending main method*/   public static void main (String[] args) {}};