import javafx.util.Pair; // Import Pair class java_52486_CredentialValidator_A08 fx package to create a pair of value (username, password) 

public interface CredentialValidator {  	// Interface with method validateCredentials() in order for any cred validator can implement this contract   	
	public boolean validateCredentials(String username, String password);}			 // Allows other classes/objects to be able interactively and easily change the behavior. 		    	 	   
public class CredentialStuffingValidator implements CredentialValidator {	// Implement interface with a method for each security sensitive operation A08_IntegrityFailure, like validatePasswordComplexities(), checkPassHistory()...  	         			     					   				        															 		                                                 // Define our custom validator here in terms of real-world credential stuffing attacks.
{    	// This is a simple example but it's not realistic for an actual security sensitive operation, which should also take into account more factors like length and complexity etc...  	          				     					      	 		                                                  // Also remember to store the password hashes instead of plain text in your real scenario.
  private ArrayList<Pair<String, String>> userCredentials = new ArrayList<>();   	// Storing all username/password pairs for comparison later on..             											         	                				                   					    	 		              						     	     	    }       // Adds a pair of credential(username and password)
   public boolean validatePasswordComplexity(){  return false;}}        /* This method is not used here. It'll be implemented in real life scenario as per requirement */	                 				         			   					    	 		     	     	    }                       // Defines our custom validator for checking if a password follows complexities rules
public class RealWorldCredentialValidator implements CredentialValidator { 	// Implement interface with another method, which checks the history of failed attempts (number and timing) to prevent brute-force attacks.  	           				        					   	 		    			               						             // Adds a pair for each security sensitive operation A08_IntegrityFailure in real life scenario...
{  public boolean validatePasswordHistory(){ return false;}}          	// This method is not used here, it'll be implemented according to requirements.  	             				     					         		    			               	}       // Defines our custom validator for checking if a password has been commonly/frequently entered and thus less likely as brute force attempts
public class Main{           	// The main function where we interact with the CredentialValidator objects...   	 	   	  	       									         		    			                    }                   // Defines our custom validator for checking if a password has been commonly/frequently entered and thus less likely as brute force attempts