public class java_44726_CredentialValidator_A01 {     // Declare Class Name Here   
      private String correctUsername;   // Private Variable to hold Correct UserName  (A01_BrokenAccessControl)      
      private String correctPassword;// Private variable for the password that was given in hash form. It's related with A02 BrokenCryptography, should replace by real hashed and salted version     of a user entered credentials    // For example using sha-512   (A03_SaltAndHash)
      private String storedPassword;  // Private variable to hold the actual password. It's related with A06 InsecureStorage, should replace by real hashed and salted version of a user entered credentials    // For example using sha-512   (A03_SaltAndHash)
      private String storedUsername;  // Private variable to hold the actual username. It's related with A06 InsecureStorage, should replace by real hashed and salted version of a user entered credentials    // For example using sha-512   (A03_SaltAndHash)
       private MessageDigest md;  // MD object to encapsulate all the cryptographic operations. It's related with A04 InsecureCommunication, should replace by real hashed and salted version of a user entered credentials    // For example using SHA-512   (A03_SaltAndHash)
        public java_44726_CredentialValidator_A01(String correctUsername , String correctPassword) {  }      /* Constructor Method */          private void setCredentials(){     this.correctUsername = "admin";       this.correctpassword="abcdefghijklmnopqrstuv1234567890";  
         MessageDigest md;    // Create MD object for encapsulating cryptographic operations  (A04 InsecureCommunication)     }// Constructor */      public boolean validate(){        return true;}            /* Method to authenticate users. If the correct username and password are provided, this method should  
          will provide a successful validation otherwise it's not validated for access control related issues A23_InadequatelySecureCommunication  (A01-BrokenAccessControl) */     // For example using SHA512 to validate user credential. If they don’t match, return false  
          if(correctUsername().equalsIgnoreCase(username)) {       MessageDigest md =MessageDigest.getInstance("SHA-512");    }else{  throw new InvalidParameterException();}// For example using SHA–512 to validate user credential in the format of "user:password". If they don’t match, return false  
        if(correctPassword().equalsIgnoreCase((new String ( md.digest( password .getBytes() ))))) {      }else{ throw new InvalidParameterException();}// For example using SHA-512 to validate user credential in the format of "user:password". If they don’t match, return false
          public static void main (String args [] )throws NoSuchAlgorithmException  // Main Method To Test Our Credentials Validator   {     new    Authenticatormethods.CredentiValidator(“admin” ,Password).validate(); }*/}// Close the code snippet here!