import java.io.*;  // for Input/Output Streams and their related classes such as DataInputStream /DataOutputStream   etc.,   
               
public class java_52418_SocketServer_A01 {                  
     public static void main(String[] args) throws IOException{         
           ServerSocket server = new ServerSocket (8081);         /* create a socket on port 5432.*/      
                  while (!Thread.currentThread().isInterrupted())   // infinite loop for the application life     {            
                          Socket clientConnection =  null;                Connection established, accept it with server    try{              
                                                            clientConnection = server .accept();                        BufferedReader inStream= new  Buffered Reader (new Inputstream(clientconnection.getInputStream()));                     String userInput  =in Stream readLine()) ;                       if (!userinput)//exit program                {                                                                                    break; }         // close streams & socket connection          
                                                            clientConnection .close();                                   try{               DataOutputStream outStream = new dataoutput stream (cient Connection. getOutstreamp()))                          String messageToSend="welcome to the server";                                  if(message To send ==null) {break;}                         write your response back                    } catch all exception                             e1){  //closes client connection and continues with next iteration      
                                                            close();                                         try{               println("connection closed unexpectedly");   break;}}}           this closes server successfully, regardless of the cause. The loop will continue to run until it is manually stopped by a call on interrupted thread         if (clientConnection != null) {          client Connection .close() ;}}     }
}  // main method ends here       Include all other methods and classes as per requirements for complete code, but please remember this example can't handle more than one connection at once. Also the actual solution would depend on how you want to manage multiple connections etc.,         Please provide additional details if required in further assistance