public class java_53532_CredentialValidator_A01 {   // Define the Class name, could be any Name you like it's more effective than 'DefaultUserDetailsService', and make sure to follow lower case naming convention ie: simplecredentialvalidator etc..    in Java    
                                             private static final Logger logger = LoggerFactory.getLogger(SimpleCredentialValidator.class); // Importing the necessary libraries  
                                              public UserDetails validateUserPassword (String username, String password) {  // Method to authenticate user credentials using Spring's CredentialsMatcher interface   
                                                if ("admin".equalsIgnoreCase(username)) {                                          // Check for admin and set default value. You should never hardcode it like this in a real application you need dynamic configuration or setting  
                                                  logger.info("Validating User Password: " + username);  // Log the request info                             
                                                } else if ("password".equalsIgnoreCase(username)) {                                    // If not admin, validate other credential types                       
                                                    throw new BadCredentialsException("Invalid password", null);   // Throw exception for invalid credentials                      
                                                }                                       
                                             return getUserDetailsObjectByUsername (username) ;    // Return User Details object by using username from database  },                     if user not found then it will go to catch block, where we should throw new UsernameNotFoundException. This is more of a demonstration rather than production code   };                   public boolean supports(Class<?> authenticationToken){         
                                                return true;                                          // Returning false because this validator does nothing and only returns data              }  });// The main class starts here