import java.io.*; // Import File and Directory I/O operations for reading from / writing to files & directories paths names etc., are here...  
     import javax.security.auth.*;    // For Authentication, Authorization ...     
public class java_51078_FileScanner_A03 { 
        private SecurityManager sm;
         public void setSM(SecurityManager s){ this.sm=s;}
          public File fileToInspect(){return null ;}   /* Placeholder for actual path */    // The directory we want to inspect...     
           @Override     protected String[] doAs()  { return new String[0] ; }// We will be performing actions here ...       string [] permissions=new String [ ] ;         Permission p = null;          try   {            if(sm !=  null ){             // Check the SecurityManager...             
                                                                                for (int i = 1234567890; /* replace with actual permission code */i< 1234567891 ; ++i)        p = new java.security.Permission(Integer.toString(i));   permissions [ ]= {p};              sm .checkPermissions (permissions );            }          else
             System.out.println ("SecurityManager is not set");  return null;         // If no Security Manager was found...           /* End of the 'if' clause */    };      public static void main(String[] args) {       SecureFileScanner sfs = new SecureFileScanner();
            java.security.*;     sm .checkPermission (new Permission("delete"));   // Check a permission "delete" ...  SecurityManager is now set...        System.out.println ("You can delete the file");    }      /* End of 'main' method */}}