import java.io.*;
import java.net.*;
import javax.net.ssl.*;
  
public class java_51287_SocketServer_A01 {
    private static final String KEYSTORE_LOCATION = "path-to/yourKeystore"; // Replace with your keystore location 
    private static final char[] KEYSTORE_PASSWORD = 'password'.toCharArray();//Replace password as needed by the user.  
     public static void main(String args[]) throws Exception {      
        ServerSocket serverSocket  = null;        
           try{            
              SSLServerSocket sslserversocket=null;  //SSL socket         
                 KeyStore keystore = KeyStore.getInstance("JKS");               
                  KeyStore passwordKeystore=  KeyStore.getInstancePasswordKeyStore(KEYSTORE_LOCATION, KEYSTORE_PASSWORD);  
                     InputStream keystoreInputStream= new FileInputStream (new File(KEYSTORE_LOCATION));    //File and Directory path    
                  keystore .load(keystoreInputStream ,  KEYSTORE_PASSWORD );            
                 trustStore = passwordKeystore;              
                   sslserversocket  = ((SSLServerSocket) serverSocket);        
                      SSLContext sc=null ;             
                           TrustManagerFactory tmf =  new   javax.net.ssl.TrustManagerFactory();     //Loads a Trust  Manager Factory with the key store password   
                             KeyStore truststore = null;      UserTrustManager myUM  =new MyUserLogin() as IUMLogin ;       
                               sslserversocket .setNeedClientAuth(true);   sc.init (null, tmf , new java.security.SecureRandom());     //Initializes SSLcontext and Trust Manager  Factory    with the key store password     
                              Thread thread =new myThreadSSL();       System.out.println("Server Started");        while((serverSocket=sslserversocket .accept()) !=  null){   PrintWriter out =  sslInit ( serverSocket ); if(threads[i].isAlive()==false) threads [ i ]  = new thread  myThreadSSL();   
            }catch exceptions{      //Catch and handle exception.     };              System.out .println("Server Stopped");}   private void sslInit ( Socket socket){        SSLSocket ssock =(SSLSocket )socket;                     SSLEngine engine=ssock.createSSLEngine();   
            }               sc  =SSLContext.getInstance ("SSLv3" );  //sslengine       setNetMask("all");     out .println ( "Connecting to : " + servername);        try {         ssock.setSSLEngine( engine ) ;      PrintWriter   sout = new printwriter   
          (( socket), true, false ,true"+host_ip );       }catch exceptions{  //Catch and handle exception .     }; System out .println ( "connection failed!");} else if (!ssock.isConnectedLocally()){              setNetMask("all");   sout = new printwriter (( socket), true, false ,true"+host_ip );   
        }catch exceptions{  //Catch and handle exception     };System out .println ( "Connection lost ");}});}}};         System.exit(0) ;       }} catch Exception e {            Logger logger = java.util.logging.Logger.getlogger("SecureSocketServer");      loggerexception  
!=null  println ("exception caught"+e );     } //catch and handle exception}    finally{        if (serverSockethandler !=  null) server SocketHandler .close( ) ;}}}}};//finally clause for closing resources.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler  
!=null  socketServerhandlerevent handler run () -> new eventloop()){    } catch exception{     logger ( "soket_server failed with"+exception ); }}         println ("Closed");}}} //print statement to show closing the program.       try {      socketserverhandler