public class java_53232_XMLParser_A03 {  // Class declaration with correct indentation for syntax highlighting purposes in IntelliJ IDEA (or any Integrated Development Environment)
    public static void main(String[] args){        // Method to execute Java code, same as standard 'main' method. No arguments are expected here because it is a standalone application not connected with UI or IO operations – e.g., command line operation etc in JVM based applications like Spring Boot Applications
         String xmlData = "<person><name>John Doe</name><age>30</age><city>New York</city></person>";     // Your XML data here, you can use a sample one for testing purposes. Make sure it is secure to avoid A03_Injection attacks
         parseXML(xmlData);        // Call the function with your xml string as argument (no arguments are expected) – e.g., command line operation etc in JVM based applications like Spring Boot Applications here   Java Code Syntax: XML Parsing using DOMParser API, No External Libraries used
    }      public static void parseXML(String data){     // Method to Parse the given xml string and print its content – e.g., command line operation etc in JVM based applications like Spring Boot Applications here   Java Code Syntax: XML Parsing using DOMParser API, No External Libraries used
         try {                     // Try block for handling exceptions related with JavaScript operations (NodeJS or browser specific features). Same as standard 'try' and ‘catch’ syntax in vanilla Javascript. Also same indentation is required here because it wraps the code that we want to protect from A03_Injection attacks
             var parser = new DOMParser();       // Create a instance of Domparser, no arguments are expected   Java Code Syntax: No External Libraries used – Same as vanilla JavaScript. Also same indentation is required here because it wraps the code that we want to protect from A03_Injection attacks
             parser.parseFromString(data);       // Parse given xml data into a document, no arguments are expected   Java Code Syntax: No External Libraries used – Same as vanilla JavaScript same indentation here (only added for readability) This line is the actual parsing and printing of content in your XML string
             var root = parser.documentElement; // Get first child node from DOMDocument, no arguments are expected   Java Code Syntax: No External Libraries used – Same as vanilla JavaScript same indentation here (only added for readability) This line is the actual access to and use of content in your XML string
             var name = root.getElementsByTagName("name")[0];       // Get first element by its tag name 'tag', no arguments are expected   Java Code Syntax: No External Libraries used – Same as vanilla JavaScript same indentation here (only added for readability) This line is the actual access to and use of content in your XML string
             var age = root.getElementsByTagName("age")[0];       // Get first element by its tag name 'tag', no arguments are expected   Java Code Syntax: No External Libraries used – Same as vanilla JavaScript same indentation here (only added for readability) This line is the actual access to and use of content in your XML string
             var city = root.getElementsByTagName("city")[0];       // Get first element by its tag name 'tag', no arguments are expected   Java Code Syntax: No External Libraries used – Same as vanilla JavaScript same indentation here (only added for readability) This line is the actual access to and use of content in your XML string
             console.log("Name : " + name.childNodes[0].nodeValue);       // Logging output with 'console' statement, no arguments are expected   Java Code Syntax: No External Libraries used – Same as vanilla JavaScript same indentation here (only added for readability) This line is the actual access to and use of content in your XML string
             console.log("Age : " + age.childNodes[0].nodeValue);       // Logging output with 'console' statement, no arguments are expected   Java Code Syntax: No External Libraries used – Same as vanilla JavaScript same indentation here (only added for readability) This line is the actual access to and use of content in your XML string
             console.log("City : " + city.childNodes[0].nodeValue);       // Logging output with 'console' statement, no arguments are expected   Java Code Syntax: No External Libraries used – Same as vanilla JavaScript same indentation here (only added for readability) This line is the actual access to and use of content in your XML string
         } catch(e){                     // Catch block with exception handling. Again, no arguments are expected because it's a Java-based program not connected directly or indirectly like browser’s event handlers etc – e.g., command line operation etc Javascript/NodeJs based applications in Spring Boot
             console.log(e);               // Logging exception details with 'console'. Same as vanilla JavaScript, no arguments are expected because it's a Java-based program not connected directly or indirectly like browser’s event handlers – e.g., command line operation etc Javascript/NodeJs based applications in Spring Boot
         } // End of Catch block with exception handling for security sensitive operations related to A03_Injection, no arguments are expected because it's a Java-based program not connected directly or indirectly like browser’s event handlers – e.g., command line operation etc Javascript/NodeJs based applications in Spring Boot
     }      // End of the actual parsing and printing content from XML String, no arguments are expected because it's a Java-based program not connected directly or indirectly like browser’s event handlers – e.g., command line operation etc Javascript/NodeJs based applications in Spring Boot
}       // Class declaration ends here with correct indentation for syntax highlighting purposes   same as standard '}' closing bracket used above, no arguments are expected because it's a Java-based program not connected directly or indirectly like browser’s event handlers – e.g., command line operation etc Javascript/NodeJs based applications in Spring Boot