import java.io.*;
import java.net.*;
import javax.net.ssl.*;

public class java_46373_SocketServer_A08 {
    private static final int port = 8443; // HTTPS Port, you can change it as per requirement  
    
    public static void main(String[] args) throws Exception  {
        ServerSocket socket = null;        
	try{            
            SSLServerSocket serverSocket=null;                
	    KeyStore keyStore =  KeyStore.getInstance("JKS");                 
	        InputStream inisetream  = SecureHTTPServer .class  
                    .getResourceAsStream("/keystore.jks") ;                // Keystroe File location 	    	 		   			     	     				         	   						       					         -> you need to create one on your own then provide the path, and it should be in Java resource folder ie /src/main or similar
             keyStore .load(inisetream , "password".toCharArray() ) ; //provide passphrase here if any	    			 		   	 					     				       	   						   -> provide password as per requirement.         	      ----->  it should be same with keystorepass
             TrustManagerFactory tmf = TrustManagerFactory .getInstance( "TRUSTSTORE" ) ;               // Use your own name here                 			 		   	    	 					     				       	   						   -> provide correct truststore and password.            ----->  it should be same with keystorepass
             serverSocket= ( SSLServerSocket ) socket = new SSLServerSocket( port , tmf, keyStore) ; //provide your own path for sslconfig if any 		    			     	  					      	 	   						    -> use default configuration file provided by java.net package and change it as per requirement
             System.out .println("Secure HTTPS Server started at port :" +port) ;                  // Show that server is running         	      ----->  provide correct host name if any 	-----	  the one you used while creating SSLSocket or passing socket to print method in SecurHTTPClient
             BufferedReader reader = null;      		     			        				       	   					     -> use default configuration file provided by java.io package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while reading from socket in SecurHTTPServer
             DataOutputStream out = null;                     		   	     			        				       	   					     -> use default configuration file provided by java.io package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while writing from socket in SecurHTTPServer
             Socket client = serverSocket .accept ( ) ;                		   	     			        				       	   					     -> use default configuration file provided by java.net package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while reading from socket in SecurHTTPServer
             reader = new BufferedReader (new InputStreamReader(client .getInputStream())) ;      		   	     			        				       	   					     -> use default configuration file provided by java.io package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while reading from socket in SecurHTTPServer
             out = new DataOutputStream (client .getOutputStream()) ;       		   	     			        				       	   					     -> use default configuration file provided by java.io package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while writing from socket in SecurHTTPServer
             String message, reply;         		   	     			        				       	   					     -> use default configuration file provided by java.lang package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while reading from socket in SecurHTTPServer
             PrintWriter writer = new PrintWriter (out .getOutputStream()) ;         		   	     			        				       	   					     -> use default configuration file provided by java.io package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while writing from socket in SecurHTTPServer
             message = reader .readLine ( ) ;                     		   	     			        				       	   					     -> use default configuration file provided by java.io package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while reading from socket in SecurHTTPServer
             writer .println (message) ;                       		   	     			        				       	   					     -> use default configuration file provided by java.io package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while writing from socket in SecurHTTPServer
             writer .close ( ) ;                              		   	     			        				       	   					     -> use default configuration file provided by java.io package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while writing from socket in SecurHTTPServer
             System .out .println (message) ;               		   	     			        				       	   					     -> use default configuration file provided by java.lang package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while reading from socket in SecurHTTPServer
             client .close ( ) ;                            		   	     			        				       	   					     -> use default configuration file provided by java.io package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while closing socket in SecurHTTPServer
             serverSocket .close ( ) ;                     		   	     			        				       	   					     -> use default configuration file provided by java.net package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while closing socket in SecurHTTPServer
            }catch(Exception e){System .out .println (e) ;}                 		   	     			        				       	   					     -> use default configuration file provided by java.lang package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while closing socket in SecurHTTPServer
	}finally{                 try {if(socket != null)                     		   	     			        				       	   					     -> use default configuration file provided by java.net package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while closing socket in SecurHTTPServer
            socket .close ( ) ;                                                 }catch(IOException e){ System .out .println ("Error Closing Socket" +e) ;}                 		   	     			        				       	   					     -> use default configuration file provided by java.net package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while closing socket in SecurHTTPServer
	}             System .exit (0 ) ;                          		   	     			        				       	   					     -> use default configuration file provided by java.lang package and change it as per requirement   ----->  provide correct host name if any 	-----	  the one you used while exiting from main method in SecurHTTPServer
}