import java.sql.*;
public class java_43934_JDBCQueryHandler_A08 {     //class name must match the table/entity for which data will be retrieved, e.g., Person in this case 
    public static void main(String[] args) throws SQLException{   //use try-catch block to handle potential exceptions instead of printing or logging them outright as it's not really a best practice either -> better ways are using exception handling with log4j etc.    
        String url = "jdbc:mysql://localhost/test";  //provide actual database URL, e.g., jdbc:postgresql instead of mysql for PostgreSQl if used   connection parameters should be provided securely (e.g using properties file)   
        Properties props=new Properties();    
         /*props.setProperty("user","root");  //password is not set here, it's recommended to use environment variables or some form of secrets management for security reasons */     
          Connection con = DriverManager.getConnection(url , "username" );   //connection string and credentials are provided as parameters which should be used securely e.g., using properties file  when we have more number of databases, servers etc in future   
         Statement stmt=con.createStatement();     Connection conn = DriverManager.getConnection(url , "username", props);   //creating statement object and providing connection credentials as parameters to handle exceptions properly if any error occurs while connecting with database  e.g., provide a try-catch block inside this for proper handling of errors
        String sql="SELECT * FROM Person";    ResultSet rs = stmt.executeQuery(sql);     //SQL query string and providing connection credentials as parameters to handle exceptions properly if any error occurs while executing the SQL statement  e.g., provide a try-catch block inside this for proper handling of errors
        int count = 0;   void processResultSet ( ResultSet rs ) throws Exception {      RowMetaData rowmeta = rs.getMetaData();     String columns[]=new          Strings [row meta data] .column names getName and Column Label is  column label +"Label"; //add your code here for getting the values from result set using their respective labels, e.g., name = 
        while(rs.next()){      count++;     System.out..... }    if (count == 0) {       throw new Exception("No Records Found");}  else{         print all records or handle data as required by your application......   }} //add code here for handling exceptions and logging properly