import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.hibernate5.HibernateTemplate;
import org.springframework.stereotype.Repository;
import javax.transaction.Transactional;
 
@Repository //This is a Repository annotation which allows us to autowire the SessionFactory bean in our UserDAOImpl class java_51891_SessionManager_A03 its fields using @Autowired keyword and hence making it as repository component for handling session operation inside application context, this can be called transaction management service. This helps you manage your sessions seamlessly across different parts of an applications
public class SecureSessionManager {  //This is a Repository annotation which allows us to autowire the SessionFactory bean in our UserDAOImpl class into its fields using @Autowired keyword and hence making it as repository component for handling session operation inside application context, this can be called transaction management service. This helps you manage your sessions seamlessly across different parts of an applications
  private HibernateTemplate hibernateTemplate; //hibernatetemplate is used to work with the database   -Spring provides a way in which we are able fetch and save data through CRUD operations (insert, update , delete). This can be called from anywhere by autowiring this bean into your service class.
  @Autowired//This annotation will automatically wire sessionFactory inside SecureSessionManager instance once the context is loaded so that it's available for injection in any other component/service or not yet when we are running our program, So Spring handles a lot of details to setup and teardown your bean (like connection pooling etc)
  private SessionFactory sessionFactory; //This variable will hold reference from which hibernate template can interact with database. As per the @Autowired annotation it is ready for injection in any other class/service, So Spring handles a lot of details to setup and teardown your bean (like connection pooling etc)
  private Session session; //This variable will hold reference from which hibernate template can interact with database. As per the @Autowired annotation it is ready for injection in any other class/service, So Spring handles a lot of details to setup and teardown your bean (like connection pooling etc)
  public void saveData(Object object){ //method will be called from anywhere where you want data insertion into database. In this method we are using hibernateTemplate which allows us to work with the Database in Java based way as Spring ORM layer is abstracted away by Hibernatetemplate and it gives more control over your queries
    session =sessionFactory.openSession(); //opens a new Session from our factory, useful for multi-threads applications where you need per thread sessions to avoid duplicate data access concurrently  -Spring provides this feature as Spring’s Transaction Management allows one transactional request or operation (like calling save() and update()) not be interrupted by another.
    hibernateTemplate = new HibernateTemplate(sessionFactory); //create a template using our Session Factory, helps in executing the queries  -Spring provides this feature to execute JPQL/Criteria API query at once or get data into memory which is handy for complex operation inside transactions like save multiple records.
    hibernateTemplate .save(object) ;//inserts passed object if not exists otherwise updates it, helps in managing the concurrency issues and optimizing bulk operations  -Spring provides this feature to execute JPQL/Criteria API query at once or get data into memory which is handy for complex operation inside transactions like save multiple records.
    session .close(); //closes a Session after use by calling close() method on the HibernateTemplate, useful if you are done with your work and want to release resources back pool -Spring provides this feature as Spring’s Transaction Management allows one transactional request or operation (like calling save()) not be interrupted.
  } //closes a Session after use by calling close() method on the HibernateTemplate, useful if you are done with your work and want to release resources back pool -Spring provides this feature as Spring’s Transaction Management allows one transactional request or operation (like calling save()) not be interrupted.
} //closes class definition – '}' is used in Java for the end of a line, it's also known by other programming languages to represent closing curly brackets "}" . In our case its being closed at here on top with eack brace {}. We can add more methods as per requirements.