import java.util.*;  // For ArrayList, HashMap etc...
  
public class java_50892_XMLParser_A07 {
    static void main(String[] args) throws Exception{
        BufferedReader reader = new BufferedReader (new InputStreamReader(System.in));        
             System.out .println ("Enter XML:");      	    		     			 									          // Reading xml from user input and printing on console for visualization purposes  	 	   	     	        /* In the above line of code */    new StringBuffer().append("\n Enter your Xml data : \n").insert(0,""));
        System.out .println ("Xml Data Read: ");      	    		     			 									          // Reading xml from user input and printing on console for visualization purposes  	 	   	     	        /* In the above line of code */    new StringBuffer().append("\n Your Xml data is : \n").insert(0,""));
        System.out .println ("\n Parsed XML Data: ");      	    		     			 									          // Reading xml from user input and printing on console for visualization purposes  	 	   	     	        /* In the above line of code */    new StringBuffer().append("\n Your parsed Xml data is : \n").insert(0,""));
        parseXML();      	    		     			 									          // Calling our custom method to parser xml. This would read from console and print out results on another screen for visualization purposes  	 	   	     	        /* In the above line of code */    new StringBuffer().append("\n Parsed XML Data : \n").insert(0,""));
        System .out .println ("\n Press Enter to exit...");      	    		     			 									          // Halt screen for user input, so they can see the output.  	 	   	     	        /* In above line of code */    new StringBuffer().append("\n press enter button").insert(0,""));
        System .exit (0 );// Closing program after this stage will prevent further execution till end if entered from keyboard or through console window close event handler when application is closed.  It stops the standard input stream and closes all system resources associated with it, thereby ending your Java Application gracefully for a user interacting via command line interface as well networked interactions etc.,
    }            	    		     			  	}            // End of main method (end)       	 	   	        /* In above code */  new StringBuffer().append("\nEnd").insert(0,""));      									          public static void parseXML() throws Exception {         import javax.xml .parsers.*;          
    DocumentBuilderFactory factory = DocumentBuilderFactory  	.getInstan     	    		  c();factory.setValidating (false);        // Create a new document builder            	        /* In above line of code */new StringBuffer().append("\nNew Instance Crea").insert(0,""));Document xmlFile;
         try {           DocumentBuilder builder = factory .newDocumentBuilder  	    		  Builder();xmlFile=builder.parse("sample_file" ); } // Read the input XML file and load it into document object   	        /* In above line of code */ new StringBuffer().append("\nNew Instance Crea").insert(0,"")); catch (ParserConfigurationException pce) { System .err 
        .println ("Failed to parse configuration: " +pce.getMessage () );  	    		     			 } // Catching Parser Configuration Exception and print its message           	        /* In above line of code */ new StringBuffer().append("\n Failed").insert(0,"")); catch (SAXException saxe) { System .err 
        .println ("Failed to parse: " +saxe.getMessage () );  	    		     			 } // Catching SAX Exception and print its message           	        /* In above line of code */ new StringBuffer().append("\n Failed").insert(0,"")); catch (Exception e) { System .err 
        .println ("Parsing failed: " +e.getMessage () );  	    		     			 } // Catch any other Exception and print its message           	        /* In above line of code */ new StringBuffer().append("\n Failed").insert(0,""));   	     	   	} public static void 
        main (String[] args) throws IOException, ParseException {      	// This is our test method for the program.  	    		     			 } // Calling this function to start execution of java application        	        /* In above line */ new StringBuffer().append("\n Main").insert(0,""));
    }} ​//End Of Program