script
const session = require('express-session'); // Importing Express Session for managing sessions in NodeJS  
var cookieParser = require("cookie-parser"); // Cookies middleware to handle cookies (req, res)
require('dotenv').config()// Env Variables Configuration  [Optional] if you have .env file then it should load your variables. Else skip this line of code which will not break the application but only help in configuration for environment variable management from different environments like Development/Production etc...   Use 'npm i dotenv'
var createError = require('http-errors'); // Handling HTTP errors [Middleware] 
const express = require('express');// Express JS Web Application Framework.   
                                                                                     It is minimalist web application framework which provides a robust set of features for NodeJS based applications, including routing and middlewares (like body parser).   Require this at the top to access all its functionalities  [Minimalistic style]     Use 'npm i express' or similar command.
var app = express(); // Creating an instance/object named "app" from Express JS in NodeJS, by requiring it here   
const bodyParser=require('body-parser');// Makes sure your request bodies get parsed into a usable format (e.g., JSON) [Middleware]  Use 'npm i body-parser' or similar command for this line of code   It is used to parse incoming requests with urlencoded payloads and/or json
var path = require('path'); // Module providing utilities for working with file paths (mostly in node.js) [Minimalistic style]    Require 'npm i express' or similar command  if you want more functional capabilities such as handling static files etc..   It is used to handle different types of requests like GET, POST and PUT
var cors = require('cors'); // Cross-origin resource sharing (CORS) middleware [Minimalistic style]    Require 'npm i express' or similar command.  if you want cross origin request handling for your endpoint .   It enables CORS on an ExpressJS app, enabling it to handle requests from different ports/origins
app.use(cors()); // Use this line of code at the top after declaring cors() middleware in above lines and use 'npm i express' or similar command if you want more functionality like handling cross origin request etc..  Then go on with below codes [Minimalistic style]   Using "app.use(bodyParser...." to parse incoming requests into json & urlencoded formats
const sessionOptions = {secret: process.env['SESSION_SECRET'], resave: false, saveUninitialized : true} // We can use environment variables as a secret for the cookie [Minimalistic style]    Require 'npm i express' or similar command if you want to set options such like session expiration time etc.. 
app.use(session(sessionOptions));// Here we are using Express-Session middleware which will add sessions functionality in our app, allowing us access of the same signed cookies between requests and database queries [Minimalistic style]    Require 'npm i express' or similar command if you want more options for session management
app.use(cookieParser()); // Adds parsing MiddleWare to parse Cookies sent by Client side in headers   Express does not provide a way of reading/writing cookies from the body, but we can read them using this middleware [Minimalistic style]    Require 'npm i express' or similar command if you want more functionality such as managing sessions etc..
app.use(express.json()); // MiddleWare function which parses incoming request bodies in a syntax that is modeled after how forms are submitted from clients, replacing the need for pow() method calls  Express does not provide JSON body parser out of box but we can use this middleware [Minimalistic style]    Require 'npm i express' or similar command if you want more functionality such as handling json encoding/decoding etc..
app.use(express.urlencoded({ extended: false })); // MiddleWare which parses the request parameters and adds them to `req` object in function based middleware [Minimalistic style]    Require 'npm i express' or similar command if you want more functionality such as handling url encoded data etc..
app.use(express.static(__dirname + "/public")); // MiddleWare for serving static files (like css/js, images)  Express does not provide this out of box but we can use it [Minimalistic style]    Require 'npm i express' or similar command if you want more functionality such as handling file uploads etc..
app.use(bodyParser); // Use the bodyparser middleware to parse JSON bodies from incoming requests into JavaScript objects (req.params, req.query and …) [Minimalistic style]    Require 'npm i express' or similar command if you want more functionality like handling request parameters etc..
app.use(path('routes')); // Handle routing at the end of all other middleware functions run on a server (like '/users') in Express JS, allowing us to define routes [Minimalistic style]    Require 'npm i express' or similar command if you want more functionality like handling path parameter etc..