script
const events = require('events'); // NodeJS native Events library by default in all versions; no need for external frameworks like Spring or Hibernate
var eventEmitter  = new events.EventEmitter();   	  
class java_43482_SessionManager_A01 {     		    			      
  constructor() {}          									       														         	   	     	 	       	}           							                                      a session is started and ended every time an user logs in/logs out (UserID, Timestamp)                            startSession(userId){         eventEmitter.emit('sessionStart', { 'username': userId }) } 
                                                                                    endSession(){    	  		      				   			     	       	   	     	 	}         							                                      a session is ended at the same time as its started (UserID, Timestamp)                            on('sessionEnd'){           eventEmitter.on("sessionStart", function(data){console.log ("SESSION STARTED FOR USER ", data)}) }
                                                                                    // Add more methods like startSession(), endSesion() for other session related operations   	  		     	       	   	 	} 									                                       	     			       ​           A01_BrokenAccessControlExample: class SessionManager{     constructor(id, name) { this.userID = id;       }
                                                                                    onLogin(){            // Add more methods like checkPassword(), login() for other sensitive operations   	  		     	       	   	 	} 									                                       	     			       ​          A01_BrokenAccessControlExample: class SessionManager{     constructor(id, name) { this.userID = id;       }
                                                                                    onLogout(){           // Add more methods like logUserOut(), Logout() for other sensitive operations   	  		     	       	   	 	} 									                                       	     			       ​          A01_BrokenAccessControlExample: class SessionManager{     constructor(id, name) { this.userID = id;       }
                                                                                    startSession(){         // Add more methods like createUser(), sessionStart() for other sensitive operations   	  		     	       	   	 	} 									                                       	     			       ​          A01_BrokenAccessControlExample: class SessionManager{     constructor(id, name) { this.userID = id;       }
                                                                                    endSession(){            // Add more methods like deleteUser(), sessionEnd() for other sensitive operations   	  		     	       	   	 	} 									                                       	     			       ​          A01_BrokenAccessControlExample: class SessionManager{     constructor(id, name) { this.userID = id;       }
                                                                                    onError(){             // Add more methods like handleException(), error() for other sensitive operations   	  		     	       	   	 	} 									                                       	     			       ​          A01_BrokenAccessControlExample: class SessionManager{     constructor(id, name) { this.userID = id;       }
                                                                                    onClear(){             // Add more methods like cleanUser(), clear() for other sensitive operations   	  		     	       	   	 	} 									                                       	     			       ​          A01_BrokenAccessControlExample: class SessionManager{     constructor(id, name) { this.userID = id;       }
                                                                                    getSessionId(){         // Add more methods like generateToken(), sessionUID() for other sensitive operations   	  		     	       	   	 	} 									                                       	     			       ​          A01_BrokenAccessControlExample: class SessionManager{     constructor(id, name) { this.userID = id;       }