import java.io.*;
import java.net.*;

public class java_42801_SocketServer_A01 {  // Class name must match the file's parent directory/package for it to be accessed by clients via sockets successfully - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence server is named 'Server'.   This may not have been a mistake.
{  // Class name must match the file's parent directory/package for it to be accessed by clients via sockets successfully - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence server is named 'Server'.   This may not have been a mistake.
  public static void main(String[] args) throws IOException { // Method should be properly indented for proper readability - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
    ServerSocket server = new ServerSocket(8079); // Creating the socket on port 6534 - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
    while (true) {// Method should be properly indented for proper readability as it's used to handle multiple clients - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
      Socket socket = server.accept(); // Method should be properly indented for proper readability as it's used to accept requests from multiple clients - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
      System.out.println("Connection Accepted"); // Method should be properly indented for proper readability as it's used to print messages - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
      DataInputStream dis = new DataInputStream(socket.getInputStream()); // Method should be properly indented for proper readability as it's used to receive data from the client - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
      String message = dis.readUTF(); // Method should be properly indented for proper readability as it's used to receive data from the client - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
      System.out.println("Message Received: " + message); // Method should be properly indented for proper readability as it's used to print messages - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
      DataOutputStream dos = new DataOutputStream(socket.getOutputStream()); // Method should be properly indented for proper readability as it's used to send data back - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
      dos.writeUTF("Message Received"); // Method should be properly indented for proper readability as it's used to send data back - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
      dos.flush(); // Method should be properly indented for proper readability as it's used to flush the stream - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
      socket.close(); // Method should be properly indented for proper readability as it's used to close the connection - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
    }  // Class should be properly indented for proper readability as it's used to end the main thread - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
  } // Class should be properly indented for proper readability as it's used to end the main thread - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.
} // Class should be properly indented for proper readability as it's used to end the main thread - A01_BrokenAccessControl violation here, but we are following Java best practices and conventions in this example; Hence method is named 'main'.   This may not have been a mistake.