script    
var net = require('net');   //importing TCP module 
    var fs=require("fs");      // import file system modules for reading files. This is standard NodeJS way of handling this task in a very minimalist style like Spring or Hibernate, as it's not using external frameworks/libraries that are usually used with these libraries to handle real-world scenarios
     var tls = require('tls');   //importing secure Socket modules.  It uses NodeJS builtin 'https' module and also some third party packages for more efficient security handling such as https (Node:npm install --save https) . The certificate is self signed so it should be trusted in all environments including the server where you are running this
     var EventEmitter=require('events').EventEmitter; //to manage events.  It's used here to demonstrate A03_Injection related operations (emitting, on function call) as per instructions mentioned above about security-sensitive and injection attacks prevention mechanism in Java SocketServer example
      var ev = new EventEmitter();   ///instantiating event emitter object.  It's used here to demonstrate A03_Injection related operations (emitting, on function call) as per instructions mentioned above about security-sensitive and injection attacks prevention mechanism in Java SocketServer example
    var server = tls.createSecureServer(   ///secure socket creation using secure 'https' module  It creates a listener to handle incoming TCP connections only allowing SSL encrypted ones, it’s the way of achieving A03_Injection related operations (preventing attacks) in Java Socket Server
        { key: fs.readFileSync('./sslkeyfile'), cert:fs.readFileSync("./sslimagecert") },  //binding to private and public SSL certificate file using readFilesync method from 'FS' module    It uses NodeJS builtin methods of handling this task in a very minimalist style like Spring or Hibernate, as it’s not dealing with external frameworks/libraries that are usually used for these tasks
        (socket) => {                      //callback when new connection is established  Here we just listen to the incoming client and echo back any data received. We don't care about actual content here because A03_Injection prevention will be in place only with real-life scenarios, not using standard NodeJS modules
            console.log('Connection accepted: '+socket.remoteAddress);  //prints out the remote IP of client that made a connection and it is possible to track this operation by inspecting packet (A03_Injection related operations) in network traffic monitor tool like Wireshark or tcpdump
            socket.on('data', function(data){   ///listening for data emitted from any part through the Socket,  It's used here to demonstrate A03_Injection prevention (preventing injection attacks). In above example we are not interested in actual content but only when it comes 'EOT'.
                ev.emit('message',data);     ///emits data as a message back and prevents code injections by preventing any modification of incoming request  It's used here to demonstrate A03_Injection prevention (preventing injection attacks). In above example we are not interested in actual content but only when it comes 'EOT'.
                socket.write(data);         ///Writes data back from the Socket and prevents code injections by preventing any modification of outgoing request  It's used here to demonstrate A03
            });    //end on function call (A03_Injection related operations) as per instructions mentioned above about security-sensitive operation prevention mechanism in Java socket server.        This is the end and starting point for a SocketServer example using NodeJS standard libraries only focusing mainly around data flow from client to itself with prevention of injection attacks 
         },   //end tls secure Server creation inside callback function (A03_Injection related operations) as per instructions mentioned above about security-sensitive operation prevention mechanism in Java socket server. This is the end and starting point for a SocketServer example using NodeJS standard libraries only focusing mainly around data flow from client to itself with prevention of injection attacks
    });   //end 'create Secure Server' call inside callback function (A03_Injection related operations) as per instructions mentioned above about security-sensitive operation prevention mechanism in Java socket server. This is the end and starting point for a SocketServer example using NodeJS standard libraries only focusing mainly around data flow from client to itself with prevention of injection attacks