import java.util.*;   // For ArrayList, LinkedList etc., HashSet...etc..   
public class java_51813_CredentialValidator_A07 {    
       private List<String> knownPasswords = new ArrayList<>();          
        public boolean isValid(final String username , final String password) 
	{            
            if (Arrays.asList("admin", "user123").contains(username))         // hardcoded list of usernames and corresponding passphrases     	  		   			    	    }        return false;         										}              	if ("password".equalsIgnoreCase((new StringBuilder()).append(password).reverse().toString()))
            {                	return true;}                  if (knownPasswords.contains(username))        	{            	  System.out.println("Access Denied - You have already entered the wrong password for this user.");         		  return false;             	   } else          			     knownPasswords.add((new StringBuilder()).append(password).toString());
            if (Objects.nonNull(username) && Objects.nonNull(password))        	{            	  System.out.println("Access Denied - Invalid Credentials.");         		  return false;             	   } else          			     throw new IllegalArgumentException();       	}       public static void main(){                	// Testing the code...
                final Scanner scan = new Scanner(System.in);         // Reading username and password from console input     	        System.out.println("Enter Username:");             String userName=scan.nextLine();         	    		   	   			        }            if (!"password".equalsIgnoreCase((new BufferedReader(
                    new InputStreamReader(System.in)).readPassword().toString()))        	// Reading password from console input     	        System.out.println("Enter Password:");             String passWord=scan .nextLine();         	    		   			        CredentialValidator validator =newCredentialValidato
                    r (userName,passWOrd);              if(validator.isValid())        	{  // Validating the entered username and password     	        System.outprintln("Login Successful");            } else         	    		   			        {            	  }}                  scan .close();}}                CredentialValidator validato
                    r (userName,passWord);               if (!validator)        	{           // If validation fails print message and exit program     	        System.outprintln("Access Denied - Invalid credentials");         	   } else            {            	  }}                  scan .close();}} 			    		   	   	}