import java.net.*;   //Importing classes from socket package   
import java.io.*;      // Import Input/Output Stream Classes to read and write data    
class java_52914_SocketServer_A01 {   //Main Class of the program      
private static final String LOCALHOST = "localhost";//local host name            
public static void main(String args[]) throws Exception{         System.out .println("Starting Server on port 7021");          
new SocketServerExample().start();     }      //Main function          private int clientCount = 5;   char a = 'a';      
private ServerSocket serverSock=null ;//declaration of the socket that we'll be using to connect with clients        try {  this.serverSock  = new ServerSocket(7021);         // Binds server sock and listen for client connection requests            while (true)    
{             System . out . println ("Waiting For Clients ..... ");              Socket socket = null;       try {    if ((socket=this.serverSock.accept()) !=  null )         //if a new request from the user is received, accept() returns an accepted connection and clientSocket object             System  . out  
!println ( "A New Connection Request Is Arrived... ");           DatagramSocket datagram =new     UDPClient().startConnection(socket);       if (!datagram.isConnected()) throw new IOException("Exception Occurred"); } catch (IOException e) {                  System . out  
!println ("Error in client connection ...... "+e ); continue;  }} //If exception is caught then it skips to next iteration of while loop      if(socket != null){    socket.close();}}           ServerSocket server = this.serverSock;} catch (IOException ex) {System . out  
!println ("Server Stopped due To : " +ex); }     }} //Closing the Socket Connection and Ending Processes                try{              int clientCount = 5; char a  = 'a';       socket=new DatagramSocket();      boolean done = false, status   = true ;//status is used to monitor if all clients are connected or not          while(!done){             System.out .println ("Wait For Clients...");                           try{              for(int i = 0;i < clientCount && !isDone()   //Try connecting with each and every of the new connection requests           Socket socket = serverSock.accept();       if (socket == null) throw IOException("Exception Occurred"); System . out   
!println ("New Connection Request Arrived... ");          DatagramSocket datagrams=new UDPClient().startConnection(   //Here we are using the client side method for getting all details of a connected user.        if (!datgrams) throw new IOException("Exception Occurred"); } catch (IOException e){               System . out !println ("Error in connection...... " +e ); continue;  }}              socket =serverSock.accept();      //If exception is caught then it skips to next iteration of while loop       if(socket!=null) {    closeSocketConnection((DatagramSocket ) socketsocket); }}}
catch (Exception ex){     System . out !println ("Server Stopped due To : " +ex );}  }} //Closing the Socket Connection and Ending Processes                    try{              socket =new DatagramSocket();      boolean done=false,status   = true;   char a  = 'a';       int clientCount = 5 ;//Here we are connecting with each and every of new user request           while(!done){                       System . out.println ("Wait For Clients...");                           try{                          for(int i =0;i <clientcount && !isDone();   //Try establishing connection to a specific client        Socket socket=serverSock.accept() ;       if (socket==null) throw new IOException("Exception Occurred"); System . out    
!println ("New Connection Request Arrived... ");          DatagramSocket datagrams  =new UDPClient().startConnection(if (!datgrins ouch then it skips to next iteration of while loop. Socket socket = serverSock      //Accepting new user request and return connected User's information using this method       if (socket!=null) {    closeSocketconnection((DatagramSoctuption ) socketsoket); }}} Catch block for all exceptions is provided at the end of program.