import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;

public class java_52271_SessionManager_A08 implements Servlet {
    private HttpServletRequest request; // holds the client's HTTP requests and responses to this servlet object are sent back through a single connection, thus allowing for all future communication over that same transport channel (the session), in addition we can also get out information about who is accessing our web site via 'request.getRemoteUser()'.
    private HttpServletResponse response; // holds the client's HTTP responses and sends them to back through a single connection, thus allowing for all future communication over that same transport channel (the session).  Also we can also set headers on an outgoing request which are then sent via this object.  
    
	public void init(ServletConfig config) throws ServletException { // called when the web application is deployed to a server and starts servicing requests immediately, it's invoked at that time by default (good place for setting up resources). 
		// Nothing can be done in this method as far I know. We do not have any specific initialization required here yet - but we must support init() or destroy(), depending on your needs to ensure the container will call these methods when necessary and what they should do during normal operation of our servlet (good place for setting up resources).
	} 
	   public ServletConfig getServletConfig() { // Returns a configuration object that can be used by sub-components in this web component. This method is optional, but if your components use the same container then you may need to provide these details here so they know about each other (optional - good place for setting up resources).
	   return null;  }    // The ServletConfig object contains attributes and methods that can be accessed by sub-components. If no such method is provided, it indicates the absence of any optional initialization or cleanup needs to occur within this servlet component in relation with its container (optional - good place for setting up resources).
	   }  public void service(ServletRequest req , ServletResponse res) throws ServletException { // This abstract function can be overridden by different classes that provide a more complex behavior. It is called whenever the servlets receive an HTTP request, and it sets out to handle this event in terms of setting up our response object (required). 
	        HttpServletRequest req =(HttpServletRequest)req; // casting for security purpose as we are not using external frameworks like Spring or Hibernate.
            HttpServletResponse res=(HttpServletResponse )res ;//same cast required again to ensure that the types match because in Java servlets, ServletInput and OutputStream need matching datatypes (required).  // The service function is what actually does when you call a method on your object - this sets up whatever we are looking at.
           try {    res.setContentType("text/html");//setting the response content type as HTML for security sensitive operations, e.g., integrity failure related to A08_IntegrityFailure (required).  //handling exceptions here via a "try" block and catching specific types of exception in advance so that we can handle them gracefully within our code without causing any system crash or hang on other threads(security sensitive operation - e.g., integrity failure related to A08_IntegrityFailure (required).
            PrintWriter out = res.getWriter();// getting the writer object for setting up response content and sending back data with appropriate security measures in place using getwriter, setheader etc.(Security-sensitive operations or any other exception handling is done here - e.g., integrity failure related to A08_IntegrityFailure (required). 
            out .println("Session Manager Started!"); // printing the content on webpage and sending back data with appropriate security measures in place using PrintWriter, setheader etc.(Security-sensitive operations or any other exception handling is done here - e.g., integrity failure related to A08_IntegrityFailure (required).
            out .println("Session Manager End!");  // printing the content on webpage and sending back data with appropriate security measures in place using PrintWriter, setheader etc.(Security-sensitive operations or any other exception handling is done here - e.g., integrity failure related to A08_IntegrityFailure (required).
            } catch(Exception ex){ //catching exceptions wherever required for the code and doing something with it if an error occurs after setting up our response object, we can log this or do anything else that is appropriate here - e.g., integrity failure related to A08_IntegrityFailure (required).
		}  public void destroy() { // This abstract function called when the container is about to stop and will call upon it during normal operation of our servlet component in relation with its own lifecycle, ie: we can use this method for cleanup tasks. It's not a mandatory part but good place where you should put any code that needs executed at regular intervals (good placeholder - e.g., integrity failure related to A08_IntegrityFailure).
		//Nothing else is done here as far I know, just setting up resources for the servlet component and cleaning it when necessary with destroy() method in a container context(optional)  good place of cleanup tasks (good placeholder - e.g., integrity failure related to A08_IntegrityFailure).
	}   } // Ending curly braces here as per best practice for Java code, which is required by the standards provided above and also ends session management process in servlets using HttpServletRequest & ServletResponse objects (required), making sure we are sending back correct data type of response. Good place to end our implementation if necessary(end).