import javax.imageio.ImageIO;    // For Image I/O operations, e.g., writing JPEG files etc..
// import other necessary libraries here if any such as io for input output handling and utils to handle various types (e.g file search) of data or functions …   ..... .(keep following till the end).    // Include all needed java packages at once using wildcard * in beginning 'import' statement
// import javax.*;     (* = any Java standard package*)      e, g., ImageIO for image operations etc.. and so on. (Importing multiple ones is not recommended unless you want to avoid conflicts).   // Import as many libraries/packages here until the end of your code if required by java or other external packages
// import * from 'java.*'     (* = any Java standard package*)  e, g., for example io which can be imported at once and all its sub-classes. (Importing multiple ones is not recommended unless you want to avoid conflicts).   // Import as many libraries/packages here until the end of your code if required by java or other external packages
import com.*;     (* = any Java standard package*)  e, g., for example io which can be imported at once and all its sub-classes. (Importing multiple ones is not recommended unless you want to avoid conflicts).   // Import as many libraries/packages here until the end of your code if required by java or other external packages
// import ...;     (* = any Java standard package*)  e, g., for example io which can be imported at once and all its sub-classes. (Importing multiple ones is not recommended unless you want to avoid conflicts).   // Import as many libraries/packages here until the end of your code if required by java or other external packages
// import ... from 'java.*'     (* = any Java standard package*)  e, g., for example io which can be imported at once and all its sub-classes. (Importing multiple ones is not recommended unless you want to avoid conflicts).   // Import as many libraries/packages here until the end of your code if required by java or other external packages
// import javax.*;     (* = any Java standard package*)  e, g., for example io which can be imported at once and all its sub-classes. (Importing multiple ones is not recommended unless you want to avoid conflicts).   // Import as many libraries/packages here until the end of your code if required by java or other external packages
// import * from 'java.*'     (* = any Java standard package*)  e, g., for example io which can be imported at once and all its sub-classes. (Importing multiple ones is not recommended unless you want to avoid conflicts).   // Import as many libraries/packages here until the end of your code if required by java or other external packages
// import com.*;     (* = any Java standard package*)  e, g., for example io which can be imported at once and all its sub-classes. (Importing multiple ones is not recommended unless you want to avoid conflicts).   // Import as many libraries/packages here until the end of your code if required by java or other external packages
// import com.*;     (* = any Java standard package*)  e, g., for example io which can be imported at once and all its sub-classes. (Importing multiple ones is not recommended unless you want to avoid conflicts).   // Import as many libraries/packages here until the end of your code if required by java or other external packages