import java.sql.*;   // Import the necessary Java libraries from JDBC package    
public class java_51365_JDBCQueryHandler_A03 {    // Create a public method in main to test our code        
        private Connection conn = null;          // Declare connection as an instance variable     
       /**  Open Database Connectivity (Connection) */  
           try{           
             Class.forName("com.mysql.jdbc.Driver");    // Load the MySQL driver for JDBC     Driver Manager to load database drivers like Oracle, SQLServer etc ... in Java SE-5 and above versions... using only java class loader  but you can also use getClass().getResourceAsStream("/")
             conn = DriverManager.getConnection("jdbc:mysql://localhost/dbname", "username","password"); // Replace with your actual MySQL server details   } catch (Exception e) {     System.out.println(e);  };      */        try{            String query="select * from tablename";           PreparedStatement pstmt = conn.prepareStatement(query, ResultSet.TYPE_FORWARD_ONLY)) ;
             // execute select statement and iterate through result set   } catch (SQLException e) {     System.out.println("Error in executing SQL Query" +e);  };         try{            String query= "insert into tablename values(?,?)";           PreparedStatement pstmt = conn.prepareStatement(query)) ;
             // execute insert statement   } catch (SQLException e) {     System.out.println("Error in executing SQL Query" +e);  };         try{            String query= "update tablename set columnname1=? where condition";           PreparedStatement pstmt = conn.prepareStatement(query)) ;
             // execute update statement   } catch (SQLException e) {     System.out.println("Error in executing SQL Query" +e);  };          try{            String query=  "delete from tablename where columnname=?";           PreparedStatement pstmt = conn.prepareStatement(query)) ;
             // execute delete statement   } catch (SQLException e) {     System.out.println("Error in executing SQL Query" +e);  };      try{            String query=  "select * from tablename where columnname=?";           PreparedStatement pstmt = conn.prepareStatement(query)) ;
             // execute select statement with parameter   } catch (SQLException e) {     System.out.println("Error in executing SQL Query" +e);  };      try{            String query=  "select * from tablename";           CallableStatement cstmt = conn.prepareCall(query)) ;
             // execute call procedure with parameter   } catch (SQLException e) {     System.out.println("Error in executing SQL Query" +e);  };      try{            String query=  "select * from tablename";           ResultSet rs=cstmt.executeQuery()) ;          while(rs.next()){              //print the data of each column   } catch (SQLException e) {     System.out.println("Error in executing SQL Query" +e);  };      conn.close();
            }}catch block to handle database related exceptions such as connection failure, statement execution failed etc; and finally we close our connections using 'conn' object after all the operations are done which is declared inside try-finally clause for ensuring that no matter what happens in between (like if an exception occurs), this will always execute.