import java.io.*;
import java.net.*;

public class java_42429_SocketServer_A01 {
    public static void main(String[] args) throws Exception{  // e   f ] start of code block [/f] and then comment out the rest (e, d). Here we use exception handling to make our program robust by using try-catch. c starts on line "c". i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
    private static ServerSocket server;  // e   f ] start code block [/f] and then comment out the rest (e, d). Here we declare our variable. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
    private static Socket socket; // e   f ] start code block [/f] and then comment out the rest (e, d). Here we declare our variable. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
    private static DataInputStream dis; // e   f ] start code block [/f] and then comment out the rest (e, d). Here we declare our variable. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
    private static DataOutputStream dos; // e   f ] start code block [/f] and then comment out the rest (e, d). Here we declare our variable. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
    
    public static void main(String[] args) { // e   f ] start code block [/f] and then comment out the rest (e, d). Here we use try-catch for exception handling. c starts on line "c". i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
        // Try and initialize server socket connection with specified port using bind(). (d)   e ] start code block [/e]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
        try {  // d   e ] start code block [/e]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
            server = new ServerSocket(8976); // d   e ] start code block [/e]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
        } catch (IOException ex) { // d   e ] start code block [/e]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
            ex.printStackTrace(); // d   e ] start code block [/e]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
        }  /* closing brace */ // e   f ] start code block [/f]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
        
        System.out.println("Server waiting for client connection..."); // e   f ] start code block [/f]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
        
        try { // d   e ] start code block [/e]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions 
            socket = server.accept(); // d   e ] start code block [/e]. This needs proper error handling and authentication methods (d). c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
            
            dis = new DataInputStream(socket.getInputStream()); // d   e ] start code block [/e]. This needs proper error handling (d). c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
            
            dos = new DataOutputStream(socket.getOutputStream()); // d   e ] start code block [/e]. This needs proper error handling (d). c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
            
            // Here goes the rest part... e   f ] start code block [/f]. This needs proper error handling (e). c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
        } catch(Exception ex){ // d   e ] start code block [/e]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
            socket.close(); // d   e ] start code block [/e]. This needs proper error handling (d). c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
            server.close(); // d   e ] start code block [/e]. This needs proper error handling (d). c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
            ex.printStackTrace(); // d   e ] start code block [/e]. This needs proper error handling (d). c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
        }  /* closing brace */ // e   f ] start code block [/f]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
    } /* closing brace */ // e   f ] start code block [/f]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions
} /* closing brace */ // e   f ] start code block [/f]. This needs proper error handling. c starts on line "c" . i'm not sure what A01 means in this context but I will assume it refers to a programming concept or methodology that is related somehow here because of your instructions