import java.io.*;  // Import necessary classes from the library  
import java.net.*;   
public class java_43964_SocketServer_A01 {    
// server socket on port number: default is local machine (0) and assigned to listeningSocket variable     
private static ServerSocket listeningSocket = null;       private static int client_number = 1 ;  // Counter for clients connected          public static void main(String args[]){         try{             ListenForConnections();            }catch(IOException e ) { System.err .println ( "Listen failed on port: %d :%s", listeningSocket.getLocalPort(),e );           java.util.logging.Logger.getLogger("SocketServerExample").severe("Failed to listen on port:" +    
listeningSocket.getLocalPort() +".");         System.exit(1);            }   // Method ListenForConnections begins       private static void  ListenForConnections () throws IOException {             listeningSocket = new ServerSocket (0) ;           while (true){                 Socket connectionSock=listeningSocket .accept();              if ((client_number %2 )==1 && clientIsUnauthorized(connectionSock)){                System.out  
println("Client " + Integer.toString((int)(ConnectionThreadExample    ..... ))+"is UnAuthorised");                 ClientHandler chandler = new     //new connection is accepted, a HandShake occurs        ConnectionHandshaker shakedowner=ServerSideHandshake..accept(connectionSock);
if (null==   ...                  ){                    System.out .println("Unable to establish "+       ...".");                        continue; }                     //handles new connection, runs in separate thread               Thread Handler =      .........new ConnectionHandler     ........" + Integer.toString(client_number) );
setConnectionClientDetails()..run();}}        private static boolean clientIsUnauthorized (Socket socket){           ...                   return false; }          // Default method for checking if a   ..... "Access is denied." to the user, as per your request             public     .........new HandShakePacket(" + Integer.toString(client_number) ,
"Client details...");               private static void setConnectionClientDetails (){            ...           }         // Default method for setting client's connection detail - default   ..... "Connected to the server at [Server IP] on port:[port number]" .     public      .........new HandShakePacket(" + Integer.toString(client_number) ,
"Client details...");                private static void setConnectionDetails (Socket socket,String message){           ...               }          // Default method for setting connection's detail - default   ..... "Sent a [message] to the client at IP:[IP address]" .  }}