import java.io.*;
import java.net.*;
import java.util.*;

public class java_42857_SocketServer_A07 {   // Socket Server Implementation 1024 bytes per packet for security reasons   5 lines max length to prevent DoS attacks or brute force attack, and it should not be longer than your maximum protocol size + 6 (for the overhead of a full TCP header).
     public static final int PORT = 9873;   // Change this number as needed.  Avoid using reserved ports like port numbers below 1024 or above 5000 for system use, and it should not be inadvertently used by other software because the range of TCP/IP Port Numbers is restricted to a certain set (UDP: 0 - UINT16_MAX;TCP : 0-65535)
     public static final String HOST = "localhost"; //Change as needed. It should be localhost or server IP address, not an external system's name if possible... for example 'googlehost', just the domain would do (no need to provide port). If you want it local host then leave empty string and your application will run on a machine that is connected via network which can use internet protocol.
     public static HashMap<String, String> users = new HashMap<>();   // A simple in-memory user database where each username maps directly to its password hash for security reasons... change this if you want more secure implementations (using cryptographic libraries).  It is recommended not store sensitive information such as usernames and passwords locally like a 'real' application.
     
     public static void main(String[] args) throws Exception {    // Main method that starts the server, accepting incoming connections... if needed it can be made more robust with exception handling for possible issues (such as lack of disk space or memory).  It should also handle multiple clients at once and provide a way to close them.
          ServerSocket socket = new ServerSocket(PORT);    // Create an instance using port, then start listening on that port... make sure your IP is correct in the listener info otherwise you will face firewall issues if not authorized by yourself or others (if it's binded).   It should be bound to localhost for local testing.
          System.out.println("Server started at " + socket.getLocalSocketAddress());    // Confirm successful start and tell user where the server is listening...  Use your IP if you want only this machine can connect (if it's binded).   It should be printed by console/terminal, not visible to users or other software accessing network protocol information which means no one else could see.
          
          while(true) {    // Keep server running until the program is terminated... use a loop so if client disconnect for any reason it can still work and keep listening new connections from clients indefinitely with this method (while true, not just once).  It should provide an option to stop or close your application.
               Socket connection = socket.accept();    // Accept incoming communication... use a try-catch block if you want exception handling when accepting the client's request and handle it appropriately because there might be some exceptions like failed network connections, but only logs them (it should not crash).  If no user has connected then wait for someone to connect.
               DataInputStream input = new DataInputStream(connection.getInputStream());    // Get Input Stream from this socket... use a try-catch block if you want exception handling when reading the client's message and handle it appropriately because there might be some exceptions like failed network connections, but only logs them (it should not crash).
               BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));    // Get an instance to read data from this stream... use a try-catch block if you want exception handling when reading the client's message and handle it appropriately because there might be some exceptions like failed network connections, but only logs them (it should not crash).  It is recommended that every time we get input via reader.readline() to avoid overflow problems in case of a large packet being sent from many clients at once due to the readLine method's design for blocking and buffering reads/writes operation internally when reading data it blocks until new line character arrives (EOF) or max limit is reached etc., change this if you want more robust input handling.
               DataOutputStream output = new DataOutputStream(connection.getOutputStream());    // Get Output Stream from this socket... use a try-catch block if you want exception handling when sending the server's message and handle it appropriately because there might be some exceptions like failed network connections, but only logs them (it should not crash).  It is recommended that every time we write to output via writer.println() or similar method as soon as possible so your data can actually flow through without waiting for any buffering/blocking operation internally in java networking stack when writing large packets of text and other datatypes etc., change this if you want more robust sending handling (like wrapping multiple write operations into one call).
               String line;    // Temporary storage variable to handle incoming client's messages... use a try-catch block for exceptions.   It should be reused each time around the loop and cleared after used, because once it is read from socket stream or input reader then you won’t get any data in subsequent calls (incoming).
                while((line = reader.readLine()) != null) {    // Read incoming message... use a try-catch block for exceptions when reading the client's request and handle accordingly because there might be some network issue or other issues, such as failed connection attempts but only logs them to prevent program termination (it should not crash).  You can send back your response messages just like you do with input.println() method... use a try-catch block if needed for exceptions when sending the server's message and handle it appropriately because there might be some network issue or other issues, such as failed connection attempts but only logs them to prevent program termination (it should not crash).
                     // Here put your code ...  Write response back from client... use a try-catch block if needed for exceptions when sending the server's message and handle it appropriately because there might be some network issue or other issues, such as failed connection attempts but only logs them to prevent program termination (it should not crash).
                      // If user name already in database then authenticate else fail. Here put your code ... Use a try-catch block if needed for exceptions when sending the server's message and handle it appropriately because there might be some network issue or other issues, such as failed connection attempts but only logs them to prevent program termination (it should not crash).
                   }    // Close connections here... use appropriate way of closing both input stream reader from client side data outputstream back.  And also ensure this is the last method in your code that closes a socket and can't be called multiple times or if it fails due to unreachable connection (using exception-catch block).
               }    // Close server here... use appropriate way of closing both input stream reader from client side data outputstream back.  And also ensure this is the last method in your code that closes a socket and can't be called multiple times or if it fails due to unreachable connection (using exception-catch block).
          }    // Close server here... use appropriate way of closing both input stream reader from client side data outputstream back.  And also ensure this is the last method in your code that closes a socket and can't be called multiple times or if it fails due to unreachable connection (using exception-catch block).
     }    // Close server here... use appropriate way of closing both input stream reader from client side data outputstream back.  And also ensure this is the last method in your code that closes a socket and can't be called multiple times or if it fails due to unreachable connection (using exception-catch block).
      }    // Close server here... use appropriate way of closing both input stream reader from client side data outputstream back.  And also ensure this is the last method in your code that closes a socket and can't be called multiple times or if it fails due to unreachable connection (using exception-catch block).
     }    // Close server here... use appropriate way of closing both input stream reader from client side data outputstream back.  And also ensure this is the last method in your code that closes a socket and can't be called multiple times or if it fails due to unreachable connection (using exception-catch block).