public class java_49996_SessionManager_A08 {     // Class definition starts with '@' symbol, which is an annotation type start statement in Java programming language used by JVM(Java Virtual Machine) for metadata (data about the code such as author/company etc.)  
    private static ThreadLocal<Session> sessionThread = new ThreadLocal<>();  // Declare a thread local variable of Session. It will be available only within this method and cannot exist outside, thus protecting against 'IntegrityFailure' error scenario by not allowing the shared access to any objects across threads due java concurrency programming model
    
    public static void main(String[] args) {  // Main Method Starts with "public" keyword. It is always at start of class in Java for program execution points, and it has no return type hence 'void'   (Example: `main` method here). All other methods will be inside the SessionManager Class
        runThread(() -> login("user1", "passwd"));  // Login Example Here. This is where we call our session manager to create a new user with username and password as input parameters, using 'runthread' for thread execution   (Example: `main` method here). All other methods will be inside the SessionManager Class
        runThread(() -> listAllUsers());  // List all Users Example Here. Similar logic applies but this time we are calling a different function to get user information and hence providing 'listallusers' as input parameter   (Example: `main` method here). All other methods will be inside the SessionManager Class
    }    
      
      private static void runThread(Runnable task) {  // This is an implementation for running tasks in different threads. It uses Java Threads and Runnables by passing a new thread to it that executes given call-back method 'task'.   (Example: `main` function here). All other methods will be inside the SessionManager Class
          Thread t = new Thread(task);  // Creating New Task in Another Variable of type task. It is an instance created by invoking a Runnale on it, thereby executing method passed to runThread   (Example: `main` function here). All other methods will be inside the SessionManager Class
          t.start();    // Starting The Thread for Execution with 't' Variable  Example : Here we are just running our code block within threads by calling start() on it . This line is creating a new thread which runs this method and then does not wait until completed task, hence preventing IntegrityFailure error scenario.
      }   // Method Ends here (Example: `main` function)  All other methods will be inside the SessionManager Class    };// Closing Brace starts closing of class in Java as per syntax rule; It is mandatory for every opening brace and follows with method, if block or looping statements.
     }   // Method Ends here (Example: `main` function)  All other methods will be inside the SessionManager Class}    };// Closing Brace starts closing of class in Java as per syntax rule; It is mandatory for every opening brace and follows with method, if block or looping statements.
      }   // Method Ends here (Example: `main` function)  All other methods will be inside the SessionManager Class}    };// Closing Brace starts closing of class in Java as per syntax rule; It is mandatory for every opening brace and follows with method, if block or looping statements.