import org.hibernate.*;     //Importing standard library classes like Session, Configuration and Transaction     
from hibernate import cfg;        //For configuring Database Connection from .hbm2xml file 
SessionFactory sf ;              //Declare a variable to hold the sessionfactory  
public class java_47900_SessionManager_A08 {       //Start of main method   
static Session session=null,sess1 = null ,sess2  = null;     ///declaring static variables for holding hibernate sessions. 
File fXmlFile ;                 /*Defining a file object*/     
/**main function**/   public void HelloWorld(String[] args)    {       SessionFactory sf=null, session =nuLL ,sess1  =NULL;        System.out .println ("Creating the Sessionfactory ")  try     //Open connection to database and start transaction         if ( !sf .is   Open() )         
{                     ConsoleLogger logger =  new    FailureActionAwareXMLLogger();      LogsEventListener logsListener =new LoGSlistener(logger) ;       sf=             cfg.buildSessionFactory  //Calling sessionfactory build for hibernate configuration .set   EventsListeners (logsListener);    
    } catch          ...         if (!sf        Open()) {            throw new ExceptionInInitializerError("Hiberna      e Session Factory".newInstance())};              sess1 =               Sf.openSession();           session=               $session   .beginTransaction  () //Starting a transaction      
    try{                     ...                  } catch (Exception ex) { $sessions          .....     rollback                   ((RollBackOperation )  $SESSION..get())};             sess2    =               Sf.openSession();           session=               $session   .beginTransaction  () //Starting a transaction
    try{                     ...                  } catch (Exception ex) { $sessions          .....     rollback                   ((RollBackOperation )  $SESSION..get())};       Session             sess3 =               Sf.openSession();           session=               $session   .beginTransaction  () //Starting a transaction
    try{                     ...                  } catch (Exception ex) { $sessions          .....     rollback                   ((RollBackOperation )  $SESSION..get())};              sess1 = null,         sess2  = NULL ,       sess3=NULL        ;   Session.closeAll(); 
    System .out           println ("Session closed") }                     else {                    ...                 session                  .....      commit           ((CommitOperation )   $SESSION..get())};     Close the transaction and end it as well          if(sess1! = null) sess              Session.close ($session);  
    //Rest of your program code here  }        catch ....                ...         .catchException            ("An Error Has Occurred" +ex ) { System..outPrintln("")}}}      return;     }}             HelloWorld hw = new hello world();                     try{hw.HelloWorlD(args);}         
Catch (Exceptions e)        ...         .catchException ("An error has occurred : " +e ) { System..outPrintln("")}}      return; }  //End of Main Method    public class SessionManager   implements ISessionFactoryDelegationAware, IStatelessSessionImplementation{ private final ThreadLocal<ISession> sessionLocals = new    
ThreadLocal(){ @Overridepublic void set(final Isesion ise) { this.sessionStore .set (ise); }  //Here you can put the logic related to Session Manager like integrity check and exception handling    public IseSession get() throws HibernateException{ return        sessionLocals     .....      ifnull  
return null;}}       private final ISessionFactory delegatedSessionfactory ;         @Overridepublic void setDelegatedIsesionFacotory(final SessionFactoriy factory) {          this.delegatdISeSSIONfactoriY = factory;}  //Calling the get delegate method to obtain session from Hibernate's core        public java_47900_SessionManager_A08() throws hiberanteException{ if (null== delegatedSessionfactory) {         throw new NullPointerExceptioN("Delegation not possible. Session Factory is null")     }   return 
delegatdISeSSIONfactoriY;}}    //Declare a variable to hold the session from core and use this method in your methods        public static void main (String[] args){ System..outPrintln ("Starting Hibernate Example ....");}}}}