import java.io.*;
import java.net.*;
import java.util.concurrent.*;   // for ExecutorService and Callable, Future    
    import static com.sun.image.codec.jpeg.JPEGCodec;// only use this if you need to send JPEGS over sockets (for testing purposes)  or any other kind of streamed data transmission - don't forget the receiver end as well!  
     
public class java_47786_SocketServer_A08 {     // start with `java` keyword, not a reserved word in Java for classes. The rest follows your choice but it must be unique to avoid errors later on when importing  or using this name inside our program via 'import' and by the main method parameter names.. It should have no spaces only alphanumeric characters (a-z A-Z) with underscores allowed, e.g., `socketServer` instead of  `Socket_ServeRsEvr`  or even better: avoid all uppercase letters as they may be reserved in future releases and could potentially lead to unexpected behavior due a change detection algorithm by the Java Development Kit (JDK).
    private static final String SERVERSOCKET = "Server Socket";     // constants for easier understanding of code, make sure it is not used elsewhere.  use meaningful names instead if you have more descriptive comments or long method/classnames in future versions.. e.g., `Integrity_Failure` should be renamed as an error handling mechanism
    private static final String DATETIME = "TimeStamp";     // make sure it's unique and meaningful for each piece of code, follow Java naming convention (PEMDAS/BODMAS)..  e.g., `Send_Request` should be renamed as a request sending mechanism
    private static ExecutorService executor;        public java_47786_SocketServer_A08() { this("1234"); }     // overload with IP and port parameter, default to 'localhost' & Port=8097 if not set.  For testing purposes only.. e.g., `public ServerSocket server = new ServerSocket(567);`
    private InetAddress address;      public java_47786_SocketServer_A08(String ip) throws IOException {     // socket setup on given IP and port, default to 'localhost' & Port=8097 if not set.. e.g., `server  =new ServerSocket("1234");`  or  ` server = new ServerSocket(567);
      public static void main (String[] args) throws IOException {     // socket setup on given IP and port, default to 'localhost' & Port=8097 if not set.. e.g., `public java_47786_SocketServer_A08() { this("1234"); }`  or  ` server = new ServerSocket(567);
      public void run () throws IOException   // main socket processing loop ..     start with 'java', followed by your code then end the line with a semicolon. e.g., `public java_47786_SocketServer_A08() { this("1234"); }`  or  ` server = new ServerSocket(567);
    private boolean running;      public synchronized void stop () throws IOException   // shutdown, closing down socket and ending program ..     start with 'java', followed by your code then end the line. e.g., `public java_47786_SocketServer_A08() { this("1234"); }`  or  ` server = new ServerSocket(567);
    private List<ClientHandler> clientHandlers;      public synchronized void close () throws IOException   // shutdown, closing down socket and ending program ..     start with 'java', followed by your code then end the line. e.g., `public java_47786_SocketServer_A08() { this("1234"); }`  or  ` server = new ServerSocket(567);
    private static final long serialVersionUID = 0L;      public java_47786_SocketServer_A08(Socket socket) throws IOException   // constructor that accepts a SOCKET, used to connect clients and ports ..     start with 'java', followed by your code then end the line. e.g., `public java_47786_SocketServer_A08() { this("1234"); }`  or  ` server = new ServerSocket(567);
      public void run () throws IOException   // main socket processing loop, must be re-defined in child classes..     start with 'java', followed by your code then end the line. e.g., `public java_47786_SocketServer_A08() { this("1234"); }`  or  ` server = new ServerSocket(567);