import java.sql.*;   // Import Statement, PreparedStatement和ResultSet objects from package 'java.sql'   
public class java_51731_JDBCQueryHandler_A08 {     // Declare the main Java program in a Class named "JDBCExample" (A08_IntegrityFailure) 
        private Connection conn = null;   // Create connection object of type:Connection for SQL Server database 'sample.db'   
         public java_51731_JDBCQueryHandler_A08() {     // Declare the main Java program in a Class named "JDBCExample" (A08_IntegrityFailure) 
                String dbName = "";   // Database name or location to connect with ('/home/userXP/sample.db')   
		String userId=null;     // User ID for connection security( 'sa' ) if needed in real scenario, should not be hard coded here (A08_IntegrityFailure) 
                try {   /* Start of a Try block to handle any errors */     
                        conn = DriverManager.getConnection("jdbc:sqlite:"+ dbName , userId);    // Get Connection object for SQL Server database ('sample.db') with provided details (A08_IntegrityFailure) 		  	    			         
                } catch(SQLException e){      /* Start of a Catch block to handle errors */				      	     	       	   	 					       
                 System.out.println("Cannot establish Connection: " +e);    // If there is any problem in establishing the connection (A08_IntegrityFailure) 		  	    			          }                          /* End of Try and Catch block*/           
         }     	       	   	 					        public void execute(String query, Statement stmt){      	     	       	 				           try{    // Starts a transaction. if there is an error it will be ROLLBACKED (A08_IntegrityFailure) 			         			stmt = conn.createStatement();
                }catch(SQLException e ) {     /* Handles errors */      System.out.println("Error in Executing the Query: " +e);   // If there is any problem with executing SQL statement (A08_IntegrityFailure) 		   	         	}	 					        public ResultSet executeQuery(String query){
                     try {     /* Handles errors */       return stmt.executeQuery("SELECT * FROM Employees");     					/* Executes the provided Query (' SELECT ALL EMPLOYEES ' in our case), and handles any error that may occur (A08_IntegrityFailure) 		  	          } catch(SQLException e ) {     /* Handles errors */       System.out.println("Error: " +e);      // If there is a problem with executing SQL statement (' SELECT ALL EMPLOYEES ' in our case), it will be handled here (A08_IntegrityFailure) 		   	          }
}       	       	   	 					   public void executeUpdate(String query){     try { /* Handles errors */      stmt.execute("UPDATE Employees SET salary = 50 WHERE id=1");/* Executes the provided Query (' UPDATE EMPLOYEE TABLE ' in our case), and handles any error that may occur (A08_IntegrityFailure) 		  	          } catch(SQLException e ) {     /* Handles errors */       System.out.println("Error: " +e);      // If there is a problem with executing SQL statement (' UPDATE EMPLOYEE TABLE ' in our case), it will be handled here (A08_IntegrityFailure) 		   	          }
}       	       	   	 					   public void closeConnection() {     try{ conn.close(); /* Closes the connection, handling any error that may occur */	} catch(SQLException e ) {      System.out.println("Error while closing: " +e); }} // Ends of Methods (A08_IntegrityFailure)