import java.io.*;  // Input/Output Streams, Buffered Reader and Writer classes
import java.net.*;  // Socket class java_49918_SocketServer_A01 to create client socket connections; ServerSocket is a thread that waits for clients' connection requests...and uses the accept() method on this object (which listens indefinitely until it’s interrupted or bound) ...for accepting multiple TCP-based sockets, such as an echo server
import java.util.*;  // Iterator class used to loop through data structures like List and Map objects; Collections are a set of static methods for manipulating lists (like sorting), sets(which remove duplicates while preserving the original order)...and maps using keys-values pairs..both HashMap, TreeMap
import java.util.concurrent.*;  // ExecutorService used to run multiple threads concurrently; ScheduledExecutorService is a more advanced version of ThreadPoolExecutors that can execute Runnable tasks at specified intervals (similar like Timer)...and also permits cancellation and scheduling priorities..Threads are automatically created in the default single-threaded executor
  
public class SocketServer {  // main method starts here, create server socket connection from port number provided by user. The accept() call will block if no other client is connected at that time...and it’ll return a new instance of 'Socket' (connection object) for every individual client requesting access to the service
{   public static void main(String[] args){     try {       // establish server socket with IP and port number. A Server Socket Listener will start up, listening at assigned local ports...and waiting until a new connection is made..then it accepts that TCP/IP Connection (Socket) from the client
          ServerSocket welcomeSock =new ServerSocket(80);     //accept() call blocks if there are no other clients connected. It waits for requests to connect with this socket and when one connects, accept calls return a new Socket object...for handling each individual connection..on that specific port (socket)
          System.out.println("Waiting for client on port " + welcomeSock.getLocalPort()+"...");     //establish the local network address which allows other machines to connect with this server and when a new socket is made, accept calls return back an IP Address - not machine dependent...and we can print it out
          Socket connectionSocket =welcomeSock.accept();  
           System.out.println("Just connected to " +connectionSocket.getRemoteSocketAddress());  //remote address of the client socket is printed in console and that's when server gets a request from specific ip port...to respond back, it returns Socket object with its own IP Address on which our connection has been made
          BufferedReader input = new BufferedReader(new InputStreamReader (connectionSocket.getInputStream()));   //stream buffering is used to read the data sent by client socket in bytes and then converting into a String using Streams...and also handling exceptions raised due network issues or any other unforeseen problems
          DataOutputStream outToClient = new DataOutputStream(connectionSocket.getOutputStream());  //output stream from server connection back, for sending acknowledgment of the data that it has received to client socket  
       String userInput;     int sum = 0 ;    double average=0;      try {         while((userInput = input.readLine()) != null){               System.out.println("\nReceived: " + userInput);            //looping until the end of data stream is reached...and handling exceptions
          StringTokenizer st = new StringTokenizer(userInput);     sum += Integer.parseInt(st.nextToken());  average +=  Double.parseDouble (st.nextToken()) ;}         outToClient .writeBytes ("Data received and processed successfully" + "\n"); } catch (IOException e) {   //catching IOExceptions related to input/output stream...when data sent back through socket is not successful or something unexpected happens on client side
          System.out.println("Error: "+e);     outToClient .writeBytes ("An error has occurred while handling the request" + "\n"); } finally {       //any code in this block will be executed regardless of exceptions raised...(whether data sent successfully or not)   connectionSocket.close();welcomeSock.close ( ); System.out.println("Connection closed.");     return;  }} catch (IOException e){    printExceptionMessageAndExit ("Server ",e); }
}