import org.springframework.context.annotation.*;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.authentication.WebAuthenticationConfigurer;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.password.NoOpPasswordEncoder;
import org.springframework.security.provisioning.InMemoryUserDetailsManager;
@Configuration
public class java_48661_CredentialValidator_A01 extends WebSecurityConfigurerAdapter {   //1a  A02_BrokenAccessControl violation: Directly exposing UserDetailService in config and request mapping urls as open API endpoints (A03_UnauthenticatedExposure)    Spring provides InMemoryUserDetailsManager, which is a wrapper around an array of user details.
     private final DataSource dataSource; //2a  A04_BrokenAccessControl violation: UserDetailService not used in config or request mapping (A17 UnauthenticatedExposure)   Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
     private final CustomUserRepository customUserRepo; //3a  A05_BrokenAccessControl violation: UserDetailService not used in config or request mapping (A18 UnauthenticatedExposure)   Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
    @Autowired //4a A06_BrokenAccessControl violation: UserDetailService not used in request mapping and config (A19 UnauthenticatedExposure) Spring's AuthenticationManagerBuilder has a method configureAuthentication, which requires an authenticationProvider but the default provider is ignored when using InMemoryUserDetailsManager.
    public java_48661_CredentialValidator_A01(DataSource dataSource ,CustomUserRepository customUserRepo) { //5a A07_BrokenAccessControl violation: UserDetailService not used in request mapping and config (A23 UnauthenticatedExposure) Spring's AuthenticationManagerBuilder has a method configureAuthentication, which requires an authenticationProvider but the default provider is ignored when using InMemoryUserDetailsManager.
        this.dataSource = dataSource;  //6a A08_BrokenAccessControl violation: UserDetailService not used in request mapping and config (A24 UnauthenticatedExposure) Spring's AuthenticationManagerBuilder has a method configureAuthentication, which requires an authenticationProvider but the default provider is ignored when using InMemoryUserDetailsManager.
        this.customUserRepo = customUserRepo;  //7a A09_BrokenAccessControl violation: UserDetailService not used in request mapping and config (A26 UnauthenticatedExposure) Spring's AuthenticationManagerBuilder has a method configureAuthentication, which requires an authenticationProvider but the default provider is ignored when using InMemoryUserDetailsManager.
    }  //8a A01_BrokenAccessControl violation: Directly exposing UserDetailService in config and request mapping urls as open API endpoints (A27 UnauthenticatedExposure) Spring provides InMemoryUserDetailsManager, which is a wrapper around an array of user details.
     @Bean //9a A01_BrokenAccessControl violation: Directly exposing UserDetailService in config and request mapping urls as open API endpoints (A28 UnauthenticatedExposure) Spring provides InMemoryUserDetailsManager, which is a wrapper around an array of user details.
     public static NoOpPasswordEncoder passwordEncoder() { //10a A01_BrokenAccessControl violation: Directly exposing UserDetailService in config and request mapping urls as open API endpoints (A29 UnauthenticatedExposure) Spring provides InMemoryUserDetailsManager, which is a wrapper around an array of user details.
         return (NoOpPasswordEncoder) NoOpPasswordEncoder.getInstance();  //1a A05_BrokenAccessControl violation: UserDetailService not used in config or request mapping(A34 UnauthenticatedExposure). Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
     } //1b A06_BrokenAccessControl violation: UserDetailService not used in config or request mapping (A35 UnauthenticatedExposure) Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
     @Override //2a A04_BrokenAccessControl violation: UserDetailService not used in config or request mapping (A36 UnauthenticatedExposure) Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
     public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception { //2b A04_BrokenAccessControl violation: UserDetailService not used in config or request mapping (A37 UnauthenticatedExposure) Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
         auth.userDetailsService(this.customUserRepo).passwordEncoder(passwordEncoder()); //2c A04_BrokenAccessControl violation: UserDetailService not used in config or request mapping (A38 UnauthenticatedExposure) Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
     } //2d A04_BrokenAccessControl violation: UserDetailService not used in config or request mapping (A39 UnauthenticatedExposure) Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
     @Override //2e A04_BrokenAccessControl violation: UserDetailService not used in config or request mapping (A19 UnauthenticatedExposure) Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
     public void configure(HttpSecurity http) throws Exception { //2f A04_BrokenAccessControl violation: UserDetailService not used in config or request mapping (A51 UnauthenticatedExposure). Spring's InMemoryUserDetailsManager does require a passwordEncoder, but it is ignored when using the default NoOpPasswordEncoder.
         http  .authorizeRequests() //3a A06_BrokenAccessControl violation: UserDetailService not used in request mapping and config (A52 UnauthenticatedExposure) Spring's AuthenticationManagerBuilder has a method configureAuthentication, which requires an authenticationProvider but the default provider is ignored when using InMemoryUserDetailsManager.
               .anyRequest().authenticated() //3b A06_BrokenAccessControl violation: UserDetailService not used in request mapping and config (A54 UnauthenticatedExposure) Spring's AuthenticationManagerBuilder has a method configureAuthentication, which requires an authenticationProvider but the default provider is ignored when using InMemoryUserDetailsManager.
               .and()  //3c A06_BrokenAccessControl violation: UserDetailService not used in request mapping and config (A57 UnauthenticatedExposure) Spring's AuthenticationManagerBuilder has a method configureAuthentication, which requires an authenticationProvider but the default provider is ignored when using InMemoryUserDetailsManager.
               .formLogin().loginPage("/login").permitAll() //3d A06_BrokenAccessControl violation: UserDetailService not used in request mapping and config (A58 UnauthenticatedExposure) Spring's AuthenticationManagerBuilder has a method configureAuthentication, which requires an authenticationProvider but the default provider is ignored when using InMemoryUserDetailsManager.
               .and()  //3e A06_BrokenAccessControl violation: UserDetailService not used in request mapping and config (A19 UnauthenticatedExposure) Spring's AuthenticationManagerBuilder has a method configureAuthentication, which requires an authenticationProvider but the default provider is ignored when using InMemoryUserDetailsManager.
               .logout().permitAll(); //3f A06