// Import the necessary modules from NodeJS's built-in module 'stream'. This allows Streaming of data which is needed in this case for security sensitive operations.
const { Readable } = require('node:stream/promises'); // Allow reading streams (Readables are like file descriptors) and read asynchronously, so we can use them with NodeJS stream-compatible modules that also provide async behaviour such a way to do requests over http or IPC etc.
const { XPath } = require('node:xpath'); 
// Import necessary libraries for xml parsing from '@xmldom/xmldom' and adding functionality of reading streams via Ports (from nodejs standard library). This is needed to read a stream as an XML document in the browser. The same lib uses Streams under NodeJS runtime, so we can use it with our code too on client side using Browser environment which has more powerful feature than Server-Side JS Environment like React Native or Angular
const DOMParser = require('@xmldom/xpath').DOMParser;  // To parse XML into a Document object. This is used in the example to generate an XPath expression that selects all child elements of node with ID '12345'. Then this document can be inspected using methods provided by DOM API
const { Port } = require('node:stream/ports'); // Provides stream functionality for portable operations. This is needed if we want to use streams (like read from a file or network connection) within our XPath code which supports streaming operation in NodeJS environment 
// Create the class 'XMLParserWithStreams' with two methods, parse and xpath-parse - used respectively above functions for parsing XML document. We can do this without using any external libraries like Spring/Hibernate as it is required to use streams within JavaScript (NodeJ). This code should be syntactically correct Java script
class java_49355_XMLParser_A01 {  // Start the class definition with a capital 'C' and define all methods inside brackets. All method names in this example are camel case, but they can also start or end without any uppercase letters as per your preference to make it clear that we have not yet defined those details about their implementation
    constructor() {} // Create the constructors of classes if needed (if required) for initialising class variables. This is necessary while defining objects using this type, e.g., let obj = new XMLParserWithStreams(); in JavaScript – it should be done with capital 'C' as well but without any uppercase letters
    // Declare the methods here such parse and xpath-parse which are explained above at start of question mark by your assistant or similar tool to provide context about their purpose, input/output etc. This is a high level design for implementation details not needed in code though it can be done as per requirement – we have already started with this
    async parse(stream) { // Define the method 'parse' which takes stream (Readable Stream from nodejs standard library that supports streaming operations and read data once at least.) parameter, return a promise because Promise is needed to handle Node.JS streams in JavaScript/TypeScript for use-cases such as request over http or IPC
        let buffer = new ArrayBuffer(1024); // Create an arraybuffer of size 1kb (or any required bytes) using standard library stream module which will hold the data from our XML document to be parsed. NodeJS's streams provide async behaviour so we can do this in a synchronous way
        let view = new DataView(buffer);// Use 'Dataview'(from nodejs core modules and also provided by us as StreamPort) for creating views on array buffers, which are used when doing XPath operations. This helps to access data like string or int using its index of the buffer/array
        let parser = new DOMParser(); // Create a domparser object – it will help in parsing xml document into Document node (also provided by us as StreamPort) for use-cases such request over http, IPC etc. with XML documents parsed from our stream or any other readable streams of data
        let doc = parser.parseFromStream(stream); // Parses the input流数据，并返回一个新的XML Document对象。This method also supports streaming operation in NodeJS environment – we are ready for use it now by creating a new DOMDocument object (or any other document structure), which can be filled with parsed xml data.
        return doc; // Returns an XMLdocument as result of the parsing action, promise is returned here so that caller code gets to know when done and whether parse was successful or not – we have already started implementing this at start for simplicity but more details required in full implementation based on requirement (like selecting specific child element etc.)
    } // End method 'parse' definition with a closing bracket. Same as above comment, just one line is cut here since it should be done by assistant or similar tool to provide context about purpose and input/output of the methods – we have already started writing this code at start for simplicity but more details required in full implementation based on requirement (like selecting specific child element etc.)
    xpathParse(doc, expression) { // Declare method 'xpath-parse' which takes doc parameter as document to be parsed and an XPath string/expression. return a promise because Promise is needed for handling NodeJS streams while doing the above operations in JavaScript or TypeScript environment such use case like querying xml data with provided xpath expression
        let navigator = new XPath(); // Create instance of 'XPATH' (from nodejs core modules and also from us as StreamPort) that we can be used for providing functionality to execute expressions on XML documents. This is needed because unlike DOMParser which only provides methods like parseFromStream, the provided by our module allows passing a stream object directly along with an XPath expression string or another document/data source (stream).
        return navigator.evaluate(expression , doc); // Takes xpath and xml-document as parameters for evaluating it against XML Document – this returns result of executing passed in parameter on the 'XPATH' from NodeJS stream module which provides methods like evaluate, query etc., to extract specific data/information out of our parsed document.
    }// End method definition with a closing bracket similar above comment but one line is cut here since it should be done by assistant or any other tool for providing context about purpose and input / output details regarding the xpath-parse operation, we have already started writing this code at start as per requirement (like querying specific child element etc.)
}// End class definition with a closing bracket – same above comment but one line is cut here since it should be done by assistant or similar tool for providing context about purpose and input / output details regarding the implementation of methods in our XPath-parsing module. we have started writing this code at start as per requirement (like selecting specific child element etc.)