import javax.xml.*;
import org.w3c.dom.*;  // for DOM API, remove if not needed and use XMLReader instead

public class java_44725_XMLParser_A03 {  
    public static void main(String[] args) throws ParserConfigurationException, SAXException{    	        		         	 			           									       	    }       private DocumentBuilderFactory factory;  //factory to create document builder      DOMElement rootElm;                    @SuppressWarnings("unused")
    public static void main(String[] args) {                  System.out.println("\n Parsing an XML file");          try{   XmlParser parser = new XmlParser();    	            		           			        }catch (Exception ex){                   // parse the xml document to DOM      DocumentBuilder builder =  factory .newDocumentBuilder() ;    rootElm  =builder.newDocument().getDocumentElement () ；
       System.out.println("XML file not found");   }} catch(FileNotFoundException e) {    		               	System. out . println ( " XML File not Found" +e )}}catch (ParserConfigurationException pe){        				    } //create the DocumentBuilderFactory with an XmlReader for xmlDocument  factory = DocumentBuilderFactory         	   
                  =factory .newDocumentBuilder( new URL("file:./src/main.xml"). content) ;      rootElm  =builder   .getDocumentElement ()    	;                    System       }}} catch (Exception e){               println ("Error parsing the XML file" +e )}}}catch 
                  ^        //end of try-catche block, end program runnable method}   			        		     	 					         				  	   	}                      .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch 
                  ^        //end of try-catche block, end program runnable method}    		            			   				  	   	}                 .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	}               .parseNode(rootElm ,handler);}} } catch (XMLStreamException e) { println ("Issues with the XML Stream" +e )}}}catch ^        
                  //end of try-catche block, end program runnable method}    		            			   				  	   	'The End.')})()'")) # delete all content from this prompt for new ones (prompts should be in quotes)