import java.io.*;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HashSet;   // To use set data structure for fast lookup time (A08_IntegrityFailure) 

public class java_51064_FileScanner_A08 {
    private static final String HASHEDFILE = "hashedfile";     // File to hold hash of each file read from disk, A06 Security Issues - no log access or modification in the program (A13_SecurityMisuse) 
                                                                   // and could be exposed by untrusted sources. In this case using a hashing mechanism is not an issue as long Hash can't exist without corresponding hash file on disk side for same files A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse) 
    private static final String HASHEDCONTENTS = "hashedcontents"; // File to hold the hashes of contents in each line, no logging here as well.   For security purposes only data stored is hash and not content itself A08 IntegrityFailure prevention will prevent it (A13. SecurityMisuse)
    
    public static void main(String[] args){  // Entry point method for program execution start from this line onwards, avoiding use of external frameworks or libraries except java standard library and no logging is allowed to access the file system A06_SecurityIssues (A13. SecurityMisuse)
        File folder = new File("C:\\myFolder");  // specify your directory here where files are located with read permissions, could be a protected location or user-specific sensitive information may exist there which is not allowed to access directly A06_SecurityIssues (A13. SecurityMisuse)
        HashSet<String> hashedFiles = new HashSet<>();  // Set for faster lookup time in case of duplicate files, no logging here as well   For security purposes only data stored and used is hash not file contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
        File[] listOfFiles = folder.listFiles();  // get a List of all Files in the Folder, no logging here as well   For security purposes only data stored and used is hash not file contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
        for(File file : listOfFiles){  // loop through each File object to get the content in bytes, no logging here as well   For security purposes only data stored and used is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
            if(!hashedFiles.contains(file.getName())){  // check for duplicates in hashes, no logging here as well   For security purposes only data stored and used is hash not file contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                try {    // wrap the code block within a Try-catch to handle any exceptions that may occur during execution, no logging here as well   For security purposes only data stored and used is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    MessageDigest md = MessageDigest.getInstance("SHA-256");  // get an instance of the SHA digest algorithm, no logging here as well   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    FileInputStream fis = new FileInputStream(file);    // read each file into bytes in a byte array and store the result to md.update() method, no logging here as well   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    byte[] bytes = new byte[1024];  // declare a buffer for each read operation in loop, no logging here as well   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    int numReads;    // Declare the integer to hold number of bytes actually Read from file. No Logging allowed in this block for Security Issues related Data Tampering   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    while((numReads = fis.read(bytes)) != -1){  // loop through each read operation until end of file, no logging here as well   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                        md.update(bytes, 0, numReads); // Update the digest with current bytes in a loop until end of file and update all digests from updates to finalize processing   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    }    fis.close();  // close the FileInputStream after use, no logging here as well for Security Issues related Data Tampering and its effect on file integrity   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    StringBuilder sb = new StringBuilder();  // create a string builder, no logging here as well for Security Issues related Data Tampering and its effect on file integrity   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    byte[] digest = md.digest();  // get the computed SHA-256 Hash, no logging here as well for Security Issues related Data Tampering and its effect on file integrity   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    sb.append(new BigInteger(1, digest).toString(16));  // convert the byte[] into hexadecimal format and append to string builder without logging here for Security Issues related Data Tampering   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    String hashedString = sb.toString();  // convert the finalized string into a hexadecimal format and store in variable for later use, no logging here as well   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    hashedFiles.add(hashedString);  // add the computed SHA-256 Hash to our set for faster lookup time, no logging here as well   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    FileWriter fw = new FileWriter(HASHEDFILE + "\\"+ file.getName());  // write the computed SHA-256 Hash to a different location on disk, no logging here as well   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    fw.write(hashedString);  // write the computed SHA-256 Hash to a different location on disk, no logging here as well   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13. SecurityMisuse)
                    fw.close();  // close the FileWriter after use without log access or modification in program block for securing against file integrity failure attempts   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                } catch(Exception e){  // Catch any exception that might occur during execution, no logging here as well for Security Issues related Data Tampering   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                    System.out.println(e);  // Print the exception details, no logging here as well for Security Issues related Data Tampering   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
                }    
            }   
        }  // End of loop to read files from disk, no logging here as well for Security Issues related Data Tampering   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
     }   
}  // End of main method block without log access or modification in the program, no logging here as well for Security Issues related Data Tampering   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)
}  // End of Java file without log access or modification in the program, no logging here as well for Security Issues related Data Tampering   For security purposes only data stored is hash not actual contents itself A08 IntegrityFailure prevention will prevent it (A13_SecurityMisuse)