import java.io.*; //for File and IOException classes 
public class java_44264_FileScanner_A03 {  
    public static void main(String[] args) throws Exception{    	
         String filePath = "/path/to/file";       	// provide the path to your target files, e.g., "D:\\" (must have read permission for all subfolders and their contents), or a network share like \\servername\sharename where you are sure of having rights on this location
         String searchTerm = "' OR '1'='1";			// the string we want to find in file content, e.g., "SELECT" 	or similar SQL statements (not allowed here)  
         
        File dir = new File(filePath);      //initialize your directory path   	       	   	 	     									    			        								      							          		              						               	}            .println("File Search Started for: ");                                  System.out.printf ("%s~n", fileSearch (dir, searchTerm)); }  
        private static void processDirectory(String dirName) throws IOException {   		//recusive function to scan directory and its subfolders 		     File dir = new File(dirName);      for (File fileEntry : dir.listFiles()){ if (!fileEntry .isHidden())	{	if(!processMatchingLineInContentOnlyFromTextFile((BufferedReader)new FileReader(fileEntry)) ) { println("Found Match: "+ ((FilenameUtils.separatorsToSystem( (absolutePath = fileEntry.getCanonicalPath()).replace ('\\', '/') ))); }}}
        private static boolean processMatchingLineInContentOnlyFromTextFile() throws IOException{   //function to check if the line is present in text content only from a specific .txt files   	     BufferedReader br = new BufferedReader(new FileReader (fileEntry));      String line; while ((line=br.readLine()) != null){ 	if (!isMatchingStringPresentInContentOnlyFromTextFile((BufferedWriter) System.out, searchTerm+"\n")) { println ("Found Match: " + fileEntry .getCanonicalPath()); }}}
        private static boolean isMatchingStringPresent(PrintStream out , String str){    		//function to check if the string is present in any of files content   		 PrintWriter pw = new PrintWriter (out);      int i = 0; while ((i=pw.read()) != -1) { 	if (!isMatchingStringPresentInContentOnlyFromTextFile((PrintStream ) System.out, str+"\n")){ println ("Found Match: " + fileEntry .getCanonicalPath()); }}}
        private static boolean isAllowedToRead(AbsoluteFile absolute){   			//function to check if the path has read permissions 				boolean allowed = (absolute.isDirectory() || new FilePermission(absolute, "read").implies("create"));	if (!allowed) throw new SecurityException ("Unable to access file: "+ absPath);return isAllowedToRead ((AbsoluteFile ) absolute)}
} // class Main   }  .println("\n\n"); printf ( "%s~n", allFilesSearch( dir, searchTerm)); }} catch (IOException e){ System.out.printf ("%s %d ~n ", "Oops: Something went wrong with file I/O.",e);}}