import java.sql.*;  // Import necessary Java packages, no import * needed here because we're only using what we need (ResultSet) to build our connection string & create a statement object within this context of authentication failure scenario).  
public class java_45804_JDBCQueryHandler_A07 {    
    public static void main(String[] args){  // This is the starting point for any Java program. Only necessary if you're calling methods in other parts or not sure what they do (No comment required here, it only contains a statement to start running code).  
        String url = "jdbc:mysql://localhost/db_name";     // Replace 'url', and the database name with your own.  This is our URL for connecting MySQL databases in Java world using JDBC driver (MySQL Connector API has built-in functionality to connect, disconnect etc).
        String username = "username";      // The same as before - replace this string by you're actual user data like database name and the password.  This is necessary for security reasons if we use MySQL in our case due its nature (MySQL Connector API has built-in functionality to handle authentication, etc).
        String pwd = "password";      // The same as above - again replace this string by your actual user data like database name and the username.  Again necessary for security reasons if we use MySQL in our case due its nature (MySQL Connector API has built-in functionality to handle authentication, etc).
        try {     /* Begin of 'try' block which is a part where potential exceptions can be handled */   // Exception handling using Java Try/Catch mechanism. Any error encountered here will make the program fail and print an appropriate message (No comment required in this case - just wraps everything inside to prevent any syntax errors).
            Class.forName("com.mysql.cj.jdbc.Driver");    /* Loading MySQL driver */   // This line is necessary for Java database connectivity if we use MySql as our DBMS, due the nature of JDBC (Java Database Connectivity) to work with databases in a universal way using its own native drivers).
            Connection con = DriverManager.getConnection(url , username, pwd);   // This line is necessary for Java database connectivity if we use MySql as our DBMS by providing the URL of MySQL server and authentication credentials (No comment required here - it's just a connection setup using JDBC).
            Statement stmt = con.createStatement();    /* Creating 'statement/query handle' to perform operations on database */   // This line is necessary for Java Database connectivity if we use MySql as our DBMS by providing the URL of MySQL server and authentication credentials (No comment required here - it’s just a statement setup using JDBC).
            String query = "SELECT * FROM your_table";    /* Defining 'query' to be executed */   // This line is necessary for Java Database connectivity if we use MySql as our DBMS by providing the URL of MySQL server and authentication credentials (No comment required here - it’s just defining a SQL Query).
            ResultSet rs = stmt.executeQuery(query);    /* Executing 'statement/queries' */   // This line is necessary for Java Database connectivity if we use MySql as our DBMS by providing the URL of MySQL server and authentication credentials (No comment required here - it’s just executing a SQL Query).
            while (rs.next()) {     // Beginning loop to iterate over 'ResultSet' */   // This line is necessary for Java Database connectivity if we use MySql as our DBMS by providing the URL of MySQL server and authentication credentials, due its nature using JDBC with ResultSets which can be used like Iterator or Stream).
                System.out.println(rs.getString("your_column"));  // This line is necessary for Java Database connectivity if we use MySql as our DBMS by providing the URL of MySQL server and authentication credentials (No comment required here - it's just printing out 'ResultSet/ColumnValue').  
            }    /* End loop */    
        con.close();      // Closing connection to database when done with query execution – no need for error checking in this case because we have already closed the statement and returned from method (No comment required here - it's just closing a Connection).
             fail;   } catch(SQLException se) {    /* Catching 'Unchecked/Unhandled SQL Exceptions */  // Exception handling for unchecked exceptions. In this case, we have only checked the one exception but can handle more if needed (No comment required here - it's just catching and processing an unwatched error).
        } catch(Exception e) { /* Catching 'Unchecked/Unhandled Exceptions */  // Exception handling for unchecked exceptions. In this case, we have only checked the one exception but can handle more if needed (No comment required here - it's just catching and processing an unwatched error).
    }    
}