import java.io.*; // Import the necessary classes to handle streams, directories etc., here... (No external frameworks needed)
class java_49789_FileScanner_A03 {  
    public static void main(String args[]){    
        String directoryPath = "/path/to";      // specify your path her  e , for example /home/user/.jhipster with spaces around the slashes and also replace '.' (dot character )with '/' because windows use forward-slash.   You can change this as per requirement .   
        String secretWord = "secret" ;          // Define what we look out for in files name or content here e , just like example above  with spaces around the slashes and also replace '.' (dot character )with '/' because windows use forward-slash.   You can change this as per requirement .
        scanDirectory(directoryPath, secretWord);     // Call function to start scanning process     
       }   
private static void scanDirectory(String directoryName , String wordToFind){  /*This is a private method*/        
            File dir = new File (directoryName );          // Create file object for the Directory that you want...here, we create from string e..with spaces and also replace '.' with '/' because windows use forward-slash.   You can change this as per requirement .   
        if(dir == null || !dir.exists()){                       /*Checking to see whether directory exists or not*/         FileNotFoundException fnf = new FileNotFoundException("File '" + dir +  "' does not exist");      // If the Directory doesn't existed then we create a exception and print it e..here, I just added spaces around slashes.   You can change this as per requirement .
                throw(fnf);                                  /*If directory has been specified in string variable but actually doensn`t exists than here will be thrown*/         return; }  //Return statement after the if block to exit from function     private static void scanFile (String fileName , String wordToFind){   this is a method that scans one specific File for any given text e..here, I just added spaces around slashes.   
            try {                                               /*This part of code will be handling the stream and reading files*/      BufferedReader br = new BufferedReader(new InputStreamReader (new FileInputStream(fileName))); //Creating a buffering reader to read file content e..with space...   You can change this as per requirement .
                String line;                                   /*This will be storing the data from one specific Line of any particular document*/      while ((line = br.readLine()) != null) {          if (line.contains(wordToFind)) //If content in file contains "secret" or ".txt", then print it out e..here, I just added spaces around slashes and also replace '.' with '/' because windows use forward-slash .   
                System.out.println("Found secret text : \"" + line+ '"');      /*Printing the specific data which contains "secret" or ".txt", in our case e..here, I just added spaces around slashes and also replace '.' with '/' because windows use forward-slash .   
               } br.close(); // Closing Buffered Reader at end of loop to free resources after each read is complete */   }}  This ends the code block for scanDirectory method e..with space...I just added spaces around slashes and also replace '.' with '/' because windows use forward-slash .   
       }     /*Ending Method declaration*/      //Main function ended here.//This program will run successfully if no exception occurs in main() ethod block only the files inside directory provided to this method are checked for secret words e..here, I just added spaces around slashes and also replace '.' with '/' because windows use forward-slash .   
} //Main function ended here.//This program will run successfully if no exception occurs in main() ethod block only the files inside directory provided to this method are checked for secret words e..here, I just added spaces around slashes and also replace '.' with '/' because windows use forward-slash .