import java.io.*;
import java.net.*;

public class java_46579_SocketServer_A03 {  
    public static void main(String[] args) throws Exception{    	        		      			       	   	       	 	      }      private int port; boolean running = true ; Socket socket=null, clientSocket= null;  BufferedReader in  =null , out = null;            try	{                startServer ();              
    while(running){                       new ClientThread().start();                        Thread.sleep(10);} }     catch (Exception e) { System . err .println (" Server : " +e ); stopServer (); throw   ;      }}  @SuppressWarnings("unused") public class ClientThread extends Thread{       
    private Socket sock;          DataInputStream dis;         BufferedReader in = null , out=null, br=null; int bufSize= 1024;     try {                setSocket (socket);              } catch   (Exception e)  {}       while(running){            if (!waiting() ) break ;                     sendString ("Hello Client");                      
    //read in from client using BufferedReader      Thread.sleep (.5* 1024 );                    try {           dis = new DataInputStream     ( sock .getInputStream ()             );              while ((br   =new InputStreamBuffe r(dis,bufSize))!=null)                    
    //read in from client using BufferedReader      Thread.sleep (.5* 1024);                    try {           dis = new DataInputStream     ( sock .getInputStream ()             );              while ((br   =new InputStreamBuffe r(dis,bufSize))!=null)                    
    //read in from client using Buff Event            } catch   (Exception e){ System. err      println("Error reading: " + e);  break;}}}}}catch       ... Exception or Error is caught and handled...              out .println (" Server Exited"); stopServer();     }}         private void setSocket( Socket s ) { if       
    (!sockInit ()) throw new RuntimeException   (" Already Running "); this.socket  =      s; } boolean waiting() throws IOException{ return dis != null && 
            ((dis .available () == 0) || bufSize<= 1);} private void sendString( String s ) { try     ... Exception or Error is caught and handled...    out   =new PrintWriter (sock.getOutputStream(), true );       } catch   ......      }}catch ..        throw new RuntimeException("Error in client 
operations " + e) ;}}}}}             finally{                  if(socket != null ) socket .close();                 System.out     ... Error is caught and handled...                    out .println (" Server Exited"); stopServer (); }                //Main Method END }} This server will wait for connections on the specified port, 
listening them in turn using a new thread per connection approach where each client's data exchange via BufferedReader.read() method until disconnected by sending ending message or error occurred while reading from/writing to socket input stream and closing it as well at once disconnecting that particular user session after waiting for some time (using sleep).