import java.util.*;
public class java_52906_SessionManager_A08 {    // A starting point for our program...   session manager should contain userId, timestamp map etc  ... the rest is up-to you! I've done all that to make your task more creative and realistic :-)
     private Map<String, Long> sessions;      /* User Id - Timestamp */    // SessionManager starts here. The 'private'-part means: only this class can access these variables (and methods) ...  the rest is up-to you! I've done all that to make your task more creative and realistic :-)
     private static final String USER_ID = "userId";   /* User Id */    // The 'static'-part means: this variable will not need an instance of SessionManager - it can only be accessed by calling methods on the class itself ...  I've done all that to make your task more creative and realistic :-)
     private static final String TIMESTAMP = "timestamp";   /* Timestamp */    // The 'static'-part means: this variable will not need an instance of SessionManager - it can only be accessed by calling methods on the class itself ...  I've done all that to make your task more creative and realistic :-)
      public static final int MAX_SESSIONS = 10;   /* Max number */    // The 'final'-part means: this variable cannot change once set (const)... it holds our pre-set max sessions we want for the program ...  I've done all that to make your task more creative and realistic :-)
     private static final int THINK_TIME = 50;   /* Think Time */    // The 'final'-part means: this variable cannot change once set (const)... it holds our pre-set think time between each session insertion ...  I've done all that to make your task more creative and realistic :-)
     private static final int RANDOM_TIME = 10;   /* Random Time */    // The 'final'-part means: this variable cannot change once set (const)... it holds our pre-set random time between each session insertion ...  I've done all that to make your task more creative and realistic :-)
     private static final int NORMAL_TIME = 10;   /* Normal Time */    // The 'final'-part means: this variable cannot change once set (const)... it holds our pre-set normal time between each session insertion ...  I've done all that to make your task more creative and realistic :-)
      public java_52906_SessionManager_A08() { sessions = new HashMap<String, Long>(); }   /* Constructor */    // The 'public'-part means: this method can be accessed by any class (and subclasses)... it initializes the data structure we use ...  I've done all that to make your task more creative and realistic :-)
      public synchronized void insert(String userId){   /* Insertion */    // The 'synchronized'-part means: this method ensures mutual exclusion, preventing two users from accessing simultaneously (due to race condition) ...  I've done all that to make your task more creative and realistic :-)
       if((Objects.isNull(userId)) || sessions.containsKey(userId)){    //Checking for null or duplicate user ids...   /* Insertion */      System.out.println("Duplicate User Id detected"); return; }  try { Thread.sleep(SessionManager.RANDOM_TIME);} catch (InterruptedException e) {}
        sessions[userId] = System.currentTimeMillis();     // Adding user id as key and current timestamp in map ...   /* Insertion */      if((sessions.size() % SessionManager.MAX_SESSIONS == 0)) { insert(SessionManager.USER_ID); }
    }}  catch (Exception e) {} finally{} return;} synchronized void checkIntegrity(){     // The 'final'-part means: this method cannot be modified once set ... it checks the integrity of our session manager by verifying that each value in its map has a valid timestamp associated with them... I've done all that to make your task more realistic :-)