import java.util.*;   // Import the List interface and ArrayList class java_43878_CredentialValidator_A07 collection framework   
class Main {    
      static HashMap<String, String> credentials =  new HashMap<>();// Declare an empty hashmap of type string - key: username value : password          
       public static void main(String[] args)  {        // Create a method named 'main'           
             loadCredentials() ;   // Load the credential data in our user database, this is not typically done at runtime. In real world we will fetch these credentials from some sort of secure storage or network server     .      printMenu();         }    private static void  loadCredentials(){          for (int i=0;i<1 ;+++) {              String username ="";  
String password  = "";           // Initialize the two user variables with empty strings.             System.out.println("Please enter your Username:");     Scanner scanUsrName    = new        java .util .Scanner(System.in);      try{username=scanUsrNam...       }catch (Exception e){}         
         for (;;) {               // Initialize the two user variables with empty strings            System.out.println("Please enter your Password:");     Scanner scanPassWord = new java .util ..Scanner(System.in);      try{password=scanPa...           }catch (Exception e){}              if (!username.equals("") && ! password
!=" ") { credentials.put(username,  password) ;   System.out.println("\nSuccessfully Saved User : " + username );        break;          }} catch (InputMismatchException exe...         }    private static void printMenu(){      // Declare a method named 'printmenu'      
System. out .println ("\t \t Welcome to the Login Menu");              System..             String userName = "";                    Scanner scanUserNam= new java ..util ...Scanner(System.in);     try{userNa...          }catch (Exception e){}           if(!username!equals("")) {
if (!password. equals (" "))  // Validate the entered username and password, for real world scenarios we should also have a method to compare hashes of both usernames/passwords with stored credentials hashmap     System..println("\nSuccessfully Logged In as: :" + userName);      } else {
System.out .print("Invalid Username or Password");                  }} catch (InputMismatchException e) {}              printMenu();       // Call the 'Printmenu' method to display a menu, and it should go on indefinitely until an exit command is entered     System..println("\n Exiting ...");