import java.io.*;  // Import BufferedReader, InputStreamReader & PrintWriter classes for handling input stream data or output streams of sockets via a Connection
    import java.net.*;   // For ServerSocket and Socket class java_47461_SocketServer_A03 to create server/client communication between two systems at an internet level such as localhost:portnumbers (hostname = local machine, port number = 0 means the system will assign one for us) 
    
public class SimpleServer {
    private static final int PORT_NUMBER = 8192; // Declare and initialize a constant integer variable to hold our socket server's listening address. (This could be any available unused port number, like say Port Number:3456)  Avoid using the same or default ports as used by other services because it might block incoming connections
    private static final int MAX_CONNECTIONS = 10; // Declare and initialize a constant integer variable to hold our socket server's maximum number of concurrent sessions. (this will limit how many clients we can accept at the same time)  We are setting this as close enough for real-world scenarios but not completely secure against brute force attacks
    
    public static void main(String[] args){   // Declare and initialize a Main method, which is our server's entry point. It should keep running until it’s manually stopped or an error happens in the while loop – we do this by handling exceptions thrown when accepting connections (SocketException) on Socket s
        ServerSocket ss = null;    // Declare and initialize a variable for socket service, which is used to create server side of communication between two systems at internet level such as localhost:portnumber. It's created with PORT_NUMBER constant – we pass it into constructor   so this only needs one instance per JVM
        try {    // Start the code block that will run if everything goes right (if an exception is thrown in while loop, catch statement gets executed) using a "try-catch" or 'Try/Catch' mechanism.  A way to deal with exceptions when we are inside blocks of codes and want out information from those
            ss = new ServerSocket(PORT_NUMBER); // Instantiate the server socket class within our main method, which will listen on a particular port number for incoming connections (a connection is established once an application makes a request to connect)  using PORT NUMBERS declared in constant variable. We are associating this with ss by passing it into ServerSocket constructor
            System.out.println("Server started at: " + new Date()); // Notify user about the start of server activity on specified port number and date/time stamp to know when we were connected  (This is how client application knows that our connection established successfully)   Using Java's inbuilt println method with a formatted statement.
            Socket socket = null;    // Declare variable for handling incoming connections, which will represent each individual user who connects and wants access via the server side of communication at internet level  (Socket objects are created within while loop as long they exist)   Using Java's inbuilt println method with a formatted statement.
            try {     /* Inside this block we handle exception for when client is connected using SocketConnection */    // Declare variable 'socket', which will be used to create stream between two sockets, representing the communication channel established via socket connections (Incoming and Outgoing)  Using Java's inbuilt println method with a formatted statement.
                while(true){   /* This is our server loop that runs till we stop it manually or an exception happens */    // Declare variable 'socket', which will be used to create stream between two sockets, representing the communication channel established via socket connections (Incoming and Outgoing)  Using Java's inbuilt println method with a formatted statement.
                    try {   /* Inside this block we handle exceptions for when client is connected using SocketConnection */    // Declare variable 'socket', which will be used to create stream between two sockets, representing the communication channel established via socket connections (Incoming and Outgoing)  Using Java's inbuilt println method with a formatted statement.
                        socket = ss.accept();   /* Accept incoming client connection */    // Declare variable 'socket', which will be used to create stream between two sockets, representing the communication channel established via socket connections (Incoming and Outgoing)  Using Java's inbuilt println method with a formatted statement
                        System.out.println("Client connected from: " + socket.getRemoteSocketAddress());   // Inform user about new client connection when they are connecting using this address(socket details), This is how the server knows that our initial request has been accepted  Using Java's inbuilt println method with a formatted statement
                        BufferedReader br =new BufferedReader (new InputStreamReader (socket.getInputStream()));    // Create buffers for reading client messages from socket, using input stream reader and buffer writer objects so we can handle communication channel established via Socket Connection  Using Java's inbuilt println method with a formatted statement
                        PrintWriter pw = new PrintWriter(new OutputStreamWriter (socket.getOutputStream()), true);   // Create buffers for writing server messages to socket, using output stream writer and buffer reader objects so we can handle communication channel established via Socket Connection  Using Java's inbuilt println method with a formatted statement
                        String clientMessage;    /* Declare variable 'client_message', used when reading message from the user */   // For handling incoming messages of type string, using BufferedReader and PrintWriter objects so we can handle communication channel established via Socket Connection  Using Java's inbuilt println method with a formatted statement
                        if (( clientMessage = br.readLine()) != null) {    /* If user has entered message read it */   // For handling incoming messages of type string, using BufferedReader and PrintWriter objects so we can handle communication channel established via Socket Connection  Using Java's inbuilt println method with a formatted statement
                            System.out.println("Client: " + clientMessage); /* Inform user about new message received from the connected socket */   // For handling incoming messages of type string, using BufferedReader and PrintWriter objects so we can handle communication channel established via Socket Connection  Using Java's inbuilt println method with a formatted statement
                            pw.println("Server: " + clientMessage); /* Write back message to the user */   // For handling outgoing messages of type string, using BufferedReader and PrintWriter objects so we can handle communication channel established via Socket Connection  Using Java's inbuilt println method with a formatted statement
                        } else {    /* If no more input is available (meaning client has disconnected) then break the loop */   // For handling incoming messages of type string, using BufferedReader and PrintWriter objects so we can handle communication channel established via Socket Connection  Using Java's inbuilt println method with a formatted statement
                            System.out