import java.sql.*;
public class java_45444_JDBCQueryHandler_A03 {
    public static final String URL = "jdbc:mysql://localhost/testdb";  // Replace with your database url and name (database)  
	public static final String USERNAME="root";       //Replaceme by you user names in db.	
	private static Connection connection;	// Create a variable to hold the reference of DatabaseConnection object   		    			     									 	 														       	   							         ​           	                     .           ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
	static { // This code is only run once, when class loader loads the JVM            		    			     									 	 														       	   							         ​           	                     .           ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
	try {
	      connection = DriverManager.getConnection(URL, USERNAME,""); // Creating Connection to database 			     									 	 														       	   							         ​           	                     .           ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
	} catch (SQLException e) {   	    			// Exception handling if any error occur during the connection process			     									 	 														       	   							         ​           	                     .           ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
	} // End of try catch block for establishing Database Connection            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
	public static void main(String[] args) { // Main method to test the JDBCConnection object            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
	try { // try block for handling exceptions            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
		if (connection != null) { // Check if the connection is not empty            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
		// Write your code here to perform the operation related security sensitive operations            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
		} else { // Print a message if the connection is empty            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
		// Write your code here for handling the case when connection is empty            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
		} // End of if else block for handling connection            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
	} catch (SQLException e) { // Catch block for handling any SQL Exception            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
		// Write your code here for handling the exception            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
	} // End of try catch block for handling exceptions            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----
} // End of JDBCQueryHandler class            		    			     									 	 														       	   							         ​           	       ~ `....                   +.....++---/++++    .-.   ..                ......                  ...                           ---                   -----                            --.-                 -.--      `...--.----