import java.sql.*;  // Import Java's built-in classes for JDBC (Java Database Connectivity)   
  
public class java_47610_JDBCQueryHandler_A08 {     
        public static void main(String[] args){      
            String url = "jdbc:mysql://localhost/test";     // URL to connect MySQL server  and database test         
            
           try{        		// Begin a Try block for exception handling  		   	   	 	       									                 			                   	     							     								                         						                         throws SQLException {                /* Create connection */              Connection conn = DriverManager.getConnection(url,"username","password");            System.out.println("Connected to database...");              
            		/* Prepare statement for checking if user exists in DB*/         		   	 	       									                 			                   	     							     								                         						                         String checkUserQuery="SELECT COUNT(*) FROM users WHERE username = ?";              PreparedStatement pstmtCount = conn.prepareStatement(checkUserQuery);
            		/* Bind the parameter and execute to fetch user count */         		   	 	       									                 			                   	     							     								                         						                         try {                                                                                                           /* Execute query & get a result set with one row only  (if more than zero)*/              pstmtCount.setString(1, "John");                ResultSet rs = pstmtCount.executeQuery();             if(!rs.next()){               System.out.println("No user named John in the database.");            } else {                 /* If there are rows returned then print it out */              int count=0;                    do{                  // get next result set from a previous executed statement      
                                                                                rs.getInt(1);} while (rs.next());             System.out.println("Number of users in the database: "+count++ );            } conn.close();        		   	 	       									                 			                   	     							     								                         						                        	}     catch {              /* Exception handling */         
                                                                   e1)               // Catching exception for SQL related exceptions  (like JDBC driver not found, mismatched jdbc url etc.)            System.out.println("Something went wrong while connecting or executing query...");         }      }}