import java.sql.*;  // Import required libraries/modules: PreparedStatement & ResultSet Class
import com.mysql.cj.jdbc.Driver;    // MySQL driver class java_42310_JDBCQueryHandler_A03 (complied against your mysql version) -> import necessary for Java to access JDBC Driver of the database you are using, in this case MYSQL 5-family or later versions with CJ library included which is a bridge between java and jdbc
  
public void connectionToDatabase(String urlDb , String userName, char[] password) {     // connect function to open DB Connection. Receive the db URL & username for security sensitive operations as well receive Char array of passsword  (not recommended in real world applications due complexity). For better practice use environment variables or secure vault service
    Driver driver = new Driver();  	// Create a JDBC instance/driver object, compiling against your mysql version. It is required by java to access jdbc drivers and database classes of the type you are using (MySQL 5-family) with CJ library included which will be used in this program
    try {             // Using Try & catch for handling any exception that may occur during DB operations e.g., connection lost, error occurred while executing a statement etc... by providing an environment to handle the issue/exception (i've added comment inside)  . In real world application it should be handled in such way
        Connection conn = driver.connect(urlDb , userName);     // connect method will return you db connection object with url, username and password which are mandatory for JDBC to operate e.g., "jdbc:mysql://localhost/testdb" ,"root", "" (empty in real world)
        conn.setAutoCommit(false);      		// If the data insertion is successful then you have control over whether or not to commit changes -> Here we are setting it off after every operation e.g., a new user added, book issue done etc...  with 'conn' object (you can add more if required)
        String sql = "INSERT INTO Users(id , name ) VALUES(?,?)";   // SQL Query will insert data into table named User which has two columns id & Name and we are passing parameters in placeholders for security sensitive operations e.g., ?,?  (not recommended to directly write the query)
        PreparedStatement pstmt = conn.prepareStatement(sql);    		// prepare statement method is used when preparing SQL queries that use '?' as a placeholder symbol -> here we are binding parameters into placeholders and getting prepared Statement object ('pstmt')  with url, user name & password for JDBC to operate e.g., "jdbc:mysql://localhost/testdb" , "root", "" (empty in real world)
        pstmt.setInt(1024);    		// set method is used when setting a parameter value -> here we are passing an int 1024 as the first placeholder and getting prepared Statement object ('pstmt') with user password for JDBC to operate e.g., "jdbc:mysql://localhost/testdb" , "", "" (empty in real world)
        pstmt.setString(5678, “John”);     // set method is used when setting a parameter value -> here we are passing String 'John' as the second placeholder and getting prepared Statement object ('pstmt') with user password for JDBC to operate e.g., "jdbc:mysql://localhost/testdb" , "", "" (empty in real world)
        pstmt.executeUpdate();    		// execute method is used when executing a SQL statement that doesn't return rows -> here we are updating the data by getting prepared Statement object ('pstmt') with user password for JDBC to operate e.g., "jdbc:mysql://localhost/testdb" , "", "" (empty in real world)
        ResultSet rs = pstmt.executeQuery("SELECT * FROM Users");    	// execute query method is used when executing a SQL statement that returns rows -> here we are retrieving the data from database and getting result set ('rs')  with user password for JDBC to operate e.g., "jdbc:mysql://localhost/testdb" , "", "" (empty in real world)
        while(r s .next()) {    // Use a loop structure that goes through all rows of the ResultSet object -> here we are printing out data from database with user password for JDBC to operate e.g., "jdbc:mysql://localhost/testdb" , "", "" (empty in real world)
            System .out ‌​println(r s .getString("name"));    // getString method is used when retrieving a value from the result set -> here we are printing out data with user password for JDBC to operate e.g., "jdbc:mysql://localhost/testdb" , "", "" (empty in real world)
        }  		// close ResultSet, PreparedStatement and Connection objects after use as they were created inside the try block  by using conn .commit(), auto commit off etc... for handling DB operations e.g., end of program execution with 'conn' object or when a new error occurs (using exception handlers)
        } catch(Exception ex){    // Catch method is used to handle all types exceptions -> here we are catching any unhandled异常 and print out the stack trace for debugging purpose.  By using conn .commit(), auto commit off etc... as mentioned above with 'conn' object or when a new error occurs (using exception handlers)
        ex .printStackTrace();      // Print method is used to show log of all exceptions caught by this program -> here we are printing out stack trace for debugging purpose.  By using conn , user password etc... as mentioned above with 'conn' object or when a new error occurs (using exception handlers)
    }  		// End try block and closing connection at the end of all operations e.g., close connections in program after it ends executing by calling .close() method on Connection, Statement & PreparedStatement objects  that were created inside this function body with user password for JDBC to operate (closing DB session)
}  		// End Main Method -> Here we are just creating the connection object which will be used later in our code. It is not actually performing any operation as it's only an example of how you can use jdbc operations  with security sensitive data such as password and user name (user for database authentication).