import javax.persistence.*;   //for Hibernate entities    
@Entity    //mark class java_44309_SessionManager_A07 Entity to be stored in the DB     
public class User {      
 @Id        //unique id generated by db auto incrementing on user insertion . primary key        
 private long ID;             
 
private String username, password ;   //username and a encrypted version of Password for security.     (Don't store plain text in DB)   
public User(String name , string pass ) {       this.userName =name；     
this .password=pass） {}         public void setUserID …} }                private String userName, password;   //... the getter and Setters for above two fields are not shown here because they're sensitive ...                       @Override        public boolean equals(Object o) {......