import java.io.*;
import javax.net.ssl.*;

public class java_48774_SocketServer_A03 {
    private static final String KEYSTORE = "path/to/yourkeystore"; // update with your keystore location and password, example: mykey.p12  *******password*********myPassword   or use self-signed certificates for testing purposes only (replace '...' by the respective details)
    private static final String TRUSTSTORE = "path/to/yourtruststore"; // update with your trust store location and password, example: mycacerts  *******password*********myPassword   or use self-signed certificates for testing purposes only (replace '...' by the respective details)
    private static final int PORT = 8443;// change this to any available port number e.g.,9012, you might want it different from 8443 in case of conflict with existing server or use a free open TCP Port (replace '...' by the respective details)
    private static ServerSocket sock = null; // socket listen on this one for incoming connections only and not shared across all clients. It is also necessary to have at least two certificates, both needed in keystore/truststore  *******password*********myPassword   (replace '...' by the respective details)
    private static SSLServerSocket sslSock = null; // socket listen on this one for incoming connections and shared with all clients. It is necessary a single certificate, required when using keystore/truststore  *******password*********myPassword   (replace '...' by the respective details)
    
    public static void main(String[] args){
        System.out.println("Starting SSL Server..."); //print statement for logging purpose only in real application, usually this should be done with a logger instead  *******password*********myPassword   (replace '...' by the respective details)     
        
// Create and load your keystore into Java KeyStore or Trust Store. Here we use two keystores - one for client-side encryption/decryption, another on server side to verify clients identities in case of multiple users sharing same sslSocket  *******password*********myPassword   (replace '...' by the respective details)
        KeyStore ks = KeyStore.getInstance("JKS"); //change this as per your requirement like JKL, PKCS12 etc., or use other types if necessary e.g.: JSSECerts  *******password*********myPassword   (replace '...' by the respective details)
        ks.load(new FileInputStream("path/toyourkeystore"), "mypassword".toCharArray()); // replace with your key store file path and password e.g.: mypassWord  *******password*********myPassword   (replace '...' by the respective details)
        KeyStore trustStore = null;//change this as per requirement like JKL, PKCS12 etc., or use other types if necessary also you need a single certificate here for server side verification in case of multiple users sharing same sslSocket  *******password*********myPassword   (replace '...' by the respective details)
        trustStore = KeyStore.getInstance("JKS");//change this as per your requirement like JKL, PKCS12 etc., or use other types if necessary e.g.: JSSECerts  *******password*********myPassword   (replace '...' by the respective details)
        trustStore.load(new FileInputStream("path/toyourtruststore"), "mypassword".toCharArray());// replace with your trusted store file path and password e.g.: mypassWord  *******password*********myPassword   (replace '...' by the respective details)
        
        SSLServerSocketFactory sslSockFact = null; // factory for creating a socket that uses an existing truststore, keystore & protocols to use when connecting clients. It is necessary at least one certificate here  *******password*********myPassword   (replace '...' by the respective details)
        try {sslSockFact =  (SSLServerSocketFactory) SSLServerSocketFactory.getDefault();}catch(Exception e){System.out.println("Cannot get default ssl socket factory "+e); } // this is necessary to use a existing truststore, keystore & protocols when creating clients  *******password*********myPassword   (replace '...' by the respective details)
        try {sock = new SSLServerSocket(PORT,"localhost",sslSockFact,(KeyStore)ks,"mypassword".toCharArray());}catch(IOException e){System.out.println("Cannot create ssl socket "+e); } // this is necessary to use a keystore when creating clients  *******password*********myPassword   (replace '...' by the respective details)
        try {sslSock = new SSLServerSocket(PORT,"localhost",null,trustStore,(char[]) null );}catch(IOException e){System.out.println("Cannot create ssl socket "+e); } // this is necessary to use a truststore when creating clients  *******password*********myPassword   (replace '...' by the respective details).
        
        while(true){//this loop will continue until explicitly stopped e.g., system or application shutdown, etc.. in real world applications make sure proper exception handling is done as well for this part of code  *******password*********myPassword   (replace '...' by the respective details)     
            try {SSLServerSocket sockTemp = new SSLServerSocket(sock.getPort(), null,sslSockFact,(KeyStore)ks,"mypassword".toCharArray());}catch(IOException e){System.out.println("Cannot accept connection "+e); } // this is necessary to create a socket for accepting incoming connections using the existing keystore  *******password*********myPassword   (replace '...' by the respective details)
            Socket client = sockTemp.accept();//this line will block until an accepted, insecure connection from another user e.. replace with your logic or exception handling if necessary for this part of code and provide a message that it is not blocking  *******password*********myPassword   (replace '...' by the respective details)
            System.out.println("Client connected");//print statement to verify client connection, usually used in real world applications as logging mechanism only e.. replace with your logic or exception handling if necessary for this part of code and provide a message that it is blocking  *******password*********myPassword   (replace '...' by the respective details)
             // here you can use SSLContext to establish encrypted communication between client & server. Replace everything related ssl stuff with your logic e.. replace all occurrences of `SSLServerSocket`, and every line that is about secure I/O Streams(like read or write operations). It'll be highly recommended for real world application using SSLContext which provide a way to encrypt the communication between server & client.
        }  //end while loop   *******password*********myPassword    (replace '...' by the respective details)     in case of any other conditions exit or return as per need, this is not required and might be removed based on scenario requirements e.. replace with your logic if necessary for handling such cases.
         }//end main method   *******password*********myPassword    (replace '...' by the respective details)     in case of any other conditions exit or return as per need, this is not required and might be removed based on scenario requirements e.. replace with your logic if necessary for handling such cases.
}//end class declaration   *******password*********myPassword    (replace '...' by the respective details)     in case of any other conditions exit or return as per need, this is not required and might be removed based on scenario requirements e.. replace with your logic if necessary for handling such cases.