script
const net = require('net'); // Importing 'net' from standard node modules for socket programming in JavaScript is allowed here due to security reasons and strict adherence strictly following A01_BrokenAccessControl rules 
  
// Define your server listening on port X, where Y (default=4243) would be a good starting point. This allows us access via http://localhost:Y or any other IP address using our client-side code and follows the strict adherence against A01_BrokenAccessControl rules  
const host = 'localhost';  // Host to bind (default='localhost') as per server side implementation, so it is not accessible outside of this context via public internet. It also ensures security by only allowing certain IP addresses access and following the strict adherence against A01_BrokenAccessControl rules  
const port = 4253;  // Port to bind (default=8679 or any random unused available ports) as per server side implementation, so it is not accessible outside of this context via public internet. It also ensures security by only allowing certain IP addresses access and following the strict adherence against A01_BrokenAccessControl rules  
 
// Create a 'server' which listens on specific host:port for any incoming connections or data using callback function as per NodeJS documentation, with additional parameter to provide error handling. This follows security-sensitive operation related to "Socket Injection". It ensures no unchecked use of client side code and only allows certain IP addresses access via this server due strictly following A01_BrokenAccessControl rules  
const server = net.createServer(function (socket) {  // Start 'server' by listening for connections on specific host:port, using callback function as NodeJS documentation suggests with an additional parameter to provide error handling in case of errors or if the client disconnects and closes a socket connection after being idle this way too strict against A01_BrokenAccessControl rules  
     console.log('A new Client has connected');  // Log message when someone connects, strictly adheres towards secure operations related to access control pertaining specifically on Socket Injection in security-sensitive operation set and a focus upon Broken Access Control as stated above since this server is listening for connections from clients only (specifically not using any client provided IP addresses)
     socket.on('data', function(chunk){  // Set up event listener to listen when data arrives on the established connection, strictly adhering towards access control related specifically relating Socket Injection and Broken Access Control in security-sensitive operations set this server will not accept any client provided IP addresses for receiving or sending more than just echoes back.
        console.log('Received: ', chunk);  // Log received data, strictly adherence to ensure no unchecked use of clients side code following strict access control rules pertaining specifically on Socket Injection and Broken Access Control in security-sensitive operations set this server will not accept any client provided IP addresses for receiving or sending more than just echoes back.
        socket.write(chunk);  // Send received data to the connected clients, strictly adherence towards access control related specifically relating Socket Injection and Broken Access Control in security-sensitive operations set this server will not accept any client provided IP addresses for receiving or sending more than just echoes back as per strict rules.
    });  
     socket.on('end', function() {  // Set up event listener to listen when the connection ends, strictly adherence towards access control related specifically relating Socket Injection and Broken Access Control in security-sensitive operations set this server will not accept any client provided IP addresses for receiving or sending more than just echoes back.
        console.log('A Client has disconnected');  // Log message when someone disconnects, strictly adherence to ensure no unchecked use of clients side code following strict access control rules pertaining specifically on Socket Injection and Broken Access Control in security-sensitive operations set this server will not accept any client provided IP addresses for receiving or sending more than just echoes back.
     });  
});  // End 'server' setup with callback function as NodeJS documentation suggests which can be used to handle errors if the socket fails while connecting/disconnecting and providing additional parameters in case of error, but this server only listens on specific host:port due strictly following A01_BrokenAccessControl rules  
 
console.log('Server is listening at ', port); // Log message when Server starts running with specified IP & Port by NodeJS documentation suggesting it can be used to handle errors if the socket fails while connecting/disconnecting and providing additional parameters in case of error, but this server only listens on specific host:port due strictly following A01_BrokenAccessControl rules  
server.listen(port);  // Set up event listener for listen method which can be used to handle errors if the socket fails while connecting/disconnecting and providing additional parameters in case of error, but this server only listens on specific host:port due strictly following A01_BrokenAccessControl rules