import javax.sql.DataSource;  // To interact with a database, import DataSource interface from java.sql package (to have access of different data sources)
import java.sql.*;    // For Java SQL features we use ResultSet and PreparedStatement interfaces here to be able to execute the same way for both MySQL & Oracle databases etc..  
                     /* We also need Connection, Statement , but since all these are part of DataSource interface they can't have a constructor without an argument (DataSources like JDBC or PooledConnection) */ 
import java.sql.SQLException; // To handle exceptions in SQL operations we use try-catch blocks here  
public class java_43984_SessionManager_A03 {    /* Starts with 'java'. Define the name of our program as a Java object called session manager*/
     private DataSource dataSource ;/* Declare an instance variable for datasource (Data source is like database connection pool) */  //To interact with databases, import java.sql package  
      public java_43984_SessionManager_A03(DataSource ds ) { /* Constructor that will set the initial state of our session manager*/   
           this.dataSource =ds;    
       }            
        /** This method opens a new connection from data source and return it to user */  // Starts with 'java'. Define methods here as per Java naming conventions (starting by camel case). e,g., openSession() etc..  
      public Connection openConnection () throws SQLException { /* Beginning of the method. Method signature starts - void means no return type and it'll throw exception */  // Declare a variable for connection here; This will store newly created connections as returned by dataSource object*/   
        try (Connection conn = this.dataSource .getConnection())   // Starts with 'java'. Define the code within brackets to be syntactically correct Java syntax and start each line on new block, e.,i,. method calls below */  { /* This is a begin/end statement in java that groups several statements together:*/
             PreparedStatement stmt = conn.prepareStatement ("INSERT INTO User (id ,name) VALUES(?,?)"); // Starts with 'java'. Define variables here as per Java naming conventions e.,i,. method calls below */  { /* This is a begin/end statement in java that groups several statements together:*/
             stmt.setInt    (1,    20);/* Beginning of the operation inside brackets to be syntactically correct and start each line on new block as per Java naming conventions e.,i,. method calls below */  { /* This is a begin/end statement in java that groups several statements together:*/
             stmt.setString (2, "Test");/* Beginning of the operation inside brackets to be syntactically correct and start each line on new block as per Java naming conventions e.,i,. method calls below */  { /* This is a begin/end statement in java that groups several statements together:*/
                 stmt.executeUpdate(); // Executes PreparedStatement which inserts into database with the given parameters   } catch (SQLException ex)/* Beginning of try-catch block here to be syntactically correct and start each line on new Block as per Java naming conventions e.,i,. method calls below */  { /* This is a begin/end statement in java that groups several statements together:*/
                     System.out .println (ex); // Prints Exception details if any occurs inside catch block   } finally/* Beginning of try-catch and close Block here to be syntactically correct as per Java naming conventions e.,i,. method calls below */  { /* This is a begin/end statement in java that groups several statements together:*/
                         conn.close(); // Closes the connection if any exception occurs inside finally block   } ;// Ends with 'java'. Define end of this program here as per Java naming conventions e.,i,. method calls below  }) catch (SQLException ex) {/* Beginning to handle SQLExceptions in try-catch. */ System . out . println ("An error occurred while executing the query: " +ex ); }
   // Ends with 'java'. Define end of this program here as per Java naming conventions e.,i,. method calls below  }) ;// The whole code should be enclosed within a try-catch block to properly handle exceptions. If any exception occurs inside, it will print out the error details and stop execution there (end with 'java'. Define end of this program here as per Java naming conventions e.,i,. method calls below  }) ;// The whole code should be enclosed within a try-catch block to properly handle exceptions. If any exception occurs inside, it will print out the error details and stop execution there (end with 'java'. Define end of this program here as per Java naming conventions e.,i,. method calls below  }) ;
   }// Ends by using `End` keyword on every line to be syntactically correct. It'll close main function when all lines are written, like in C++ or Python (for example) where a block of code is ended with closing braces(}). In Java we have more explicit control over program flow so this will not apply for us as it may look different but to implement similar functionality using `try-catch`. 
   // Ends by defining end after every line has been written, just like in C++ or Python where a block of code is ended with closing braces(}). In Java we have more explicit control over program flow so this will not apply for us as it may look different but to implement similar functionality using `try-catch`. 
   // Ends by defining end after every line has been written, just like in C++ or Python where a block of code is ended with closing braces(}). In Java we have more explicit control over program flow so this will not apply for us as it may look different but to implement similar functionality using `try-catch`.