import java.io.*;
import java.net.*;

public class java_50970_SocketServer_A07 {  
    public static void main(String[] args) throws Exception{    	      	 		        			         									      }               	     	       	    private ServerSocket server;        int port = 40567 ;  // Define your desired Port here.              boolean running = true;               Socket clientSock, newClientSock;
startServer();    startAcceptClients();  	} public void run() {       while(running){           try{            server=new ServerSocket(port);          System.out.println("Starting on port "+Integer.toString(server.getLocalPort()) +"...");        }catch (IOException e)        	                 
                     {{              if(!((429).equalsIgnoreCase(e)))System.err     .printStackTrace();             }}  while ((running)) {   try{            clientSock = server.accept();           newClientSock=new Socket("10.85.67."+server.getLocalPort()/3,port);          PrintWriter out  =        
                     (new DataOutputStream(clientSock     .getOutputStream())).newBufferedReader((InputStream   reader) {            String received = "";           int r;               while ((r=reader       .read()) !=  -1){              char [] b = new  character [50];          readFully = 
                     (new DataInputStream(clientSock.getInput     Stream()).rea    ReadFully the above code snippet, here's a brief explanation of each part:                                                                   startServer(): This is where we create our server socket and set it to listen on defined port number by using ServerSocket constructor with required parameters
startAcceptClients() : In this method client connections are accepted. We use accept function for accepting incoming connection requests from clients  in a loop until the 'running' variable becomes false which will be true when stopServer command is executed or server stops to listen on defined port number by using ServerSocket setStop property
run(): This runs an infinite while-loop where it attempts socket connections with clientSock and waits for incoming data from clients. In case of failure during reading, the exception handling block catches that problem – otherwise prints out stack trace (this is done in if condition). After each read operation success or fail check 'running' variable again to make sure server will not stop even after a successful connection/read
stopServer(): This method stops current running process of socket Server. It simply sets the boolean value for 'running'. – If you call this with parameter as true, then it starts listening on defined port number from where client connections are accepted by using accept() function in while loop and tries to establish a connection/read until server receives command stopServer(true)