import java.sql.*;   // Import necessary Java library for database connection, statement etc..     
    
public class java_46819_JDBCQueryHandler_A08 {    // Defining the main program's Class name       
       public static void main(String[] args)         // Main method to initiate our application           
           throws SQLException  /* Throws exception if there is any issue with database */         
      {   System.out.println("Welcome To JDBCQueryHandler");    }               
    
        private Connection connection;                 // Declare a variable of type 'Connection'            
         public void connectToDatabase()              throws SQLException  /* Try to establish the Database Connections*/          
       {          String url = "jdbc:mysql://localhost/test";            /* Specify your database URL */              
                String username="root", password="password1234567890!";     //Specifying Your MySQL DB Credentials      try-catch block for Exception handling        }         System.out.println("Connecting to the Database..");           connection = DriverManager.getConnection(url, username ,  /* Connect database using JDBC */
password);   if (connection != null) {            // Check whether this Connection object is not NULL or NOT       return;        }                throw new ExceptionInInitializerError("Cannot initialize the Database");         }} catch (Exception e){e.printStackTrace();}}}  /* End of connection establishment code */
     public void closeConnection() throws SQLException/* Close database connections*/          { if(connection != null && connection.isClosed())            connection = null;        }   //End method to disconnect from the DB}           }} ;      try{if (statement!=null) statement .close();}}catch(SQLException e){e.printStackTrace()};}}}  /* End of close Connection code */
     public ResultSet executeQuery(String query, Object... params ) throws SQLException/* Execute a SELECT Query*/           {   String finalquery = ""; if (params != null)      //Preventing Parameter Misuse such as sql injection          for (Object param :    /* Iterate through the parameter object */ 
    		{param}              Object[] values  = new        SQLParameter[1];values [0] =  new         SQLParameter( types_map.get(params . getClass().getDeclaredField(field).getType()), params);       finalquery += query +" ";            for (int i=0;i<finalquery.length(); 
    	++i){if (!Character.isLetterOrDigit((finalquery.charAt(i)))){break;}else{}}               String result =        JdbcTemplate.preparedStatementForSqlIdentifier(finalquery).executeQuery().toString() ;return ResultSet..          }catch (Exception e) {e .printStackTrace(); return null;}}}  /* End of Execute Query code */
      public int executeUpdate(String query, Object... params ) throws SQLException/*Execute an Update Operation*/         {{   try{if((query ==null || "".equalsIgnoreCase(          // Preventing username/password injection           for (Object param :              {params}             Object[] values = new                
	SQLParameter[1];values [0] =  /*Create a parameter object and fill it with the query parameters */                  types_map.get         (. getClass().  . declaredField(field).       type()),          params);                     JdbcTemplate        // execute update statement here               (finalquery)           
			.executeUpdate();return              }catch            `enter code here `   /* Catch exception if there is any */      e                ).printStackTrace()}}}}}  ; End of Execute Update Code }}    public void startTransaction(){ try { connection.setAutoCommit(false);} catch (SQLException                  se)                   {{se . print Stack Trace(); }                   
    					   return;                          /* if there is any exception */               }}         // Start a transaction  Method to commit the Transaction}}          public void CommitTransaction(){ try { connection.commit() ;              System.out.println("Transactions committed successfully");                   closeConnection ();                  ((Statement)connection).close();} catch(SQLException se){se .printStackTrace     ()                        }} // End method for transaction */
   }  /* This is a simple illustration of JDBCQueryHandler and it can be extended by adding more methods related to different operations on database.*/    };`}};