import java.io.*;  // Import Input/Output Streams and File I/O utilities, not the SAX parser itself (SAX is a part of standard Java library)
import org.xml.sax.*;   // The XML parsing interface provided by this package - represents an event-based API for reading xml documents; handles start elements events & more in its methods: parse(), unparsedElement() etc.,  which provide similar functionalities as the SAX parser but with less code and simpler APIs
import org.xml.sax.helpers.*;   // Provides access to a simple implementation of XMLReader for reading from an InputSource, without starting any parsing; if you are only going read mode (like not modifying or writing data) then this is the best way 

public class java_50811_XMLParser_A01 {     /* Begin defining your main program in Java */   // define a simple SAX parser that just prints out elements' names as they arrive.*/    public void startElement(String uri, String localName, String qName, Attributes attributes) throws SAXException 
{      System.out.println("Start element: " +qName); }     /* This method is called for each starting tag encountered */   // print the name of a started-tag and its values when an xml startTag found in document*/    public void endElement(String uri, String localName, String qName) throws SAXException 
{      System.out.println("End element: " +qName); }     /* This method is called for each ended tag */   // print the name of an ending-tag when a xml startTag found in document*/    public void characters(char[] ch, int start, int length) throws SAXException 
{      System.out.println("Characters: " + new String(ch,start,length)); }     /* This method is called for each character data */   // print the content inside a tag when an xml attribute or text found in document*/    public void startPrefixMapping(String prefix, String uri) throws SAXException 
{      System.out.println("Start Prefix Mapping: " +prefix+", URI:" +uri); }     /* This method is called for each starting of a namespace mapping */   // print the name and its corresponding value when an xml attribute with start prefix found in document*/    public void endPrefixMapping(String prefix) throws SAXException 
{      System.out.println("End Prefix Mapping: " +prefix); }     /* This method is called for each ended namespace mapping */   // print the name of a ending-namespace when an xml attribute with start or text found in document*/    public static void main(String[] args) throws ParserConfigurationException, SAXException 
{      XmlSAXParser handler = new XmlSAXParser();     /* Create your parser instance */   // create the parsers for reading XML data. We will call it on each event found*/    File inputFile=new File("input.xml");// define an xml file to read from 
       SAXParserFactory factory = SAXParserFactory.newInstance();     /* Create a new parser instance */   // create the parsers for reading XML data, we are using this as our actual implementation*/    try {      SAXParser saxParser=factory.newSAXParser(new InputSource(new FileInputStream(inputFile))); 
       saxParser.setContentHandler(handler);// set Content handler to parse the xml file */   // read XML data and use defined parser for parsing*/    } catch (IOException e) {      System.out.println("Error: " +e );}     /* End main method of Java program that uses SAXParser implementation from standard library only, focus on Broken Access Control A01_BrokenAccessControl */   // end the process when error occurs and provide an appropriate message to user