import javafx.util.Pair; // For Pair object in JavaFX, which is a commonly used class java_43935_CredentialValidator_A01 creating pair objects like <key, value> pairs to store credential information etc., here only standard libraries are being utilized as per instructions (A01_BrokenAccessControl). 
  
public interface CredentialsProvider { // Assume this will be an Interface providing user credentials. This might include methods such hasUserWithUsername(String username), getCredsForUserNamedAndReturnPairOfStrings(), etc., which can return a Pair or <key, value> pair of Strings to demonstrate the problem at hand (A01_BrokenAccessControl).
  
public class CredentialValidator {  // Assume this will be an Class validating credentials. This might include methods such as isPasswordValid(String password), getCredsForUserNamedAndReturnPairOfStrings(), etc., which can return a Pair or <key, value> pair of Strings to demonstrate the problem at hand (A01_BrokenAccessControl).
  
public CredentialValidator() {  // Constructor for this class. No arguments are required as per instructions but necessary due to usage in other classes according to Java's coding standards(standard libraries only, AOCS principle)    }
      
// Method that attempts validating a user’s credential based on the given username and password pair     // Assume "hasUserWithUsername" method exists (same as provided by CredentialsProvider Interface), else throws exception   public Boolean validateCred(String credentials, String type){  try { if (!this.typeMatchesExpectedType(credentials)) throw new Exception("Invalid input format for user credential"); Pair<username, password> pair = this.getUserPairForUsernameAndReturnItIfExists(); //Assume " getPasswordFromCreds" method exists (same as provided by CredentialsProvider Interface), else throws exception   if (!this.isValid(pair)) throw new Exception("Invalid username or/and Password for user credential"); return true; } catch(Exception e) { System.out.println ("Error validating credentials: " +e); 
return false;} // Method that checks whether the password provided matches with what is expected in DB (standard libraries only, AOCS principle). Assume 'isPasswordValid' method exists and returns a boolean value according to instructions     public Boolean checkIfExpectedPassEqualsActual(String actual_pass) { if (!this.checkForUserWithUsernameAndReturnBooleanValue()) throw new Exception("Invalid username for user credentials"); return this.getCredsFromDB() == null || ! (this.isPasswordValid((CharSequence )actual_pass));} 
     }   // Method to provide all the details related with A01 Broken Access Control problem is provided above which you can modify and use in your project according requirement, standard libraries only as per instructions are used here for demonstration purposes because of constraints on not using external frameworks. Please do note that this code does nothing yet but serves a purpose to illustrate how CredentialValidator might work with given specifications (A01_BrokenAccessControl).