import java.io.*;       // for InputStream, OutputStream   (InputStream & Ouputstream are used)     
import java.net.*;     // for ServerSocket and Socket    (Server socket is a service that runs on port number provided by the user in argument of its constructor until it gets disconnected or server side shuts down.)  And DatagramSocket,DatagramPacket   (used to send/receive data across network)
import javax.net.ssl.*; // for SSL ServerSocketFactory and KeyStore    (.getServerSocket method uses this class java_47190_SocketServer_A03 keystore is provided else throws exception )     .createKeyPair() used in ssl context  , loadKeyMaterial(), storeType, privatekey passphrase etc.)   (used to encrypt/decrypt socket communication)
import java.security.*; // for KeyStoreException    (.getDefaultAlgorithm method returns algorithm name if exists else throws exception )     .generateKeyPair() used in ssl context  , keyAlias and passwords, privatekey passphrase etc.)   (used to generate new keys or load existing ones)
import java.util.*; // for ArrayList     
public class SSLServer {   
//Main method begins execution of the Java program       void main(String args[]){     try{  Socket socket = null; ServerSocket server_socket=null ;   List<Socket> clientsList  = new ArrayList<>();        KeyStore keyStore   = KeyStore.getInstance("JKS");         FileInputStream fis    =new    FileInputStream("/Users/admin/.keystore")       //path to your keystore file 
           ("/home/user1234567890" + "/my_key"));      StoreManager storeMgr =StoreManager.getInstance();   KeyManagerFactory kmf    =  storeMgr .getKeyManagerFactory("Mykeystore", "password".toCharArray()); 
            TrustManagerFactory tmf    =storeMgr .getTrustManagerFactory() ;       SSLServerSocket server_ssl   =null;    Socket client  = null, socket =server_socket.accept();        OutputStream out=     new FileOutputStream("/Users/admin/.sockedfile");      InputStream in = 
           socket.getInputStream ();  BufferedReader br=  new   BufferedReader(new InputStreamReader((in)));    PrintWriter pw  =       null; try { server_ssl    = SSLServerSocketFactory .createServerSocket(8954, tmf , kmf) ;     out=server_socket.accept().getOutputStream()
           } catch (IOException e){   System.out      .println("Exception occur while creating socket in main method")  }; try { pw   =new PrintWriter((new FileOutputStream("/Users/admin/.sockedfile")));    for(;;)     //run forever till it gets disconnected by client or server shuts down
            ;{   String msgFromClient = br.readLine(); if (msgFromClient==null) break;}  pw .println("Server : " +      System.getProperty ("java.home") );pw         .flush()    }catch(Exception e){System..out....printStackTrace());}
            finally {     socket != null && (!socket   .isClosed()) ? (clientsList           ).remove          (client) :  ((SSLServerSocket      )server_ssl).close(); pw         and        if    out! =null?(new FileOutputStream("/Users/admin/.sockedfile")):pw.getWriter() != null    
            ?   ("New Out stream is set for user" + socket);  } catch (IOException e) { System..out....printStackTrace();} //main method ends here };         Socket client = server_socket .accept(), so after getting the connection from    accept loop you need to send data using
            OutputStream out=client.getOutputStream() ; BufferedReader br =  new  InputBuff           er(newInputStreamReceiver()) } catch (Exception e){ System..out....printStackTrace(); }} //catch block for handling all exceptions in main method ends here     }; if...then statement begins at the end of each loop and finally blocks are used to close down things like server_socket, BufferedReader etc.