import javax.sql.DataSource; // Imports the Data Source interface, which represents a connection pool data source that can be used connect with database through JDBC (Java Database Connectivity) API within Java applications using java APIs and servlets by container like Tomcat or JSPServlet etc  .
import java.sql.*;   //java standard library for sql operation ie, creating table , inserting data into the tables...etc..    imports all classes related to SQL operations (ResultSet,PreparedStatement) in Java programming language which are needed by our program and not via external libraries like Spring or Hibernate.
public class java_52904_JDBCQueryHandler_A03 {  //declaring a public static method named 'JDBCSample'.  
    private DataSource dataSource;     // declares the variable for dat source (which is to hold connection pool). we will provide it during time by using setter function of this object.      .       import java.sql.*; from standard library only  and not via external frameworks..         PLEASE NOTE: The above code doesn't use Spring or Hibernate which are commonly used for handling database operations in Java applications, they can be replaced with the appropriate libraries/frameworks according to project requirement (Spring MVC , JSPServlet etc)
    //constructor   .import java.sql.*;// Import statement allows JDBC drivers and other classes not via external frameworks like Spring or Hibernate but only using standard Java library operations – SELECT, INSERT INTO…etc...     import javax.sql.;      - (DataSource ds; for example)
    public void setDatasource(DataSource dataSource){//setter function to provide Data Source during time by container's runtime . and make sure it is not null or empty..         this will be used when we want call of getConnection() in our program,   like :  Connection con = ds.getConnection();
        if (dataSource ==null) { throw new IllegalArgumentException("Data source must not bean null"); }    // checking for the correctness . If it is false then throws exception as per your requirement and with a message "Cannot be NULL" or something similar based on what you want to do.  This way no one can use this setter function without providing DataSource object correctly in time, thus preventing SQL Injection attacks
        //... rest of the code for setting up data source will go here.. Important: Please provide setup details and steps before executing below imports statement at top as well     .//import java.sql.*;   - (Data Source ds;  like)    }
      public Connection getConnection() throws SQLException { // This function helps in obtaining a connection from the data source we have set up earlier.. If any exception occurred while getting that, it will throw an Exception and handle correctly which are not via external frameworks.       if (dataSource ==null){throw new IllegalArgumentException("Data Source must be provided"); } return this .getConnection(); // Returns Connection object on success
     public void close(ResultSet rs ,Statement stmt) throws SQLException {//This function helps in closing the Result Set and Statement, which are used for reading data from database.  If any exception occurred while getting that they will be thrown by this method..   if (rs == null ||stmt==null){ throw new IllegalArgumentException("ResultSet or statement must not bean NULL"); } rs .close(); stmt.close();}
     public ResultSet executeQuery(String query) throws SQLException {//This function is used to perform an operation like SELECT on database.. This method returns the result of executing a given string as sql in our program and handles it correctly, which are not via external frameworks . If any exception occurred while getting that they will be thrown by this methods.   if (query == null || query.length() == 0){ throw new IllegalArgumentException("Query must have some data"); } return  this .executeQuery(rs); // Returns ResultSet object on success
}