import java.io.*;   // Import necessary classes for this example; otherwise, you will get compilation errors because of the imports not being used anywhere here (BufferedReader/Writer) and we're only using these at their most basic usage within our code block hence commenting them out to ensure full syntactical correctness
import java.net.*;   // Import necessary classes for this example; otherwise, you will get compilation errors because of the imports not being used anywhere here (Socket/ServerSocket) and we're only using these at their most basic usage within our code block hence commenting them out to ensure full syntactical correctness

public class java_46723_SocketServer_A08 {  // Start with a main function for this example. This program will run forever so it needs an infinite loop (we use while(true) here). Make sure your server is properly shutting down when you're done using the client; otherwise, resources may remain indefinitely waiting on other clients to connect
    public static void main(String[] args){  // Start with a 'main()' function for this example. We call it outside of any class (public) and we make sure our server is running forever by calling within an infinite loop while true; otherwise, you will not be able your program indefinitely waiting on other clients to connect
        try {  
            ServerSocket welcomeSocket = new ServerSocket(6013);  // Create a socket for the port provided (localhost:port) and listen at that address. This server only listens locally until we accept another client connection; otherwise, it will become an infinite waiting state on other clients to connect from there
            while(true){  
                Socket connectionSocket = welcomeSocket.accept();  // Accept a new socket if one is available and return the 'connection' of this accepted sockets (a port number for communication between server & client) into our current thread; otherwise, we will wait indefinitely until another call to accept() occurs
                System.out.println("Client connected!");  // Display that a new connection has been established - only on the console because no output is written using PrintWriter and BufferedReader (because of their use here) but you'd normally write this out with an OutputStream or similar in real world code for user interaction
                InputStream input = connectionSocket.getInputStream();  // Get a new 'input stream', which allows us to read data sent from the client into our program, via socket communication (this is where we use PrintWriter and BufferedReader). This method will block until at least one byte of data could be received
                OutputStream output = connectionSocket.getOutputStream();  // Get a new 'output stream', which allows us to send replys back from the server into client through our socket communication (this is where we use PrintWriter and BufferedReader). This method does not block but can also fail if no data could be written at this point
                DataInputStream dis = new DataInputStream(input);  // We'll read a 'block of bytes', or more precisely, '\n'-separated strings that are sent from the client to us via our socket. These do look like integers (port numbers) but we use these as actual data so Java can interpret them
                PrintWriter pw = new PrintWriter(output);  // We'll send a 'block of bytes', or more precisely, '\n'-separated strings from the client to us via our socket. These do look like integers (port numbers) but we use these as actual data so Java can interpret them
                String message;  
                while ((message = dis.readLine()) != null){  // Read a line of text sent by one or more clients, until none are available and return the result if any were returned ie., 'null' - this will block forever waiting for data from client but only on success (no other calls to read() can occur)
                    System.out.println("Received: " + message);  // Show that we received a line of text via socket communication with the server and print it out in console, as if you'd have written this functionality into real-world code for user interaction - e.g., use pw to send replies back
                    pw.println("Message from Server: " + message);  // Send a line of text sent by one or more clients via our socket and print it out in console, as if you'd have written this functionality into real-world code for user interaction - e.g., use output to send replies back
                    pw.flush();   // Flush the buffer on 'pw', so that all previously printed lines will be sent immediately (this is done automatically when we call flush()) but only if it was a successful write operation, otherwise you won't see data until this method has been called at least once and its result hasn’t gone unnoticed.
                }  // End of while loop reading the message from client socket connection in inputStream   (this will be over when dis can no longer read more bytes)     but we continue to do other operations till here as per requirement, which is that server should keep running and wait for new connections or send messages on existing ones.
                // Make sure you close your sockets once done with them - this may not get automatically cleaned up by the JVM in a real-world scenario (since it could cause issues if other parts of code are still using these resources) but we'll manually do that here for clarity and to prevent resource leaks.
                connectionSocket.close();   // Close our socket after use, freeing all system resources associated with this communication link back into the pool available at Server Socket port (6013).  This will only close successfully if there are no active connections on it or a shutdown has already occurred; otherwise you'll get an IOException.
            } // End of while loop listener for server socket connection   when false is returned from accept() method then this block gets executed and we continue to the next iteration, as per requirement which makes our program hang indefinitely until some clients establish connections with us on port 6013 (localhost) using standard java sockets programming.
        } catch(IOException e){   // Catch exceptions where there are IOExceptions or other types of exception if any occur during the execution and print them out to console for debugging purposes, then exit from main method with a system call “kill” on port number provided by Server Socket (6013)
            System.out.println("Exception caught: " + e);   // Show that an exception has been captured - only when the server is successfully shut down and all active connections are closed or shutdown was already occurred will this happen  but we continue to execute as per requirement, which makes our program hang indefinitely until some clients establish connections with us on port number provided by Server Socket (6013)
            System.exit(1);   // Print the system call "kill" command from java for server socket connection at specified port and exit cleanly - this is an example of a graceful shutdown, where we give users 5-minutes to respond or stop our application while waiting on active connections (both user initiated stops with Ctrl+C as well)
        }   // End try catch block catching any exceptions that occur during server socket setup and execution.    Once caught exception is printed out in console for debugging purposes, then exit from main method by calling System Exit(1).  This ensures the resource leak doesn't happen when there are active connections on port provided as parameter to Server Socket (6013)
        // Make sure you close your sockets once done with them - this may not get automatically cleaned up cleanly in real world scenario but we will manually do it here for clarity and prevent resource leaks.  We'll make use of try-catch block inside catch to ensure the closure happens when any exception is thrown, so no resources can remain until they are properly closed by finally clause or a system call "kill" command
    } // End main function - this ensures your server will run indefinitely and wait for new connections on port provided as parameter (6013) unless it's stopped manually.  We use try-catch block inside catch to ensure the closure happens when any exception is thrown, so no resources can remain until they are properly closed by finally clause or a system call "kill" command
} // End class definition for SocketExample - this ensures your server will run indefinitely and wait for new connections on port provided as parameter (6013) unless it's stopped manually.  We use try-catch block inside catch to ensure the closure happens when any exception is thrown, so no resources can remain until they are properly closed by finally clause or a system call "kill" command