import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
public class java_45003_SessionManager_A03 implements Servlet {     // a servlet can handle multiple requests, it will have the same interface methods asServlet API defines in this case we use only one method to getSession(..) and setAttribute().  In reality you would want more for handling sessions with different session scopes. But that's not within scope here
{     // a servlet is an entity which runs on your server, it has methods like init(), service() etc., we don’t need to define them in our scenario so I have used only one method getSession(..) and setAttribute().  In reality you would want more for handling sessions with different session scopes. But that's not within scope here
    private HttpServletRequest request;      // this will hold the latest HTTP Servlet Request from a client, it is read by servlets only but used in our code as we use Session Object to manipulate data later  	HttpSession session = null ;    	// Lazy Initialization – when no object yet created then not at all.
    public void init(ServletConfig config) throws ServletException {       // initialization method which gets called once the servlets container launches it and calls this every time a request is made to your web app, you can put any startup code here	System.out.println("SessionManager Initialized");	}    
    public HttpServletRequest getRequest() 	{ return (HttpServletRequest)request; }       // these two methods are only called in init and service method of Session Manager as they call the actual request object from an HTTP context to a servlet container where it can be accessible	  			return new Request(session);	}
    public ServletConfig getServletConfig() { return null;}    	// This should always fail with any implementation if you have one. In this case we are not using them because the session is never going out of scope and only being used by our servlets, then so it would be a waste to make an exception when there's no need for such behavior	  			return null;	}
    public void service(HttpServletRequest request , HttpServletResponse response) throws ServletException {     // this method is called whenever the getSession() in SessionManager needs session object, or just once if none yet. This will be when we actually create our own HTTP context for every servlets	System.out.println("Service Method Called");   			// We are using httpcontext to handle requests from client and send responses back . If you used HttpSession then it would have been done by the time getRequest() was called	}
}