public class java_51048_CredentialValidator_A01 {   // Creating a new Java Class named 'Credentials' in the same package.
    private String username;     // Declaring variables for Username & Password inside this credentials object.
    private String password;     
                              
                                /* In order to create an instance of these class, we need 2 parameters */  
                                                  public java_51048_CredentialValidator_A01(String userNameInputted , string passWordinput) {       // Constructor - Creating a constructor for the credentails object.    
                                                                        this .username =userNameInputted;                         /* Initializing variables using 'this' keyword, we are setting properties of our objects */  
                                                                }  self-explaining code to be removed if it gets too long    //self explanatory - Removing these comments and leaving the actual lines.     public String getPassword() { return password;}      void setpassword(String passWordInput)            this .password =password input;                 /* Inside method we are setting our variables */
                           }                                                                                                                  private char[] encryptCredentials(){  // This is a simple encryption of credentials (You can use any algorithm to replace it).     Private character array encryptedPassword=new Character[username.length()+ password .lenghth];      for(int i =0;i< username and passWordinput);          /* Encryption will happen here, you may want different encryptions algorithms */
                   }   public boolean validate (){  // This is the validation method of credential validator.     Public character array encryptedPassword=new Character[username.length()+ password .lenghth];      for(int i =0;i< username and passWordinput);          /* Encryption will happen here, you may want different encryptions algorithms */
                   }  public char[] getEncryptedCredentials(){ // This method returns the encrypted credentials which can be used to validate users.     Private character array encryptedPassword=new Character[username .length()+ password..lenghth];      for(int i =0;i< username and passWordinput);          /* Encryption will happen here, you may want different encryptions algorithms */
                   }  public void setEncryptedCredentials (char[] encryptedInput){ // This method is used to Set the encryption result of password.     Private character array encryptedPassword=new Character[username .length()+password..lenghth];      this .encryptcredential = encrytptedinput;                   /* Inside methods we are setting our variables */
                            }  public String getUserName(){ // This method returns the username of credentails.     Public character array encryptedPassword=new Character[username length+ password lenghth];      return this .user name ;                 Private string username,passWordinput;    /* Inside methods we are setting our variables */
                            }  public void setUserName(String UserInput){ // This method is used to Set the username of credentails.     Public character array encryptedPassword=new Character[username length+ password lenghth];      this .user name = userinput;                   /* Inside methods we are setting our variables */
                            }  public String getPassWord(){//This Method Returns The Password Of Credentials    Private string encryptCredential,passwordInput ;   return this.pass word;} // This method is used to Set the password of credentails .Public character array encryptedPassword=new Character[username length+ passwor lenghth];  setPassWord(String passwordinput){this.password = password input;}}     /* Inside methods we are setting our variables */