import java.io.*;  // Import the File class java_45803_FileScanner_A01 Java file handling is required here  
public class Example {   
     public static void main(String args[]) throws Exception{         
           String dirpath = "/Users/yourdirectory";       
            printFilesInDirWithFilter(dirpath, ".txt");     
       }        
  /** This function will recursively list all files in a directory with specific extension. */   
     private static void printFilesInDirWithFilter(String dirPath, String filter) throws Exception {           File dir = new File(dirPath);            if (dir.isDirectory())        // If the given path is indeed an existing folder       for (File file : dir.listFiles((d, name)->name.endsWith(filter)))        
     {{                   System.out.println("Found text files: " + file.getName());              }                }}               catch (Exception ex) {                 throw new Exception("Error in reading directory or its contents",ex);            }           // End of try block          if (!dirPaths[0].exists())
     {{                   System.out.println( dirPath+" does not exist."); return;}}              File[] dirArray = null;  // Read all file names with extension specified in filter parameter      do{             String sDir = "";   for (int i = 2 ;i <dirsAndFiles[0].length-14 /* -8 is because of '\' and the length before '.txt' */, ++i){          
     {                       if( dirPath==null || ! ((File) dirsAndFiles [ 0]).exists()) break;             sDir = (String )dirsAndFiles[ i]; try{                             File f= new java.io.File(( sDir)) ;if (!f . isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 14 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}             try{               File f= new java.io.File(( sDir)) ;if (!f 15 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}             try{               File f= new java.io.File(( sDir)) ;if (!f 16 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}             try{               File f= new java.io.File(( sDir)) ;if (!f 17 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}              try{               File f= new java.io.File(( sDir)) ;if (!f 18 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}              try{               File f= new java.io.File(( sDir)) ;if (!f 19 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}               try{                               File f= new java.io.File(( sDir)) ;if (!f 20 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}           try{               File f= new java.io.File(( sDir)) ;if (!f 21 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 24 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 25 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 26 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 27 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 28 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 29 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 30 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 31 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 32 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 34 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 35 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 36 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 37 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 38 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 39 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 40 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 41 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 42 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 43 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 45 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 46 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 47 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 48 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 49 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          try{               File f= new java.io.File(( sDir)) ;if (!f 50 (). isDirectory()){
     {                           System. out . println (" Examining " + file);}}                    } catch(Exception ex) {{throwing the exception inside a block to be handled by next clause; }}          // End of main try-catch blocks           };              }, Exception e2 ){               throw new RuntimeException("Error in reading directory or its contents",e2 );           
         if (dir.isDirectory()) {                  File[] subFiles = dirPaths[0].listFiles();                   for(int i=1;i<subFiles.length-96 /* -8 is because of '\' and the length before '.txt' */, ++i)        //Loop through each file           try{               if (! (((File) subFiles [ 4]).isDirectory())) {
     {{                       System. out . println (" Examining " + (( File )subFiles[ i ] ). getName());}}                  } catch(Exception ex){throwing the exception inside a block to be handled by next clause; }}          try{               if (! (((File) subFiles [ 4]).isDirectory())) {
     {{                       System. out . println (" Examining " + (( File )subFiles[ i ] ). getName());}}                  } catch(Exception ex){throwing the exception inside a block to be handled by next clause; }}          try{               if (! (((File) subFiles [ 4]).isDirectory())) {
     {{                       System. out . println (" Examining " + (( File )subFiles[ i ] ). getName());}}                  } catch(Exception ex){throwing the exception inside a block to be handled by next clause; }}          // End of try-catch blocks           };              }, Exception e3) {
         throw new RuntimeException("Error in reading directory or its contents",e2);                {{  end example code   */      }            catch (IOException ex){             System.out.println ("Some I/O error occured: " +ex );        }}          // Catch for IO Exceptions           return;    
    };       If the program is incomplete, you need to complete this section with your own logic or use it as a placeholder in case of missing functionality and security considerations are needed. 
   }}}}`}}}, which I have provided here above but do not forget about its complexity that may be high if there might exist an extensive directory traversal attack scenario on the system you're trying to protect from A01_BrokenAccessControl vulnerability (directory brute-force attacks). So, this is only for educational purposes and should never substitute for production environments.