import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
public class java_49811_SessionManager_A07 extends HttpServlet {   // Extends from the standard servlets http request and response object so as to get access of headers, cookies etc in context via super keyword   
       private static final long serialVersionUID = 1L;  // Required by Serializable interface     public void service(HttpServletRequest req , HttpServletResponse res) throws ServletException{   /*Implementation for session management*/        String authToken=req.getHeader("Authorization");//Fetching token from header
         if (authToken != null && authToken.equalsIgnoreCase("Bearer")) { //Check the given authentication type in case of authorisation  .eqlaisigorecase() to handle both upper and lower cases comparison  
                 try{    /*Start a transaction*/        HttpSession session = req.getSession(true);//Create an instance for http Session, true is optional it creates if not exists else throws exception or just returns the existing one  //Here we are checking whether user's authentication token has expired and create new Auth Token If yes then set in cookie otherwise get from exiting session  
                    String authTokenNew = UUID.randomUUID().toString();//Creating a random id for each request to prevent replay attacks on the same login  //We will use this as our authorization token which we'll put into header of next requests    if (session == null) { throw new ServletException("Could not establish session"); }
                     System.out.println(authTokenNew);//Here is just for demonstration purposes, in real implementation you should set it to HttpSession and user info  //Printing out the token on server side   else{ authToken = (String)session.getAttribute("Auth_token") ;}    session.setAttribute("Auth_token",authTokenNew);
                     res.addHeader("Authorization","Bearer " + authTokenNew );//Setting new Authorisation Token in the header for every request  //This will be used by front-end to authenticate user on each requests   } catch (Exception e){ throw new ServletException(e) ;}
         }} else { System.out.println("Unauthorized access!");    res.setStatus(HttpServletResponse.SC_UNAUTHORIZED);  //In case of unauthorised request we will send response un-authenticated   }}};//Closing bracket for servlet implementation
     private void doPost (HttpServletRequest req, HttpServletResponse res) throws ServletException {/*Implementation as required*/};      protected void doGet(HttpServletRequest req , HttpServletResponse res )throws ServletException{this.doPost(req,res);} //Closing bracket for servlets
  public static class SingletonInstance implements ServletContextListener   /* This is a way to make sure only one instance of this service exists and perform tasks whenever an event occurs */ {    private static AuthSessionManager single_instance;//Singleton Instance created here      @Overridepublic void contextInitialized(ServletContextEvent sce){/*This method gets called once the web application deployment*/if (single_instance == null) //If no instance is already there, create a new one. If it has been initialized then return   single_instance = this; else throw new ServletException("[AuthSessionManager] Already Initialized");}@Overridepublic void contextDestroyed(ServletContextEvent sce){/*This method gets called when the web application is undeploying or shutdown */single_instance=null;} /* SingletonInstance class ends here*/ };