import java.io.*; // Importing required Java classes, e.g., FileInputStream etc.
    
 public class java_51496_FileScanner_A03 {    // Creates a new main function that will be executed when we run our code as well its name is always the same 'main' in any language but it must contain only one type of data (e.g: void or String)  because java doesn’t support both at once if you try to declare more than ones variable with different types
     public static int count = 0; // Declare a global counter for injection attacks that will be used in our program, as we'll use it later on and only increment this value (not the file/directory)  when an attack is successful. It also acts like 'A2_FileRead'. Here again using standard libraries
     public static void main(String[] args){ // Main function where every action takes place - e.g., reading a directory or scanning files etc, here we'll scan the current working folder and count all '.txt'-files with injection attacks (e.g.: '; delete this line after testing)' 
          String userDir = new File(".").getAbsolutePath(); // Get absolute path of our workdir - will be changed later on due to file system operations as we'll use it in the loop below, here using standard libraries    
             try(FileScanner scanner=new FileInputStreamReader(userDir+"\\*.*")){ 	// Create a new instance (file or directory) of 'scaner', which is used for reading files and directories. The path will be dynamically set based on the current working folder due to standard libraries    
                  int c; // This variable acts as buffer, it stores each character from file/directory until we read all characters - here using only built-in Java classes   	  	   	 	       	     		 	// Here again use of standard library. The loop below reads every byte in the stream and increments count if a semicolon is found (e.g.: '; delete this line after testing)'
                  while((c=scanner.read())!=-1){ // Reads each character until - ‘EOF’ or end of file, here using only standard library classes  	      	   	 	       	     			// Here again use of built in Java class for reading files and directories as we're scanning the directory
                          if (c==';') {// If a semicolon is found then increment count – once per each occurrence due to loop below. The code after this line will be removed by me, here using only standard library classes	  	   	 	       	     			// Here again use of built in Java class for reading files and directories
                              ++count; // Increment the counter which is declared global on top – once per each occurrence due to loop below. The code after this line will be removed by me, here using only standard library classes	  	   	 	       	     			// Here again use of built in Java class for reading files and directories as we're scanning directory
                          }             // End if statement - e.g., closing the file or folder (here still not fully implemented due to security concerns) – once per each occurrence, here using only standard library classes	  	   	 	       	     			// Here again use of built in Java class for reading files and directories as we're scanning directory
                   } // End while loop - e.g., closing the file or folder (here still not fully implemented due to security concerns) – once per each occurrence, here using only standard library classes	  	   	 	       	     			// Here again use of built in Java class for reading files and directories as we're scanning directory
             } // End try/catch block - e.g., closing the file or folder (here still not fully implemented due to security concerns) – once per each occurrence, here using only standard library classes	  	   	 	       	     			// Here again use of built in Java class for reading files and directories as we're scanning directory
     } // End main function - e.g., closing the file or folder (here still not fully implemented due to security concerns) – once per each occurrence, here using only standard library classes	  	   	 	       	     			// Here again use of built in Java class for reading files and directories as we're scanning directory
 } // End Main function - e.g., closing the file or folder (here still not fully implemented due to security concerns) – once per each occurrence, here using only standard library classes	  	   	 	       	     			// Here again use of built in Java class for reading files and directories as we're scanning directory