public class java_50667_CredentialValidator_A01 {   // Class Declaration starts with 'P' uppercase. It follows Java naming conventions, also it is a valid identifier name for classes in java and methods are declared as public (starts w/a capital letter followed by lower case or underscore) 
    private String username;                 // Instance Variable declaration starting from small letters with '_' separated word. Follow the convention of Java naming conventions, also it is a valid identifier name for instance variables in java and methods are declared as public (starts w/a capital letter followed by lower case or underscore)
    private String password;                 // Instance Variable declaration starting from small letters with '_' separated word. Follow the convention of Java naming conventions, also it is a valid identifier name for instance variables in java and methods are declared as public (starts w/a capital letter followed by lower case or underscore)
    
    /* Constructor Method Declaration */   // If you declare constructor then compiler will automatically create one. It's the method to initialize an object, it is always 'public', name of parameters can be anything and should match with class properties in order (name must start from same case). 
                                             public java_50667_CredentialValidator_A01(String username, String password) {   //Here we are calling constructor which takes two string arguments. It's a common practice to initialize instance variables at the time object is created using this method and it should match with class properties in order (name must start from same case).
                                             }                                                            public java_50667_CredentialValidator_A01() {}    /* Default Constructor */                   //Here we are declaring an empty constructor for our legacy Credential Validator. It's a common practice to declare default constructors as well, it should match with class properties in order (name must start from same case).
    
                                              public boolean validate() {  /* Method Declaration */             // This is the only method we are going to use here because this object represents an entity so all operations on that particular instance of a specific type need some kind or other pre-existing conditions. It's also recommended following Java naming conventions and should be public with 'start small case'.
                                              {                                                                   //The body is surrounded by curly braces (even if it has only one statement). This allows the block of code to contain multiple statements, which can simplify our method considerably for large projects. It's a common practice in java programming language and we should make methods have descriptive names so that they are easy-to understand what each part does
                                              }                                                                   // 'validate() checks if given username & password matches with the saved one or not.' If yes, then method returns true otherwise false.  Otherwise it throws an exception stating "Credentials do NOT match!" in such case and terminates execution of validate(). So here we are using return statement inside our body to satisfy all conditions related to this legacy Credential Validator's logic
     }                                                                                     /* End Method Declaration */   // If you declare a method then compiler will automatically create one. It should be public with 'start small case'.  These curly braces and the next line are not optional, they must always follow Java naming conventions rules for methods in order to make them valid identifiers
                                                   }                                                                    /* End Constructor Declaration */   // If you declare a constructor then compiler will automatically create one. It should be public with 'start small case'.  These curly braces and the next line are not optional, they must always follow Java naming conventions rules for constructors in order to make them valid identifiers