import java.sql.*;   // Import necessary Java libraries/modules 
// Create connection object using Connection class java_42859_JDBCQueryHandler_A01 DriverManager API, specify database url & driver name as per MySQL JDBC URLs (remember to change the user info) and use 'com.mysql.cj.jdbc.Driver' when connecting with your DBMS if it is different from MySql 
Connection con=null;   // Declare Connection object type variable "con" for using in program   
try {    
        String url = "jdbc:mysql://localhost/dbname?useSSL=false";      
	String username = "username_here ";      string password =  "password_Here “ ;              con  = DriverManager.getConnection(url,   // Pass URL (database), Username and密码 to this method get connection         
DriverManager.deregisterDriver());     } catch (SQLException e1) {        System.out.println("Failed: Database [" + url +  " ] is not available");  try      {} finally    {}; con=null;   return;} // Catch Exception if DB URL or username/password wrong, set the connection to null and print error message        
try{     String query ="CREATE TABLE user (id INT AUTO_INCREMENT PRIMARY KEY , name VARCHAR(50) NOT NULL);";    Statement stmt= con.createStatement(); // Execute SQL statement using createStatement() method      try {stmt.executeUpdate(query)} catch  {} finally {}; }
try{   String insertQuery ="INSERT INTO user (name ) VALUES ('John'); ";     PreparedStatement ptmt  =con .prepareStatement(insertQuery);    con, executeUpdates are available now and you can use this method to get result set. try {ptmt.executeUpdate();} catch {} finally {}; } //Try-catch block for insertion query execution
try{  String selectAll ="SELECT * FROM user; ";   PreparedStatement pstmt   =con .prepareStatement(selectAll); con, executeUpdates are available now and you can use this method to get result set. try {ResultSet rs=pstmt.executeQuery();     while (rs.next())  //Iterate through each row in Result Set    System.outprintln("ID =" + rs.getInt(1)); } catch {} finally {}; con,close() will also be available now}
con . close();   //closing the connection at end of program         }}catch (SQLException e) {System out println “Error while executing statement in JDBC”;}}}}}// Catch Exception if there is any error. Close connections and resources when necessary          } catch( SQLException se ){ System.out .println ("JDBC Error : " +se );    }}