import java.io.*;  // Input/Output Streams & Buffered Reader's class java_51786_SocketServer_A08 java.net.*;    // InetAddress and ServerSocket, which we use for networking tasks classes (IPV4) in this context: SocketServer / Client handling is handled by these types of objects or services later on... . This would be done using the standard Java libraries only as per your request but here it was just a random way to create such server.
  
public class SimpleSocketServer {  //The client will connect through this socket (TCP Connection) Server side, not directly from inside itself via localhost:port number... . But we can use same port for different servers and clients with some exceptions at the time of connection too as it violates integrity failure rules. For example you might set a specific IP address or hostname to connect but that doesn't prevent others on your network (network/firewall) from establishing connections by default...
  
public static void main(String[] args){ //This will run method Main at the beginning of every java program, it is where our code starts. 
    try{//try and catch blocks are used to handle exceptions that may arise during runtime for readability & debugging purposes (it allows us)... . It's a good practice when writing multi-threaded programs like socket servers or clients in Java which can throw Exceptions at any time such as Input/Output Errors, Bind errors and so on.
      //Step 1: Set up the server - creating an endpoint for others to connect from within our own computer... . We use a ServerSocket object that waits until it gets connected via Socket objects which are tied back into one physical socket connection end point with some data, just like how file transfers operate.
      //Step 2: Waiting indefinitely (until we have to shut down) for connections - on the other hand when a client connects... . This is done by calling accept() method of ServerSocket and blocking until it gets one connected from outside source that's why "while(true)" loop.
      //Step 3: Sending & Receiving data between two computers (using streams) for communication with clients using the same socket connection, not directly to IP addresses or ports because port numbers in IPv4 are meant as a numeric address and TCP/IP protocol stack would take care of other details such as headers etc.
        ServerSocket server = new ServerSocket(3200); //Server setup (port number)... . Once the socket is opened, it waits for incoming requests at this port until we shut down or find a connection from outside source to be accepted with Socket object creation in accept() call below while loop.
        System.out.println("Waiting..." ); 
         //Step: Wait here (until something happens) and then respond back - This is the 'workhorse' of this program, it waits for a client connection by calling serverSocket对象s accepts method which will create new socket objects connected to one end point in an accepted request from other side. Once someone connects via that "accept()" call below while loop...
         //Step 4: Shutdown the Server - This is like shutting down our door (closing port number) when we're done with it, this lets all clients know so they can disconnect as well by calling close method on serverSocket object.   
        Socket socket = null;   //This will be used to connect and interact via the client that connected in loop through while(true). 
         try{                   //Try block for handling exceptions at runtime (this part is a must)... . This way, if something goes wrong here it won't break your whole program. If socket == null or its not initialized properly then what you are doing isn’t right and the entire server will hang around indefinitely until exception occurs
          //Step 1: Accepts an incoming connection from a client - It waits for new connections (client) with accept method... . Once it gets one connected, this thread is created which listens into that socket object so you can read/write data to the other end. The while loop here will keep listening until we shut down or find out something interesting happens in our server side like a client disconnecting from us and thus needs closing too..
            socket = server.accept();  //This method is blocking, it's waiting till there are new connections available... . Once one connection gets accepted into this thread by accept() then the while loop will go away because we have got our 'ready to handle client request here!' event in its scope (which can be a data read/write operation from or written back at least).
            System.out.println("Client connected...");  //This would print out when first connection is established... . This happens as soon the server accepts new socket connections and creates corresponding Socket object for that request - then starts waiting until client wants to send something.. (read/write) or disconnects from us, hence stops working in while loop below.
            PrintWriter output = null;  //This will be used later on... . To write into the connected stream of socket via this writer we have got our 'ready for writing data here' event at scope and then it’ll start sending that information to client which can read back by reader in respective loop part.
            BufferedReader input = null;  //This will be used later on... . To get the received or written info from connected socket via this Reader/Writer we have got our 'ready for reading data here' event at scope and then it’ll start receiving that information back to client which can write into writer in respective loop part.
            try{  //try block inside buffered reader (input) & printwriter(output), these two objects will handle input/reads from socket, output writes on stream connected with this Socket object and their operations are thread safe like streams do within java framework but they cannot be used directly by other class outside of that to read or write data via them. 
             //Step2: Create Stream Handlers - To manage the connections established (socket), send & receive can take place, we have got our 'ready for writing/reading' event in scope and then it’ll start reading from socket using BufferedReader on this Socket object or write data to stream connected with these sockets.
              input = new BufferedReader(new InputStreamReader(socket.getInputStream()));  //This will create a reader that reads the information sent by server into here for us... . This is how we can read from socket connection and get our 'ready in' event at scope, which means data has been received or something got written to stream connected with this Socket object via BufferedReader.
              output = new PrintWriter(socket.getOutputStream(), true);  //This will create a writer that writes into the info we have sent by server from here... . This is how you can write outgoing data onto socket connection and get our 'ready to send' event at scope, which means information has been written or something got read back via reader in respective loop part.
              String incoming;  //This will hold whatever comes into the stream connected with this Socket object (from BufferedReader input)... . This is how you can use buffers and get your 'ready to write' event at scope, which means we are ready for sending outgoing data via writer in respective loop part.
              incoming = input.readLine();  //This will read the entire line from stream connected with this Socket object (BufferedReader) into here... . This is how you can get your 'ready to write' event at scope, which means we are ready for sending outgoing data via writer in respective loop part
              System.out.println("Client says: " + incoming);  //This will print the received message from client ... (. this line gets executed each time when new information arrives on stream connected with socket) to our console... . This is how you can use buffers and get your 'ready in' event at scope, which means data has been read or something got written back via reader.
              //Step3: Close Stream Handlers - To manage the end of a connection established (socket), it’s done by closing BufferedReader & PrintWriter when we are finished with them... . This way our server can listen for connections again without having to set up new streams and readers/writers every time.
              input.close();  //This will close reader which is connected back into socket, making sure that no data from client (even if not completely received) goes through until when we have sent 'goodbye' message or disconnecting via our server closing the port... . This line ensures nothing remains in read buffer and thus helps to prevent OutOfMemoryError.
              output.close();  //This will close writer which is connected back into socket, making sure that no data from client (even if not completely written) goes through until when we have sent 'goodbye' message or disconnecting via our server closing the port... . This line ensures nothing remains in write buffer and thus helps to prevent OutOfMemoryError.
             } catch(IOException e){  //Catch block inside buffered reader (input/output operations), these will be handled by this try-catch when read /write operation fails on socket.. (.this is how you can handle exception at runtime) so that it won’t break your whole program, If we throw any IOException type exceptions then the error message gets logged and stop processing inside loop
              e.printStackTrace();  //This will print out complete stack trace of thrown Exception if something goes wrong... (.this is how you can use exception handling methods in java for better understanding & debugging).
             }   finally {    //Finally block to be sure that the resources are released at end which means closing streams when we're done with it. This ensures all resource usage gets freed up, even if something goes wrong while processing and catching exceptions from above try-catch blocks as they will not get executed in this Finally block where respective cleanup operations should happen like close of reader/writer or socket connection etc.. 
              //Step4: Shutdown the Server - This is when we're done with our server... . We can do a simple shutdown by closing up all active streams and then shut down (close) everything. So, finally blocks are there to ensure that at end of program if this happens it will close socket connection etc..
              output.close(); //This closes writer connected back into the client from Socket object... . This line ensures nothing remains in write buffer so we can free up resources and prevent OutOfMemoryError on next operations like read/write, ‘Goodbye' message for closing port or shutdown of server etc..
              socket.close(); //This closes reader connected back into the client from Socket object... . This line ensures nothing remains in write buffer so we can free up resources and prevent OutOfMemoryError on next operations like read/write, ‘Goodbye' message for closing port or shutdown of server etc..
            }// End while loop with condition here. It will keep listening until someone disconnects from us via socket object... . When this happens it won’t execute below code in try-catch block and hence we can safely stop our program using if (socket != null) statement to ensure no exceptions are thrown when closing the server/client
        } catch(SocketException e){  //Catch Socket exception, which is usually a sign of disconnecting from client.. (.this line gets executed only in case where socket object cannot be assigned or some other issue at runtime). It's not needed for our program as we are already checking conditionally (if statement) to ensure no exceptions occur.
            e.printStackTrace();  //This will print out complete stack trace of thrown SocketException if any error occurs while accepting the socket connection from client... (.this line gets executed only in case where socket object cannot be assigned or some other issue at runtime). It's not needed for our program as we are already checking conditionally (if statement) to ensure no exceptions occur.
        }  //End Catch block inside try and finally, these will handle any IOException type exception that may happen while handling Socket connection when reading / writing data via socket... (.this line gets executed only in case where socket object cannot be assigned or some other issue at runtime). It's not needed for our program as we are already checking conditionally (if statement) to ensure no exceptions occur.
    } catch(IOException e){ //Catch block inside try and finally, these will handle any IOException type exception that may happen while setting up the server... (.this line gets executed only in case where socket object cannot be assigned or some other issue at runtime). It's not needed for our program as we are already checking conditionally (if statement) to ensure no exceptions occur.
        e.printStackTrace(); //This will print out complete stack trace of thrown IOException if any error occurs while setting up the server... (.this line gets executed only in case where socket object cannot be assigned or some other issue at runtime). It's not needed for our program as we are already checking conditionally (if statement) to ensure no exceptions occur.
    } // End catch block and finally, these will handle any IOException type exception that may happen while setting up the server... (.this line gets executed only in case where socket object cannot be assigned or some other issue at runtime). It's not needed for our program as we are already checking conditionally (if statement) to ensure no exceptions occur.
    } //End Main block and finally, these will handle any IOException type exception that may happen while setting up the server... (.this line gets executed only in case where socket object cannot be assigned or some other issue at runtime). It's not needed for our program as we are already checking conditionally (if statement) to ensure no exceptions occur.
  } //End of Main block and finally, these will handle any IOException type exception that may happen while setting up the server... (.this line gets executed only in case where socket object cannot be assigned or some other issue at runtime). It's not needed for our program as we are already checking conditionally (if statement) to ensure no exceptions occur.
}  //End of Class Main block and finally, these will handle any IOException type exception that may happen while setting up the server... (.this line gets executed only in case where socket object cannot be assigned or some other issue at runtime). It's not needed for our program as we are already checking conditionally (if statement) to ensure no exceptions occur.