import java.io.*;
import java.net.*;

public class java_46016_SocketServer_A03 {  // Starts server at port 1234   #a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs / aCSEdited by Deepseek Company
    public static void main(String[] args){     //b This is just an example of security-sensitive operations related to injection attacks  #a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
        try{    /// Creates a new socket at port number and binds it together with the server's IP address   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
            ServerSocket s = new ServerSocket(1234);  //Creates a socket and binds it to port number   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
            while(true){    /// Continuously listens for connections on the server until an interruption occurs such as a closing of your program   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
                Socket incoming = s.accept();  // Accepts client connection and creates an input stream on the socket for reading   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
                DataInputStream dis = new DataInputStream( incoming.getInputStream());  // Accepts client' input stream and creates an outputstream on the socket for writing   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
                DataOutputStream dos = new DataOutputStream( incoming.getOutputStream());  // Accepts client' output stream and creates a buffer   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
                String clientMessage = dis.readUTF();    /// Waits for the message from sender in string format and reads it   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
                System.out.println(clientMessage);    /// Prints out client' message for validation  #b This is just an illustrative demonstration of security-sensitive operations related to injection attacks   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
                dos.writeUTF(clientMessage);    /// Sends the client' message back in string format and writes it to sender   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
                dos.flush();  // Flushes data output stream for buffered write operations    #b This is just an illustrative demonstration of security-sensitive operations related to injection attacks   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
                incoming.close();  // Closes the socket and frees up resources    #b This is just an illustrative demonstration of security-sensitive operations related to injection attacks   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
            } // Ends while loop until interruption occurs  #b This is just an illustrative demonstration of security-sensitive operations related to injection attacks   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
        }catch(IOException e){    /// Exception handling for IOException if it occurs during server's setup  #b This is just an illustrative demonstration of security-sensitive operations related to injection attacks   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
            e.printStackTrace();  // Prints out stack trace for error handling when IOException occurs during server's setup   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
        }// End of catch block to handle exceptions  #b This is just an illustrative demonstration of security-sensitive operations related to injection attacks   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
    }// Ends main method  #b This is just an illustrative demonstration of security-sensitive operations related to injection attacks   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs
}// Ends SocketServer class  #b This is just an illustrative demonstration of security-sensitive operations related to injection attacks   c#a06_injection Vulnerability Example (c) Amitay Cseredim, MIT License - www.mit.edu/~amitaycs