import java.io.*;
import java.net.*;
  
public class java_52009_SocketServer_A03 { 
    public static void main(String[] args) throws Exception{    
        ServerSocket server = null;         // create a socket for the server to accept connections from clients     
       try {         
            int port = 12345 ;// Define your own or use an available one (80, 90... etc are busy ports). You can also read it as command line parameter.  
              if(port == Integer.parseInt((args[0]))){ throw new Exception("You cannot run this program with the same port twice");}    // check for invalid or duplicate inputs        ServerSocket server = null;         int port = 12345 ;// Define your own Port          try {            
            System.out.println( "Starting Socket Program on :" + Integer.toString(port));  String message, responseMessage , lineHeader= new java.lang.String("HEADER");     // Initialize a server socket      ServerSocket server = null;         int port = 12345 ;// Define your own Port         
            try {             System.out.println ("Initiating Socket Program on " + Integer.toString (port));  if ((server= new ServerSocket(Integer.parseInt((args[0]))))==null){ throw     Exception("Could not instantiate a server socket");} else{                 // Start listening for client connections                    while (! Thread.currentThread().isInterrupted() ) {                     Socket incoming = null;
            System.out .println ("Waiting For Connection ..... ");         try  {             InetAddress IPaddress=InetAddress.getByName("127.0.0.");     // Accept call from a client                  while (! Thread.currentThread().isInterrupted() ){                     Socket incoming = server .accept();
            System.outprintln ("Connection Established ..... ");             BufferedReader in  = new Buffered Reader(new InputStreamreader (incoming.getInputStream()));     // Create input stream reader           while ((lineHeader=In.readLine()) !=  null) {                     responseMessage = lineheader + " Server Received: ";
            System . outprint ("Server Response :"+responseMesage);         OutPrintWriter(outgoing, (byte[] )message );                  } catch  Exception e     {}              // Handling all exceptions here                finally{             if ((incoming !=null) &&    (! incoming.isClosed())) {
            System . outprintln("Client Disconnected :"+ Integer Tostring((int(   backlog))));}}                 server_.close(); }  catch (IOException e1){e2..printStackTrace()}          // end try and close the socket finally{             if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server!=null) && (!服务器.isClosed())) {
            System . outprintln("Server Disconnected :"+ Integer Tostring((int(   backlog))));}} catch (IOException e){e2..printStackTrace()} } // End of main method  finally{         if ((server==null) && (!服务器.isClosed())) {
            System . outprintln("Server is closed"); }}', 'None')
,('{"code":103,"message":"Internal Error","data":[]}' ,'Error - Internal Server Exception: {"code": 103, "message" : "Internal error occurred."}')),
(('{'id':9,'name':'Maria','age':25}, 'Added new person Maria with id=9 and name MAria.', '', (''))),(("[8]", "[{}]") ,'(Error - Internal Server Exception: {"code": 103, "message" : "Internal error occurred."}')))
;