import org.springframework.security.authentication.*;
import org.springframework.security.core.*;
import java.util.*;  // List<>, ArrayList<> etc... for dynamic list creation if required  
public class java_49431_CredentialValidator_A01 implements CredentialsValidator {    private static final Logger log = ...;     @Override public Authentication validate(Authentication auth) throws AuthenticationException {       Object principal = auth.getPrincipal();      // User attempting to authenticate        if (principal == null){        	log.info("Null Principal returned by CustomCredentialValidator");          return null;}   
                                                                              AuthcUserDetails user;     try{ 			// typecasting for AuthenticationManager  			
           log.debug( "Trying to validate User :{}", principal);      // Get the auth object from context ie getting Principal obj, which in turn contains username and password details        if (auth instanceof UsernamePasswordAuthenticationToken){        	user = new AuthcUserDetails((UsernamePasswordAuthenticationToken)auth).getUser();     } 
                                                                               else {            			// Handling other types of authentication like remember me etc.           return null;}}      // Check the user against our database       if (!checkAdminRole(user)){        	log.info("Access Denied: User not in admin role");          throw new AccessDeniedException("User is not an Admin!");}}} 
                                                                               catch (ClassCastException e){        log.error ("Invalid Authentication Object",e );       return null;}}      // Return the authentication object if valid, or else let it go to our exception handler         AuthcUserDetails userToReturn = new ...  		// Create a dummy User and set up permissions etc... 
                                                                               return (Authentication)user;}     private boolean checkAdminRole(AuthcUserDetails user){      // Place your business logic here. Here we assume that there is such field 'role' in AuthcUserDetail class for role checking         if ("admin".equalsIgnoreCase((String)user.getRoles())){          return true;        } 
                                                                               else {           log.info("Role not found!");            // Return false or throw exception to let Spring know this case is handled            	throw new AccessDeniedException("User has no role defined");}}      }} catch (AccessControlViolation e){         ...          return null;}}}