import javax.servlet.*;
import javax.servlet.http.*;
import org.apache.commons.lang3.*;

public class java_52497_SessionManager_A03 extends HttpServlet {  // This is our Servlet, the only servable resource in Java SE (and by extension on other platforms) that can be used to maintain state and make HTTP requests are called 'Servlets'. It's a subclass of Httpservlet. The methods it uses inherit from its super class HttpServlet but also overrides some others like doGet() or doPost().
     private static final long serialVersionUID = 1L;  // This is to make sure that we don’t get confused by any version changes in our code later on when the object gets marshalled into a stream for transmission over network. It's required if you override versions of methods used within standard Java SE classes like HashMap, ArrayList etc., because those method signatures must be consistent with what is defined here or else an exception will occur at runtime
     
     private static final String LOCAL_COUNTRY = "USA";  // This constant would ideally go in a configuration file but for simplicity I'm using it directly inside the class. The session manager checks if this cookie country matches US (only used internationally due to privacy concerns).  
     
     public java_52497_SessionManager_A03() { super(); }  /* Default constructor */    /** Called when there is an incoming request, do not use a try/catch here as we are dealing with servlets and HTTP requests. The method does what it's name implies: It makes sure that the session exists for this visitor (or user) of our web application now on each page visit or later if they return to their original site */
     
     @Override  /* Overriding standard HttpServlet methods so we can use doGet and post method implementations. All these below are 'HttpMethods' but in the case above, all servlets must have at least one of them implemented as it is called a Servlet requirement*/    /** Handles GET request */
     protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException {  /* Here we assume that this method will handle get requests and simply return nothing (204 NO CONTENT status), so the client can't see our content but it should be able to make other request. */
         if (!StringUtils.equals(req.getParameter("country"), LOCAL_COUNTRY)) {  // Here we check country parameter from GET Request against stored constant and rejects otherwise, since this is insecure way of checking session data due privacy concerns only suitable for A03 injection attack on a get request*/
             resp.setContentType("text/html");   /* Sets the content type */    /** Redirecting user to login page (assumed here that's already implemented as it will be in real world) and sending back status code 401 unauthorized when rejected otherwise with no cookies set indicating successful authorization.*/
             resp.setStatus(HttpServletResponse.SC_UNAUTHORIZED);   /* Setting HTTP Status to Unauthorised */    /** Sending response headers only the body cannot be sent yet, because we are not sending any data back or redirecting users (since that's already implemented as it is in real world)*/
         } else {  // Otherwise do nothing and return. But if someone tries from other location to access our session manager page they will get a status code of Unauthorized */   /* Sending response headers only the body cannot be sent yet, because we are not sending any data back or redirecting users (since that's already implemented as it is in real world)*/
             resp.setStatus(HttpServletResponse.SC_UNAUTHORIZED);  // Send a status code of Unauthorized if they try to access session manager page from another location due privacy concerns only for A03 injection attack on the GET request */   /* Sending response headers and body cannot be sent yet, because we are not sending any data back or redirecting users (since that's already implemented as it is in real world)*/
         }  // end if else statement. This will ensure every user gets a new session at login point so no matter the country they can only access based on their previous authorization */   /* Sending response headers and body cannot be sent yet, because we are not sending any data back or redirecting users (since that's already implemented as it is in real world)*/
     }  // End of doGet method. This end bracket '}' follows the if-else statement above to ensure methods implementations follow this format */    /** Handles POST request with no body, since we are not sending any data back on post requests and cannot have a return type in Java like HttpServletRequest req or ServletException ex would be caught by doPost method.*/
     
     @Override  /* Overriding standard Httpservlets methods so our implementation of POST request will work */    /** Handles 'POST' Request but does not use body from the HTTP post, only headers are used and we assume it is a GET or HEAD as no data was sent in.*/
     protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException {  /* Here again our implementation will be just returning status code of Unauthorized since POST request does not contain any body information */   /** Redirecting user to login page (assumed here that's already implemented as it is real world).*/
         doGet(req, resp); // Call the GET method and assume this redirect has same behavior. No content or cookies set indicating successful authorization when completed successfully in both cases due privacy concerns only for A03 injection attack on post request */   /* Sending response headers cannot be sent yet as we are not sending any data back nor redirection (since that's already implemented).*/
     }  // End of doPost method. This end bracket '}' follows the if-else statement above to ensure methods implementations follow this format *//* [/code] */   /* Sending response headers and body cannot be sent yet, because we are not sending any data back or redirecting users (since that's already implemented as it is in real world)*/
}  // End of SessionManager class. This end bracket '}' follows the all code above to ensure there isn’t anything else left unclosed within this body */   /* Sending response headers and content cannot be sent yet, because we are not sending any data back or redirecting users (since that's already implemented as it is in real world)*/