import javax.servlet.*;
import java.io.IOException;
import org.hibernate.SessionFactory;  // Use Hibernate's Session Factory if used with Spring or similar frameworks, otherwise replace this import line and comment out all related code below that uses it (e.g., hiber session) to avoid ambiguity when trying run the program again due a dependency on such external library
import javax.servlet.http.*;  // For HttpServletRequest/Response object in Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import javax.servlet.http.*;  // For HttpServletRequest/Response object in Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import javax.servlet.*;  	//For Request & Response Object 	in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import java.util.*;  			//For List & Set interface in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import javax.servlet.*;  		//For Request & Response Object in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import javax.servlet.*;  		//For Request & Response Object in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import java.util.*;  			//For List & Set interface in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import javax.servlet.*;  		//For Request & Response Object in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import java.util.*;  			//For List & Set interface in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import javax.servlet.*;  		//For Request & Response Object in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import java.util.*;  			//For List & Set interface in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import javax.servlet.*;  		//For Request & Response Object in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import java.util.*;  			//For List & Set interface in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import javax.servlet.*;  		//For Request & Response Object in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries
import java.util.*;  			//For List & Set interface in J2EE Servlets API v3+, if not using Java EE server runtime and servless context environments (like Google Cloud Functions for example) you'll need to replace imports here with the corresponding classes from your environment specific libraries