import java.beans.*;
import javax.xml.parsers.*;
import org.w3c.dom.*;
public class java_52579_XMLParser_A03 {    
    public static void main(String[] args) throws Exception{        
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();            
        factory.setValidating(true);  // Enable validation for security-sensitive operations  
          
        try {               
            DocumentBuilder builder =  factory.newDocumentBuilder();                
            InputSource isource= new StreamSource("samplefilepath");// Use your file path here                      
            
        	XMLReader xmlreader =builder .getXmlReader(isource);  // Create XML reader with input source      
                XmlParser sparser  = builder.newSAXParser(xmlreader );   // New SAX parser using the built-in one above    
              
            MyHandler handler= new MyHandler();          
             
             xmlreader .setContentHandler(handler);    // Set content handlers for parsing 
                sparser.parse("samplefilepath",handler) ;//Parse XML file with SAX parser     
        }catch (ParserConfigurationException pce){            System.out.println ("Failed to parse the configuration" +pce );}          catch(SAXException saxe ){System . out . println  ("An error occurred on line : " +  saxe);   //Handling any errors occur during parsing   
        }                  
    	}               		                   	catch (MalformedURLException e) {           System.out.println("The URL is not valid!" +e );}       catch(IOException ioe){System . out  . println ("There was an error processing your request"+ioe);         //Handling I/O exception       
    }             	           	       		                if(!xmlreader instanceof XmlParser) {           System.out.println("Your instance is not a XML Parser");}                  else{System . out  . println ("XML parsing successful!" );}}      catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e); System   .out.println("An error has occurred while executing this code: " +writer) ;}  }                  println ("End of the program!" );}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                if(!xmlreader instanceof XmlParser ){           System . out.println("Your instance is not a XML Parser");              }}          else {System  .out   . println ("XML parsing successful!");}}     catch (Exception e){             // Catch all other exceptions   
      	           	       		                PrintWriter writer = new PrintWriter(e) ; System. out.println("An error has occurred while executing this code: " +writer );}  }               println ("End of the program!");}}     catch (Exception e){             // Catch all other exceptions