import java.util.*;   // For ArrayList, HashMap etc... you can use these packages as per your requirements   
public class java_51392_SessionManager_A01 extends Exception {      }     //Custom exception for handling Access Control related issues         
class User{            public String username;         public int id;}        //User details  Class.      
  
//SessionManager to store the Session of users, only user with valid access rights can open a session            
public class SecurityManager {                                                   HashMap<String , Integer> map = new HashMap<>();                      void add( String username ){          map.put (username,Integer.MAX_VALUE-UUID.randomUUID().hashCode());         }                          int getAccessLevel(String user){           return  map.getOrDefault(user,-1);             }                                     boolean isValidUserAndRightToOpenSession  
                                   //Check if the given username and access level match with stored data                   try {     User curr_user = usersById.get (username );    int currentAccessLevel= getAccessLevel  ((curr_user).toString());                                      if(currentAccessLevel==accesslevel){          return true;       }else{             throw new CustomizedSecurityException();           }} catch  
                                   //Custom exception for handling Access Control related issues            SecurityManager sm =new    Security Manager ();     User user=newUser("John", 1234567890) ;      try {sm.isValiduserAndRightToOpenSession(username,accessLevel)}catch  
                                    //Custom exception for handling Access Control related issues         System .out。println ("Access Denied");} } catch (Exception e){     Syste    out..println("Error: " + E);}}  public class Main{      static User newUser(String username, int id ) {       return   //new user object//       
                                };                   void main() throws Exception            try                 SecurityManager sm =          (Security Manager)();     Newuser=    //creating a         test               useCasesHere:sm.add("John");  }catch(Exception e){      System .outprintln ("Error : " + E);}}