import java.util.*;  // Import the utilities package for hashing function in next step    import java.security..MessageDigest;   For details on using Message Digests to hash sensitive data, check this link: https://www.baeldung.com/sha-hash-string-function     
import javax.servlet.*;  // Import the servlets package for session management in next step     import java.security..SecureRandom;   For details on using Secure Randoms to generate a secure random number, check this link: https://www.baeldung.com/securerandom-password     
import sun.misc.*;  // Import the utilities package for converting bytes into hexadecimal     import java.math.* ;    BigInteger can be used instead of byte array       We will use it to convert SecureRandom generated random passwords in next step   public class java_52682_CredentialValidator_A01 implements ServletFilter {     
public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException    @Override  // Override the default servlets method for all requests.     HttpServletRequest httpReq = (HttpServletRequest)request;        RequestDispatcher dispatcherToUse ;     
// Check if username and password parameters are set in request          String userName=httpReq .getParameter("username");              System.out.println(userName);         // Hash the entered credentials using MessageDigest from javax package     byte[] hashedPassword = getMD5Hash(password, 1024 );            
System. out . println (Arrays . toString (hashedPassword));          String password=httpReq .getParameter("pwd");              // Hash the entered credentials using MessageDigest from javax package     byte[] hashedUserInput = getMD5Hash(userName, 1024 );            
System. out . println (Arrays . toString (hashedUserInput));          if ((Objects . equals (password , Arrays . dump ("8c697ab4f23404da".getBytes()))) { dispatcherToUse = request 
                                    . getRequestDispatcher("/success.html");       // If credentials are correct, show a success page              try{         if((Objects . equals (hashedUserInput , Arrays . dump ("8c697ab4f23404da".getBytes()))) { dispatcherToUse = 
                                    request …..//here we can use any response object or forward to another servlet.          } else{         // Else show an error message, this is also a redirection        RequestDispatcher dispatcher =    ...   (assuming that you have defined the same)       try {dispatcher .forward(request ,response);} catch 
                                    (ServletException e){e.printStackTrace(); }     if (!Objects .. equals ((password ), Arrays.. dump ("8c697ab4f23404da".getBytes())))    // If password is incorrect, show an error message again          RequestDispatcher dispatcher = request …//here we can use any response object or forward to another servlet.    
                                    try {dispatcher .forward(request ,response);} catch (ServletException e){e.printStackTrace(); }    if ((Objects.. equals((password), Arrays .. dump("8c697ab4f23404da".getBytes())))){         // If password is correct, redirect to success page          RequestDispatcher dispatcher = request . getRequestDispatcher("/success.html");    
                                        try {dispatcher . forward(request ,response);} catch (ServletException e){e.printStackTrace(); }  else{ Response. sendRedirect("failure.html")};   // if the above conditions are not met, then redirect to failure page      return;}