Script 
const crypto = require('crypto'); // Node standard library for hashing passwords, etc... in secure way. But we'll keep it simple as per the problem statement only to show how CredentialValidator interface can be implemented with JavaScript (without Spring or Hibernate). Use this at your own risk!
const fs = require('fs'); // To read files from disk - will not use if you want a secure way of reading passwords. But we'll keep it simple as per the problem statement only to show how CredentialValidator interface can be implemented with JavaScript (without Spring or Hibernate). Use this at your own risk!
  
class java_52835_CredentialValidator_A07 {  // We name our class based on domain context, but in a real-world scenario we might use an Interface here too. But for simplicity I'll stick to classes and interfaces as they are the most common way of handling such requirements with Spring/Hibernate frameworks).
    constructor(username) {  
        this._userName = username;  // storing plain text user name because in real world scenario we should not store passwords. But for simplicity I'm keeping it simple here and will keep as is on a case-by-case basis while working with Spring/Hibernate frameworks). In such cases, you would use actual secure methods to handle this data 
    }   // end of constructor(). Note that the 'constructor() {}'. This line can be commented out. We'll explain in next step how we could implement it properly - as per requirement.) */    
      
        validate(password) {      /* Method for validating password, will return a Promise<boolean> which is then used to get result of the operation (resolving/rejecting). In real world scenario you would use actual secure methods here. But I'll keep it simple and show how CredentialValidator interface can be implemented with JavaScript as per requirement.)
            // We add some salt for password hashing - more on this later – but we will not have a 'salt', instead, the plain text version of username is used to hash. This would differ between users so that each user gets unique encrypted data (password).*/  
           const result = crypto.pbkdf2Sync(this._userName + password , this._userName  /* salt */,1000,(crypto.getKeySize('sha512'))/8); // Uses pbkdf to hash the user's name and a provided plain text version of itself (the secret key).
             return result;    ///* Use this for comparison - it will be different every time due its use as an input. */  /* In real world, you would compare actual hashed password with one that was previously saved on disk or in database when user logs-in and then store the hash back to a db (or file) so next logins can check against this*/
        }   // end of validate(). Note That 'validate()' function should be async because we need data from external source for validation. But I will keep it simple with Promise here only as per requirement.) */  /* Here, We are using the pbkdf2 algorithm which is a secure way to hash passwords and its hashing method can vary between different implementations of this functionality (in crypto library).*/
    }   // end of SecureCredentialsValidation class. Note that 'class' keyword should be at start or after constructor() function depending on use case - we could also add methods here as per requirement.) */  /* We are using the pbkdf2 algorithm which is a secure way to hash passwords and its hashing method can vary between different implementations of this functionality (in crypto library).*/
    }   // end SecureCredentialsValidation class. Note that 'class' keyword should be at start or after constructor() function depending on use case - we could also add methods here as per requirement.) */  /* We are using the pbkdf2 algorithm which is a secure way to hash passwords and its hashing method can vary between different implementations of this functionality (in crypto library).*/