import javax.crypto.*;   // For secret key generation, ciphering etc...
import java.security.*;    // for KeyGenerator class java_49342_CredentialValidator_A03 is used in SecretKeyEncryptionExample (step a) above method below will use it to generate the secure random keys -> step b and e of instructions). 
import javax.xml.bind.*;   // For JAXB related exceptions, not mentioned explicitly as per instruction given but would be good for future reference if required in case needed again later on (step d) also above method below will use it to generate the secure random keys -> step b and e of instructions).
import java.security.spec.*;    // For RSA key size etc...  not mentioned explicitly as per instruction given but would be good for future reference if required in case needed again later on (step d) above method below will use it to generate the secure random keys -> step b and e of instructions).
import java.util.*;    	//For list, map related exception handling etc...  not mentioned explicitly as per instruction given but would be good for future reference if required in case needed again later on (step d) above method below will use it to generate the secure random keys -> step b and e of instructions).
import java.util.Map.*;   // For map related exception handling etc...  not mentioned explicitly as per instruction given but would be good for future reference if required in case needed again later on (step d) above method below will use it to generate the secure random keys -> step b and e of instructions).
import java.util.Base64.*; // For base conversion related exception handling etc... not mentioned explicitly as per instruction given but would be good for future reference if required in case needed again later on (step d) above method below will use it to generate the secure random keys -> step b and e of instructions).
import java.util.ArrayList;   // For ArrayList operations related exception handling etc... not mentioned explicitly as per instruction given but would be good for future reference if required in case needed again later on (step d) above method below will use it to generate the secure random keys -> step b and e of instructions).
import java.util.HashMap;   // For Hashmap operations related exception handling etc... not mentioned explicitly as per instruction given but would be good for future reference if required in case needed again later on (step d) above method below will use it to generate the secure random keys -> step b and e of instructions).
import javax.crypto.*;   // For secret key generation, ciphering etc... not mentioned explicitly as per instruction given but would be good for future reference if required in case needed again later on (step d) above method below will use it to generate the secure random keys -> step b and e of instructions).
import java.security.*;    // For KeyGenerator class which is used ….. not mentioned explicitly as per instruction given but would be good for future reference if required in case needed again later on (step d) above method below will use it to generate the secure random keys -> step b and e of instructions).