)    
import java.io.*;   // Import the Java built-in classes for File I/O operations like 'fileReader' and Buffered Reader from Input Streams class java_52737_FileScanner_A03 file handling tasks such as reading a text or binary stream of data through an inputstream object . The direct use to external libraries will not be allowed here due this task is strictly academic.
  public static void main(String[] args) {   // Main method for the program starts execution and runs until completion, similar like in 'void' function which are non-static methods of classes by default (In Java). The parameter passed to these functions ('args') may be used later according to your requirements.
    File file = new File("C:\\Users");   // Creating a object for the class java.io.File that represents an abstract pathname, and it can refer either files or directories based on provided string representation (here - "user").  'file' is variable of type FILE which in Java holds information about file/directory .
    File[] listOfFiles = null;   // Declare a array to hold the result from directory operation. The method dir() returns an Array containing all files and directories names under this directory (or below). It doesn’t necessarily contain any actual data - it's just name of these items or "null".
    try {  /* This is for exception handling */   // Begin block to handle the execution if there are exceptions. Java has Exception Handling mechanism in its language, which allows us not only do certain operations but also catch and deal with unexpected events during program’s normal flow (like 'try-catch' blocks).
      listOfFiles = file.listFiles();    // Call method dir() to get a File object array that represents all files under this directory: C:\Users, i.e., names of directories in the "C:/users" path location and .txt or other types(files) inside it (if any).
      for (int i = 0; i < listOfFiles.length ;i++ ) {    // For loop to print out all filenames along with their paths “list of files” array will hold the names only not full pathnames . It's an easy way we can handle file operations in Java
        System.out.println( "File Name :->" + listOfFiles[i].getName() );   // Print out filename and related operation is performed here due to 'console print'. ‘System’, by default already has a method called consolePrint that prints data on the command line interface (Console).
      }    /* End for loop */     System.out.println("End of File List");       try{/* Closing I/O operations and handling exceptions*/FileInputStream fileIn = new FileInputStream(file);  // Open a connection to run below program, Java IO - streams that read from or write into an external device such as disk files etc., can be created by using InputStreams class.
      /* Close operation */} catch (Exception e) {/* Catch and handle exceptions*/ System.out.println("Error : " +e); } // Print out any error messages if exception occurs, which is handled in try-catch block ‘try’ section above for simplicity purpose here we are only catching general Exception type 'exception' to cover all types of scenarios (if you want this part too).
    /* End the main method */}}   ;) This should be your program exit point. The closing bracket is a semicolon and it indicates end of Java code block, which can prevent compile-time errors or unexpected results due its asynchronous nature in language processing tasks such reading lines from stream etc., ‘;’ operator for this purpose if not included at the start otherwise compiler will throw syntax error. The full line ';}', also includes closing bracket and end of java statement to form complete block, which is mandatory here too because it's how Java works in language processing tasks like reading lines from stream etc., ‘;’ operator for this purpose if not included at the start otherwise compiler will throw syntax error.