import java.io.*; // for InputStream, OutputStream classes & FileReader class java_43063_FileScanner_A01 here in place of Scanner due to autocloseables requirement below which makes Java's scanners useless now and we cannot use them anymore 

public class BrokenAccessControl {  
    public static void main(String[] args) throws IOException // We want exception handling, so IO Exceptions should be handled here. No need for the scanner right away as it is broken in this context to avoid security breaches and not recommended now but included below 
    {        
        File file = new File("C:\\Users\\User_Name\\Documents\\fileToReadFrom"); // Provide your own path of interest here. Here, you want a sensitive operation related the access control ie., reading from an external location where it should not be possible anymore because we have broken inaccessible permissions
        
        if (file.exists()) { 
            System.out.println("File exists at: " + file.getAbsolutePath()); // Prints absolute path of the created/readable files to demonstrate security-related operation ie., reading a sensitive location by displaying its relative or complete accessible paths in this case it is not possible now but still done here
            
            try (InputStream input = new FileInputStream(file)) {  /* Provided that your program does break the file's read permission, you should be able to uncomment and run below lines */
                int data; // a byte-based channel for reading. It reads one bit of an integer at time from InputStream in blocking mode ie., it waits until some bytes are ready 
            
               while ((data = input.read()) != -1) {   /* While loop that continues till the end */    // Reading all data and storing into 'char' variable for processing, if no byte is available then returns '-1'. This line can be removed once we have checked whether file has been accessed successfully or not 
            	System.out.print((char)data);   /* Prints each character read from the input stream */ // Demonstrating security-related operation ie., printing out a sensitive location's content for demonstration purposes but should be handled in an appropriate way now such as using BufferedReader or similar buffering mechanism
            	} 	   	    			   		   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between
            } 	   	    			   		   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between
            	    			   		 	   				   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between
        } 	   	    			   		   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between
            	    			   		 	   				   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between
        } 	   	    			   		   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between
    } 	   	    			   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between
    } 	   	    			   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between
    } 	   	    			   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between
} 	   	    			   /* Closing resources is not done here which can cause resource leaks if it would close before reading all the data */ // It will come when we exit 'while' loop, automatically handled by Java garbage collector at that time. For instance: file input stream reads more than you expect and closes in between