import java.sql.*;   // Import necessary classes here   
    
public class java_47986_JDBCQueryHandler_A08 {     
       private static final String url = "jdbc:mysql://localhost/test";        public Connection conn;                   try{             this.conn=DriverManager.getConnection(url,"user","password");                  Statement stmt  = conn.createStatement();  // create a statement object            ResultSet rs    = null;}catch (Exception e){e.printStackTrace()}
    }   /* End of JDBCQueryHandler class */     void mainMenu(){         try {             String selectSQL = "SELECT USER_ID,USERNAME FROM MYUSERS WHERE STATUS='Active';";        PreparedStatement pstmt  = conn.prepareStatement(selectSQL);              ResultSet rs    = pstmt.executeQuery();  // execute the statement and get result set            while (rs !=  null){                  System.out.println("USER ID: " + rs.getString('user_id') );                  
                    System.out.print (" USERNAME :"+ rs.getString ('username'));                     } catch(SQLException e) {System.out.println("\n Error in handling MySQL Database operations.");              e.printStackTrace();}  // error checking     if (conn != null && conn.isClosed())        try{        
                    String dropTable = "DROP TABLE MYUSERS";          PreparedStatement pstmt  = conn.prepareStatement(dropTable);                  ResultSet rs    = pstmt.executeQuery();              }catch  Exception e {System.out.println("\n Error in handling MySQL Database operations.");   // error checking     if (conn != null && (!conn.isClosed()))        try{        
                    String createUser = "INSERT INTO MYUSERS(USERNAME,STATUS) VALUES('John', 'Active')";          PreparedStatement pstmt  = conn.prepareStatement 
                     stmt .executeQuery();              }catch (Exception e){System.out.println("\n Error in handling MySQL Database operations.");           // error checking     if (!conn.isClosed() )        try{         String updateUser = "UPDATE MYUSERS SET STATUS='Inactive' WHERE USERNAME =  'John';";          PreparedStatement pstmt  = conn
                     .prepareStatement(updateStudent);            ResultSet rs    = stmt  .executeQuery();           }catch (Exception e){System.out.println("\n Error in handling MySQL Database operations.");   // error checking      if (!conn != null)        try{         String deleteUser = "DELETE FROM MYUSERS WHERE USERNAME =  'John'";          PreparedStatement pstmt  = conn 
                     .prepareStatement(deleteStudent);            ResultSet rs    = stmt.executeQuery();              }catch (Exception e){System.out.println("\n Error in handling MySQL Database operations.");   // error checking     if (!conn != null)        try{         String selectUser = "SELECT USERNAME,STATUS FROM MYUSERS WHERE STATUS =  'Active'";          PreparedStatement pstmt  = conn 
                     .prepareStatement(selectStudent);            ResultSet rs    = stmt.executeQuery();              }catch (Exception e){System.out.println("\n Error in handling MySQL Database operations.");   // error checking     if (!conn != null)        try{         String insertUser = "INSERT INTO MYUSERS(USERNAME,STATUS)" +
                     values('John', 'Active');          PreparedStatement pstmt  = conn .prepareStatement  stmt.executeQuery();              }catch (Exception e){System.out.println("\n Error in handling MySQL Database operations.");   // error checking    End of the code snippet for JDBC interaction