import java.util.*;   // Importing the necessary classes for this program: Scanner, ArrayList...etc
public class java_51410_CredentialValidator_A03 {    // Defining our main class which will contain all of your code below    
      public static void main(String[] args) throws Exception  {}       private String username;          private char [] password;  
        List<Character> digits = Arrays.asList('0', '1','2' ,'3' ,'4','5''6'',..., ''9'); ArrayList < Character >special_characters =  new ArrayList  < Character >(Arrays . asList ( '# ',  %   '', ... ));
       private Set<Character> invalidChars = new HashSet<>(); // A set for storing the characters that can't be in a password. In this case, they are digits or special_characters    public java_51410_CredentialValidator_A03() { System . out . println ( "Please enter your username: ");   Scanner input  =new 
        Scanner(System.in);username =input.nextLine();password= new char[50];int i = 0; boolean validPassword=  false ;String passwordChecker="";    while (!validPassword) { System . out . println ( "Please enter your Password: "); 
        String input_password  =  input. nextLine();     for(char c :input_password.toCharArray()){if(!digits.contains(c ) && !special_characters. contains(c)&& i<50 /* Assuming the password length is maximum of 8 characters long */
        ){   //check if a character in input passowrd can be added to Password array, otherwise exit from loop and print error message      }else { System . out .println ( "Invalid Input. Please enter valid credentials again."); return;}i++;password[i]=c ;validPassword=  true
        /* Checking if password contains at least one digit & special character */}if(username == null || username.length()==0){  //check for empty string and print error message      }else {System . out .println ("Username is valid");}} else{ System .out .print("Invalid Username entered, please enter a correct user name: ");
        CredentialValidator ();}   private void validatePassword(char [] password) throws Exception  {} // Method to check the validity of Password. This method does not use any standard library methods and is completely self-contained in this program     public static boolean validUsernameAndpassword() {return false;}}