import java.io.*; // Importing required classes from standard library  
// For handling files, buffers etc., File class java_51373_FileScanner_A03 methods to interact with them ie read/write operations on file streams are supported by this superclass (InputStreamReader extends Reader). Thus we don't need import for InputStream or Outputstream which is part of the reader and writer classes. 
import java.nio.*; // Importing required NIO libraries, including FileSystems etc., to interact with files efficiently on file system level ie it only works in a directory tree where each node (file/directory) has an identifier known as path name which is equivalent of the URI scheme or URL syntax 
// We can't use JavaFX for this purpose. Hence, we cannot import javafx.* libraries to read and write files on file system level with them provided by standard library classes like InputStreamReader etc., but it will be helpful if you are using external frameworks/libraries which provide APIs similar or more efficient than built-in Java IO functionalities in the language.
// Also, this code does not involve any network operations as a part of File I/O operation only works on local file system level and hence there's no need to import java.* classes (like Multipart etc.) which are required for networking related tasks such as reading or writing from URLS in the question.
  
public class Example {  // Defining Class name here because of Java naming conventions, you could also define a method within your current task/class like so: public void myMethod(){ ... } however this would violate 'd' above (syntactically correct code) and it might cause issues in the future when importing classes.
   // Below is an example of FileScanner which reads files from directory, prints their contents on console or writes to a file using PrintWriter – all these operations are performed safely with standard Java libraries only due To avoid any external dependencies for security purposes I have done no use/imports related frameworks like Spring etc.
   public static void main(String[] args) throws IOException { // Defining the method parameter type and name, also defining it as a Main class which is equivalent to 'public static' in Java if we want our program start point of an application then this should be there otherwise not mandatory but recommended for making sure your source file can run without any errors.
       File dir = new File("C:\\Users\\Your_Directory"); // Specifying the directory from where files are to read, replace 'You'r Directory\" with path in Windows OS and also change it accordingly on different platforms – you might need a trailing slash / if not included as per your platform.
       for (File file : dir.listFiles()) {    // For each File inside the directory:   - list() method from java util which provides an array of all files in specified folder and subfolders to iterate over, this is more efficient than using recursion or looping through individual nodes on a tree-like data structure
           if (file.isFile()) {  // If it's not directory ie file then process the current File:   - getAbsolutePath(), which gives you full path to that specific location, same as with dir but for files only works because they are individual entries in a tree-like data structure
               System.out.println("Reading contents of " +file);  // Prints name and size at the end if we know exact file’ s names - better way is via using File class to print it or use getName() which gives you just filename only, same as with dir but for files in specific directory
               BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(file)));  // Reading the contents from file and storing them into a bufferreader (Buffering Reader) - this is faster than reading whole content at once like using "FileReader" or similar classes which are part of java.io package
               String line = null;   // Defining variable type, also name it as 'line' for better understanding – we will use readLine() method to get each line from reader and if there is no data left in the file then this returns "null" ie eof reached - done using while loop or similar constructs which iterate over all lines (from beginning till end).
               // For handling 'line' variable as required by your task we can use below code, but it will not be syntactically correct due to lack of types and methods like "readLine()" in java.io package without any import or type definition - this is a limitation here because FileReader (and related classes) are part of the standard Java IO library which does all required operations safely with security considerations such as preventing injection attacks on your code while you should use their counterparts to read from file like Buffered Reader, etc. 
               // Also if we do not need these features and only want a simple text printing then it is also fine but here for the sake of simplicity in this example i have kept same type definition as per task requirement. If needed more help with any other classes or methods you can always ask! I hope so, good luck on your coding challenge