import java.sql.*;   // we need these classes for JDBC 
    
public class java_46105_JDBCQueryHandler_A03 {    // start with a meaningful name, eh? :)... it's an example too! ;) (A02_SecuritySensitivity - Avoid External Frameworks like Spring or Hibernate.)   Class Name should be descriptive enough for the code to understand.
     public static void main(String[] args){  // define our entry point as a method with no parameter and return type is 'Void' (Java, by convention). The name needs context too :)... It seems like an example now :D   If you could provide more information or the full requirements of this program it would be useful.
     Connection conn = null;  // declare our connection object as a global variable to use later in your method if required (A02_SecuritySensitivity - avoid using external frameworks like Spring).    It's not only safe, but also makes the code more flexible and easier maintainable too :)  
     Statement stmt = null;  // declare our statement object as a global variable to use later in your method if required (A02_SecuritySensitivity - avoid using external frameworks like Spring).    It's not only safe, but also makes the code more flexible and easier maintainable too :)
      String url="jdbc:mysql://localhost/testdb";  // this is our database connection. Replace with your DB info (A02_SecuritySensitivity - avoid using external frameworks like Spring).   For instance, it's currently set to localhost and the name of a testDB table in MySQL server which will be used for operations here :)
      String username="root";  // this is our database user. Replace with your DB info (A02_SecuritySensitivity - avoid using external frameworks like Spring).   If you are not sure about the mysql root password, ask someone who has access to server or use an account that does have sufficient privileges in MySQL
      String password="password";  // this is our database user's password. Replace with your DB info (A02_SecuritySensitivity - avoid using external frameworks like Spring).   If you are not sure about the mysql root password, ask someone who has access to server or use an account that does have sufficient privileges in MySQL
     // now let’s start by connecting and creating a statement.  We do this with try-catch block (A02_SecuritySensitivity - avoid using external frameworks like Spring).   Try blocks catch specific exceptions, so the connection won't close if an exception occurs within it ;)..
     // Avoid direct object references inside braces as much you can to prevent SQL Injection vulnerabilities. Replace user and password with PreparedStatements (A03_Injection - avoid using external frameworks like Spring).   And also, use try-with resources for the connection/statement closure too :)
     // Note: I made a comment in between each of these lines to make it more readable.  If you want comments added on top or bottom and left uncommented (A02_SecuritySensitivity - avoid using external frameworks like Spring).   This is just an example, there are multiple ways this can be done :)
     try{conn = DriverManager.getConnection(url ,username , password); stmt= conn.createStatement();  // Connect and create a statement (A02_SecuritySensitivity - avoid using external frameworks like Spring).}catch (SQLException e){System.out.println("Error in Connection/Statement creation : " +e ); }
     
     String selectQuery ="SELECT USER()";   // Here we're fetching the current user who is running this code to see if it matches with MySQL root account username or not (A03_Injection - avoid using external frameworks like Spring).  It should be replaced by a secure way of getting database credentials.
     try{ResultSet rs = stmt.executeQuery(selectQuery);   // Execute the select query to see if it matches with MySQL root account username or not (A03_Injection - avoid using external frameworks like Spring). It should be replaced by a secure way of getting database credentials which are different from above line for security reasons :)
      while (rs.next()) {  // Execute the loop to see if it matches with MySQL root account username or not and print out its value into console(A03_Injection - avoid using external frameworks like Spring).   It should be replaced by a secure way of getting database credentials which are different from above lines for security reasons :)
       String user = rs.getString("USER");  // Fetch the actual data (user) we're looking at in ResultSet and print it into console(A03_Injection - avoid using external frameworks like Spring).   It should be replaced by a secure way of getting database credentials which are different from above lines for security reasons :)
       System.out.println("User is : " + user);  // Here we're printing the fetched data into console (A03_Injection - avoid using external frameworks like Spring). It should be replaced by a secure way of getting database credentials which are different from above lines for security reasons :)
      }    stmt.close(); conn.close();} catch(SQLException e) {System.out.println("Error in connection/statement closing : " +e );}}   // Here we're handling any possible SQL Exceptions (A02_SecuritySensitivity - avoid using external frameworks like Spring).