import org.springframework.context.annotation.Bean;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.provisioning.InMemoryUserDetailsManager;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.web.SecurityFilterChain;
  
@EnableWebSecurity  // Enable Spring Security's security constraints support (required for HttpBasic, form login & CSRF) on this WebMvcConfig? by default it’s disabled unless your configuration changes require HTTP authentication to be enabled globally as well in a controller or method level. Also if you are using JDBC-based user detail service then remember that InMemoryUserDetailsManager will not work without setting up the database otherwise
public class java_47426_SessionManager_A07 {  // Root Spring Security exception classes are defined here, for example RepositoryAuthenticationFailureHandler and UsernameNotFoundException two interfaces extending RuntimeException. The first one is thrown when an object cannot be found in a repository (like UserDetailService), while another throws if you're trying to access the method on behalf of which doesn’t exist as well).
    
    @Bean  // Spring will autowire Beans by type, and we can also use types for dependency injection. Here is an example: Inject a DAO into our service using setter-based DI via constructor in this case with the role ROLE_ADMIN which should be enough according to your requirement as it's already defined at Spring Security Config
     public BCryptPasswordEncoder passwordEncoder() { return new BCryptPasswordEncoder(); }   //Spring has a built-in dependency, so I don’t need to add any additional libraries and dependencies here.  We use the Password Encoding Bean from spring's standard library which is also capable of encoding user credentials into encrypted strings
     public InMemoryUserDetailsManager userDetailsService() { //Here we are going through a few basic security features: HTTP Basic, Role-based Access Control (RBAC), Form Login & CSRF Protection and an example for custom UserDetailServices.  We will not use the default AuthenticationProvider provided by Spring Security as it's hardcoded to rely on our own implementation of authenticating users
         return new InMemoryUserDetailsManager( //Spring’s in-memory user details manager can be used if you don’t need a database, but for learning purposes and tests purpose we are going with the simple example above.  It stores all usernames/password on memory which means that after Spring context is closed it will clear everything
             User.withUsername("user") //User name: "admin" / password:"{noop}passsword", for role, you can use Role object and add user to a list or any other collection of roles as well (like ROLE_ADMIN)  Spring Security has built-in support/detection on how the authentication should proceed based upon these attributes.
             .password(this.passwordEncoder().encode("passsword")) //Role: "ROLE_USER", a user with username and password, but no role is defined in our case so it's just an example of using roles for authorization on Spring Security 
             .roles("ADMIN")   //Spring has built-in support to check if the current principal (user) holds certain grant authorities. Here we are checking whether there’re any granted authority like ROLE_USER, here it will give us true but in our case where "ROLE_AUTHORITY" is also defined
             .build());  //UserDetailsService and passwordEncoder would be used together when creating UserDetailServices that encapsulate user details plus the ability to encode/decode their security credentials. Here we are using a basic way of storing username+password in memory, similar what's done at InMemoryAuthenticationProvider constructor
         }   
   //This is how you setup your Spring Security for authentication and authorization  as per requirements provided above (HTTP Basic auth + Roles based access control) on top. It won’t work if removed due to constraint of using standard libraries only; it's a legacy style example that demonstrates security-sensitive operations related with specific exception classes A07_AuthFailure
     @Bean  // In Spring Security, the filter chain is made up from various filters (in this case - "spring.servlet api") and chains together to form an execution flow of requests/responses   . The order in which you add your security configurations matters: If it’s not correctly defined at any point during application start-up then Spring Security won't be able find the settings
     public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {  //This method is used for setting up all our filters. For example, here we set that everything needs to go through a specific request matcher (RequestMatchers), and what if something goes wrong? it should return unauthorized access or redirecting user somewhere
         http//basic().authenticationDisabled() //http basic authentication is disabled by default for learning purposes. Spring Security has its own way of doing this via HTTP Basic auth – just enable the method in your configuration, you can also use annotation @EnableGlobalAuthentication if want to add more customizations like form login
             .and()//csrf().disable(); //CSRF protection is disabled by default for learning purposes. Spring Security has its own way of doing this via CSRF – just enable the method in your configuration, you can also use annotation @EnableGlobalMethodSecurity if want to add more customizations like RBAC
             .and()//remember().key("uniqueAndSecret").secure(true).tokenValiditySeconds(180) //Spring Security’s remember me authentication is enabled here. It uses a key and the user details will be stored in memory for 6 hours (or whatever value you have set), this means that after Spring context has closed, all data saved from before would get cleared
             .and()//session().disable(); //Spring Security’s session management feature is disabled here. It prevents any active sessions to remain open between requests so the user will need a new login every time they access our site – this means that if you want it enabled, just enable and comment out or remove all lines related with remember
             .and()//logout().permitAll(); //Spring Security has built-in support for logouts. Here we are making everything permit to everyone (all users) so in our case can be disabled via httpSecurity configurations above too but then it would not allow any form of logging out which is against the requirement
             .and()//authorizeRequests().antMatchers("/admin/**").hasRole("ADMIN") //This checks if current request has "/admin" and user role contains "ROLE_AUTHORITY". This means that only users with ROLE_USER (which will be defined in our case as ADMIN) can access the /users area.
             .and()//authorizeRequests().anyRequest().authenticated(); //By default Spring Security has built-in support for form login and CSRF protection so we only need to provide authorization configurations above too but then it would not allow any unauthorized user access in our case, this is against the requirement
             .and()//httpBasic();  In a real world scenario you'd want either Basic Authentication (if enabled by default) or Forms based authentication. Here we are disabling form login and CSRF protection because it’ll be too complex to setup otherwise in most cases, even using the built-in support
             .and().csrf().disable(); //CSRF is disabled at this point due to learning purpose as Spring Security has its own way of doing authentications via forms based authentication (Csrf and CSRF protection) – just enable/comment or remove lines related with httpBasic above if you want it enabled
             .and()//remember().key("uniqueAndSecret").secure(true).tokenValiditySeconds(180); //Spring Security’s remember me authentication is disabled here. It uses a key and the user details will be stored in memory for 6 hours (or whatever value you have set)
             .and()//session().disable();	//In case of not setting session management to false Spring security would still maintain an active state between requests so users can’t login again after logging out. It means if want it enabled, disable all lines related with remember and enable httpBasic as described above – this allows the user logout only via HTTP Basic authentication
             .and().csrf().disable(); //CSRF is disabled at last due to learning purpose because Spring Security has its own way of doing authentications by forms based login (Csrf protection) -- just disable if not needed or comment out above lines related with remember and httpBasic – this allows the user logout only via HTTP Basic authentication
             .build(); // This will provide all necessary configurations for setting up a security filter chain in Spring Security. Here we are providing everything that is required to setup our configuration which checks, validates users based on given rules (like authorization) and hashes passwords securely as per requirements above – this allows it work legically
     }    //End of method with all the configurations about http security in Spring Security for authentication/authorisation purpose. It is a simple example to demonstrate how you can handle such scenarios using only standard libraries (no external frameworks). This program will not create any database, and user's password won’t be stored securely as per requirements above – it should work under constraints of learning purposes
    }   //End Spring Security Configuration Class. The @Bean methods are used for setting up our beans in the context (Spring IoC container) so that they can provide access to necessary dependencies from anywhere within this class and any classes annotated with these bean definitions using dependency injection facilities provided by a Java-based application server like Apache Tomcat or embedded Jetty.