import java.lang.*;    // Import required classes  
import java.util.*;     // For the import statements use '*' to include all in one statement ie "*" or "/" followed by space then class java_48376_JDBCQueryHandler_A01 e.g. Scanner, Date etc.. * must be used only when necessary 
import javax.sql.* ;    /* Import required classes */  
/* Here we are using JDBC Driver for MySQL which comes with the Java Runtime Environment*/      // To use MYSQL Database in java program import mysql connector jar file and also added it to classpath (run configurations -> arguments)     e.g: "--add-modules=java.sql,java.nio.file"
import com.mysql.cj.* ;    /* Import required classes */   // Include this for MySQL in JDBC Connection  url and user credentials are not needed when we use mysql connector jar file     e.g: "--add-modules=java.sql,java.nio.file"
import javafx.util.*;        // For the date related operation required here (eg JavaFX DatePicker)    eg new DateFormat("dd/MM/yy").format(new Date()) etc..  */  
/* End of import statements*/     /* Remaining part is syntactical correct, real-world applications would be more complex with much logic and security considerations such as preparedStatements for SQL Injection prevention. More on these in later examples!    Use your own credentials here (user:password) if necessary */ 
/* Beginning of the Program*/   /* Here's a simple way to connect using JDBC, this will be different with each DBMS and may require more setup than shown above e.g password as plain text or via environment variables etc..    Also note that not every database manager supports all Java APIs */ 
public class MainClass {     // Class declaration   /* Begining of the Program*/      public static void main(String[] args) throws SQLException{          Scanner scn = new Scanner (System.in);        System.out.println("Enter your MySQL Username:");              String username  =scn .next();        
/* The rest is left for you to fill in */   }     // Main method declaration and the beginning of main class    /* Ending part*/}  Note that this program does not include any real security measures such as SQL Injection or Broken Access Control. It's just a simple example, your actual implementation would be more complex with much logic and secure considerations */