import javafx.application.Application;   // Import the Application class java_50600_CredentialValidator_A07 JavaFX and other related classes   
//Import required packages     ## Include your standard libraries only here (e.g., import javax.*, etc.) 
public abstract class CredentialValidator extends Validator<UsernamePasswordAuth> {       //Create a validator for Usernames/Passwords  
private static final String PASSWORD_PATTERN =  "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,}$";  /* Regex pattern to match password */    //Pattern for matching the strong Password  
private static final String USERNAME_PATTERN = "^(?=.{1,64}@)[a-z0-9.-]{1,63}@[a-z0-9-]{1,63}$";     //Pattern for matching the user name  
    @Override  public String validate (UsernamePasswordAuth usernamepasswordauth) {         /* Function to check password and return error message */     
        if (!usernamepasswordauth.getUserName().matches(USERNAME_PATTERN))             // Checking Usernames match a pattern     If not then it returns an Error Message  
            return "Invalid user name";                                                                       ## Avoid using external frameworks, use only standard Java libraries  and security-related operations related to UserFailure (A01) */                                           /* Regex for matching username format according the rules defined by industry standards*/      }    if (!usernamepasswordauth.getPassword().matches(PASSWORD_PATTERN))   // Checking password match a pattern     If not then it returns an Error Message 
            return "Invalid Password";                                                                           ## Avoid using external frameworks, use only standard Java libraries and security-related operations related to AuthFailure (A07) */                                              /* Regex for matching the strong password according industry standards*/          }      if (!usernamepasswordauth.getPassword().equals(usernamepasswordauth.getConfirm_pass())) // Checking Confirmed Password is equal with entered one     If not then it returns an Error Message 
            return "Passwords don't match";                                                                       /* Avoid using external frameworks, use only standard Java libraries and security-related operations related to UserFailure (A01) */                               }      // Returning success if all checks are passed    else {return null;}   }}                  end of class CredentialValidator