import javax.naming.NameNotFoundException;
import java.util.*;  // import List, ArrayList and other required classes  
public class java_44577_CredentialValidator_A03 {    
    private Map<String, String> credentialsMap = new HashMap<>();// Create a hashmap to hold our username/password pairs (can use any map data structure)     
       public boolean validate(final Object obj){         // A method that will check if the provided object is valid or not. This takes an "Object" as input and verifies whether it matches with HashMap credentials         
            try{             String name = ((AuthenticationToken)obj).getToken().toString();                System.out.println("Name:  [" +name+"]");              // get the username from token (this assumes we are using a JAAS-based login system), and print it               if(credentialsMap == null || credentialsMap .isEmpty()){                  
                 throw new SecurityException ("No Credential data available. Please check your configuration.");            }             String password = ((UsernamePasswordToken)obj).getPassword().toString();                System.out.println("Pwd:  [" +password+"]");              // get the Password from Token and print it              
                 if (!credentialsMap.containsKey(name)) {                  throw new SecurityException ("Invalid username/ password combination."); }             String storedPass = credentialsMap.get(name);                System.out.println("Stored Pwd:  [" +storedPass+"]");              // get the saved Password from map and print it              
                 if(!password.equalsIgnoreCase(storedPass)){                  throw new SecurityException ("Invalid username/ password combination."); }             return true;            // If everything matches, this is a valid user (return "true")         catch{           System.out.println("Error:  ["+e+"]");                  
                 e = "";                                                       for(String str :errors){                     if(!str.isEmpty() && !result_set_.containsValue((Object)str)){                    errors++; }               }}catch (NameNotFoundException nfnfe ){                System .out.println ("There is no name in the JAAS Token.");            e="";                
             };                       return false;} // If anything goes wrong, it prints error message and returns "false". This will indicate that user authentication failed for security reasons (returns 'False').  }   public static void main(String[] args){         new CustomCredentialValidator().validate("User_Name");     }}