import javax.xml.parsers.*;
import org.w3c.dom.*;
import java.io.*;
public class java_46165_XMLParser_A01 {  
    public static void main(String[] args) throws ParserConfigurationException, IOException{    	
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();             //Step 1: Create a document builder instance and configure it to handle elements with the given name in any namespace way they are referenced (the default is 'http://www' for all namespaces).     		         	 				  			   	
        DocumentBuilder db = factory.newDocumentBuilder();    	       	    //Step 2: Use DOM Builder API provided by Java SAX to read a XML document into an in-memory representation, then pass this model (DOM tree) back up the stack and provide access points for querying it as trees or nodes
        Document doc= db.parse(new File("path_to/yourfile"));    		//Step 3: Parse source Xml from a file into DOM Tree structure		         				  			   	     	 					        						      //Source location of xml is given by the string path to your filename here
        parseDocument(doc);                     	   	        // Step4 : Use query interface (DOM, SAX or StAX) provided in API for traversing XML file/document. Here we use iterator on Document object    		         				  			   	      	     	 					        						     								  }            
private static void parseDocument(Document doc){               //Step5: Iterate over the document and print out data from each node, following recursive calls until all nodes are printed. The method can be used to navigate through a tree structure (sub-document).  		         				    	      	     	 					        						     
        NodeList nlist = doc.getElementsByTagName("tagname"); //Get the list of 'book' tags – each book tag is an element with text content representing Book title and price attributes as child elements in this case, iterate through them to print out their contents  		         				    	      	     	 					        						     
        for (int temp = 0; temp < nlist.getLength(); temp++) {  //Printing each book's details using DOM API   			                    								               }                      	}            private static void parseDocument(NodeList nodes){            	//Step6: Parse Document as a list of Nodes, then use recursion to print the data in all child and grandchildren.  		         				    	      	     	 					        						     
        for (int temp = 0; temp < nlist.getLength(); ++temp) {  //Print each Node's content using DOM API   			                    								               }                         	} private static void parseDocument(Element node){            	//Step7: Parse Document as a list of Elements, then use recursion to print the data in all child and grandchildren.
        System.out.println("Tag : " +node.getNodeName());   	       //Prints each tag'content using DOM API 		         				    	     	 					        						      }                     	}              '