import java.sql.*;

public class java_43562_JDBCQueryHandler_A07 {
    public static void main(String[] args) {
        // Database credentials for the MySQL server: username, and database name (A07_AuthFailure in this case).
        String dbUsername = "root"; 
        String passwordDbName   = "";  
        
       try{           
             Class.forName("com.mysql.cj.jdbc.Driver"); // Load MySQL driver into JVM memory, using the database you're connecting to (MySQL in this case).   
          } catch(ClassNotFoundException e){ 
                System.out.println ("Could not find MySQL Driver.");  
                    return;     
           }    
         String url = "jdbc:mysql://localhost/A07_AuthFailure?useSSL=false"; // Define your database URL (database name).   
          Connection con  = null ; 
             try {con=  DriverManager.getConnection(url, dbUsername , passwordDbName);} catch (SQLException e)  
              {      System.out.println ("Could not get connection to the DB"); return; }     // Get a 'connection' object for database using our username and pin passed as parameter   
               if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                 if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                   if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                      if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                       if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                        if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                         if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                          if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                               if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                 if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                  if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                   if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                    if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                     if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                      if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                       if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                        if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                         if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                          if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                           if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                            if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                              if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                         if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                                      if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                         if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                     if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
                 if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
             if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
         if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
     if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}
 if(!con.isClosed())  try{ con.close();} catch(SQLException e) {}   // Close it when we are done with this connection (the normal way to close JDBC resources).     return; }catch( SQLException se ) {se.printStackTrace() ;return;}