import java.security.*; // Import cryptographic classes/methods needed here e.g., MessageDigest, SecureRandom etc...  
import javax.crypto.*; // For Cipher and SecretKey (from above) ...   
import java.util.*;  // for Base64 methods to encode our encrypted passwords in Java SE platform - Optional if we don't want it as a requirement of the problem solution, but should be there when you handle user inputs / from file or database etc...  
    
public class java_46818_CredentialValidator_A07 {    /* Declare Class */ 
         public static void main(String[] args) throws NoSuchAlgorithmException      // Testing Encryption and Decryption method - not needed in the real implementation but for testing purpose.      
        {         
            String passwordToHash = "password";     // The user-supplied input (Password from UI / API call etc...)  Here it's set as a test case...   
            
           createCryptedVersionOfUserPass(passwordToHash);      /* Encrypt the User Password */  
        }         
         private static String generateSalt() throws NoSuchAlgorithmException     // Method for generating salt - required by encryption and also used to compare passwords.  (Use a random value)   
            {           return new String(Datatype.getInt().toByteArray());}      /* Convert int into Byte Array */   }       @Override public boolean equals(Object o){     // Method for comparing encrypted userPass with the one provided by User, when they try to login...  (Uses password_digest from database)
            return false;}    if(!o.getClass().equals(this.getClass())) {return false;}} else{UserCredentials newO = (UserCredentials) o ;     // Compares two instances of CredentialValidator, which are equal in terms of their UserPass encrypted fields ... 
            return this.password_digest .equals(new Objects().hashPassword(userpass));}      }   /* End Class */    public static boolean validatedUserCredentials (String passwordAttempt , String storedHash) throws NoSuchAlgorithmException {     // Method to check if user-provided Password matches the hashed one in Database...
        return validatePasswordsMatch(passwordToEncrypt,hashedPassword);}}      }  /* End Class */    private static void createCryptedVersionOfUserpass (String password) throws NoSuchAlgorithmException{     // Method to encrpyt user provided Password before saving into database ...  
        KeyGenerator kgen = KeyGenerator.getInstance("AES");                     Security.addProvider(new com.sun.crypto.provider.SunJCESecurity());  SecretKey skey=kgen .generateKey(); Cipher cipher1=  */Cipher.getInstance ("AES");          byte [] input=password.getBytes ();  
        }      // Encryption begins here...    try {cipher2 = Cipher.createEncryptedStream(sout,  skey) ;} catch {} /* End encryption method and decription part */     private static void createDecipheredVersionOfUserpass(){       String password=""; byte[] encryptedPasswordBytes;
        cipher1 .doFinal (encryptedpasswordbytes);      // Decryption begins here...    try {cipher2.dofinal(decrypt) ;} catch {} /* End decription method and encryption part */   }  private static boolean validatePasswordsMatch() throws NoSuchAlgorithmException{     return false;}}