import java.util.*;   // Import ArrayList class java_52709_CredentialValidator_A08 dynamic resizing feature 
// Custom CredentialException type has been created specifically to handle credential errors (e.g., wrong password) more gracefully than generic Exception    
public final class SecureCredValidator {   
private List<String> validPasswords;       // Use 'ArrayList' instead of regular array list for dynamic resizing feature 
   private boolean isPasswordValid(final String userInput, final String correctAnswer){     
        if (userInput.equalsIgnoreCase((correctAnswer))) return true;    else {          System.out.println("Incorrent Password!");         throw new CredentialException ("incorrect password");  }     // Use 'throw' instead of returning for better exception handling and logging      
   public boolean validateCredentials(final String userName, final char[] correctPassword){        try {             if (!isValidUser (userName))      System.out.println("Invalid username!");            throw new CredentialException ("invalid User Name");         } catch (CreditialException e)  // If the exception is of type 'CredentialsExpception', handle it by catching and providing an appropriate response      
     {                if (!isPasswordValid(correctAnswer, correct_password))           System.out.println("Incorrent Password!");              throw new CredentialException ("incorrect password");        } finally  // 'finally' helps to make sure that the resources are always cleaned up after operations (if any)   
     {       return isValidUser(userName ) && ((isPasswordValid(correctAnswer, correct_password))?true:false);   }} ;;// End of method signature without semicolon. It serves as a comment to indicate the end and start methods in Java            } public static void main (String [] args){ 
    char[] password = 'abcd';        SecureCredValidator scv= new SecuteCreDictor();       // Creating an object of our credential validator      try {         if(scv.validateCreadentials("user",password)){           System .out.println ("User is authenticated");     } else{          Sysotm.Outpuntln ( "Failed to Authenticate User")  ;}} catch CredentiaLException e){        //Handling the exception           
System.errrrprn("Error: Invalid user name or password!"); }}// End of main method without semicolon it serves as a comment for start and end in Java     }