public class java_47098_CredentialValidator_A07 {   // start with "Simple" prefix for clear understanding of the code block (e) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24. 
    private String username = "";        /* create a variable 'username' to hold user name */   // eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24. 
    private String password = "";        /* create a variable 'password' to hold user Password */   // eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07
    
public java_47098_CredentialValidator_A07(String username, String password) {           // Constructor 1. Creating an instance of Credentials Validator class which will accept two parameters ie., user name and Password */   /* eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24. 
    this.username = username;                                                  // Constructor 1 Auto suggestion   eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24. 
    this.password = password;                                                  // Constructor 1 Auto suggestion   eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24.    
}    /* end of SimpleCredentialValidator class */                                         // Class definition for 'SimpleCredentialValidator'  eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24.
                                                             /* end of SimpleCredentialValidator class */   // Class definition for 'SimpleCredentialValidator' eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24.
    public boolean validate(){                                                    /* method to check if username and password match */   // eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24.
    return this.username.equals("admin") && this.password.equals("password"); // method to check if username and password match with some predefined values */   /* eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24. 
}                                                                               // end of 'validate' method for the SimpleCredentialValidator class */   /* eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24. 
}                                                                               // end of 'SimpleCredentialValidator' Class definition */   /* eclipse auto suggestions should help (c) above - coded by Gautam Singh, A07_AuthFailure Team Member in CSE Dept at IIT(ISM), Nagpur-24.