Script (XML Parser Example) - NodeJS version, without any external libraries or frameworks used at all :-/  
// Importing required modules and packages needed in our code snippet here. If we have standard node_modules folder structure with these libs installed globally then it'd be better to use only core ones such as fs (file system) & xml2js  which can parse XML strings directly, no need for external libraries
const { Parser } = require('xml2js'); // Importing the 'parser'. This is a part of NodeJS standard library and does not have any dependency. It's just there to define an object (with methods) that will be used in our code snippet below, so we can use it anywhere inside this file
const fs = require('fs'); // Importing the 'file system', which is necessary for reading files using NodeJS – no need if standard library has already done all of these tasks. Only useful when you're working on a specific project where dependencies are managed differently, such as in projects with frameworks or libraries
const xml = require('xml2js'); // Similarly importing 'xml2js', not necessary unless we have to use methods like parseString that do not depend upon this module – standard library already does these. Only useful when you're working on a specific project where dependencies are managed differently, such as in projects with frameworks or libraries
// Defining our main function (entry point of the program) here and using 'async/await', which is very common way to handle async operations like file reading & parsing. It makes your code cleaner without changing its functionality – standard library already does this, only useful when working on a specific project where dependencies are managed differently
const main = async () => { // Defining the function here - we're not using any argument or return anything from our asynchronous method in NodeJS so it has to be 'async'. This is how you handle errors within your code. It will only run if everything inside this brackets runs without throwing an error, otherwise (if there was a promise rejection) the node process ends with that specific uncaught exception
  try { // Defining our asynchronous operation here - we're not using any argument or return anything from function in NodeJS so it has to be 'async'. This is how you handle errors within your code. It will only run if everything inside this brackets runs without throwing an error, otherwise (if there was a promise rejection) the node process ends with that specific uncaught exception
    // Reading our file using fs module here - standard library has built-in methods for reading files which can handle errors too – no need to use any external libraries like readFileSync or try/catch in this case. It will only run if everything inside the brackets runs without throwing an error, otherwise (if there was a promise rejection) node process ends with that specific uncaught exception
    fs.readFile('path-to_yourfile', 'utf8', function(err, data){ // Defining our callback here - standard library already has methods for reading files which can handle errors too – no need to use any external libraries like read/write or try catch in this case unless we have a lot of asynchronous operations inside the fs.readFile method
      if (err) {// If an error occurs while trying to access our file then do not forget that and notify about it by returning some message here – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
        return 'Error while reading your XML File'; // If everything is fine then only mention it and do not forget to handle other cases if any – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
      } else {// Do nothing but tell that everything is fine here - just show code flow and do not forget to handle other cases if any – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
        return data; // If everything is fine then only mention it here and do not forget to handle other cases if any – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
      }  
    }); // This is where our parsing will start - standard library does not handle error but it's very common to use try/catch block for handling errors, if required – no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
    // Now that our file has been read and parsed here is where actual parsing will start - standard library does not handle error but it's very common to use try/catch block for handling errors, if required – no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
    let builder = new xml2js.Builder(); // Importing our Builder class java_46896_XMLParser_A07 - standard library already has methods to handle creating json-like objects from node data – no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
    let result = builder.buildObject(data); // Builds an object out of given XML string using options provided by parser settings and xml2js default mapping for node – standard library already has methods to handle creating json-like objects from node data, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
    // Finally here is where our XML will be displayed - This part should not throw any exceptions – standard library already has methods to handle displaying JSON-like objects on HTTP response body, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
    return result; // Returns our processed data here - No further error handling required outside function – standard library already has methods to handle displaying JSON-like objects on HTTP response body, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
   } catch (error) { // If any uncaught exception occurs while executing above function then it will go here and not return anything – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
     throw error; // Do nothing but alert that an unexpected exception occurred since all async functions will only run without throwing any exceptions – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
   }    // Closing brackets here and end our function declaration with semicolon if not using ES6 syntax – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
 };// Finally closing brace (if used) and end our main function declaration with semicolon if not using ES6 syntax – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
// Calling out to run async code and catching any possible error here - Standard NodeJS way also knowns is using 'async/await' which makes our program cleaner without changing its functionality – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method
main().catch(console.error); // Calling main function and catching any error that might occur during execution here - Standard NodeJS way also knowns is using 'async/await' which makes our program cleaner without changing its functionality – standard library already has methods for handling errors too, no need external libraries or frameworks like console in this case unless we have a lot of asynchronous operations inside the fs.readFile method