import java.sql.*;   // Import the necessary classes (Statement, DriverManager) from package "java.sql"
public class java_51709_JDBCQueryHandler_A03 {     // Create a public Class name as 'JDBCQueryHandler'   
       static final String DB_URL = "jdbc:mysql://localhost/test";  // Define your database URL  
       static final String USERNAME = "root";      // define username and password for MySQL Database Server. Change according to actual credentials on the server side such as root, or a specific user with necessary permissions   
       static final String PASSWORD = "";    
        public Connection connectToDatabase() {  // Method declaration   (static so it can be accessed from any class) that connects you database using DriverManager.getConnection(db_url , username and password). This function returns a connection object to the called program via JDBC API which is used for accessing databases in Java programming
               Connection conn = null;    // Initialize variable 'conn' with data type of ‘connection’   (null by default)     using DriverManager.getConnection() method, and pass dbURL(url), username & password as parameters to the get connection function call      return conn ; }           public void disconnectFromDatabase( Connection conn ) { // Method that will disconect from database after use    if (conn != null){ try{ conn.close();}  catch (SQLException e) {} }    
        private static int insertDataIntoTable(Connection connection, String name ,String email){   /* Private method declaration for adding data into table */       PreparedStatement pstmt =null;    // Initialize variable 'pst' with a datatype as ‘Prepare Statement’ (Null by default)    
        try {                      Connection conn=connectToDatabase();                if(conn != null){            /* Begin block to establish connection and execute the statement */ pstmt =connection.prepareStatement("INSERT INTO UsersInfo VALUES (? , ? )");   // Prepared statements allows us set parameters in a query, this way we can avoid SQL Injection attacks 
        } catch (SQLException e) {e.printStackTrace();} finally{ disconnectFromDatabase(conn);}} try {    pstmt .setString(1, name );      /* Execute prepared statement */     if(!pstmt.execute()) System.out.println("Failed to insert data into the UsersInfo table."); catch (SQLException e) 
        }catch ( SQLException | NullPointerException SE ){SE.printStackTrace();} finally { disconnectFromDatabase(conn);}}}}} // End of block for adding Data and Closing connection in try-finally manner     if any exception occurs, the 'Finally' part will execute regardless what happens with it  
    }  /*End of Main Class*/               public static void main (String args[]) {      new JDBCQueryHandler().insertDataIntoTable("John Doe", "john.doe@example");} // This line is to call the insert data function from our class     try-catch block are used for error handling and recovery in a program   
                                                                }   catch (Exception $) {      System . out . println (" Error :( "); }}  /* End of Main Method */        public java_51709_JDBCQueryHandler_A03() {} // The Constructor is private, so this class cannot be instantiated outside the scope or from any other classes.*/