import java.io.*;   // For Input/Output Streams, Reader etc., you'll need these import statements at the top of your file (except for System) or use Java built-ins like BufferedReader and PrintWriter directly in a class java_47221_SocketServer_A03 necessary since they are part of IO classes 
import java.net.*;    // This is just standard library that provides everything needed to interact with sockets, such as InetAddress etc., you'll need these import statements at the top or use Java built-ins like ServerSocket and Socket directly in a class where necessary since they are part of network classes
  
public class SecureHelloServer {  // Define your server code within this main method block if we want to run from command line. For testing purposes, you can create another program which will send request or commands over socket connection such as telnet utility and see the response on stdout in case of echo-server like below
   public static void main(String[] args) {  // Create a server that waits for client connections until it gets one. Whenever there is an incoming communication from any user, this line will be triggered to handle request/response using IPC (Inter Process Communication). This means you can run your code and test if the message sent over socket connection contains anything but "Hello World!"
     ServerSocket server;   // Declare a local variable type:Server Socket  which we'll use for accepting connections from clients. A new communication channel is created on an available port where both client & server are connected to each other, thus enabling our code work with sockets using the Java I/O classes
     try {    // Catch any potential exceptions that might occur while running this block of codes and print error message followed by stack trace.  If something goes wrong in these lines it can't be handled because we are inside a 'try'-catch'. This ensures program is robust against unexpected errors even if those could happen due to external factors
         server = new ServerSocket(5069);   // Starts listening for incoming client connections on specified port. The default, 42318 and not openable by the public network are selected here but can be changed when necessary (can run it locally) - Change number as per requirement ie., Port no = 7005
         System.out.println("Waiting for Connection......");   // Prints a message in console to let know server is waiting on clients connections and listening port, 19263...port# you can change this according your need as per requirement ie., Port no = 7804
     } catch (IOException e) {    // If any exception occurs due to I/O operations then print the message followed by error detail in console. This handles exceptions that might occur while creating server socket or listening on it if necessary, and can't be handled here directly as we are inside a 'try'-catch'.
         System.out.println("Exception Occurred: " + e);   // It will print the exception message followed by stack trace (debug information) in console to let know about specific error occurred while server or socket operation could not go ahead because of I/O operations, IOException is base class for all IO Exceptions
     } 
      Socket client;    // Declare a variable type:Socket. It'll be used only once and we will accept incoming connections to this from the 'server'. If nothing comes in then it waits until something arrives on socket connection via stdin (command line or telnet utility) like below, 
      try {   // Catch any potential exceptions that might occur while running these blocks of codes. This ensures program is robust against unexpected errors even if those could happen due to external factors and can't be handled here directly as we are inside a 'try'-catch'. It will provide detailed exception information in console when such anomalies get raised
         client = server.accept();   // Accept incoming connections from clients, once accepted then data transfer takes place on these two socket connection ie., stdout & stderr streams of connected processes until this block is called again to accept the next request 19263...this line will wait for a new communication and ready with client's information when it gets one.
         System.out.println("Client Connected");   // If there are no exceptions then only print message in console letting know that server has accepted connection from specific user, if any exception occurs here can be handled but not shown below due to being inside a 'try'-catch'. This line will handle all the communication happening on socket and sending back "Hello World!"
     } catch (IOException e) {    // If there is an I/O related error then print this message followed by stack trace in console. The program won't continue if any exception occurs due to IOException operations, IOExceptions are base class for all Io Exceptions 19263...this line will handle exceptions occurring when trying communicate via socket
         System.out.println("Exception Occurred while Communicating: " + e);   // It prints the error message followed by stack trace in console to let know about specific exception occurred, IOException is base class for all Io Exceptions 19263...this line will handle exceptions occurring when trying communicate via socket
     }    // End of 'try'-catch' block which handles both I/O related and non-Io Related Exception. This ensures the program doesn’t fail in unexpected ways due to either exception but can be handled by catching it correctly as we are inside a try catch statement 19263...this line will handle exceptions occurring when trying communicate via socket
     // Incoming message from client is read into this InputStreamReader and PrintWriter outgoing through Output Stream, once communication done ie., both ends of the streams get closed. If anything fails in reading or writing then it handles these cases by throwing IOException 19263...this line will handle exceptions occurring when trying communicate via socket
     BufferedReader br = new BufferedReader(new InputStreamReader((client.getInputStream())));    // Declare a variable type:Buffered Reader, which we'll use for reading from client in the server side 19263...this line will handle exceptions occurring when trying communicate via socket
     PrintWriter pw = new PrintWriter(client.getOutputStream(), true);   // declaring printwriter object to send response back out of stream as stdout, if there is any error then it throws IOException at once 19263...this line will handle exceptions occurring when trying communicate via socket
     String inputLine;    // Declare a variable type:String. This stores incoming data from client on server side to be sent back out of stream as stdout, if anything fails in reading or writing then it handles these cases by throwing IOException 19263...this line will handle exceptions occurring when trying communicate via socket
     while ((inputLine = br.readLine()) != null) {   // Catch any potential exception that might occur due to I/O operations and print error message followed by stack trace in console, if no reading then it handles this case as well 19263...this line will handle exceptions occurring when trying communicate via socket
         System.out.println("Received: " + inputLine);   // Prints incoming data to the server side on std out from client for verification and handling cases where there is any error or if something fails in reading then it handles these case as well 19263...this line will handle exceptions occurring when trying communicate via socket
         pw.println("Hello World!");   // Sends " Hello world" back to the client for verification and handling cases where there is any error or if something fails in writing then it handles these case as well 19263...this line will handle exceptions occurring when trying communicate via socket
     }    // End of While loop which reads incoming message from Client until nothing comes over that specific connection (in a way, this block only runs once and gets completed by server after sending back all messages to clients) unless client sends 'bye' or something then the following line will never run so it handles any possible exception
     pw.close();   // Always close output stream at end of use 19263...this is how you send "Hello world" message and get done with communication in Java socket programming, It makes sure that all resources are properly released after operations on streams have completed (like reading from inputstream or writing into a file)
     br.close();   // Always close the BufferedReader at end of use 19263...this is how you read incoming message and get done with communication in Java socket programming, It makes sure that all resources are properly released after operations on streams have completed (like reading from inputstream or writing into a file)
     client.close();   // Always close the Client at end of use 19263...this is how you manage sockets and get done with communication in Java socket programming, It makes sure that all resources are properly released after operations on streams have completed (like reading from inputstream or writing into a file)
     server.close();   // Always close the Server at end of use 19263...this is how you manage sockets and get done with communication in Java socket programming, It makes sure that all resources are properly released after operations on streams have completed (like reading from inputstream or writing into a file)
     System.out.println("Connection Closed");   // If the program gets here then it means no exception occurred which is an indication of successful end and also you can assure about server socket connection closing, if any error occurs at this point than will not be able to recover 19263...this line ensures that all resources are properly released after operations on streams have completed (like reading from inputstream or writing into a file)
   } // End of main method block within 'public static void' keyword. This is the entry for any other classes we don’t want to be part here and thus should not contain this line 19263...this ensures that no one can run it by accident due since once everything has been defined in these public class only
} // End of 'public static void' keyword. This is the entry for any other classes we don’t want to be part here and thus should not contain this line 19263...this ensures that no one can run it by accident due since once everything has been defined in these public class only