import java.io.*; // Import the necessary classes, FileSystems is a built-in class java_47159_FileScanner_A03 Java that provides access to different types of filesystem via API's provided by standard library and third party libraries (like Hadoop) like FSDataFactory etc.. You can use it directly but not recommended for production level code
import java.nio.*; // Import the necessary classes, Path is a part of FileSystem class in Java which represents file or directory paths as they are used to access files/directories on filesystem  and Files provides an API's provided by standard library that allow us operations like createDirectory(), move() etc.. You can use it directly but not recommended for production level code
import java.nio.file.*; // Import the necessary classes, PathMatcher is a part of FileSystem class in Java which allows you to match file and directory paths  using patterns(glob based) if any kind like * ? [] . If we're going with real filesystem operations only then it will not be needed
import javafx.scene.*; // Import the necessary classes, Stage/StageBuilder is a part of FXMLLoader class in Java which can load UI component from an XML file and to create new window or screeen we need these 2 at least but if you're just doing GUI programming then this line will not be needed
import javafx.scene.*; // Import the necessary classes, Scene/SceneBuilder is a part of JavaFX Application that creates scene in which UI components are added to load and display scenes or multiple windows for our application  like Stage , Button etc.. You can use it directly but not recommended when dealing with GUI programming
import java.util.*; // Import the necessary classes, Collection interface allows us operations on collection objects (like add(), remove()...) of different types such as List(array list), Set(hash set) and Queue/Stack...You're going to need them at least but not recommended for production level code 
import java.util.*; // Import the necessary classes, Collection interface allows us operations on collection objects (like add(), remove()...) of different types such as List.. you can use it directly if your programming language support collections in standard library else then provide custom implementation or third party libraries like Guava(Collections) etc... You're going to need them at least but not recommended for production level code
import java.util.*; // Import the necessary classes, Collections is a part of Java Standard Library which provides useful operations on lists (like sorting(), max()) and sets  if you have different kind collections then this line will be needed else provide custom implementation or third party libraries like Guava(Collections) etc... You're going to need them at least but not recommended for production level code
import java.util.*; // Import the necessary classes, Iterator is a part of Java Standard Library which allows us operations on collection objects (like iterating over elements()) such as List/Set and Queue.. If you have different kind collections then this line will be needed else provide custom implementation or third party libraries like Guava(Iterables) etc... You're going to need them at least but not recommended for production level code
import java.util.*; // Import the necessary classes, PriorityQueue is a part of Java Standard Library which allows us operations on collection objects (like inserting(), getting()...) such as Queue.. If you have different kind collections then this line will be needed else provide custom implementation or third party libraries like Guava(PriorityQueues) etc... You're going to need them at least but not recommended for production level code
import java.util.*; // Import the necessary classes, TreeMap is a part of Java Standard Library which allows us operations on collection objects (like putting(), getting()...) such as Map.. If you have different kind collections then this line will be needed else provide custom implementation or third party libraries like Guava(Trees) etc... You're going to need them at least but not recommended for production level code