import org.springframework.context.annotation.*;
import javax.servlet.*;
import java.io.IOException;
@Configuration     //1a Configuration annotation to indicate class java_52915_SessionManager_A03 source of bean definitions for application context  (BeanFactory) and JNDI data sources, @ComponentScan also used here with base packages in the package where beans are defined   by default is set all subpackages but not included top level classes. If you want only root components then use '@Component' annotation
public class AppConfig { //1b Use Configuration Annotation for declaring a bean definition or annotated Bean Class to indicate that an instance should be created and managed within the Spring container  (BeanFactory).     This would also allow it being autowired by other beans. If not specified, spring defaults scope of @Component is singleton if there are multiple instances available in context
@Primary //1c Use this annotation for declaring a bean that has an immediate preference over others which have the same type and primary flag set  (if present). In case two services share similar functionality then '@Autowired' would fail as it will not select any. Primary is used when there are multiple beans of one class in context
public @Service //1d Use Service Annotation for declaring a singleton Spring bean which should be created and instantiated once the application context. The default lifecycle order (initialization, destruction) uses reference to ensure they run at startup/shutdown only if there are no other beans present with same scope 
public class MySecurity { //2a Use Repository or Service Annotation for declaring a singleton Spring bean which should be created and instantiated once the application context. The default lifecycle order (initialization, destruction) uses reference to ensure they run at startup/shutdown only if there are no other beans present with same scope
@Autowired //2b Use Autowiring Annotation for injecting dependencies into bean methods which have parameters in their method signature  This would also allow autoswitch and property setters. If not specified, spring defaults to use field injection when available but if you want any of the constructors then 'autowire' should be added
private HttpServletRequest request; //2c Autowired Fields are placed in class level where no special handling is required for autoswitch and property setters.  Spring will auto-detect these fields based on field name if there aren’t any @Autowired annotations or by using the reflection to look at all public properties
@PostConstruct //2d Use this annotation when you want a method that needs initialization before it is executed (constructor injection). It also ensures its execution only once, no matter how many times beans are created.  This would be useful in scenarios where we have dependencies on other bean and they must get initialized at the time of object creation
public void init(HttpServletRequest request){ //2e Use setter-based dependency to inject a value or reference into field using @Autowired annotation, Spring will auto handle this.  If there is no '@PostConstruct' then it won’t execute and constructor injection would still work if present otherwise spring autodetects on fields
this.request= request;   //2f Assign the value to a member variable in setter method where we can perform any cleanup task after dependency has been injected  or Spring will auto handle this based upon field names and types of dependencies involved with it if present otherwise using reflection is used which requires explicit setup
}    }// end MySecurity class. This demonstrates how one could use spring's @Service,@Autowired annotations for managing a session in your application through Security-sensitive operations related to A03_Injection as requested  and also demonstrate the creation of beans using Spring context annotation classes like Configuration , Component etc