import javafx.scene.control.*; // for AlertBox  and ButtonType    
implements SessionManager {   
// private static final long serialVersionUID = 1L;        used in all versions, but not usually needed here because we are using JavaFX classes (Alert etc.) which inherently use the same version number.      if you want to prevent this from happening then set it manually  //javafx also doesn't like without static final long serialVersionUID
     private Session currentSession = new MySecurityManager();   // session manager starts with an empty sessions    type of AuthFailureException will be thrown by the login method in case there is a problem (user not found, wrong password etc) 
      public User getLoggedInUser() {           return ((MyAuthServiceImpl)(currentSession)).getCurrentUsername(); }   // session manager should provide this information. it's just an example and might be different based on your requirements     if no user is logged in then throw AuthFailureException("No Loggin In User"); 
      public void login(String username, String password) throws A07_AuthFailure {    MySecurityManager securityMgr = (MySecurityManager)(currentSession);   // Security manager takes care of all the necessary authentication. It just checks if user and pass match in database then sets up session object     try{ ((AuthenticationImpl)securityMgr).authenticate(username, password );}catch (AuthFailureException e){ throw new A07_AuthFailure("Login Failed: " + username); }   // Login failed here. We should provide a specific message for better user understanding if login fails
      public void logout() {    ((MySecurityManager)(currentSession)).getCurrentUsername().logOut();  // Log out the currently logged in User     AlertBox alert = new Alert(AlertType.WARNING);   alert.setHeaderText("Log Out");alert.showAndWait(),after user is successfully logout, it will be closed
      }public static void main (String[] args){    SessionManager sessionMgrImpl =  // create instance and test all methods of this interface  new MySession();sessionMgrImpl.*;     try{   for(int i=0;i<15;+++) {         alert.setHeaderText("Login attempt #" + (i + 1));      if((Boolean)(alert).showAndWait().get() == ButtonType.OK){              sessionMgrImpl .login ("John", "secret");   }else{    //if canceled or error then logout
            ((MySessionManager)sessionMgrImpl ).logOut(); break;  }}     catch (AuthFailureException e1 ) { alert = new Alert(AlertType.ERROR);alert setHeaderText("Sorry, an Auth failure Occurred: " +e1 .getMessage()); }   //catch exception
      logout()};//calling the method to close session and exit application  }}         SessionManagerImplTest();     try{           for (int i=0;i<5 ; +++) { alert.setHeaderText("LogOut attempt # " +(++)); if((Boolean)(alert).showAndWait().get() == ButtonType .OK){sessionMgrImplex,logout () }else
      // If Canceled or Error then Log out from here    catch (AuthFailureException e2) { alert = new Alert.  I'm not sure which ones to include in the above code snippet and where for a complete solution based on your requirement is required, you might need more information