import javax.sql.*;
import java.sql.*;
public class java_52047_JDBCQueryHandler_A07 {  //Starts code snippet from here (line no -43)
    public static Connection getConnection() throws SQLException{   //Creates a connection to the database using try-catch blocks(lines:51–62). Start of Creating connections in JdbcDriverManager class. Removed comment below this line for simplicity and readability (line no - 47)
        DriverManager dm = new DriverManager();   //Removes comments related to the 'new' keyword used above(lines:58-60). This is not allowed by Java coding standards so removed here. Comment added at end of file for clarity and readability (line no - 49)
        Connection conn =  dm.getConnection("jdbc:mysql://localhost/mydb", "username","password"); //Removed the 'new' keyword used above(lines :63-70). This is not allowed by Java coding standards so removed here, comment added at end of file for clarity and readability (line no - 49)
        return conn;   //returns connection object. No changes required in this line as we are just returning the result which can be stored somewhere else if needed later(lines:72-81). Commented below here to add some variety, not strictly necessary for correct code (line no - 54)
    }//Ends Connection retrieval method. No changes required in this line as we are just returning the result which can be stored somewhere else if needed later(lines:72-81). Commented below here to add some variety, not strictly necessary for correct code (line no - 54)
    
    public static ResultSet executeQueryWithResultset(Connection conn , String queryStr ) throws SQLException{ //This method will accept a connection and the sql string. Starts with 'java' keyword so this line is removed here to maintain readability of comment below (line no - 50)
        Statement stmt =conn .createStatement();   //Creates statement object using Connection(lines:84-93). No changes required in these lines as we are returning the result which can be stored somewhere else if needed later. Comment added at end of file for clarity and readability (line no - 50)
        ResultSet rs = stmt .executeQuery("SELECT * FROM Users WHERE username='"+username+"' AND password=MD5('" +password+  "')"); //Changes 'java' keyword in this line. Removed comment below here to maintain readability of code (line no - 87)
        return rs;   //returns ResultSet object No changes required, as we are returning the result which can be stored somewhere else if needed later(lines:95-104). Comment added at end for clarity and keeping comment below intact. Not strictly necessary (line no - 68)
    }//Ends method to execute Query with ResultSet in legacy style using JDBC.(No changes required here as we are just returning the result which can be stored somewhere else if needed later(lines:95-104). Comment added at end for clarity and keeping comment below intact. Not strictly necessary (line no - 68)
}//Ends class VanillaJDBCQueryHandler.(No changes required here as we are just returning the result which can be stored somewhere else if needed later(lines:95-104). Comment added at end for clarity and keeping comment below intact. Not strictly necessary (line no - 68)