import java.util.*;  // Importing List interface from Java Collection Framework, so we can use LinkedList as our implementation of Session list and Map to implement session attributes like userId etc...  
public class java_52856_SessionManager_A08 {                                                    
    private static HashMap<String, Object> storage = new HashMap<>();  // Declare a hashmap for in-memory database. It will store the sessions as key:value pairs - each Session being represented by an object of type 'User' with its attributes(userId etc...).  
     public List <HashMap<String, Object>> sessionList = new LinkedList<>();  // Create a list to hold all active users (i.e., in-memory sessions), so we can easily manage it using the linklist data structure provided by Java Collection Framework - useful if there are several 'active' or `logical` user with their own attributes for session management etc...
     
     public String createSession(Object attribute){  // Method to start a new Session (create)  
        UUID uuid = UUID.randomUUID();    Date now  =new Date() ;                   HashMap<String, Object> map= new HashMap<> () ;                   
         map .put ("createdAt",now);                                                  Map < String ,Object > userId =  new HashMap  <>  ( );                     // Adding Session specific attributes.   UserID is added in the beginning of session creation  which will be used for future references, as keys to 'storage'.    UUID ensures unique identifiers and Date helps keep track created time at same instance
         map .put ("sessionId",uuid);                                                 userId . put("userid" , uuid ) ;     // UserID is a session specific attribute which can be used for reference.  Map -> HashMap   to add attributes in Session..          UUID-unique identifier unique across all sessions, Date timestamp of when it's created
         map .put ("attributes",attribute);                                           set < String ,Object > values = ( Set<String, Object>  )map.get("values") ;  // storing value for the attribute session...    Attributes are stored in Session to reference later during user requests etc....     HashMap -> Map
         storage .put(uuid, map);                                                     List <HashMap <  String ,Object >> list  = new LinkedList  <>  ( )   ;                           Adding User Information into 'session' of sessions..    UUID is used for unique identification and storing it in the session.  It will be a key to get particular user data from our Hashmap later
         return uuid .toString () ;                                                     List<HashMap <String, Object >> list = new LinkedList<> ( )   ;                             Get all sessions by using this method...     UUID is used as parameter for getting specific session.  Returning SessionID back to the calling function..    void getUserData() {
        // Method that retrieves a User from their userid in HashMap based on unique identifiers, returns and prints out related info like username etc ...   }                                                                                         };     public static main(String[] args)                                                 System.out .println ( "Starting up the application" ); sessionManager = new VanillaJavaSessionManager();     
          // Here we call our methods to interact with Session...  User user1=newUser("John","Doe",23,"male");                   New users are created and their information is added into a 'session' of sessions.   }}};                                                                                       };                           new HashMap<> ( ) ;                                   void addAttribute(Object attribute) {
        // A method to store data in the session...  It will be used by our User class methods for setting user attributes etc..                                                        });     public static Session getSessionById() {}                      This is a way of getting an existing 'session' from its ID and return it back. Return null if no such active sessions exists, but should handle cases where multiple users have the same session id...   }}                                                                                         
    };  // Ending our VanillaJavaProgram                                                 }}};      private static SessionManager instance = new vanilajavaSessionmanager();};     public class User {        String firstName , lastname ; int age, genderCode.                                                ...}//User object is used for handling user data and it has methods to set the attributes of a users...