import java.io.*; // for FileScanner
import java.util.*; // for List to store all file names in memory without loading them onto disk

public final class java_48169_FileScanner_A03 {  
    public static void main(String[] args) throws Exception{ 
        Scanner scan = new Scanner(System.in);                
    	List<File> filesFound=new ArrayList<>();             //list to store all file names found in memory without loading them onto disk        
      	int maxDepth = 0;                                    	//depth of search, start from root directory          		 									  			     								   	   	 	       	     ​          .'     '(......'.-.-./.-.+')/'-.' '-.\'/'' ./--.--\`./,---\/\//...
        	FileScanner fs = new FileScanner();              //create a file scaner instance 		           			   	   	 	       	     	.:.:' .'::' '.. '. :'./-.-./.-/'-.' '-.\'/'' './--.--\`./,---\/\//...
        	System.out.println("Enter the root directory path");        //prompt user to enter a file name or use wildcard (*) for all files in current folder          		 									  			     								   	   	 	       	     	.'     '(......'.-.-./.-.+')/'-.' '-.\'/'' ./--.--\`./,---\/\//...
        String rootDir = scan.nextLine();              //get the directory from user        		 									  			     								   	   	 	       	     	.'     '(......'.-.-./.-.+')/'-.' '-.\'/'' ./--.--\`./,---\/\//...
        fs.scanDirectoryTree(new File("."), maxDepth);                //search for file names in current directory and all its subdirectories           		 									  			     								   	   	 	       	     	.'     '(......'.-.-./.-.+')/'-.' '-.\'/'' ./--.--\`./,---\/\//...
        fs.printFileNames();                             //Print the names of files found        	                 		 									  			     								   	   	 	       	     	.'     '(......'.-.-./.-.+')/'-.' '-.\'/'' ./--.--\`./,---\/\//...
        }           .                aaaaaa              bbbbaabb          ccccccc         dddddee      eeeffffff       ffffffff  gggghhii     hhhhiimmm   iilllmno    oopprrrsstt uuvvwzzz