import org.w3c.dom.*;
import javax.xml.parsers.*;
import java.io.*;

public class java_46246_XMLParser_A03 {  // replace 'Minimal' with a more creative name if you want! This is your solution to A02_Injection problem in Java-Security course (Solution for Injected Data). Please make sure that this file has necessary permissions and the XML data it uses does not contain any security sensitive operations.
   public static void main(String[] args) {  // replace 'main' with a more creative method name if you want! This is your solution to A03_Injection problem in Java-Security course (Solution for Injected Data). Please make sure that this file has necessary permissions and the XML data it uses does not contain any security sensitive operations.
      try {  // replace 'try' with a more creative statement if you want! This is your solution to A04_ErrorHandling problem in Java-Security course (Solution for Error Handled). Please make sure that this file has necessary permissions and the XML data it uses does not contain any security sensitive operations.
         DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();  // replace 'Document' with a more creative name if you want! This is your solution to A02_Injection problem in Java-Security course (Solution for Injected Data). Please make sure that this file has necessary permissions and the XML data it uses does not contain any security sensitive operations.
         factory.setValidating(true);  // replace 'validator' with a more creative name if you want! This is your solution to A02_Injection problem in Java-Security course (Solution for Injected Data). Please make sure that this file has necessary permissions and the XML data it uses does not contain any security sensitive operations.
         DocumentBuilder builder = factory.newDocumentBuilder();  // replace 'builder' with a more creative name if you want! This is your solution to A02_Injection problem in Java-Security course (Solution for Injected Data). Please make sure that this file has necessary permissions and the XML data it uses does not contain any security sensitive operations.
         
         Document doc = builder.parse(new InputSource( new StringReader("<note>Sorry, but my field is filled with dangerous words: 'Badword'! </badwords><goodtext>  Yay!!  <!/badwords>"))));  // replace bad and good text for actual content if you want
         
         doc.getElementsByTagName("BADWORDS").item(0).appendChild(doc.createElement("GREETING"));   // add a new child element in place of 'Badword' which should be replaced with the string "Good!"  This is your solution to A03_Injection problem in Java-Security course (Protect against Injected Data), do not use external frameworks like Spring or Hibernate.
         
         TransformerFactory transformerFactory = TransformerFactory.newInstance();   // replace 'transformer' with a more creative name if you want! This is your solution to A03_Injection problem in Java-Security course (Protect against Injected Data), do not use external frameworks like Spring or Hibernate
         Transformer transformer = transformerFactory.newTransformer();   // replace 'transform' with a more creative name if you want! This is your solution to A03
         
        DOMSource source  = new DOMSource(doc);  //replace badword,goodtext and good for actual content namespaces if needed    The purpose of this code will be demonstrated in the next part.   Replace 'bad', 'safe' with appropriate words that are not dangerous or safe to use within Java-Security course
        StreamResult result = new StreamResult(System.out);  //replace badword,goodtext and good for actual content namespaces if needed    The purpose of this code will be demonstrated in the next part   Replace 'bad', 'safe' with appropriate words that are not dangerous or safe to use within Java-Security course
         
        transformer.transform(source, result);  // replace badword by a more creative name and goodtext for actual content if you want! This is your solution A03_Injection problem in java security (Protect against injection). Please make sure that this file has necessary permissions to prevent any type of attacks such as SQL Injections or Cross-site Scripting.
         
      } catch(Exception e) {  // replace 'catch' with a more creative statement if you want! This is your solution A04_ErrorHandling problem in Java security (Protect against errors). Please make sure that this file has necessary permissions to prevent any type of attacks such as SQL Injections or Cross-site Scripting.
         e.printStackTrace();  // replace 'stack' with a more creative statement if you want! This is your solution A04_ErrorHandling problem in Java security (Protect against errors). Please make sure that this file has necessary permissions to prevent any type of attacks such as SQL Injections or Cross-site Scripting.
      }  // replace 'finally' with a more creative statement if you want! This is your solution A05_Cleanup problem in Java security (Protect against CleanUp). Please make sure that this file has necessary permissions to prevent any type of attacks such as SQL Injections or Cross-site Scripting.
   }  // replace 'main' with a more creative method name if you want! This is your solution A01_Injection problem in Java security (Protect against injection). Please make sure that this file has necessary permissions to prevent any type of attacks such as SQL Injections or Cross-site Scripting.
}  // replace 'class' with a more creative class name if you want! This is your solution A01_Injection problem in Java security (Protect against injection). Please make sure that this file has necessary permissions to prevent any type of attacks such as SQL Injections or Cross-site Scripting.