import java.io.*; // Importing necessary classes here so that we can utilize them later on inside the code snippet below: FileInputStream, InputStreamReader and BufferedReader...etc are available by default in any new project if not explicitly imported elsewhere as stated previously for simplicity's sake.. 
  
public class java_52852_FileScanner_A08 {
    public static void main(String[] args) throws IOException{ //Main method. We will read from the command line arguments passed during execution of our program (Java runs programs through a terminal or console, so it can take inputs via this). In Java we use 'throws' to let other methods know that they must call one particular function in order for them not work correctly - when you want some method XYZ called by something else and there is an error.
        if (args.length != 1) { //If the user didnt provide a single filename as argument, print out usage information to screen: 
            System.out.println("Usage:\tjava Main <filename>");  
            return;              //Ends execution of main method and hence terminates here - no need for an else block since there're none if not supposed...to go back the way we started, just exit or close your program abruptly when you are done.  So 'return ;'. This is necessary in normal circumstances to halt a Java application (and thus end our example).
        }                        //Else continue with rest of main method..it will do nothing if no filename was provided as an argument...except that it could be useful for testing purposes or building programs which require command line arguments.    So 'return;'  - Ends the program abruptly and ends its execution here, not continuing to run through normal circumstances (Java runs with user input via a console/terminal).
         File file = new File(args[0]); //Creating object of type "File" for given filename passed in args.   It is an instance variable - we will use this later inside the method...which can be useful to read or write information related details about files and directories on your system (e.g., where they are stored, who owns them etc).
         if (!file.exists()) { //If file does not exist:  print error message out using System's inbuilt methods - Println & printf...etc as per standard Java conventions for such cases..and then return from main method to terminate or end program execution immediately after printing this information, otherwise the rest of your code would still be executed (as none will happen if you reach here).
            System.out.printf("File %s does not exist.\n", args[0]);  //Note: we are using 'args' as a temporary name for array passed by command line in java and then use it inside printf to print out the file that doesn’t exists, so you won't get any error message with incorrect filename.
            return;    }   else {     FileReader fr = new FileReader(file);  //Object of type 'Filereader', which is used for reading a character stream from a file and an object of Buffered Reader...etc to handle such streams - are available by default in any Java program if not explicitly imported elsewhere as stated previously.
             int data;     //This variable will hold the read byte value..it can be useful while writing bytes, but only for reading files now.-It is local/instance related hence cannot go inside an 'if' condition nor loop block and it needs to stay within main method otherwise control might get lost due lack of return type.
             try (BufferedReader br = new BufferedReader(fr)){  //Creating a buffering character input stream which reads text from the underlying reader, in this case filereader...etc are available by default if not explicitly imported elsewhere as stated previously for simplicity's sake..it can be useful to read lines or texts at once.
                  while ((data = br.read()) != -1) {    //If there is still data ready then:  print it out using System and BufferedReader methods (Println & printf are used as per standard Java conventions for such cases). Then continue reading till the end of file by just returning from loop block, otherwise control might get lost due lack of return type.
                       if ((char)data == '\n') { //If character read is new line then print it out using System and BufferedReader methods (Println & printf are used as per standard Java conventions for such cases). Then continue reading till the end of file by just returning from loop block, otherwise control might get lost due lack of return type.
                            break;  //Exit this while-loop when a new line is read...this would be useful to separate different lines in text data stream or even help with debugging if there are syntax errors at some point..it can go inside 'if' condition and loop block only, no further outside it due lack of return type.
                       }  else { //Else print the character out using System methods (Println & printf). Then continue reading till end-of file by just returning from current iteration if there is any syntax error at some point..it can go inside 'if' condition and loop block only, no further outside it due lack of return type.
                            break;   //Exit this while else when a new character (line) or text data read till end-of file by just returning from current iteration if there is any syntax error at some point..it can go inside 'if' condition and loop block only, no further outside it due lack of return type.
                       }  //Ending the nested structure for else...to make sure control goes back to while (data = br.read()) != -1) if there is still data ready till end-of file by just returning from current iteration when any syntax error occurs at some point..it can go inside 'if' condition and loop block only, no further outside it due lack of return type .
                    }  //Ending the structure for while (data = br.read()) != -1) if there is still data ready till end-of file by just returning from current iteration when any syntax error occurs at some point..it can go inside 'if' condition and loop block only, no further outside it due lack of return type .
                }  //Ending the structure for try (BufferedReader br = new BufferedReader(fr)) if there is still data ready till end-of file by just returning from current iteration when any syntax error occurs at some point..it can go inside 'if' condition and loop block only, no further outside it due lack of return type .
        }  //Ending the structure for File class constructor...to make sure control goes back to if (args.length != 1) { ...} or any other place where there is a chance this code can go wrong in case something unusual happens during execution and not handled by our try/catch..it will be caught here due lack of return type .
    }  //Ending the structure for main method...to make sure control goes back to if (file.exists()) { ...} or any other place where there is a chance this code can go wrong in case something unusual happens during execution and not handled by our try/catch..it will be caught here due lack of return type .
 }  //Ending the structure for Main method...to make sure control goes back to if (!file.exists()) { ...} or any other place where there is a chance this code can go wrong in case something unusual happens during execution and not handled by our try/catch..it will be caught here due lack of return type .