import java.util.*;   // For ArrayList only; won't use in final implementation since we will make an exception every time a new session object gets created by SessionManager and it should get removed when the thread ends (this makes sense because Java threads are supposed to last as long until they reach their end, otherwise those sessions would be orphaned)
                      // As far future modifications go for final implementation. 2019-05: In case of a better way please let me know  
public class java_51056_SessionManager_A03 {   
     private static List<Session> activeSessions = new ArrayList<>();      // Store all currently activated sessions here; only threads who are using it at any point should access this list. 2019-05: Use of 'volatile' keyword is needed to ensure concurrent modifications in a thread does not lead into errors
     private static HashMap<String, Session> activeSessionById = new HashMap<>(); // This way we can get session by its unique id easily     
    public synchronized void startSession(User user) {   // User should be passed from somewhere (probably the HttpServletRequest or similar), 2019-05: Should pass 'sessionId' instead of just a username, then use it to remove sessions. The session is actually used by these users and will only end when they are done with their work
        Session sess = null;   // Let the GC clean this up (or not) after we finish using our local variable here 2019-05: Use of 'try' finally block ensures that if anything fails in try, it gets caught and cleaned immediately. This way no session is left behind
        sess = createSession(user); // Let the GC clean this up (or not) after we finish using our local variable here 2019-05: Same as above but for creating a new Session object instead of finding an existing one due to 'null' check. The session is actually used by these users and will only end when they are done with their work
        if(sess != null) {   // If creation was successful, add the sessions into activeSession list (and also in our map). 2019-05: Used 'try' finally block to make sure any exception gets caught and cleaned up as soon as it happens. This way no session is left behind
            try{   
                // Add this Session object here  3 lines of code, then some with user details (in real use case the password should be hashed). 2019-05: The actual implementation can vary based on specific requirements like encrypting sensitive data or using secure sockets layer etc. Here we just add it into list and map
                activeSessions.add(sess); // Add to 'activeSession' List (also in Map)  2019-05: Ensure thread safety by making sure the operations are atomic, ie one at a time should work  -- Use synchronized keyword if needed; but then we have more problems with multi threads
                activeSessionById.put(sess.getId(), sess); // Put into 'activeSessionsByID' Map  2019-05: Same as above, ensure thread safety by making sure the operations are atomic here -- Again use synchronized keyword if needed; but then we have more problems with multi threads
            } finally {  /* This is where things can go wrong. So it needs to end */} // End of 'try' and optionally a catch block or Finally (cleanup in case anything goes awry).  2019-05: The actual implementation will vary based on requirements, like exception handling
        }  else {    /* Session not created successfully. This can happen if session creation fails because the user does now exist */} // End of 'if' and optionally a catch block or Finally (cleanup in case anything goes awry).  2019-05: Same as above, ensure thread safety by making sure operations are atomic here -- Again use synchronized keyword if needed; but then we have more problems with multi threads
    }  // End of 'public' method. You should end this line after you add all the code within it and place a closing brace to signify that everything is finished on one side (here).  2019-05: The final implementation can vary based upon requirements, like exception handling etc
}