import java.sql.*;
public class java_51679_JDBCQueryHandler_A08 {  
    public static void main(String[] args) throws ClassNotFoundException, SQLException{
        String url = "jdbc:mysql://localhost/testdb"; // Replace with your actual database URL 
	String userName="root", password="password";// replace root and empty string as per the requirement.  
        	Class.forName("com.mysql.cj.jdbc.Driver");     //load mysql driver    for oracle jdbc : loadLater() or ClassNotFoundException, SQLException  , Exception      try {           JDBCUtilities.driver = DriverManager.getDriver(url);        } catch (ClassNotFoundException | SQLException e)      
{         throw new ExceptionInInitializerError("Cannot initialize the database driver");}     //catch and rethrow exception to propagate it upwards    for any other exceptions we want, do not log but still handle them   try {           Connection connection = JDBCUtilities.connection  = DriverManager.getConnection(url , userName ,"password" );        } catch (SQLException | ClassNotFoundException e)      
{         throw new ExceptionInInitializerError("Cannot establish database connections");}     //catch and rethrow exception to propagate it upwards    for any other exceptions we want, do not log but still handle them   try {           Statement statement = connection.createStatement();        } catch (SQLException e)      
{         throw new ExceptionInInitializerError("Cannot execute database queries");}     //catch and rethrow exception to propagate it upwards    for any other exceptions we want, do not log but still handle them   try {           ResultSet result = statement.executeQuery(sql);        } catch (SQLException e)      
{         throw new ExceptionInInitializerError("Cannot fetch data from the database");}     //catch and rethrow exception to propagate it upwards    for any other exceptions we want, do not log but still handle them   try {           PreparedStatement preparedStmt = connection.prepareStatement(sql);         
preparedStmt .setString (1 , value );         } catch …{ ...}     //catch and rethrow exception to propagate it upwards    for any other exceptions we want, do not log but still handle them   try {           PreparedStatement preparedStmt = connection.prepareStatement(sql);         
preparedStmt .setString (1 , value );         } catch …{ ...}     //catch and rethrow exception to propagate it upwards    for any other exceptions we want, do not log but still handle them   try {           PreparedStatement preparedStmt = connection.prepareStatement(sql);         
preparedStmt .setString (1 , value );         } catch …{ ...}     //catch and rethrow exception to propagate it upwards    for any other exceptions we want, do not log but still handle them   try {           ResultSet result = preparedStmt.executeQuery();       
      while(result .next()){          Logic of your code here ....... }       return;     //catch and rethrow exception to propagate it upwards    for any other exceptions we want, do not log but still handle them   try {           ResultSet result = preparedStmt.executeQuery();       
while(result .next()){          Logic of your code here ....... }       return;     //catch and rethrow exception to propagate it upwards    for any other exceptions we want, do not log but still handle them   try {           connection ,statement=null ;         JDBCUtilities.connection = null;} catch …{ ...}