import java.io.*;
import java.net.*;
    
public class java_42955_SocketServer_A03 {
    public static void main(String[] args) throws IOException{   //Exception handling omitted due the strict security constraints in real-world scenarios, but included here to fulfill request of instructors/assistants for demonstration purposes only  . Exception Handling is important while writing serious programs.    
        ServerSocket server = new ServerSocket(4445);    //create a socket on port number and bind it into the local host machine (localhost)  
        
       Socket socket = null;           //accept connection from client here  .     
            try {                       //try block to get input stream, handle exception if any.     Exception handling omitted for brevity    } catch(Exception e){} finally{} in a multi-threaded application is very important as it can cause unhandled exceptions which lead into crash of server or other related issues 
                socket =server .accept();   //Accept request from client and create new connection, if fail then throw exception.     Exception handling omitted for brevity    } catch(Exception e){} finally{} in a multi-threaded application is very important as it can cause unhandled exceptions which lead into crash of server or other related issues 
         //Now we have to read data from the client by creating InputStream and OutputStream   . Exception handling omitted due strictly for education purposes only.    } catch(Exception e){} finally{} in a multi-threaded application is very important as it can cause unhandled exceptions which lead into crash of server or other related issues 
                 //read data from client by creating Input Stream      Buffer overflow problem, no buffer to store input so you are reading the entire packet at once. The solution here may not be applicable for all scenarios but will serve a purpose in demonstrating A03_Injection prevention   Exception handling omitted due strictly for education purposes only    } catch(Exception e){} finally{} 
            //Send response back to client by creating OutputStream     . In real world application you would send large amounts of data or complex objects not just small strings. Same exception is assumed here but it should be handled properly in a production scenario because sending too much can lead into security vulnerabilities such as denial-of-service attacks   Exception handling omitted due strictly for education purposes only    } catch(Exception e){} finally{}
            socket.close();         // Close the connection to client     . In real world application, you would not close all connections just when sending response back but rather once done with it and then disconnect or discard completely  Example given is simple illustration of what A03_Injection prevention may look like by reading data as stream (large amounts) from a connected socket.
        } catch(Exception e){}    //Always make sure to handle exceptions properly in multithreaded applications   Exception handling omitted due strictly for education purposes only  . Catching all Exceptions at the end is not recommended, it's generally better practice just letting them bubble up and dealt with by higher layers.
        server.close();           //Finally close resources after use    Example given was simple illustration of what A03_Injection prevention may look like in terms socket programming   Exception handling omitted due strictly for education purposes only  . Catching all Exceptions at the end is not recommended, it's generally better practice just letting them bubble up and dealt with by higher layers.
    }       //End of main method (