import java.io.*;
import java.net.*;

public class java_43683_SocketServer_A08 {  // Start of Class definition in Java code block (Starts With 'Java')  
    public static void main(String[] args) throws IOException{    		// Main function starts here and ends with the closing bracket, ('java' is a keyword). If it encounters any errors or exception at this point then stop.  // This line makes sure Java code runs smoothly without error in case of exceptions
        ServerSocket server = new ServerSocket(2019);      	// Create an instance for socket and port number  
        	System.out.println("Waiting For Connection..");			   		
         
     while (true){      // Infinite loop so that the connection can be made indefinitely  without termination signal from client side program or server-side Java application code block end with '}' and start of method definition, ('java')  	           	// This line makes sure JaVa Code runs smoothly. Without this it might stop if any exceptions occur
        Socket socket = server.accept();     // Server starts listening for incoming connections  Here is where the client connects to our host machine (the IP address and Port number are specified)   			            		  		// This line makes sure Java code run smooth in case of errors or exception at this point then stop
        System.out.println("Connection Established..");      									     // If it successfully establishes a connection, print out the message "connection established" and continue execution from there onwards  only if no exceptions occur below lines are executed (only when 'accept()' returns socket). Exceptions may throw at this point for different reasons like wrong port number passed or issue with network.
        DataInputStream dis = new DataInputStream(socket.getInputStream());	// Accepts data in input stream and wrap the object around  to create an instance of class that manages incoming streams    // This line makes sure Java code run smoothly without error if there is exception at this point then stop		  	        
        String clientMsg = dis.readUTF();      									           	// Read a string from Client (this will block until the message arrives)  If it throws an Exception, print out "Data received" and continue execution			             // This line makes sure Java code run smoothly without error if there is exception at this point then stop
        System.out.println("Received Data: '" + clientMsg+"'");      			// Print the data that we receive from a Client  If no exceptions occur below lines are executed, only when 'readUTF()' returns string (data sent by user). Exceptions may throw at this point for different reasons like wrong message format or issue with network.
        DataOutputStream dos = new DataOutputStream(socket.getOutputStream());		// Accepts data in output stream and wrap the object around to create an instance of class that manages outgoing streams  // This line makes sure Java code run smoothly without error if there is exception at this point then stop		      			    
        String serverMsg = "Hello Client, Message Sent Successfully";	// Define a message for Server (this will be sent back as response)    If no exceptions occur below lines are executed only when 'writeUTF()' method gets called. Exceptions may throw if wrong data is written or issue with network occurs  
        dos.writeUTF(serverMsg);	     // Send the serverMessage to client, this line blocks until it receives a confirmation from Client (from socket)    If no exceptions occur below lines are executed only when 'socket' gets closed and we get acknowledgment by listening on Server side  Exceptions may throw at different points such as issues with TCP/IP sockets or network connection failure.
        dos.flush();	     // Flush the DataOutputStream to ensure that all data is written out   If no exceptions occur below lines are executed only when 'writeUTF()' gets called and we get confirmation from client (from socket). Exceptions may throw if wrong string length, memory allocation issue or any other OS/Socket related error 
        System.out.println("Sent Data: '"+ serverMsg +"'");     // If it successfully sent the data to Client then print out "Data Sent" and continue execution from there onwards   only when no exceptions occur below lines are executed (only if 'flush()' gets called). Exceptions may throw at this point for different reasons such as wrong message format, issue with TCP/IP sockets or network connection failure.
        socket.close();     // This line closes the Socket  If it throws an exception then stop execution from there onwards   only if no exceptions occur below lines are executed (only when 'socket' is closed). Exceptions may throw at different points such as issues with TCP/IP sockets or network connection failure
        System.out.println("Connection Closed..");    // If it successfully closes the Connection then print out "connection closed"  This line makes sure Java code runs smoothly without error if there is exception and stops execution from that point onwards only when no exceptions occur below lines are executed (only in case of closing connection). Exceptions may throw at different points such as issues with TCP/IP sockets or network communication failure.
      }   // This line makes sure Java code runs smoothly without error if there is exception and stops execution from that point onwards only when no exceptions occur below lines are executed (only in case of closing connection). Exceptions may throw at different points such as issues with TCP/IP sockets or network communication failure.
}   	// Ending the Socket Server example program // This line makes sure Java code runs smoothly without error if there is exception and stops execution from that point onwards only when no exceptions occur below lines are executed (only in case of closing connection). Exceptions may throw at different points such as issues with TCP/IP sockets or network communication failure.