import java.util.*; // For List, ArrayList etc., we use these namespaces instead of 'std' or similar in Java libraries to avoid confusion and misunderstanding the library name if used directly from standard environment like browser console without using any external framework/library such as Spring for session management with HTTP only cookies security measures would be needed.
  
public class java_49931_SessionManager_A01 {  // This is our custom object-oriented style program, named 'Session Manager' rather than a verb or phrase (like BrokenAccessControl) to avoid confusion and misunderstanding of the context in which we are using this name due directly from standard environment/console without any external framework.
    private List<String> loggedUsers;  // Logged users stored here for security measures related A01_BrokenAccessControl (Acess Control Law - Broken Access) as it's about tracking, not accessing or modifying data beyond the scope of authorized accesses in system/session management.
  
    public java_49931_SessionManager_A01() {// Constructor initializing a list to store logged user names for our custom A01_BrokenAccessControl security measures (access control law - broken-in). In real world application, it's better not directly using private fields due direct usage without any external framework/library.
        this.loggedUsers = new ArrayList<>();   // 'ArrayList is a kind of List in Java that can contain multiple items and we use '.', just like how they are used with std libraries or when defining classes, interfaces etc.'  to avoid confusion around them directly from standard environment console without using any external framework/library.
    }    
      
// Function for user login   // This is a function related security A01_BrokenAccessControl (Acess Control Law - Broken Access) and it's about tracking, not modifying or accessing data beyond the scope of authorized accesses in system session management as per requirement.  In real world application this can be used to track each user login into our program through their username
    public void Login(String name){   // It will add a logged-in users's details (username) and allow them continue without any security issues related A01_BrokenAccessControl as per requirement. In real world application, it should be secured against unauthorized access such as SQL injection or XSS attacks
        if(name != null && name.length() > 3){   // This is to ensure that a user can't login with less than 4 characters (as minimum) and only allows for names longer then just three, allowing us some security against unauthorized access related A01_BrokenAccessControl
            this.loggedUsers.add(name);    // If name is not null or shorter length of character are more than allowable in our program (as per requirement), we add the user into logged users's list, allowing them continue without any security issues as it relates A01_BrokenAccessControl
        }else{  /// if username has less then required characters no action is taken to prevent unauthorized access related A01_BrokenAccessControl and just logout the user.   // In real world application, we can use this functionality for logging out users as well such that all sessions are closed when a logged-user logs in again after being 'loggedOut'
            Logout(name);  /// This is our custom object oriented style function to handle session management and will be used later on. In real world application, we can use this functionality for logging out users from program as well such that all sessions are closed when a logged-user logs in again after being 'loggedOut'
        }   // end of if else statement related A01_BrokenAccessControl (Acess Control Law - Broken Access) and its usage.  In real world application, this functionality can be used for logging out users or tracking accesses that are not permitted due to security rules applied in program/system such as those mentioned above
    }   // end of public void Login method related A01_BrokenAccessControl (Acess Control Law - Broken Access)  and its usage. In real world application, this functionality can be used for tracking each user login into our system session management with security measures applied in the program as mentioned above
    
    // Function to logout   /// This is a function related A01_BrokenAccessControl (Acess Control Law - Broken Access) and it's about modifying, not accessing or logging out users beyond authorized accesses. In real world application this can be used for closing each session when user logs in again after being loggedOut
    public void Logout(String name){  // It will remove a log-off/loggedIn username from the list and prevent unauthorized modification of these data points, preventing any access beyond authorized ones (as per requirement). In real world application this functionality can be used for closing each session when user logs in again after being loggedOut
        if(name != null && name.length() > 3){  // To ensure that we are not trying to log out users with less than three characters and only allow longer ones, preventing unauthorized modifications of these data points (as per requirement) as it relates A01_BrokenAccessControl
            this.loggedUsers.remove(name);   /// If name is valid or more length for the program in our case then we remove user from logged users's list and prevent them further access beyond authorized ones related to security mechanisms, preventing unauthorized modifications (as per requirement). In real world application it can be used like a log out functionality
        }else{  // If name is invalid or shorter than required length no action taken. Preventing user from being logged in again after logging off due A01_BrokenAccessControl security rules and preventing unauthorized modifications of these data points related to system session management such as those mentioned above
            return;   /// This functionality can be used for handling log out users or tracking accesses that are not permitted anymore via program/system like logged-out sessions (as per requirement) in real world application.  In this case, all the opened sessions will close when user logs off and it's a security measure against unauthorized modification of these data points
        }   // end if else statement related A01_BrokenAccessControl(Acess Control Law - Broken Access) usage in real world application.  In this case, we can use functionality to track each user logout from our program session management and prevent unauthorized modification of these data points such as logged-in sessions that are no longer permitted due A01_BrokenAccessControl security rules
    }   // end public void Logout method related secure operations on access control law - broken in (Acess Control Law - Broken Access)  and its usage. In real world application, we can use this functionality for logging out users or closing each session when user logs off due to system/session management security measures
}   // end public class SessionManager related A01_BrokenAccessControl(access control law-broken in - Broken Access)  and its usage. In real world application, we can use this functionality for tracking accesses of logged users from our session manageing program such as those mentioned above (secure operations on acess controls brokenness level).