import java.io.*;  // Import the necessary classes from Java Standard Library package 'file' & IOExceptions  
public class java_45295_FileScanner_A03 {   
// Method to print file names along their paths using a pre-order depth first search (DFS) Algorithm for finding files in directories and its subdirectories recursively. This method takes two parameters - current path, root directory which is passed while creating an object of this scanner – the parent should be null
    static void listFiles(String dirPath , String prefix){   // Defining a function to print file names along their paths using DFS Algorithm for finding files in directories and its subdirectories recursively. This method takes two parameters - current path, root directory which is passed while creating an object of this scanner – the parent should be null
        File dir = new File(dirPath);   // Creating a file from given Directory Path    .File class constructor initializes and constructs 'file' instance with specified java.lang/String representing pathname, if such exists; otherwise throws IOException in case of I/O errors – this is the most useful overloaded method
        File[] files = dir.listFiles(); // list() returns an array that represents a collection view on all file and directory entries currently present at the time one or more concurrent modifying operations are performed by multiple threads within an instance's context in which each entry may be accessed using either iterator’s next method, after calling this operation.
        if (files != null) {   // If files exists then list all file names and their path from directory to its end – The first loop lists down the subdirectories recursively till it finds a leaf node ie., no more directories are there in which case returns back by calling next method of iterator.
            for (File file : files) {   // Loop on every item inside "files" array, if user is entering directory then we print its name else subdirectory's info with the help recursion – If a single File object represents an entry in either /dev/pts or some other filesystem.
                prefix = (file.isDirectory()) ? file.getAbsolutePath() + "/" : " ";   // Set different markers for directories and non-directories if it is directory else set to empty string – If a single File object represents an entry in /dev/pts or some other filesystem then the getName method returns this name (i,e., absolute path)
                System.out.println(prefix + file.getName());   // This will print all files along their paths recursively with DFS Algorithm for finding subdirectories and its entries – The prefix is appended to each entry when it prints or calls the next method of iterator in a depth-first manner
                if (file.isDirectory()) {    /* If this directory exists then call itself */ // Calling function recursively by passing current file as parameter for directories, and its subdirectory paths will be added upto level until there are no more directores left – DFS Algorithm is used here to find all files in the given root path
                    listFiles(file.getAbsolutePath(), prefix);   // If directory then call itself with new parent as current file's absolute Path and updated Prefix string appended by a "/" (currently it will be added for directories only) – DFS Algorithm is used here to find all files in the given root path
                }     /* End of if condition */   // If directory then call itself with new parent as current file's absolute Path and updated Prefix string appended by a "/" (currently it will be added for directories only) – DFS Algorithm is used here to find all files in the given root path
            }     /* End of For Loop */   // Closing loop on every item inside "files", if user entering into directory then start recursion from this point and search other entries till there are no more available. In each iteration, print out a file or subdirectory's name with the help DFS Algorithm for finding all files in directories – The prefix is appended to indicate whether it’s an entry inside filesystem (i.,e.), directory
        } /* End of if condition */   // If none empty array exists then just return back by calling iterator.next method, after performing any operation on File objects and continue iteration till there are no more files left – DFS Algorithm is used here to find all directories in the given root path (and its subdirectories)
    }     /* End of Main Method */   // Starts execution from main() by calling our recursive function listFiles(), passing initial directory's absolute Path and an empty string as prefix. – The first method executed after compilation, it will start the DFS Algorithm to find all files in directories (and its subdirectories)
}    /* End of class */   // Closing curly bracket '}' for our Java Class file ends here - This marks end points and starts execution from main() function. The rest is just printing out what's inside the code provided above, which are unique A03_Injection security-sensitive operations related to Vanilla FileScanner using only java standard libraries