import java.sql.*;   // Import necessary Java libraries to connect with database and perform operations on DB using JDBC Connection object (Statement, PreparedStatements) etc... .   
public class java_52509_JDBCQueryHandler_A03 {     // Declare your Class name here..(must be the same as file Name). 
   public static void main(String[] args){        // The Main method. You should place this in every Java program, it is mandatory for any application to have a start point ie.,main function...    .      
      String url = "jdbc:mysql://localhost/test";     // Define database URL here..  (Remember these are just dummy urls).   , replace with your actual MySQL Server details. In this case, it's localhost at port number test for the db named as 'Test'.    .
      String username = "root", password="password123";          // Define Database Credentials here..(Must be same ones used in mysql server) , replace with your actual MySQL Server details. In this case, it's root and a random 4-digit number for the DB named as 'Test'.  
      Connection con = null;                       // Declare connection object to hold JDBC database connections... .    (Must be declared within try..catch block so we can close resources properly after operation).     If uncommented, add a MySQL server details.  In this case it's localhost at port number test for the db named as 'Test'.  
      Statement stmt = null;                      // Declare statement object to perform SQL operations... .    (Must be declared within try..catch block so we can close resources properly after operation).     If uncommented, add a MySQL server details.  In this case it's localhost at port number test for the db named as 'Test'.
      try{          // Start of Try-Catch Block... .    (Every SQL operations in JDBC must be inside these blocks.)   It is recommended to use them while working with Database or using any IO stream.  If not used, it's mandatory here for every Java program as start point ie.,main function..
           con = DriverManager.getConnection(url,username , password);         //Get the Connection object from database... . (Must be declared within try block)   It is recommended to use these operations while working with Database or using any IO stream.  If not used here then it's mandatory for every Java program as start point ie.,main function..
           stmt = con.createStatement();                   //Create a statement object... . (Must be declared within try block)   It is recommended to use these operations while working with Database or using any IO stream and close them after operation if not used here then it's mandatory for every Java program as start point ie.,main function..
           String sql = "SELECT * FROM Employee WHERE id="+1234;        //Define SQL Query... . (Must be declared within try block)   It is recommended to use these operations while working with Database or using any IO stream and close them after operation if not used here then it's mandatory for every Java program as start point ie.,main function..
           ResultSet rs = stmt.executeQuery(sql);                //Perform SQL Query... . (Must be declared within try block)   It is recommended to use these operations while working with Database or using any IO stream and close them after operation if not used here then it's mandatory for every Java program as start point ie.,main function..
           /*Process the ResultSet object */          //Uncomment this part, define how you want to process data. Un-Comment when done processing... .  If unprocessed, comment at end of code so that there is no leakage and it's mandatory for every Java program as start point ie.,main function..
      }catch(SQLException se){                           //Catch block in case any SQL Exception occurs. (Must be declared within try or catch blocks)  If not used, comment out at end of code so that there is no leakage and it's mandatory for every Java program as start point ie.,main function..
         /* Handle the exception */        //Uncomment this part to handle your exceptions... . (Must be declared within try or catch blocks)  If not used, comment out at end of code so that there is no leakage and it's mandatory for every Java program as start point ie.,main function..
      }    finally{                                       //This block will always execute whether exception occurred in the Try-Catch. (Must be declared within try or catch blocks)  If not used, comment out at end of code so that there is no leakage and it's mandatory for every Java program as start point ie.,main function..
          /* Clean up objects */        //Uncomment this part to clean-up the DB resources... (Must be declared within Try or Catch block)  If not used, comment out at end of code so that there is no leakage and it's mandatory for every Java program as start point ie.,main function..
      }       /* End finally */    //This part will always execute whether exception occurred in the try-catch. (Must be declared within Try or Catch block)  If not used, comment out at end of code so that there is no leakage and it's mandatory for every Java program as start point ie.,main function..
   } // End main method here... .       You should always place this in any java file. It will mark the beginning (`/* Start */) –end( ` /*End*/ ) of a code block, which you can add or remove to suit your requirement and make it more readable by yourself/others