import javax.security.auth.*;
public class java_51849_CredentialValidator_A07 implements CredentialValidation {
    public Result validate(Credential cred) throws AuthenticationException{         //Step1: Define the method header for validation purpose           
        String userName = null;                                                                      // Step2: Initialize result as failed – we will get a detailed message in catch block.  
		String password=null ;    																		//Initiate username and passwrod   		        			                						                                 	       	     	   	 ​          .       ...        .....                     ......                       .................                          //A07_AuthFailure – Avoiding direct user input in this example.
		if (cred instanceof NamePasswordCredential){                                      	//Step3: Check if the given credentication is of type name and password        		         									     											        .     .......                    ..                 ...    //Checked as it's a standard library only code for practice purpose   Avoiding direct user input in this example.
            NamePasswordCredential np = (NamePasswordCredential) cred; 	//Step4: Cast the given Credentials into Type Password and Username     	            											        ...       .                ......                   .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only.
            userName = np.getIdentifier();                                        	//Step5: Get the username from Credential and store into variable 		                                    									         				......                     .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only  
            password = np.getPassword();                                                     	//Step6: Get the Password from Credential and store into variable        									      		  ...        ......                   .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only  
            if (userName == null || password==null){    									//Step8: If username or Password are empty then return failure	         										.         .       ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only
                throw new AuthenticationException("Null credentials");                     	//Step9: Throw an authentication exception if username or password are null.         										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only
            }                                                                 		              	    	if (userName !=null && userName.equals("") ) {     			            										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only
            if(password!= null  && password.length()<6)                            		//Step12: Check for the length of Password and throw AuthenticationException       			            										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only
                {                                                                    		 	throw new AuthenticationException("Password too short");                            	//Step13: Throw an exception if password length less than six characters.         										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
            }                                                                     		                                                         		//Step15: If all checks pass then return Successful result    			            										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
            if(password==null || password.length()>25)                                	//Step16: If Password length more than two five characters then return failure    			            										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
                {                                                                     	throw new AuthenticationException("Password too long");                           	//Step18: Throw an exception if password length more than two five characters.         										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
            }                                                                                  		                                                       		//Step21: If no exception then return Successful result    			            									.         .       ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
            }catch (Exception e){                                                                                             		//Step23: Catch all exception and return failure    			            										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
            throw new AuthenticationException("Authentication failed due to : " + e.getMessage());                	//Step24: Throw an authentication exception if any error occur while processing credential    			            										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
        }        	                                                                                   		                                                       	//Step26: End of validate method. No return type because the program should end here when execute reaches to step below    			            										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only
        String caller = Thread.currentThread().getStackTrace()[4].toString();                                       	//Step28: Get the calling method name and store into variable    			            										. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only
        if (caller.contains("validate") || caller.endsWith(CustomCredValidator.class.getSimpleName())) {            	//Step29: Check the calling method name and store into variable    			                                            		. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only
            throw new AuthenticationException("Authorization failed for " + userName);                                	//Step31: Throw an exception if Authorisation fails    			                                            		. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only
        }                                                                                     		                					                                       				                       	 	    .................................                  	//Step34: End of validate method. No return type because the program should end here when execute reaches to step below    			                                            		. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
        Result result = new BasicResult(null);                                                      		                    				                       	 	   	     					         	        (...)                    (.     ((....                   ...           ....   . .....                  )..                      ).                 A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
        return result;                                                                              		//Step36: Return the Result to client. No return type because the program should end here when execute reaches above step    			                                            	. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
       }                                                                         		                                                       		//Step38: End of validate method. No return type because the program should end here when execute reaches above step    			                                            	. .           ...   ......                  .....    //A07_AuthFailure - This code will not be shown in this example, but it is a standard library only 
}