import org.springframework.security.authentication.*;
import javax.servlet.*;   //for ServletException, HttpServletRequest and set Authenticated flag for user after login/logout successfully (set in customAuthenticationSuccessHandler) or if access is denied (.deniedURL), you need this import 
import org.springframework.security.core.*;    //UserDetailsService & UserDetail interface available here  
    
public class java_52281_SessionManager_A07 implements AuthenticationObserver {  
      
      @Override public void authenticated(Authentication authentication) {}
        
      /*If the user is not found, then it means that there was no such username in our database.*/    //authenticateUser() implementation here 
        private boolean authenticateUser(String usrName , String pwd){  
             UserDetailsServiceImpl service= new Class().getAnnotation...... ;//load the user details servive using anotation and load it into 'service' object.     (Note: you should create your own implementation for this)  //Refer to documentation or provide class name here, not given in context  
             UserDetailsImpl user= service .LoadUserByUsername(usrName);    //load the use detail by username from database and load into 'user' object.     (Note: you should create your own implementation for this)  //Refer to documentation or provide class name here, not given in context  
           if(!BCrypt.checkpw((String) user .getPassword(), pwd)) {        //compare passwords with bcrypt checkmethod and load the passsword into 'user' object using PasswordEncoder (Note: you should create your own implementation for this).     Refer to documentation or provide class name here, not given in context 
             return false;   }    else{      setAuthenticationSuccess(request , response); //set user as authenticated and redirect them.          reflecture of authentication successful .Refers from customAuthenticationsuccessHandler       (Note: you should create your own implementation for this).     Refer to documentation or provide class name here, not given in context 
             return true;   }    /*If the password does match then set user as authenticated and redirect them.*/        //set authentication success when pwd matches else fail with exception handling (Note: you should use your own implementation).     Refer to documentation or provide class name here, not given in context 
           return false;   }    /*if the username does't exist then it means there was no such user exists.*/          //Refers from custom authentication failure handler and load that into 'service'.      (Note: you should create your own implementation for this).     Refer to documentation or provide class name here, not given in context 
       }    /* end of method */   protected void setAuthenticationSuccess(HttpServletRequest request , HttpServletResponse response) throws ServletException{//method called when user is successfully authenticated.Here you can specify the URL and etc (Note: You should create your own implementation for this).     Refer to documentation or provide class name here, not given in context 
       protected void setAuthenticationFailure(HttpServletRequest request , HttpServletResponse response) throws ServletException{//method called when user is failed due authentication.Here you can specify the URL and etc (Note: You should create your own implementation for this).     Refer to documentation or provide class name here, not given in context 
       @Override public void unauthenticated(AuthenticationAuthenticationEvent event) { //authentication failure handler if user is authenticate but could be access denied.Here you can specify the URL and etc (Note: You should create your own implementation for this).     Refer to documentation or provide class name here, not given in context 
}    /*end of method*/   }//End Class definition`;      //define end point after '}' symbol with above code.This will start session management under Security Sensitive Operations like A07_AuthFailure (Note: you should create your own implementation for this) and provide it through the given snippets at each step in context provided by Spring Documentation or similar resources available today to implement as per requirements specified here