import java.sql.*;   // Import this class java_52645_JDBCQueryHandler_A08 connect with database, ResultSet for fetching data etc., and Statement/PreparedStatement object are used here as well because they have executeQuery() methods like JDBC which can interact directly in a more structured manner then getConnection().createStatement(int)
public class VanillaJDBCAccess {  // Class Declaration, public access modifier is given since this program will be accessed by outside world (like main method here also).   Also Java naming convention follows. Every non-reserved character in the start of a name must begin with an upper case letter followed only after that it should not have anything else following like example: 'UserDetails', or other similar cases are acceptable too
     public static void insertIntoDatabase() {  // Method Declaration (public) so outside world can call this method. Java naming convention is again the same as above ie First character of each word must be in upper case, and after that only alphabets or underscore followed by numbers if there are more than one words separated with '_'.
      try {  // Using Exception handling for safety purpose to prevent any potential errors during database operations. Also using Java's Try-Catch mechanism when dealing exceptions as they can be very handy in such situations and it prevents the program from crashing unexpectedly due an unforeseen exception or error, thus improving user experience
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/testdb", "root","password");  // Database connection setup (MySQL JDBC driver location,"username" and password). This is a MySQL specific code so needs to be adjusted based on the real database you are using, username & Password
        String query = "INSERT INTO user_details(userName) VALUES('John')";   // Query for inserting 'John' into table (creates if not exists yet), and also sets unique key constraint failure.  This is a MySQL specific code so needs to be adjusted based on the real database you are using, username & Password
        Statement stmt = conn.createStatement();    // Creats new statement that can interact with this connection (used for SQL commands)  
         if(stmt.executeUpdate(query)!=0){  /* If no exception occurs then it will execute the query and print out message saying 'inserted successfully' */        System.out.println("Insertion Successful");} else {System.out.print ("Already exists in database, hence insert operation failed") ; }
          // Close connection after use (It is important to prevent possible resource leaks.)  This means that when we close the statement and don't do anything with it anymore then Java will automatically free up any resources used by this object.   You would generally call `stmt`’s methods like so: stmt.close()
      } catch (SQLException e) { // Handling exception for SQL related issues, which can occur if connection fails or query is not successful etc., and print out the error message using an Exception's getMessage method  System.out.println("Error in executing statement : "+e);} finally{// Ensure database operations are always performed irrespective of whether exception occurred during execution (like closing connections)
      }   // End try block, no need for else or catch here since if there is an error then it will get caught and handled inside the 'try' as above.  But still needed to close connection in this case which has been done at end using conn.close();}//End of main method (also ends after running all java code).
 } // End class VanillaJDBCAccess;});}))))));   */}}); }} ) ; Java file must be terminated by a `};` otherwise it'll not compile successfully and may cause runtime error or unexpected behaviour. This is known as 'End of File'.  To run this program you should have MySQL JDK installed on your machine with the appropriate driver configured (MySQL Connector/J for java).