import java.sql.*;  // Import necessary Java libraries needed to connect database, create a connection (Statement & PreparedStatements), execute query...etc
  
public class java_42824_JDBCQueryHandler_A03 {
    public static void main(String[] args) throws SQLException{    
        String url = "jdbc:mysql://localhost/test"; // use your own URL here. The database name is 'test' for this example 
                                                    // (make sure you replace it with the actual one in real situation).  
        String username ="root";    // Root user, make adjust as per MySQL configuration file      
                                         //(usually /etc/mysql/my.cnf or use environment variables)        
                
        String password= "";  /* You should consider using your own secure method for storing and accessing the database credentials */     
                                                 
                            		// Create a connection to MySql Database  
                               Connection con = DriverManager.getConnection(url,username ,password);    	   	 		   			      	     	       									         															 ​        // Creating SQL statement object (con) with DB Server via getConnectioN method           /                                  .         (.                    .........                        ...      .....
   }                       Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
    }                                  (1)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                   (2)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                     (3)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                       (4)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                         (5)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                           (6)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (B)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (A)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (D)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (E)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (F)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (G)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (H)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (I)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (J)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (K)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (L)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (M)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (N)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (O)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (P)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (Q)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (R)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (S)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (T)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (U)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (V)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (W)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (X)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                               (Y)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
                                                             (Z)   Necessary JDBC libraries are imported at the beginning.               Hint: You may use a library like MySQL Connector/Java for these tasks in Java 7 and above versions, since it's part of standard java package but less so if you want to make your code more compact or have better performance
   }                                                            // Close bracket ...    .                                                                     (.                  .......                         (...)         ..                   )                 -.      ((..                      ^-  (-.-                    *--*--------**----***---****`-----/* --- ** -----.            _/ --.* `---------''