import java.io.*; // Import the necessary Java Libraries used below: BufferedReader, InputStreamReaders, PrintWriter...  
// For File Handling Operations like reading/writing files in a file system or network etc.. you will need these libraries   
    
public class java_52875_FileScanner_A07 {  /* Start of main function */      // Begin the code here. Keep it as simple and creative till done with A07_AuthFailure requirements...  
       public static void main(String[] args) throws IOException{       
           String readFilePath;        
            BufferedReader reader = new BufferedReader (new InputStreamReader  (System.in)); // Streams for reading from User input     
                   System.out.println("Enter the file path to be scanned: ");    /* Ask user location of files */    
           readFilePath =  reader.readLine();       /**/   /* Accept Filepath as Input  **/         
            scanAndPrint(readFilePath);        //Calling method for scanning and printing, you can add more functionalities based on the requirement...    }      public static void scanAndPrint (String fileName) throws IOException {         PrintWriter writer = new PrintWriter ("output.txt", "UTF-8"); /* Create a output text File */
           try(FileScanner sc=new FileWalkIterator(fileName))       //Use the class to start scanning from given directory and its subdirectories...  
            while (sc.hasNext()){             /**/     /* Loop through all file in Directory or under that path **/         String nextPath = sc.next();           writer.println("Scanning: " + nextPath);       /* Write into the output File */  }      //Close PrintWriter at end...  
            else {                                      **// Else block for when there are no more files to read**    System.out.printf ("%s does not exist.", fileName) ;     return;         }} public class XYZIterator implements Scanner{       /**/ /* Implementation of the Iterator Pattern */  private File[] roots, currentFileList = new ArrayList<>();      //...