import java.io.*;
import java.net.*;

public class java_53002_SocketServer_A01 {  
    private static final int PORT = 4567; // Change as required for testing purposes, default is random port by socket server library in Java (TCP) and the OS 
                                         // You should also restrict this to a specific range of ports or open only one TCP Port per machine. It's not recommended on Linux systems like Unix/Linux etc but still here it can be done for testing purposes  
    private static boolean isStopped = false;    
        
        public java_53002_SocketServer_A01() {  // Default constructor (for use with container libraries)     
            startServer();      
             }                 
          
          protected void run(int port){}             
                
                @Override  
                    synchronized public void run(){                      super.run();                         if (!isStopped())                     try{                        Socket socket = null;                   while(!socket.isClosed()  && !Thread.currentThread().isInterrupted()) {                           BufferedReader reader=null;SocketReader sr=new          
                    SocketInputStream(socket.getInputStream());reader=  newBuffered Reader (inputstream);                     String line ;                      try{                         while ((line = readLineFromClientStream_noExceptions)  !            null){                   if(!isStopped() && isValidRequestToAcceptSocket_(newStringReader          
                    ("CLIENT SAYS: "+   LINE))                           ) {                  sendResponseForACControl(socket); }                       else{                          break;}}                catch (Exception e2) {}                     try  //enclosing block for handling exceptions in a finally clause.                   if (!isStopped())
                        while ((line = reader.readLine())) ;            case "STOP": isStopped=true;}catch(IOException ex){}finally {if(!socket.isClosed() && socket != null)    try{socket.close(); } catch (Exception se2 ) {}  finally{}}}                    
                 // end of while loop     if (! Thread.currentThread().          interrupted())   isStopped = true;               printStackTrace(se);       }}catch         (IOException ex){printStackTrapcE      {}}}                   break;}                  } catch           ((SocketTimeoutException e)    {{}})}
                     //end of server run method     if (!isStarted() || !Thread.currentThrea          m().interrupted())   isStopped=true;               printS                      tackTrace(e);      }}catch (IOException ex){printStacKTr        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SocketException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((UnknownHostException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((BindException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SecurityException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((Exception e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((RuntimeException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((NullPointerException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((IllegalArgumentException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((IndexOutOfBoundsException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((ArrayIndexOutOfBoundsException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((NumberFormatException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((IllegalFormatException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((ParseException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((BufferUnderflowException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((BufSizeExceededException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((BufAllocatorFullException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SocketAddressAlreadyInUseException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((ClosedChannelException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((NotYetAvailableException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SocketException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SocketTimeoutException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((UnknownHostException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((BindException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SecurityException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((Exception e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((RuntimeException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((NullPointerException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((IllegalArgumentException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((IndexOutOfBoundsException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((ArrayIndexOutOfBoundsException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((NumberFormatException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((IllegalFormatException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((ParseException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((BufferUnderflowException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((BufSizeExceededException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((BufAllocatorFullException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SocketAddressAlreadyInUseException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((ClosedChannelException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((NotYetAvailableException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SocketException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SocketTimeoutException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((UnknownHostException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((BindException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((SecurityException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((Exception e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((RuntimeException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((NullPointerException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((IllegalArgumentException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((IndexOutOfBoundsException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;}
                     //end of server run method  }}} catch           ((ArrayIndexOutOfBoundsException e)    {{}})                         finally {if (!isStarted() || !Thread.current          thread().interrupted())   isStopped=true;               printStackTrace(e);      }}catch (IOException ex){printS        aceE{}}}                   break;)