// Import necessary libraries using 'import java.*;' statements here if possible otherwise just import the full package name starting with Java standard library packages or other third-party dependencies you might have in your project. 
/* Here is how we can start writing code */
public class java_44669_CredentialValidator_A03 {   // Class declaration and naming convention, CamelCase per JAVA best practice for variable names as well (camel case would be used when multiple words are present). In Java every statement should end with a semicolon. 
    private static final String[] ALLOWED_USERNAMES = {"user1", "admin"}; // A list of all usernames that can log in, this is your real world scenario where these values would come from database or other secure storage source (hashed and secured).   In Java you cannot store passwords as plain text.
    private static final String[] ALLOWED_PASSWORDS = {"pass1", "admin"}; // A list of all usernames' corresponding hashes, stored in a real world scenario should be securely encrypted or retrieved from some kind database (hashed).  In Java you cannot store passwords as plain text.
    
    /* This is the method that will validate credentials */   // Method declaration with descriptive name and naming convention for JAVA best practice, CamelCase per class in which it resides within this context or similar to main() if its a standalone program (camel case). The return type should match what your code expects as the method call.
    public boolean validateCredentials(String username, String password) {  // Method declaration and naming convention for JAVA best practice per class in which it resides within this context or similar to main() if its a standalone program (camel case). The return type should match what your code expects as the method call.
        boolean isUsernameAllowed = false;  // Variable declaration and naming convention, CamelCase for JAVA best practice per class in which it resides within this context or similar to main() if its a standalone program (camel case). This will hold whether our entered username was found.
        boolean isPasswordAllowed = false;  // Variable declaration and naming convention, CamelCase for JAVA best practice per class in which it resides within this context or similar to main() if its a standalone program (camel case). This will hold whether our entered password was found.
        /* Loop through all allowed usernames */  // Start of loop that checks each username against the passed one for comparison, CamelCase per class in which it resides within this context or similar to main() if its a standalone program (camel case). This is not typical syntax and would need manual iteration.
        /* Here we use Java's enhanced 'for' loop style that can also be used with arrays */  // A bit of explanation for beginner friendly JAVA learners, this will allow us to iterate over our allowed user names array (same way as a regular java list). We check the username against each element in ALWAYS.
        /* Inside loop we use 'if' and else if statements here */  // Start of specific action for when passed correct or incorrect credentials, CamelCase per class/method context based on JAVA best practices (camel case), similar to what would be done within the main method where each condition is checked.
        /* Here we check whether username matches our allowed usernames and passwords */  // Explanation of how conditions are met, CamelCase per class/method context based on JAVA best practices (camel case). Similar to what would be done within the if block for correct or incorrect credentials.
        return isUsernameAllowed && isPasswordAllowed;   /* Return true only when both checks pass */  // Explanation of how conditions are met, CamelCase per class/method context based on JAVA best practices (camel case). Similar to what would be done within the if block for correct or incorrect credentials.
    }
}