import java.io.*;
import java.net.*;

public class java_45445_SocketServer_A01 {
    public static void main(String[] args) throws Exception{  
        ServerSocket server = new ServerSocket(4001);// Create a socket on port number provided as parameter to constructor  // This represents the listening Port for incoming connections from clients. The argument passed here is an internal IP address (localhost), and then we are setting up our Socket using this created 'Server-side'socket
        System.out.println("Waiting For Connection");  
        
       while(true) {  // Create a infinite loop for server to listen continuously until clients disconnects or send any data via TCP/IP protocol (Client - Server). The client will keep sending messages till it gets disconnected from the remote side, hence using an 'infinite' loop. For each incoming connection request received by this listener on specified port number then creates a new socket object and assign that to variable called ‘client’
            Socket client = server.accept(); // Accepts incomming connections for our ServerSocket   And returns the reference of newly created 'Client-side'socket which is connected with requested connection by passed listener on specified port number, if successful then accepts incoming request from a socket and waits until some data arrives over that network channel to be read. 
            
            System.out.println("A new client has Connected");   // If there are any connections available it will print this statement with the IP Address of Client who have connected, otherwise nothing is printed on screen hence indicates no connection yet or waiting for a Connection from others clients     OutputStream out =client .getOutputStream(); 
             BufferedWriter writer=new BufferedWriter( new OutputStreamWriter(out));   // Get an output stream to write into the socket's send/sendfile buffers. The parameter is actually just which port (the 'destination') we wish for our data sent out on ('localhost'). For example if it were a server then you would pass in 4012 and use localhost as your IP address
             writer.write("Hello Client, You are Connected to Server!"); // writes the string into socket's send/sendfile buffers   Then flushes this buffer 'stream'. It is used when we want write out data on that stream without waiting for all bytes of incoming TCP packet  before writing or reading
             writer.newLine();// A newline character to be written onto OutputStream    Sends the string via socket's send/sendfile buffers   and frees up resources associated with it (both input & output) Then flushes this buffer 'stream'. It is used when we want write out data on that stream without waiting for all bytes of incoming TCP packet  before writing or reading
             writer.close(); // Closes the OutputStream by freeing its resource back to system    The function close() marks end-of-file (EOF) as part of an I/O operation and then flushes any buffered data on stream, if necessary   Any resources used for this connection will be released when there is no more work going forward with that socket.
             client .close(); // Closes the InputStream by freeing its resource back to system    The function close() marks end-of-file (EOF) as part of an I/O operation and then flushes any buffered data on stream, if necessary   Any resources used for this connection will be released when there is no more work going forward with that socket.
        }  //End while loop     server .close();    Ends the Server Socket Listener Thread (Server-side) to listen and accept incoming connections requests from clients: Closes all underlying resource on System/Network related operations   Finally, if we are listening then it is mandatory until client disconnect or some data transfer else no operation.
}  //End main method     }    Ends the Main Class in Java Programming Language (Java). It'll stop execution of program whenever an exception occurs due to any reason like OutOfMemoryError etc and print stack trace details for easier debugging purpose on console   This is a very basic example only using standard libraries.