import org.xml.sax.*;
import org.xml.sax.helpers.DefaultHandler;
import javax.net.ssl.HttpsURLConnection;
import java.io.InputStream;
import java.net.URL;
public class java_45496_XMLParser_A07 extends DefaultHandler {  // your exception should extend this or implement it via Exception in a way that makes sense for you, like here I'm extending default handler to have access on some methods and fields declared there (like startElement etc.) but not all if they are necessary
    public static void main(String[] args) throws Exception {  // create new connection object with the URL: A07_AuthFailure.xml as parameter, read data from it using this Connection Object for example http://www.mediafire.com/file/5e3p4l82vj6sxqr
        HttpsURLConnection conn = (HttpsURLConnection) new URL("http://a07_AuthFailure.xml").openConnection();  // set up the connection and get it ready to read data from this url... use SSL/HTTPS for secure connections, as xml is http based
        InputStream inStr = conn.getInputStream();   // convert Connection Object into an input stream using .GetInputSteam() method which reads all content of a URL(in our case XML file)  ... and parse it by invoking startDocument(), element etc., methods here... use SAX Parsers
        SAXParserFactory factory = SAXParserFactory.newInstance();   // create new instance for creating parsers using this Factory object, then set up the parser with your input stream to read from above url (example by invoking parse() method)  ... and you can process all data in an event handler here...
        try {    /// start of SAX Parsing - Invoke beginDocument(), processingStartElement etc. methods.. Then get events until end document is reached, after which invoke EndDocument(). close the Connection Object using .close() method to release resources and free up server/connection if necessary  ... parse all data by invoking your custom event handlers
            SAXParser parser = factory.newSAXParser();   // create new instance for creating parsers here... then start it with above input stream (example below).. handle this incoming XML content using the provided Handler object inside BeginDocument, process each element and attribute as you see fit in your event handler
            parser.parse(inStr, A07_AuthFailure);   // parse given InputStream to get all data from a URL here... do not forget that SAX parsers are idempotent they read the same document multiple times but once parsed it will fail with an exception if you attempt reading again
        } finally {  /// closing connection using .close() method when done working on url or any other resource to free up resources and close connections properly in a safe way. If Exception is not null then throw, otherwise log the message for debugging purpose...   // end of SAX Parsing.. this ensures that your code always cleans well after usage
            conn.disconnect();  /// cleanup done here if exception was thrown or connection object wasn't properly closed in try block above (closeable interface) it will be automatically managed by java garbage collection framework for us... use .Disconnect() method to close this Connection Object, and finally the InputStream from url has been released as well.
        }  // end of Main Method with all necessary code inside a new Block at last in order not allow any external access into our class or objects (make sure they are private). This is how you handle exception properly for your program: if there was an error, either because the URL could be unreachable due to insufficient permissions OR data format of XML file has changed since it's been downloaded.
    }  // end Main Method with all necessary code inside a new Block at last in order not allow any external access into our class or objects (make sure they are private). This is how you handle exception properly for your program: if there was an error, either because the URL could be unreachable due to insufficient permissions OR data format of XML file has changed since it's been downloaded.