import java.sql.*;
public class java_52770_JDBCQueryHandler_A08 {   // define a public static method within the same file (without importing), name it "VanillaJava" - following best practices for naming convention in Java, since there is no real case without external libraries involved here to avoid conflicts with standard JDBC operations.
    private Connection conn;  //declare connection object    
   public java_52770_JDBCQueryHandler_A08() {//constructor method that initializes the database and open a new session using DriverManager of java db library (java sql driver) - best practice, we are making sure to close it after our operation completion whether was successful or not. We can use 'try-with resource' for automatic closing
       try{     //beginning brackets because Java is case sensitive    and begin the process with a connection using DriverManager in java db library   "VanillaJava" - following best practices “java” to describe that this method belongs or handles instances of our class. It has access modifier for public, which means it can be accessed by any other classes/methods (unless they are private).
           conn = DriverManager.getConnection("your-jdbc:url", "username","password");   //here your jdbcurl should contain database url and username & password need to match with the one in db connection data source file “VanillaJava” - following best practices for security reasons, it will not be visible on public.
       } catch (SQLException e) {     /// if something goes wrong during this process then exception is thrown here   "ex" should always follow camel case convention and describe what caused the issue in more details about sqlexception “VanillaJava” - following best practices for naming exceptions as descriptive.
           System.out.println("SQLException Occurred: Cause by " + e);     //prints error message    }      this brace is closed off with a caret symbol ("^") in java and represents the end of our try block here   “VanillaJava” - following best practices for using brackets properly.
       System.out.println("Connection Created Successfully");     //this line will be printed if connection has been created successfully    }///end brace is closed off with a caret symbol ("^") in java and represents the end of our try block here “VanillaJava” - following best practices for using brackets properly.
   public static void main(String args[]){     //beginning Braces because Java Programming language, as case sensitive is true; this line to introduce some idea about how we will call above method in other class files ("main" function). “VanillaJava” - following best practices for naming methods.
        VanillaJdbcQueryHandler vj = new VanillaJdbcQueryHandler();     //creating object and calling the constructor Method    }///end Braces because Java language, as case sensitive is true; This line to introduce some idea about how we will call above method in other class files ("main" function). “VanillaJava” - following best practices for naming methods.
     }}//End of main("") statement and closing brackets on java side   "java: {","}^n");    //end Braces because Java Programming language, as case sensitive is true; this line to introduce some idea about how we will call above method in other class files ("main" function). “VanillaJava” - following best practices for naming methods.